### ISSUE TITLE
#include "gapii/cc/gvr_spy.h" fails

### ISSUE THREAD

**Issue by robertfoss** [google/gapid#1009]
Built on e843f4e7, interrupted by an error.

```
In file included from /home/hottuna/.go/src/github.com/google/gapid/gapii/cc/gles_exports.cpp:23:
/home/hottuna/.go/src/github.com/google/gapid/gapii/cc/spy.h:22:10: fatal error: 'gapii/cc/gvr_spy.h' file not found
#include "gapii/cc/gvr_spy.h"
         ^~~~~~~~~~~~~~~~~~~~
```

**Comment by ben-clayton** [comment]
Please try: `do build generate` followed by `do build`.
The CMake build system has broken dependencies which we haven't spent much time investigating as we still intend to switch to Bazel, sometime Soon™

**Comment by robertfoss** [comment]
That improves the situation!

I have encountered some other issues, like fmin/fmax being defined twice and the "-fcolor-diagnostics" compiler option being missing. Are you interested in reports for that too?

**Comment by ben-clayton** [comment]
Hi @robertfoss,

The `fmin`/`fmax` issue is being tracked here: https://github.com/google/gapid/issues/636.

This is really an issue with the [ASTC encoder library](https://github.com/ARM-software/astc-encoder). We should really be filing issues there.

> "-fcolor-diagnostics" compiler option being missing

I'm not aware of that one. Please feel free to file an issue for that.

Thank you for the quick response!
