### ISSUE TITLE
Add tests for GLSL compat

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#1023]
Currently if the shader doesn't have a #version header, I'm not entirely sure we are doing the right thing. I speculate that the default versions picked on Android and desktop may differ.

Research, fix or close this issue.

**Comment by pmuetschard** [comment]
According to the [GLES 2.0 GLSL spec](https://www.khronos.org/files/opengles_shading_language.pdf), Section 3, Page 13:
> Version 100 of the language does not require compilation units to include [the #version] directive, and compilation units that do not include a #version directive will be treated as targeting version 100. 

And according to the [GLES 3.0 GLSL spec](https://www.khronos.org/registry/OpenGL/specs/es/3.0/GLSL_ES_Specification_3.00.pdf), Section 3.4, Page 11:
>The directive “#version 300 es” is required in any shader that uses version 3.00 of the language... Version 1.00 of the language does not require shaders to include this directive, and shaders that do not include a #version directive will be treated as targeting version 1.00.

Also, note that `#version 100` may appear **after comments and whitespace** while, `#version 300` and later must be the first line (in fact, the spec mentions that three times!)

**Comment by dsrbecky** [comment]
On input, if the #version is missing, glslang will parse it as 1.00

On compat ouput, we always explicitly generate #version statement 

So I believe are always do the right thing.

**Comment by ben-clayton** [comment]
Why does [this page](https://www.khronos.org/opengl/wiki/Core_Language_(GLSL)#Version) suggest that the default is 1.10?

Sounds like we could do with a test for these cases.

**Comment by dsrbecky** [comment]
"GLSL version numbers were not always in sync with the GL version"
It is unaltered

**Comment by dsrbecky** [comment]
Also it is page for desktop GLSL, which is also unrelated.
The only thing we care about for the default is the GLSL ES spec.

**Comment by dsrbecky** [comment]
Hmmmm.... the page does contradict what pascal quoted.  In any case, it does not affect us.

**Comment by ben-clayton** [comment]
You sure that glslang always adds a `#version` even if the original shader didn't have it? Because if it didn't a difference in default version between GL and GLES could affect us.

I'd guess it would, but again, it's the sort of thing that a simple test wouldn't be hard to assert.

**Comment by dsrbecky** [comment]
I am sure that glslang treats the shader is if it was declared 1.00.

The generated SPIR-V code is version independent.

For the generated desktop code the shaders just have a fixed header which includes the version.

Let me flip the question around - with our toolchain it is almost impossible to "remove #version if and only if was not present originally"

**Comment by dsrbecky** [comment]
I can try to add some test to check the fixed header always contains #version string if it is a priority.

**Comment by ben-clayton** [comment]
I completely agree with what you're saying.

My point is that a test would be nice because we're relying on the implementation details of glslang, which is a bit of a black-box to GAPID. Let's say someone updates glslang to include SPIRV metadata which includes the original version in the source, and this is used to try and generate GLSL with a similar version.
Maybe a far-fetched example, but a test would at least keep our assumptions fixed.
Maybe one day an even better GLSL x-compiler comes out that we decide to switch to, and then all these forgotten assumptions come and bite us.
Who knows, but a simple test that just asserts a fundamental assumption about shader versioning sounds like a good idea to me.

**Comment by ben-clayton** [comment]
> if it is a priority 

Nope, it's not overly high priority at this time.

**Comment by dsrbecky** [comment]
There was a bunch of tests for the old compat layer, we could re-enable those (after updating the expected output to what the current tooling generates).  I think it seems increasingly likely that we are sticking with glslang as it just works (tm) for now.

Of course, personally, I just want to run our toolchain through the deqp shader test set :-)
