### ISSUE TITLE
[installer.cpp:140] Couldn't resolve the interceptor library.

### ISSUE THREAD

**Issue by stcdalyc** [google/gapid#1026]
![qq 20170830210819](https://user-images.githubusercontent.com/6738727/29873839-63c6b92e-8dc7-11e7-9197-89d3c40bb423.png)

the main error is：
I/GAPID   (32404): [installer.cpp:132] Installing GAPII hooks...
F/GAPID   (32404): [installer.cpp:140] Couldn't resolve the interceptor library.

my device is Redmi 3
related logcat:
[logcat.txt](https://github.com/google/gapid/files/1263660/logcat.txt)

**Comment by ben-clayton** [comment]
Hi @stcdalyc,

Are you able to build from source? If so, are you able to test whether e33a6a1 fixes your issue?

Many thanks for the bug report.
Ben

**Comment by stcdalyc** [comment]
sorry, i can't build successfully.
see #1040

**Comment by stcdalyc** [comment]
@ben-clayton
I'm sure that it has been fixed

**Comment by ben-clayton** [comment]
Okay @stcdalyc. Please reopen if you encounter the issue again.

**Comment by stcdalyc** [comment]
@ben-clayton 
Actually, i can't reopen it, because in github, 

> you cannot re-open your own issues if a repo collaborator closed them

**Comment by ben-clayton** [comment]
Oh, that's a shame. Would you like me to reopen it?

**Comment by stcdalyc** [comment]
No need, because the problem has been fixed
