### ISSUE TITLE
Flakey test: TestMemoryAndGrpcStash

### ISSUE THREAD

**Issue by sjfricke** [google/gapid#1033]
Not really sure how big of a deal of it is, but noting that without an internet connection you will fail a clean `do build` due to robot failing

```
GOT: --- FAIL: TestMemoryAndGrpcStash (2.33s)
	testing.go:39: 20:14:26.876 I: Starting grpc server
	assertion.go:248: Error:lookup
		    Got       0
		    Expect == 17
FAIL
```
or
```
GOT: --- FAIL: TestMemoryAndGrpcStash (5.56s)
        testing.go:39: 17:06:04.815 I: Starting grpc server
        assertion.go:248: Error:lookup
                    Got     `Entity not found`
                    Expect  success
        assertion.go:248: Error:lookup
                    Got       <nil>
                    Expect != `nil`
FAIL
```

**Comment by dsrbecky** [comment]
I believe this particular is just flaky (which we should fix).
Missing internet connection was probably just random correlation but not causation.

**Comment by sjfricke** [comment]
I can repeatably build with or without my internet turned off or on and these errors occur every time without any internet during the build. Not really sure, nor looked into yet, how the testing framework works, but my laptop takes a long time to clean build and was trying to carry it around with me while it compiled XD

**Comment by ben-clayton** [comment]
I agree with @dsrbecky  - I've just tried running these tests with and without my wifi enabled. They fail roughly with the same probability. This bug report has given be the motivation to investigate why the tests are flakey - it seems the stash tests (and maybe code generally) makes assumptions about certain gRPC calls blocking when they don't.

I'll try and figure out a fix for these.
