### ISSUE TITLE
Windows build error: "error: undefined reference to 'setupterm' "

### ISSUE THREAD

**Issue by stcdalyc** [google/gapid#1040]
the main error is:
............................
-- Looking for setupterm in tinfo
-- Looking for setupterm in tinfo - found
...........................
C:/Users/galoisli/go/src/github.com/google/gapid/third_party/llvm/lib/Support/Un
ix/Process.inc:350: error: undefined reference to 'setupterm'
C:/Users/galoisli/go/src/github.com/google/gapid/third_party/llvm/lib/Support/Un
ix/Process.inc:368: error: undefined reference to 'tigetnum'
C:/Users/galoisli/go/src/github.com/google/gapid/third_party/llvm/lib/Support/Un
ix/Process.inc:372: error: undefined reference to 'set_curterm'
C:/Users/galoisli/go/src/github.com/google/gapid/third_party/llvm/lib/Support/Un
ix/Process.inc:373: error: undefined reference to 'del_curterm'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invoca
tion)
ninja: build stopped: subcommand failed.

it's wired, i don't know why..

and the whole log:
[new 29.txt](https://github.com/google/gapid/files/1267099/new.29.txt)

**Comment by ben-clayton** [comment]
We have now switched build systems to Bazel. Marking this as obsolete.
