### ISSUE TITLE
Pasting doesn't work in the goto command view

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#1067]
(but middle click works on linux?)

**Comment by dsrbecky** [comment]
Ctrl+V works on Linux as well

**Comment by pmuetschard** [comment]
Is this OSX? I can confirm that I see this on OSX. It appears that the spinner widget doesn't allow cmd-v pasting, though it those allow pasting via the popup menu.

**Comment by ben-clayton** [comment]
> Is this OSX?

yes
