### ISSUE TITLE
Vulkan particle systems doesn't display in gapic main window

### ISSUE THREAD

**Issue by sjfricke** [google/gapid#1077]
Running the Sascha Willems Particles application it doesn't display correctly on the main window. In the top part and in a video replay it shows up fine, I have tried clicking through all commands in a single frame and it seems just not display it yet it shows up in the Geometry tab.

* [Image of gapic](https://drive.google.com/file/d/0B46b_H3-cALrMnJ5T0lBbjVyVVE/view?usp=sharing)
* [Trace File](https://drive.google.com/open?id=0B46b_H3-cALrZ0Y4TkhTZW9WRXc)
* [Video of trace](https://drive.google.com/open?id=0B46b_H3-cALrRERSTmdTZXN1NE0)

**Comment by AWoloszyn** [comment]
This is because the Tumbnails(and Video) do not show Alpha, but the main framebuffer view does. If you turn off Alpha for the framebuffer, it should show up correctly.

(The 4 squares, uncheck the Alpha channel).

**Comment by sjfricke** [comment]
Ok, that makes sense, sorry bout that one

**Comment by ben-clayton** [comment]
> Ok, that makes sense, sorry bout that one

Don't be sorry. [It's a real discoverability issue](https://github.com/google/gapid/issues/723).
