### ISSUE TITLE
v0.6.0 does not capture VR SDK correctly

### ISSUE THREAD

**Issue by rishi-rranjan** [google/gapid#1093]
v0.6.0 has the support for Google VR SDK. But when I capture the log for [ndk-treasurehunt](https://github.com/googlevr/gvr-android-sdk/tree/master/samples/ndk-treasurehunt) GVR sample, I don't see the frames being displayed correctly in GAPID GUI. It's just black and striped frames being displayed.  

I have seen this behavior when GAPID sees errors. GAPID Log tab is reporting error. 

```
E 07:01:00.733 gapir glGetError() returned: 0x506
E 07:01:00.734 gapir [11955]renderer: GL_INVALID_FRAMEBUFFER_OPERATION error generated. Operation is not valid because a bound framebuffer is not framebuffer complete.
E 07:01:00.734 gapir glGetError() returned: 0x506
E 07:01:00.734 gapir [11969]renderer: GL_INVALID_FRAMEBUFFER_OPERATION error generated. Operation is not valid because a bound framebuffer is not framebuffer complete.
E 07:01:00.734 gapir glGetError() returned: 0x506
E 07:01:00.737 gapir [12317]renderer: GL_INVALID_FRAMEBUFFER_OPERATION error generated. Operation is not valid because a bound framebuffer is not framebuffer complete.
E 07:01:00.737 gapir glGetError() returned: 0x506
E 07:01:00.737 gapir [12376]renderer: GL_INVALID_FRAMEBUFFER_OPERATION error generated. Operation is not valid because a bound framebuffer is not framebuffer complete.
E 07:01:00.737 gapir glGetError() returned: 0x506
E 07:01:00.737 gapir [12440]renderer: GL_INVALID_FRAMEBUFFER_OPERATION error generated. Operation is not valid because a bound framebuffer is not framebuffer complete.
```

I am not able to upload the capture file as the format is not supported to upload here.

**Comment by ben-clayton** [comment]
Hi @rishi-rranjan,

We're going to push another build soon (within the next couple of days) which contains a number of additional fixes for GVR. I'll ping you when it's out.

Many thanks,
Ben

**Comment by ben-clayton** [comment]
Hi @rishi-rranjan. I've just released [binaries for v0.6.1](https://github.com/google/gapid/releases/tag/v0.6.1).
Do you mind checking if this is still an issue for you?

**Comment by ben-clayton** [comment]
Hi @rishi-rranjan,
I just built and tested this myself and unfortunately I'm seeing the same issues with v0.6.1. I'll investigate now.

**Comment by rishi-rranjan** [comment]
Hi Ben,
I am based in PT so just saw this mail. I will try this anyway to see the
behavior. I will be happy to test any release you want me to try.

Thanks,
Rishi

**Comment by ben-clayton** [comment]
I've just submitted a fix for this issue, but it requires a new binary.
What OS are you using? I can upload the specific file with a fix.

**Comment by rishi-rranjan** [comment]
Windows 10.

**Comment by ben-clayton** [comment]
Here is a drop-in replacement for [gapit.exe](https://github.com/google/gapid/files/1307382/gapit.exe.zip). This hopefully will fix your issue.

Cheers,
Ben

**Comment by rishi-rranjan** [comment]
Hi Ben,
           I did try this on top of 0.6.1 but I see the same issue. I will
capture my screen and gapid log and send it to this mail in sometime.

Thanks,
Rishi

**Comment by rishi-rranjan** [comment]
Hi Ben,
            Please ignore my last comment. I was looking at wrong GLES
content. This works for me now.

Thanks,
Rishi

**Comment by ben-clayton** [comment]
That's great. Thanks for the super speedy reply!

**Comment by rishi-rranjan** [comment]
Hi Ben,
           I am trying to capture GVR with our end to end solution. The APK
is built from same sample GVR NDK but we render the frames on a remote
server and feed it to GVR APIs to enable much higher complexity content on
GVR.

With our solution, I am not able to capture any frames but I can see the
frames being displayed on screen. I am attaching a capture(zipped file of
trace). Can you please review and let me know if this is an issue with
GAPID?

Thanks,
Rishi

**Comment by ben-clayton** [comment]
Hi @rishi-rranjan,

I've started a private chat with you on Gitter to better understand your use case and issue.

Cheers,
Ben
