### ISSUE TITLE
Replay of 1000 frame bloom trace created crazy long video

### ISSUE THREAD

**Issue by tobine** [google/gapid#1125]
This is with 0.6.1 release, running from ubuntu Linux on a Pixel phone.

I captured 1000 frame bloom trace in ~11s and replay took ~20min to create video. Then the video contents replay correctly for ~2.5m and then there are many, many hours of a static frame after that.

I captured a 50 frame bloom trace and it worked fine. Took ~5.6s to capture and video replays in 10s.

**Comment by AWoloszyn** [comment]
That is quite odd, I will investigate.
Out of curiosity if you open the trace in the UI, does it show the same thing?

**Comment by tobine** [comment]
The trace looks fine in the GUI and after a second look it may have just been an error in copying the video file. My first copy still appears corrupt, but the original now looks good and replays in 3:20.
