### ISSUE TITLE
Texture with format B10G11R11_UFLOAT_PACK32 showing up black in the UI

### ISSUE THREAD

**Issue by AWoloszyn** [google/gapid#1160]
The texture does have data, it ranges from very small (0.001) to fairly large (90+),
but the texture view shows uniformly black.

The UI shows "correct" values on the text during the hover-over.

It might be nice for the user to be able to specify a curve for the texture (This one would need to be exponential in order for the data to be correctly visualized).

I am not 100% sure if this is a bug, or just a byproduct of how we display Float textures.

**Comment by AWoloszyn** [comment]
This looks to be an issue with Nan's/infs in the tone-mapper. 
This is fixed by
#1183

**Comment by pmuetschard** [comment]
Just to follow up on this. While Ben's change to ignore nan/∞ values in the client is fine, did we check that the source data also contained these? and that it's not a bug in the server translation code that generated them? or in the client reading the server response? I just wanted to make sure we're not just applying a band-aid solution that is covering up another bug. @AWoloszyn, I think you we're in the process of uploading a trace to drive for me with this issue, if you'd like, just share it with me and I'll make sure we're good.

**Comment by ben-clayton** [comment]
To be clear, my change was to ignore abnormal numbers when calculating the tonemapping range. We should probably color / flash infs / nans so they aren't hidden.

**Comment by pmuetschard** [comment]
I think the problem here is that we are interpreting the data incorrectly. I have re-ordered the channels to be reverse, and now there no longer are any NaN/infs, **and** the texture looks more like what you'd expect: https://screenshot.googleplex.com/HrEXvZkyezw

**Comment by AWoloszyn** [comment]
Fixed by #1198.
We had another bug open for this as well, but we had our channels flipped for PACK32 types.

Fixed #632 at the same time.
