### ISSUE TITLE
Some applications do not call Application.onCreate

### ISSUE THREAD

**Issue by AWoloszyn** [google/gapid#1189]
I am not 100% sure what causes this, but I have seen it in at least one applications.

This means that the interceptor never gets properly installed.
For Vulkan-only tracing, we can in theory start the trace in ApplicationLoader and continue. Investigate, iof we are doing a Vulkan-only trace, the feasibility of doing this.

**Comment by ben-clayton** [comment]
@baldwinn860 is also looking into this for certain GLES apps.

**Comment by pmuetschard** [comment]
The difference is that for @baldwinn860, the break point that isn't hit is the `ApplicationLoader.getClassLoader` one, **not** `Application.onCreate`. @AWoloszyn, are you certain that it hit `ApplicationLoader.getClassLoader`?

**Comment by AWoloszyn** [comment]
Absolutely, If we remove ApplicationLoader.getClassLoader breakpoint, and ONLY have the onCreate breakpoint, it is missed. The application continues on its way without ever being intercepted.

**Comment by AWoloszyn** [comment]
Fixed with https://github.com/google/gapid/pull/1207
