### ISSUE TITLE
Server crash with sample app: vulkanShadowmappingomni

### ISSUE THREAD

**Issue by Qining** [google/gapid#1199]
panic: Expecting a map of u32 -> structures [recovered]
	panic: Panic at command 1526:vkQueueSubmit(queue: 3968306656, submitCount: 1, pSubmits: {3968673612 0}, fence: 0) → VK_SUCCESS:
Expecting a map of u32 -> structures [recovered]
	panic: 
--- *resolve.GlobalStateResolvable ---
 path:<after:<capture:<id:<data:"\235*\032J\211\010w\023x\322=i3\010V&Y\324\\\351" > > indices:1526 indices:0 indices:0 indices:20 > >

**Comment by AWoloszyn** [comment]
Fixed by #1200
