### ISSUE TITLE
Improve build times

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#12]
Due to the amount of code generation the API files produce, our clean-build times are typically around the 10 minutes mark, and incremental builds are often 4-6 minutes (YMMV).

As much as I like office sword fighting, we should work hard to reduce these for everybody's sake.

**Comment by ben-clayton** [comment]
@dsrbecky did some great work reducing our C++ build times.
Dropping priority as it's not as horrible as it used to be.

**Comment by dsrbecky** [comment]
At some point, I have also done a lot of work to improve go build times (it used to be forced to run single-threaded; improving the cmake files to enable parallel builds for Go was a massive improvement to incremental go builds).

PS: All go commands get executed as part of cmake's link rule.  I didn't bother fixing that, as it is just implementation detail.  Just be mindful that when build says "Linking gapis", it means "compiling and linking gapis", and the linking part is pretty darn quick.. nothing to worry about (well, it used to be noticeable when all links were single-threaded, with the parallel implementation all the dozens of executables and test kick of at the same time, so negligible linking time now).

PPS: The current bottleneck for incremental work is usually just the time it takes to compile the gles, gles_test, vulkan, and vulkan_test packages.  All taking about half a minute, but all done in parallel now.

Bluntly closing the issue, as I have no more ideas on how the build times could be improved (other then avoiding the generated C++ and Go mutate code).
