### ISSUE TITLE
Texture data missing in a Vulkan trace

### ISSUE THREAD

**Issue by pmuetschard** [google/gapid#1235]
Tracing https://github.com/LunarG/VulkanSamples/blob/master/demos/cube.cpp (on Desktop Linux), the cube texture is shown as all zero in the texture view. This appears to be due to how the texture is initialized:

```
272: vkCreateImage(device:28500048, pCreateInfo:*0x00007ffde4461f90, pAllocator:(nil), pImage:*0x00007ffde4462ce0)->0
273: vkGetImageMemoryRequirements(device:28500048, image:28480064, pMemoryRequirements:*0x00007ffde4461f40)
274: vkAllocateMemory(device:28500048, pAllocateInfo:*0x00007ffde4462cf0, pAllocator:(nil), pMemory:*0x00007ffde4462d10)->0
275: vkBindImageMemory(device:28500048, image:28480064, memory:29320992, memoryOffset:0)->0
276: vkGetImageSubresourceLayout(device:28500048, image:28480064, pSubresource:*0x00007ffde4461f30, pLayout:*0x00007ffde4461f60)
277: vkMapMemory(device:28500048, memory:29320992, offset:0, size:262144, flags:0, ppData:*0x00007ffde4461f28)->0
278: vkUnmapMemory(device:28500048, memory:29320992)
```

Note that the texture is 256x256 RGBA8 which matches the size of the mapped memory (262144). I have not exported the observed memory to verify its content, but I did check that it is not all zeros and it looks like color data.

Trace: https://drive.google.com/open?id=0B1KipO2Z_BxDYlMyekFlcVY2c3c

**Comment by AWoloszyn** [comment]
Thanks for the note. This is because right now, we do not show textures that map into Linear memory. In fact this is the only sample I have seen that uses Linear texture memory at all. We tend to only show images that use VkCmdCopyBufferToImage.

However, just to make sure, this SHOULD likely show up if you do a mid-execution capture, rather than starting from the beginning of the trace.

**Comment by pmuetschard** [comment]
With MEC, the texture doesn't show up at all (i.e. the texture list is empty).
Trace: https://drive.google.com/open?id=0B1KipO2Z_BxDRjFkY2xka015dzg

**Comment by ben-clayton** [comment]
Added to milestone - we can remove if this isn't deemed important enough to block the release.

**Comment by pmuetschard** [comment]
I just opened the MEC trace again and now the texture does show up as Andrew expected. I don't know if I was blind, or looking at the wrong thing. Tracing from start, does still show zeros.

**Comment by Qining** [comment]
Vulkan Textures are disappeared again in UI now.

**Comment by ben-clayton** [comment]
Any updates on this?

**Comment by Qining** [comment]
As for my follow-up at Nov 16, the issue has been fixed.

**Comment by ben-clayton** [comment]
Thanks
