### ISSUE TITLE
Modifying a SPIR-V shader to something invalid panics the server

### ISSUE THREAD

**Issue by pmuetschard** [google/gapid#1247]
I mistakenly added OpNoop instead of OpNop and booom.

Ben says the offending line is:
https://github.com/google/gapid/blob/cce0f7e1fae67af341726ad6bb8f78f006e89fab/gapis/api/vulkan/resources.go#L724

- You cannot return nil there

**Comment by ben-clayton** [comment]
Also:

https://github.com/google/gapid/blob/cce0f7e1fae67af341726ad6bb8f78f006e89fab/gapis/api/vulkan/resources.go#L736-L742

The type you want is `memory.Size`.

**Comment by Qining** [comment]
@ben-clayton I think the TODO comment is stale now and we should remove it? We've been using `memory.Size` for a while for the `CodeSize`.

**Comment by Qining** [comment]
@ben-clayton, oops, sorry, I forget the memory.Size is just an alias of uint64

**Comment by ben-clayton** [comment]
An alias is not like a C++ typedef - it is a distinct type

**Comment by ben-clayton** [comment]
If the hack has been removed, then feel free to drop the comment. I'm not sure what's hack and what's non-hack here.

**Comment by Qining** [comment]
Not sure either, I will dig deeper to check.
