### ISSUE TITLE
Certain frames differ between FBO and Replay

### ISSUE THREAD

**Issue by baldwinn860** [google/gapid#1261]
Robot has found that FBOs do not match replays on either the first frame for many apks, or during a layout switch (going from portrait to landscape mode). This causes SXS Video to error since one frame has gone over the difference threshold.

This may be a minor problem but it does diminish the usefulness of Robot.

 - Some possible fixes (in preferential order):
   - fix replay so the first frame and layout swaps match observed frames properly
   - detect and ignore the first frame or layout swap frame
   - only have SXS Video error if the average frame difference is above a threshold (this means we may start to get some false positives for potentially bad errors)

**Comment by ben-clayton** [comment]
There shouldn't be any difference at all. We should have identical frames, always.
