### ISSUE TITLE
UI becomes janky during trace capture

### ISSUE THREAD

**Issue by andreasbhansen** [google/gapid#1360]
I'm using GAPID as an alternative to the previous Android Studio GPU Monitor, as it has been removed from Android Studio 3.0.
Now, my main question is how to properly record and analyze animated interfaces using GAPID.

Method: I start a GAPID trace capture, automatically executing the chosen app on my USB connected Nexus 5X. I then click a button to play an animation in the app, however the animation becomes super janky and the app only renders a few frames of it. If I run the same animation without the trace capturing, the animation is perfectly smooth.

Thus, the results displayed in GAPID is not anywhere representative to the actual performance of the animation/interface.

Is this intended behaviour? Are there other, better methods to analyze animations than GAPID?

Thanks.

**Comment by ben-clayton** [comment]
Hi @andreasbhansen,

Tracing performance is highly dependent on the amount of data being sent to the graphics driver (and therefor being recorded into the trace).

In our experiences tracing standard Java applications is normally not too bad on performance, but apps that make use of external textures (camera or video feeds) are known to have poor performance.

If you are happy sharing the application with me, I can take a look to see if there are any obvious bottlenecks that could be optimized.

Many thanks,
Ben

**Comment by AWoloszyn** [comment]
There have been a ton of improvements in this area. Please feel free to re-open if this is still a significant problem.
