### ISSUE TITLE
MEC tracing for Vulkan is broken

### ISSUE THREAD

**Issue by Qining** [google/gapid#1379]
The problem is in https://github.com/google/gapid/commit/45b4728a952df770d0389e2ff2bbe32bf35b2e19, the call to `saveInitialSate()`.
@dsrbecky Simply commenting out the call fixes the problem for Vulkan.

**Comment by dsrbecky** [comment]
Hmmm, I tried a quick Vulkan MEC trace locally and it did work for me... I will try again.
