### ISSUE TITLE
Update the vulkan layer to play well with the new loader.

### ISSUE THREAD

**Issue by AWoloszyn** [google/gapid#1407]
See: https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/loader/LoaderAndLayerInterface.md#layer-conventions-and-rules

**Comment by Qining** [comment]
This should have been fixed already.
Tested with Validation layers and Vulkan loader 1.1.70, both tracing and replaying work fine.

**Comment by AWoloszyn** [comment]
Fixed!
