### ISSUE TITLE
Hide deleted resources.

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#1422]
The texture view shows textures that have since been deleted. This is probably true of other resource types like shaders too.
We should hide these (with maybe an option to show all resources regardless of time).

**Comment by AWoloszyn** [comment]
As a stop-gap to debug your issue more quickly:
You should be able to use the state block to see which images are currently in memory. The view in the state block is up to date, just not the texture view.

Personally for things like this I use the command line tools included in the build. I apologize if I don't have the GLES filter (I work primarily with Vulkan), but it should be similar, and you can get it from the state block.

`gapit state --depth 6 --filter "[root, Images, *, Info, Extent]" trace.gfxtrace`

which provides an output of:

```
 root:
    ├── Images:
    │   ├── 64772912:
    │   │   ├── Info:
    │   │   │   ├── Extent:
    │   │   │   │   ├── Width: 256
    │   │   │   │   ├── Height: 512
    │   │   │   │   └── Depth: 1
    │   ├── 91121968:
    │   │   ├── Info:
    │   │   │   ├── Extent:
    │   │   │   │   ├── Width: 1920
    │   │   │   │   ├── Height: 1080
    │   │   │   │   └── Depth: 1

```

**Comment by kuszczakadam** [comment]
so in the State -> Objects -> Textures I have only 1 texture which is EXTERNAL_OES from camera, I don't see others and I am quite sure there should be there. Even stuff like buttons on the screen which are shown in Textures tab.

**Comment by AWoloszyn** [comment]
This is fixed now for textures.
