### ISSUE TITLE
Lots of errors logged from gapir

### ISSUE THREAD

**Issue by pmuetschard** [google/gapid#1435]
On Windows.
Open [this trace](https://drive.google.com/open?id=1JU_1YxkQfcLuioWWh4fMa_t2KBZbldqf) of Templerun2 captured on an S8.
Notice all the errors logged from gapir regarding calling of unsupported functions `glDeleteShader`, `glDeleteTextures`, `glDelete...`. Ala:
```
E 00:42:53.958 gapir Attempted to call unsupported function glDeleteShader
└──      gles_gfx_api.cpp:15701
```

I find it hard to believe that these functions are unsupported and I have not seen the error messages on other traces.

**Comment by ben-clayton** [comment]
Perhaps they're being called when there's no context. We are required to re-resolve the functions at certain points. It's not impossible that one of these resolves happened when the context was unbound / deleted.

**Comment by pmuetschard** [comment]
The application has a single context and thread and there is no call to eglDestroyContext.

**Comment by pmuetschard** [comment]
Also, I'm not seeing the same error reported on Linux.

I'm now also getting the same errors on a trace of VVR.

**Comment by pmuetschard** [comment]
The plot thickens: the first printed error complains about glDeleteRenderbuffers, however the trace does not actually contain a call to this function. Sounds more and more like a bug on our side.

**Comment by ben-clayton** [comment]
There's code to delete objects at the end of replay, so if there was a framebuffers created, we'll generate a command to delete it.
