### ISSUE TITLE
Trying to trace a Windows app fails because it's trying to find an adb

### ISSUE THREAD

**Issue by BuschnicK** [google/gapid#1467]
I'm trying to trace a native x64 Vulkan app on Windows 10. It fails because it's trying to find an adb which of course doesn't exist.

```
Press enter to stop capturing...
17:57:20.064 F: <gapit> Main failed
Error: 
   Cause: adb could not be found from ANDROID_HOME or PATH
ANDROID_HOME: 
PATH: [snip]
search: [adb]
Tracing failed:
com.google.gapid.server.ChildProcess$EarlyExitException: gapit has exited with exit code 1
	at com.google.gapid.server.ChildProcess.runProcess(ChildProcess.java:98)
	at com.google.gapid.server.ChildProcess$1.run(ChildProcess.java:69)
```

**Comment by AWoloszyn** [comment]
Thank you for the report. I will take a look at fixing this, but I won't have the time until some point next week.

As a temporary solution to unblock you, you can grab just the platform-tools from https://developer.android.com/studio/releases/platform-tools.html, which is a very small download. All you would have to do is then set the path to adb.exe under edit->preferences.

**Comment by AWoloszyn** [comment]
This is no longer a problem.
