### ISSUE TITLE
DCE bug with eglCreateImageKHR / glEGLImageTargetTexture2DOES.

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#1498]
We're getting crashes in compat for `glEGLImageTargetTexture2DOES` as the `eglImage` is nil.

Just before this crash a preceding `eglCreateImageKHR` asserts with `assert(image != null)`.

It appears this only happens with DCE enabled, and is likely a missing dependency between EGLImages and textures.

I'll add a work around for V1.0.0 and try to fix this in the first point release.

**Comment by AWoloszyn** [comment]
Fixed!
