### ISSUE TITLE
The gapis server has exited with an error code of: 2

### ISSUE THREAD

**Issue by mugabutie** [google/gapid#1507]
GAPID Version: 1.0.0:024668b60c6c6f7cfcbcaf6b9fda74960f9f7ac4
OS: windows 7 amd64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

**Comment by ben-clayton** [comment]
I'm afraid there is not enough information to go on here.
