### ISSUE TITLE
GAPID Packaging

### ISSUE THREAD

**Issue by pmuetschard** [google/gapid#152]
# Package Layout

## Windows
The installer allows the user to install the package anywhere, suggesting `%PROGRAMFILES%\gapid`. The installer will install GAPID into the selected folder with the following structure. Along with an installer, we provide a `.zip` file that can be extracted anywhere. Both will follow the same structure:
```
<install root or gapid inside .zip>\
├─ jre\...
├─ lib\
│  ├─ GraphicsSpyLayer.json
│  ├─ gapic.jar
│  ├─ libgapii.dll
│  ├─ libVkLayer_VirtualSwapchain.dll
│  └─ VirtualSwapchainLayer.json
├─ strings\en-us.stb
├─ build.properties
├─ gapid-arm64-v8a.apk
├─ gapid-armeabi-v7a.apk
├─ gapid-x86.apk
├─ gapid.bat (shell script to launch the client)
├─ gapir.exe
├─ gapis.exe
├─ gapit.exe
├─ libgcc_s_seh-1.dll
├─ libstdc++-6.dll
└─ libwinpthread-1.dll
```

## MacOS
The built package consists of a `.dmg` disk image containing the `GAPID.app` application and link to `/Applications` to make "installing" easy. The `GAPID.app` can be run from anywhere and follows the following structure:
```
GAPID.app/
└─ Contents/
   ├─ MacOS/
   │  └─ <see below>
   ├─ Resources/GAPID.icns
   └─ Info.plist
```
Along with the `.dmg` disk image, we also provide a `.zip` file with the same content's as inside the `Contents/MacOS/` folder of the `.app` package:
```
<Content/MacOS inside .app or gapid inside .zip>/
├─ jre/...
├─ lib/
│  ├─ gapic.jar
│  └─ libgapii.dylib
├─ strings/en-us.stb
├─ build.properties
├─ gapid-arm64-v8a.apk
├─ gapid-armeabi-v7a.apk
├─ gapid-x86.apk
├─ gapid (shell script to launch the client)
├─ gapir
├─ gapis
└─ gapit
```
When running the `.app` application, the `gapid` script is invoked. When using the `.zip` file, the only way to run the application is via the terminal by running the `gapid` script or the executables.

## Linux
We provide a Debian `.deb` package and a `.zip` file with the same contents. The package installs into `/opt/gapid`, while archives can be expanded anywhere. The Debian package depends on `openjdk-8-jre` and neither it nor the `.zip` archives contain the JRE. The launcher script looks for `java` first on the `$PATH`, then `$JAVA_HOME` and finally the hard-coded `/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java`, which the `openjdk-8-jre` package provides.
```
/{opt|wherever}/gapid/
├─ lib/
│  ├─ gapic.jar
│  ├─ GraphicsSpyLayer.json
│  ├─ libgapii.so
│  ├─ libVkLayer_VirtualSwapchain.so
│  └─ VirtualSwapchainLayer.json
├─ strings/en-us.stb
├─ build.properties
├─ gapid-arm64-v8a.apk
├─ gapid-armeabi-v7a.apk
├─ gapid-x86.apk
├─ gapid (shell script to launch the client)
├─ gapir
├─ gapis
└─ gapit
```

**Comment by ben-clayton** [comment]
We also want interceptor libraries for the host targets

**Comment by ianthehat** [comment]
The arch stuff was only because we had a single package download across all platforms, I agree it should die.
All the android stuff should be inside the apk, but you will have a collection of apks. Having lots of {abi} directories with gapid.apk in them seems silly, let's change the apk name to gapid_{abi}.apk and put them all in one folder
You do not need the .a files

**Comment by ben-clayton** [comment]
I agree with everything Ian said. I know, I'm scared too.

**Comment by ben-clayton** [comment]
> The msvc dlls shouldn't be needed. We're not building with the VS toolchain.

**Comment by ben-clayton** [comment]
I'd propose:

```
├─ lib\
│  ├─ GraphicsSpyLayer.json
│  ├─ libgapii.dll
│  ├─ libVkLayer_VirtualSwapchain.dll
│  ├─ libVkLayerGraphicsSpy.dll
│  └─ VirtualSwapchainLayer.json
├─ strings\en-us.stb
├─ runtime\... (contains JRE)
├─ gapid-arm64-v8a.apk
├─ gapid-armeabi-v7a.apk
├─ gapid-x86.apk
├─ gapir.exe
├─ gapis.exe
├─ gapid.exe
├─ gapit.exe
├─ gapid.cfg
└─ gapic.jar
```

`GAPID.ico` should be embedded in the exe.

**Comment by pmuetschard** [comment]
> I agree with everything Ian said. I know, I'm scared too.

Updated to reflect all the things Ian said, shudder.

> The msvc dlls shouldn't be needed. We're not building with the VS toolchain.

These (and the packager.dll) are put there by the javapackager tool and I assume they are needed by the gapid.exe created by the same.

> GAPID.ico should be embedded in the exe.

Ditto.

> <Ben's structure>

Unfortunately, the `app\` folder is imposed by the packager tool. However, I'm starting to think that the javapackager tool may not give us all that much benefit and we could just write our own launcher script... in... sigh... go.

**Comment by ben-clayton** [comment]
> These (and the packager.dll) are put there by the javapackager tool

That's crap. How big are they?

**Comment by ben-clayton** [comment]
> write our own launcher script... in... sigh... go.
SGTM. We'd could to do some voodoo to embed the icon.

**Comment by pmuetschard** [comment]
> How big are they?

All together, 2.5MB

**Comment by ben-clayton** [comment]
That's not too bad. Let's not worry about it for now.

**Comment by ianthehat** [comment]
That's twice in one week Ben, maybe you should make a doctor's appointment?

**Comment by ben-clayton** [comment]
Perhaps you're making more sense.

**Comment by pmuetschard** [comment]
It turns out that libVkLayerGraphicsSpy is not needed on the desktop. Removed.
Also removed Vulkan from OSX.

**Comment by ben-clayton** [comment]
Resolved?

**Comment by pmuetschard** [comment]
I've updated it with the latest and greatest details. The only thing remaining is a Windows installer, whose value is debatable at this time.

**Comment by ben-clayton** [comment]
Perhaps you could take the latest details and add it as a package.md document? Perhaps in the kokoro directory?
