### ISSUE TITLE
Codegen

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#1540]
All the features that need implementing and testing in the compiler:

### Types (target space)
- [x] Arrays
- [x] Bitfields
- [x] Enums
- [x] Maps
- [x] Pointers (`T*`)
- [x] Primitives (`u32`, `f32`, `bool` ...)
- [x] References (`ref!T`)
- [x] Strings
- [x] Structs (`class T`)

### Types (storage space)
- [x] Arrays
- [x] Primitives (`u32`, `f32`, `bool` ...)
- [x] Pointers (`T*`)
- [x] Structs (`class T`)

### Expressions
- [x] `ArrayIndex`
- [x] `ArrayInitializer`
- [x] `BinaryOp`
  - [x] Integer: `+`, `-`, `*`, `/`, `<<`, `>>`, `|`, `&`, `==`, `!=`, `<`, `<=`, `>`, `>=`
  - [x] Float: `+`, `-`, `*`, `/`, `==`, `!=`, `<`, `<=`, `>`, `>=`
  - [x] String: `+`, `==`, `!=`, `<`, `<=`, `>`, `>=`
- [x] `BitTest`
- [x] `BoolValue`
- [x] `Call`
  - [x] Externs
  - [x] Subroutines
- [x] `Cast`
- [x] `ClassInitializer`
- [x] `Clone`
- [x] `Create`
- [x] `EnumEntry`
- [x] `Float32Value`
- [x] `Float64Value`
- [x] `Global`
- [x] `Ignore`
- [x] `Int16Value`
- [x] `Int32Value`
- [x] `Int64Value`
- [x] `Int8Value`
- [x] ~~`Label`~~ (removed from language)
- [x] `Length`
  - [x] Map
  - [x] String
- [x] `Local`
- [x] `Make`
- [x] `MapContains`
- [x] `MapIndex`
- [x] `Member`
- [ ] `MessageValue`
- [x] `Null`
- [x] `Observed`
- [x] `Parameter`
- [x] `PointerRange`
- [ ] `Select`
  - [x] Case matched
  - [ ] Case not matched
- [ ] `SliceIndex`
  - [x] In bounds
  - [ ] Out of bounds
- [ ] `SliceRange`
  - [x] In bounds
  - [ ] Out of bounds
- [x] `StringValue`
- [x] `Uint16Value`
- [x] `Uint32Value`
- [x] `Uint64Value`
- [x] `Uint8Value`
- [x] `UnaryOp`
- [x] `Unknown`

### Statements
- [x] `Abort`
- [x] `ArrayAssign`
- [x] `Assign`
  - [x] `==`
  - [x] `+=`
  - [x] `-=`
- [x] `Branch`
- [x] `Call`
  - [x] Externs
  - [x] Subroutines
- [x] `Copy`
- [x] `DeclareLocal`
- [x] `Fence`
- [x] `Iteration`
- [x] `MapAssign`
- [x] `MapIteration`
- [x] `MapRemove`
- [ ] `Read`
- [x] `Return`
- [ ] `SliceAssign`
  - [x] In bounds
  - [ ] Out of bounds
- [x] `Switch`
- [x] `Write`

### Reference Counting
- [x] Strings
- [x] Slices
- [x] References (`ref!T`)
- [x] Maps
- [x] Transitive releases (fields within references being released when the object is freed)

**Comment by AWoloszyn** [comment]
Done!
