### ISSUE TITLE
Add support for aggregate parameters / return values

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#1542]
Unfortunately it would appear that LLVM does not implement ABI rules for calling conventions - this [is left up to the frontend](https://github.com/llvm-mirror/clang/blob/master/lib/CodeGen/TargetInfo.cpp).

GVR has a number of functions that pass struct parameters.
Vulkan has `vkCmdSetBlendConstants` which passes a `f32[4]` array.

If we intend for the compiler to implement functions with a true API signature then we'll have to implement the ABI calling conventions. [AMD64](https://github.com/hjl-tools/x86-psABI/wiki/x86-64-psABI-r252.pdf) looks particularly fun.

Using pointers-to-structs appears to be fine, which may be enough for our needs.

**Comment by AWoloszyn** [comment]
Could we hand-write the special cases where we have to pass aggregates by value in C++?

In vulkan, afaik, there is JUST the one command, not sure how bad it looks in GVR.

**Comment by AWoloszyn** [comment]
Worked around!
