### ISSUE TITLE
Framebuffer images missing

### ISSUE THREAD

**Issue by jherico** [google/gapid#1545]
I'm having a similar issue to #1446 with GLES captures from my android device being played back on my Windows desktop.  I'm running the 1.0 release and testing with a Google Pixel device.  

Attaching 
[hifiinterface_20180112_2357.zip](https://github.com/google/gapid/files/1628164/hifiinterface_20180112_2357.zip)

**Comment by ben-clayton** [comment]
Hi @jherico,

Thank you for the bug report.
I can reproduce and I'm investigating.

Cheers,
Bem
