### ISSUE TITLE
Bazel clean ups

### ISSUE THREAD

**Issue by pmuetschard** [google/gapid#1558]
- [x] Remove all cmake things 
- [x] Remove git modules
- [ ] Proper visibility rules
- [ ] Fix hdrs attributes in cc libraries
- [x] Rename .inl files to .inc
- [x] Add/Remove manual tags
- [x] Create run targets that work
- [ ] Break apart java rules
- [x] Investigate the Windows SDK rule (remove?)

**Comment by ben-clayton** [comment]
I've ticked the bits I think are done. @pmuetschard please can you take a look?

**Comment by pmuetschard** [comment]
Done. The remainder is quite unimportant, so we can close this bug if you'd like.
