### ISSUE TITLE
The gapis server has exited with an error code of: 2

### ISSUE THREAD

**Issue by interboboy** [google/gapid#1559]
GAPID Version: 1.0.0:024668b60c6c6f7cfcbcaf6b9fda74960f9f7ac4
OS: mac os x x86_64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

**Comment by ben-clayton** [comment]
Hello @interboboy,

Unfortunately there's simply not enough information here to go on.
Was there a stack trace printed when you hit this crash?

Cheers,
Ben
