### ISSUE TITLE
The gapis server has exited with an error code of: 2

### ISSUE THREAD

**Issue by zhgyee** [google/gapid#1580]
GAPID Version: 1.0.2:8aa5252a138e27a17f162f729ca6d62117d23286
OS: windows 10 amd64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

**Comment by zhgyee** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x760933]

goroutine 5715 [running]:
github.com/google/gapid/core/app/crash/reporting.Reporter.sendReport(0x265b375, 0x5, 0xc049590ff0, 0x2e, 0xc042261db0, 0xa, 0xc04a5dca74, 0xb, 0x3ef1cc0, 0xc055362e00, ...)
	T:/src/github/src/github.com/google/gapid/core/app/crash/reporting/reporting.go:107 +0x3e3
github.com/google/gapid/core/app/crash/reporting.Reporter.reportMinidump(0x265b375, 0x5, 0xc049590ff0, 0x2e, 0xc042261db0, 0xa, 0xc04a5dca74, 0xb, 0xc049f5bef0, 0x4d, ...)
	T:/src/github/src/github.com/google/gapid/core/app/crash/reporting/reporting.go:145 +0x26d
github.com/google/gapid/core/app/crash/reporting.ReportMinidump(0x265b375, 0x5, 0xc049590ff0, 0x2e, 0xc042261db0, 0xa, 0xc04a5dca74, 0xb, 0xc049f5bef0, 0x4d, ...)
	T:/src/github/src/github.com/google/gapid/core/app/crash/reporting/reporting.go:89 +0xbf
github.com/google/gapid/gapis/replay/executor.executor.handleCrash(0xde4e5000000200, 0xc050042000, 0x199c, 0x1a80, 0xc053b58000, 0x4812, 0x5000, 0xc0554a4000, 0xbb51ac, 0x10ffffc, ...)
	T:/src/github/src/github.com/google/gapid/gapis/replay/executor/executor.go:197 +0x48d
github.com/google/gapid/gapis/replay/executor.executor.handleReplayCommunication(0xde4e5000000200, 0xc050042000, 0x199c, 0x1a80, 0xc053b58000, 0x4812, 0x5000, 0xc0554a4000, 0xbb51ac, 0x10ffffc, ...)
	T:/src/github/src/github.com/google/gapid/gapis/replay/executor/executor.go:160 +0x4eb
github.com/google/gapid/gapis/replay/executor.executor.execute.func1(0xde4e5000000200, 0xc050042000, 0x199c, 0x1a80, 0xc053b58000, 0x4812, 0x5000, 0xc0554a4000, 0xbb51ac, 0x10ffffc, ...)
	T:/src/github/src/github.com/google/gapid/gapis/replay/executor/executor.go:97 +0xef
created by github.com/google/gapid/gapis/replay/executor.executor.execute
	T:/src/github/src/github.com/google/gapid/gapis/replay/executor/executor.go:109 +0x5b4

**Comment by AWoloszyn** [comment]
Need more info: Specifically a gfxtrace file if you have one.
