### ISSUE TITLE
Stop adding TRANSFER_DST_BIT to images in MEC.

### ISSUE THREAD

**Issue by AWoloszyn** [google/gapid#1616]
We should do different things depending on the contents of img.Info.Usage

This is for single sampled non-depth images.

1) If it contains VK_IMAGE_USAGE_TRANSFER_DST_BIT, then prime images how we are
2) elif it contains VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT,
    Generate a texture + quad + shader + graphics pipeline and prime it by rendering into it
3) elif it contains VK_IMAGE_USAGE_STORAGE_BIT, then create a "compute" pipeline & 
    copy into the image
4) else, there are no valid contents that we can add to the image.

**Comment by Qining** [comment]
PR: #1656, #1739, #1750, #1756 take care of the color/depth/stencil attachment images.

Storage bit images are still not handled.
