### ISSUE TITLE
GAPII initial connection seems to take a long time

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#1619]
Something in master seems to have made the initial connection stall. I'm not seeing this happen in `v.1.0.3`:

```
10:24:17.411 I: [start] <gapit> Installing interceptor libraries
10:24:17.958 I: [start] <gapit> GVR library not found
10:24:18.090 I: [start] <gapit> Waiting for connection to localhost:53125...
10:24:57.367 I: <gapit> Creating file '/Users/bclayton/Documents/blah.gfxtrace'
10:24:57.869 I: <gapit> Capturing: 16B in 0s
10:24:58.875 I: <gapit> Capturing: 32.80KB in 1.003s
```

Note the 40 second delay between `Waiting for connection...`  and `Creating file`.

**Comment by ben-clayton** [comment]
Could this have anything to do with the flock stuff @Qining ?

**Comment by AWoloszyn** [comment]
I have noticed this as well, but I have not yet had the chance to look into it.

**Comment by ben-clayton** [comment]
Whatever caused this, appears to have fixed itself for me.
