### ISSUE TITLE
Frames shown are different than output on device screen (Unity3D)

### ISSUE THREAD

**Issue by alexbu92** [google/gapid#1621]
When using GAPID to debug Unity3D applications built for Android using OpenGL ES 3, the frames shown in the debugger are extremely different from the what I see on the device's screen in certain cases. It probably has something to do with transparency since it's only when I introduce alpha mask textures in my shaders that it displays this behavior. Typically, in GAPID I see what I would actually like to see on my device while my device shows something different, hence the debugging. Is there some underlying reason that there is a difference? It might help in actually debugging the erroneous behavior on the device.

**Comment by ben-clayton** [comment]
Hi @alexbu92,
GAPID does some translation to replay OpenGL ES on desktop GL. It is possible there's a bug in this code.
Are you willing and able to share a trace file demonstrating this issue? It would be a great help in figuring out the problem.

Cheers,
Ben

**Comment by alexbu92** [comment]
[gapid_trace.zip](https://github.com/google/gapid/files/1728862/gapid_trace.zip)

This is the trace. That is what I was expecting to see, but on my device I see a solid grey with a slightly darker row on the right. Texture 31 is supposed to be my alpha mask from which I sample the red channel. In this debug build I simply used a shader that displayed this texture full screen to see what was going on.

**Comment by alexbu92** [comment]
[gapid_trace2.zip](https://github.com/google/gapid/files/1759359/gapid_trace2.zip)

@ben-clayton  this is another trace with the same result: What I see in GAPID is what I would want to see on my device but instead on the device all I see is a dark grey fill. One additional detail since last time is that this only happens on Nougat devices while Oreo devices work fine. Also, I get a repeating "bindTextureImage: clearing GL error: 0x502" in the adb log when running on Nougat devices.

**Comment by ben-clayton** [comment]
Hi @alexbu92 ,

Thank you for the reports. Sorry for the delay in looking into this, I've been working on something that is particularly high priority (it's blocking us from doing any more releases). Fortunately, I'm very close to finishing this work, so I'll hopefully be taking a look into this later this week.

Thank you for your patience.

Cheers,
Ben

**Comment by alexbu92** [comment]
@ben-clayton  Thank you for your interest. Just wanted to add another clue: by coincidence the Nougat device has a Mali G-71 (Galaxy Note 8) while the Oreo devices (Nexus 6P and OnePlus 3) both have an Adreno. Wondering if maybe the android version has nothing to do with it.

**Comment by ben-clayton** [comment]
Hi @alexbu92,

I've finally found the time to look into this.

There are two suspicious things with these traces which are highlighted in the report tab:

From `gapit_trace.gfxtrace`:
Invalid Operation
 * `30861`: Error `glBindTexture`
 * `30869`: Error `glBindTexture`

Both of these are erroring because you've bound the texture as an external texture (`GL_TEXTURE_EXTERNAL_OES`), and then (where it errors) you attempt to bind it as a texture 2D (`GL_TEXTURE_2D`). This is illegal. The texture takes the kind on the first binding, so texture 31 will be an external texture.

As for why it looks different - it's probable this is just caused by undefined behavior due to the errors described above.

Does this resolve your original question?

Many thanks,
Ben

**Comment by alexbu92** [comment]
Thanks for the response but unfortunately I don't think that was it as those two keep showing up in the report even now that everything works correctly.  I think those two glBindTextures fail because something is still initializing at that point but they get called every frame so they should be working.

**Comment by ben-clayton** [comment]
I'm happy to take another look if you don't mind sending another trace.

**Comment by alexbu92** [comment]
Is there a way to cut frames from a trace? Trace capturing is slowing the application down quite significantly which means that the trace has to run for quite some time before the app reaches the point where everything is set up and it is executing the aforementioned alphamasking operation. The trace files way up to 1gb.

**Comment by ben-clayton** [comment]
Currently, I'm afraid not. We are working on adding mid-execution capture support for OpenGL ES, which should fix this issue.
