### ISSUE TITLE
adb can find my device, the GAPID App not (OSX)

### ISSUE THREAD

**Issue by Grunewald17** [google/gapid#1649]
I've tested it with my MacBook Pro (El Captain) and my Desktop (High Sierra).

Both can not find my 4 Android Devices (connected via USB).

GAPID Version: 1.03

Java Version 9 Build 181  and Java Version 8

**Comment by Grunewald17** [comment]
It seems that you can not connect multiple devices, and also the list is always empty after search (you have to select a device, but it looks like no device found)

**Comment by ben-clayton** [comment]
Thank you for the bug report @Grunewald17,

> It seems that you can not connect multiple devices

This is not a known issue and we will investigate. Are you able to share what your devices are?

> the list is always empty after search (you have to select a device, but it looks like no device found).

I have also observed this. We will certainly fix this.

Thanks,
Ben

**Comment by Grunewald17** [comment]
Devices: 

- Motorola G5 (not Plus) with Android 7.0 
- Asus ZenPad P01MA with Android 6.0.1
- Acer A500 with Android 5.1

The only device that was recognized by GAPID was my Motorola G5 with Android 7.0. All other devices are not found by GAPID. Adb in the Terminal have found all my devices. Don't know why GAPID can not list these.

There is also a trick to not quit the Android Studio or Eclipse if you want to capture a trace: 

Start the GAPID App first, then Android Studio or Eclipse, then you can transmit a new App version and then capture a trace, without to open close both apps again and again.

It would be nice to have a "Switch off debug" Add-On for Android Studio and Eclipse to switch off the whole debug function. Then you don't need this trick.

Hint to Android Studio: I prefer Eclipse, because Android Studio is to slow and complicated to handle Android Apps (i7 Skylake 4 GHz, 32 GB Ram, GTX 1060 6 GB and 750 GB SSD). Android Studio is no fun. Maybe you can make it easier, like Apple devices are... no script editing (to include Android Libs)... more easy GUI supported Settings. Then maybe I would use Android Studio.

Thanks.

**Comment by Grunewald17** [comment]
Also a bug: if you connect a device after you started the GAPID App, then you have to close GAPID and open it again.

**Comment by ben-clayton** [comment]
Hi @Grunewald17,

For the ASUS device, does it have the `Auto-Start Manager`? If so please can you [allow GAPID APKs to start on device boot as described here?](https://www.asus.com/support/FAQ/1013752/#)

Many thanks,
Ben

**Comment by Grunewald17** [comment]
Yes, but this is not relevant, because the GAPID can not find the Device, so the APK cannot be uploaded. Ergo, Auto-Start Manager has nothing to do.

**Comment by ben-clayton** [comment]
GAPID actually installs an APK to find out more information about the device before it populates the list. If that APK cannot be run, the device will never appear.

**Comment by Grunewald17** [comment]
Interesting. After Auto-Start: "Allow" GAPID, then it was working with the Asus Device too. Thanks.

**Comment by Grunewald17** [comment]
Ups not working... found and connect but then crashed:

Press enter to stop capturing...
15:37:59.174 I: [gapidapk.EnsureInstalled] <gapit> Examining gapid.apk on host...
15:37:59.179 I: [gapidapk.EnsureInstalled] <gapit> Looking for gapid.apk...
15:37:59.852 I: [gapidapk.EnsureInstalled] <gapit> Found gapid package...
15:38:00.742 I: <gapit> Adding new device
15:38:00.742 I: <gapit> Device list:
15:38:00.742 I: <gapit>   FANPFP049897
15:38:01.574 I: <gapit> Package is debuggable
15:38:01.709 I: [start] <gapit> Turning device screen on
15:38:01.751 I: [start] <gapit> Checking for lockscreen
15:38:01.788 I: [start] <gapit> Checking gapid.apk is installed
15:38:01.788 I: [start] <gapit> Forwarding
15:38:01.827 I: [start] <gapit> Starting activity in debug mode
15:38:02.950 I: [start] <gapit> Forwarding TCP port 56323 -> JDWP pid 26389
15:38:02.961 I: [start] <gapit> Connecting to JDWP
15:38:02.966 I: [start] <gapit> Waiting for ApplicationLoaders.getClassLoader()
15:38:02.971 W: [start] <gapit> Couldn't break in ApplicationLoaders.getClassLoader. Vulkan will not be supported.
15:38:02.971 I: [start] <gapit> Waiting for Application Creation
15:38:02.973 I: [start] <gapit>    Waiting for Application.<init>()
15:38:04.764 I: [start] <gapit>    Waiting for android.app.Application.onCreate()
15:38:04.810 I: [start] <gapit> Installing interceptor libraries
15:38:05.348 I: [start] <gapit> GVR library not found
15:38:05.471 I: [start] <gapit> Waiting for connection to localhost:56308...
15:38:06.427 I: <gapit> Creating file '/Volumes/Leer/platform-tools/tracings/helike3d_20180301_1637.gfxtrace'
15:38:06.932 I: <gapit> Capturing: 16B in 0s
15:38:06.955 I: <gapit> EOF: 16B

**Comment by ben-clayton** [comment]
Is there anything in logcat that indicates why it stopped / crashed?

**Comment by Grunewald17** [comment]
No. With my Moto G5 it's working fine.

**Comment by gwangsc** [comment]
I found out that only the following steps work for me:
1. plug in the device
2. open gapid app
3. select device from the list. 

If I do 2 before 1, then I won't be able to see the device in the list.

**Comment by AWoloszyn** [comment]
We made a bunch of changes to the UI for tracing, this should be fixed now.
