### ISSUE TITLE
Incremental builds on Windows may use stale gapid.apk

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#1665]
@pmuetschard and I found a bug in the bazel build rules which means changes to the `AndroidManifest.xml` is not always used when building APKs. `gapid.apk` adds a hash of the source files to the `android:versionName` field, and this is used by `gapit` to decide whether we need to push a new apk to the device. Because this hash is not being updated, changes to any of `gapid.apk` (`libgapii.so`, `libinterceptor.so`, `deviceinfo`, etc) will not be visible post-build.

This appears to only affect Windows. We do not know why.

The work around is to manually uninstall the APK(s) (note there is a separate APK for armeabi and aarch64) before running gapit or gapis:

```
adb shell pm uninstall com.google.android.gapid.aarch64
adb shell pm uninstall com.google.android.gapid.armeabi
```

[The bazel bug is tracked here](https://github.com/bazelbuild/bazel/issues/4734).

**Comment by AWoloszyn** [comment]
Fixed upstream.
