### ISSUE TITLE
GAPIS mistimes connecting to gapid.apk when relaunching it.

### ISSUE THREAD

**Issue by baldwinn860** [google/gapid#1666]
If a device is already running gapid.apk, after having finished a replay, GAPIS will cause it to relaunch it when run from another GAPIT command. For some reason the timing of the relaunch coincides with GAPIS sending the connection request, which gets refused. For some reason this causes the GAPIT command to hang.

A hack bandaid to get this functionality working for robot is in #1663 by force-stopping the gapid.apk instances on the device.

**Comment by AWoloszyn** [comment]
Likely fixed with GRPC changes.
