### ISSUE TITLE
gapis crash in postImageData() when transforming vkDestroyInstance

### ISSUE THREAD

**Issue by y-novikov** [google/gapid#1682]
Since vkDestroyInstance is called after VkDestroyDevice, GetState(s).Devices.Get(vkDevice) is nil in https://github.com/google/gapid/blob/master/gapis/api/vulkan/read_framebuffer.go#L204
Looks like vkDestroyInstance needs some special treatment

Attached is a trace that reproduces this:
[angle_end2end_tests_20180226_1807.gfxtrace.zip](https://github.com/google/gapid/files/1772450/angle_end2end_tests_20180226_1807.gfxtrace.zip)

gapis Log:

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: Panic at command 860:vkDestroyInstance(instance: 20754784, pAllocator: 0):
runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: Panic at command 860:vkDestroyInstance(instance: 20754784, pAllocator: 0):
runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x241a571]

goroutine 37 [running]:
github.com/google/gapid/core/app/crash.Crash(0x2f29020, 0xc420211820)
	core/app/crash/crash.go:89 +0x131
github.com/google/gapid/core/app/crash.handler()
	core/app/crash/crash.go:56 +0x54
panic(0x2f29020, 0xc420211820)
	GOROOT/src/runtime/panic.go:491 +0x283
github.com/google/gapid/gapis/api.ForeachCmd.func1(0xc420e48e38, 0xc420e48e98)
	gapis/api/cmd_foreach.go:39 +0x29c
panic(0x3016560, 0x4cae490)
	GOROOT/src/runtime/panic.go:491 +0x283
github.com/google/gapid/gapis/api/vulkan.postImageData(0x4d069c0, 0xc420600ba0, 0x7fc10c0563c0, 0xc420898240, 0xc420731ee0, 0x10000002c, 0x8000000080, 0x8000000080, 0x4cd7400, 0xc4207d23f0, ...)
	gapis/api/vulkan/read_framebuffer.go:226 +0x6c1
github.com/google/gapid/gapis/api/vulkan.(*readFramebuffer).Color.func1(0x4d069c0, 0xc420600ba0, 0x4d3d800, 0xc42054db80, 0x4cd7400, 0xc4207d23f0)
	gapis/api/vulkan/read_framebuffer.go:151 +0xb3d
github.com/google/gapid/gapis/api/vulkan.(*readFramebuffer).Transform(0xc4207b8460, 0x4d069c0, 0xc420600ba0, 0x35c, 0x4d3d800, 0xc42054db80, 0x4cd7400, 0xc4207d23f0)
	gapis/api/vulkan/read_framebuffer.go:65 +0x402
github.com/google/gapid/gapis/api/transform.TransformWriter.MutateAndWrite(0xc420898240, 0x4cd5340, 0xc4207b8460, 0x4cd7400, 0xc4207d23f0, 0x4d069c0, 0xc420600ba0, 0x35c, 0x4d3d800, 0xc42054db80)
	gapis/api/transform/transforms.go:98 +0x89
github.com/google/gapid/gapis/api/transform.(*TransformWriter).MutateAndWrite(0xc4207d2780, 0x4d069c0, 0xc420600ba0, 0x35c, 0x4d3d800, 0xc42054db80)
	<autogenerated>:1 +0xa1
github.com/google/gapid/gapis/api/transform.(*fileLog).Transform(0xc4208440a0, 0x4d069c0, 0xc420600ba0, 0x35c, 0x4d3d800, 0xc42054db80, 0x4cd7400, 0xc4207d2780)
	gapis/api/transform/file_log.go:69 +0x962
github.com/google/gapid/gapis/api/transform.TransformWriter.MutateAndWrite(0xc420898240, 0x4cd5200, 0xc4208440a0, 0x4cd7400, 0xc4207d2780, 0x4d069c0, 0xc420600ba0, 0x35c, 0x4d3d800, 0xc42054db80)
	gapis/api/transform/transforms.go:98 +0x89
github.com/google/gapid/gapis/api/transform.(*TransformWriter).MutateAndWrite(0xc4207d27b0, 0x4d069c0, 0xc420600ba0, 0x35c, 0x4d3d800, 0xc42054db80)
	<autogenerated>:1 +0xa1
github.com/google/gapid/gapis/api/vulkan.(*VulkanTerminator).Transform(0xc4207d8e70, 0x4d069c0, 0xc420600ba0, 0x35c, 0x4d3d800, 0xc42054db80, 0x4cd7400, 0xc4207d27b0)
	gapis/api/vulkan/vulkan_terminator.go:445 +0x6b5
github.com/google/gapid/gapis/api/transform.TransformWriter.MutateAndWrite(0xc420898240, 0x4cd5240, 0xc4207d8e70, 0x4cd7400, 0xc4207d27b0, 0x4d069c0, 0xc420600ba0, 0x35c, 0x4d3d800, 0xc42054db80)
	gapis/api/transform/transforms.go:98 +0x89
github.com/google/gapid/gapis/api/transform.(*TransformWriter).MutateAndWrite(0xc4207d27e0, 0x4d069c0, 0xc420600ba0, 0x35c, 0x4d3d800, 0xc42054db80)
	<autogenerated>:1 +0xa1
github.com/google/gapid/gapis/api/transform.(*fileLog).Transform(0xc420844088, 0x4d069c0, 0xc420600ba0, 0x35c, 0x4d3d800, 0xc42054db80, 0x4cd7400, 0xc4207d27e0)
	gapis/api/transform/file_log.go:69 +0x962
github.com/google/gapid/gapis/api/transform.TransformWriter.MutateAndWrite(0xc420898240, 0x4cd5200, 0xc420844088, 0x4cd7400, 0xc4207d27e0, 0x4d069c0, 0xc420600ba0, 0x35c, 0x4d3d800, 0xc42054db80)
	gapis/api/transform/transforms.go:98 +0x89
github.com/google/gapid/gapis/api/transform.(*TransformWriter).MutateAndWrite(0xc4207d2810, 0x4d069c0, 0xc420600ba0, 0x35c, 0x4d3d800, 0xc42054db80)
	<autogenerated>:1 +0xa1
github.com/google/gapid/gapis/api/vulkan.(*makeAttachementReadable).Transform(0xc4207d8e10, 0x4d069c0, 0xc420600ba0, 0x35c, 0x4d3d800, 0xc42054db80, 0x4cd7400, 0xc4207d2810)
	gapis/api/vulkan/replay.go:306 +0xcc5
github.com/google/gapid/gapis/api/transform.TransformWriter.MutateAndWrite(0xc420898240, 0x4cd5300, 0xc4207d8e10, 0x4cd7400, 0xc4207d2810, 0x4d069c0, 0xc420600ba0, 0x35c, 0x4d3d800, 0xc42054db80)
	gapis/api/transform/transforms.go:98 +0x89
github.com/google/gapid/gapis/api/transform.(*TransformWriter).MutateAndWrite(0xc4207d2840, 0x4d069c0, 0xc420600ba0, 0x35c, 0x4d3d800, 0xc42054db80)
	<autogenerated>:1 +0xa1
github.com/google/gapid/gapis/api/transform.(*fileLog).Transform(0xc4208540c8, 0x4d069c0, 0xc420600ba0, 0x35c, 0x4d3d800, 0xc42054db80, 0x4cd7400, 0xc4207d2840)
	gapis/api/transform/file_log.go:69 +0x962
github.com/google/gapid/gapis/api/transform.TransformWriter.MutateAndWrite(0xc420898240, 0x4cd5200, 0xc4208540c8, 0x4cd7400, 0xc4207d2840, 0x4d069c0, 0xc420600ba0, 0x35c, 0x4d3d800, 0xc42054db80)
	gapis/api/transform/transforms.go:98 +0x89
github.com/google/gapid/gapis/api/transform.(*TransformWriter).MutateAndWrite(0xc4207d28d0, 0x4d069c0, 0xc420600ba0, 0x35c, 0x4d3d800, 0xc42054db80)
	<autogenerated>:1 +0xa1
github.com/google/gapid/gapis/api/transform.Transforms.Transform.func1(0x4d069c0, 0xc420600ba0, 0x35c, 0x4d3d800, 0xc42054db80, 0x0, 0x0)
	gapis/api/transform/transforms.go:39 +0x84
github.com/google/gapid/gapis/api.ForeachCmd(0x4d069c0, 0xc4207d8c30, 0xc420678000, 0x35d, 0x400, 0xc420e48f80, 0x0, 0x0)
	gapis/api/cmd_foreach.go:46 +0x21f
github.com/google/gapid/gapis/api/transform.Transforms.Transform(0xc42040a400, 0xb, 0x10, 0x4d069c0, 0xc4207d8c30, 0xc420678000, 0x35d, 0x400, 0x4cd5480, 0xc4207b8440)
	gapis/api/transform/transforms.go:38 +0x22c
github.com/google/gapid/gapis/api/vulkan.API.Replay(0x4d069c0, 0xc4207d8c30, 0xc420854050, 0xc420854048, 0x32ac680, 0xc4206009c0, 0xc4207d8900, 0x2, 0x2, 0x4d97960, ...)
	gapis/api/vulkan/replay.go:638 +0x226d
github.com/google/gapid/gapis/api/vulkan.(*API).Replay(0x5697a30, 0x4d069c0, 0xc4207d8c30, 0xc420854050, 0xc420854048, 0x32ac680, 0xc4206009c0, 0xc4207d8900, 0x2, 0x2, ...)
	<autogenerated>:1 +0x11d
github.com/google/gapid/gapis/replay.(*Manager).execute.func1()
	gapis/replay/batch.go:149 +0x1d1
github.com/google/gapid/core/app/benchmark.(*DurationCounter).Time(0xc42021f7e0, 0xc4201e5ed8)
	core/app/benchmark/counter.go:163 +0x9d
github.com/google/gapid/gapis/replay.(*Manager).execute(0xc4203d00c0, 0x4d069c0, 0xc4207d8c30, 0x4cd9a80, 0xc4203c4130, 0xafdd44e077fcb7d, 0x7027efd624a8ed5e, 0xe13c8645e81e5d5, 0x10d3588b47b3be93, 0x2552c9a514de7c8e, ...)
	gapis/replay/batch.go:148 +0xd00
github.com/google/gapid/gapis/replay.(*Manager).batch.func1(0x4cd9a80, 0xc4203c4130, 0xc4201e64a0, 0x47b3be930e13c864, 0x14de7c8e10d3588b, 0x77fcb7d2552c9a5, 0x24a8ed5e0afdd44e, 0x5e81e5d57027efd6, 0x32ac680, 0xc4206009c0, ...)
	gapis/replay/batch.go:83 +0x5aa
github.com/google/gapid/gapis/replay.(*Manager).batch(0xc4203d00c0, 0x4d069c0, 0xc4207d89c0, 0xc420ac6340, 0x2, 0x2, 0x3216140, 0x3696328, 0x3254300, 0xc4205d0fa0, ...)
	gapis/replay/batch.go:84 +0x4b7
github.com/google/gapid/gapis/replay.(*Manager).(github.com/google/gapid/gapis/replay.batch)-fm(0x4d069c0, 0xc4203ca810, 0xc420ac6340, 0x2, 0x2, 0x3216140, 0x3696328, 0x3254300, 0xc4205d0fa0, 0x1)
	gapis/replay/manager.go:126 +0x9b
github.com/google/gapid/gapis/replay/scheduler.(*bin).exec(0xc42020c200, 0x4d069c0, 0xc4203ca810, 0xc4203c4160)
	gapis/replay/scheduler/scheduler.go:243 +0x345
github.com/google/gapid/gapis/replay/scheduler.(*Scheduler).run(0xc4203d03e0, 0x4d069c0, 0xc4203ca810)
	gapis/replay/scheduler/scheduler.go:176 +0xa1d
github.com/google/gapid/gapis/replay/scheduler.New.func1()
	gapis/replay/scheduler/scheduler.go:73 +0x5a
github.com/google/gapid/core/app/crash.Go.func1(0xc4203d0400)
	core/app/crash/crash.go:65 +0x45
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

**Comment by AWoloszyn** [comment]
This should be fixed by https://github.com/google/gapid/pull/1683

**Comment by AWoloszyn** [comment]
Actually fixed by https://github.com/google/gapid/pull/1690
