### ISSUE TITLE
libwinpthread-1.dll is required to run gapis.exe / gapit.exe

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#17]
Something in our CMake rules is pulling in pthreads when we compile our go executables (and possibly c++ executables).

Because of this, the executables to not run unless `libwinpthread-1.dll` can be found on `PATH`.

The work around for now is to have `msys64\mingw64\bin` on your `PATH`.

**Comment by pmuetschard** [comment]
Along with libwinpthread-1.dll, we also seem to pull in libstdc++-6.dll (which then pulls in libgcc_s_seh-1.dll) from mingw.

**Comment by ben-clayton** [comment]
I think we've learnt to just live with this.
