### ISSUE TITLE
Build failure on Linux

### ISSUE THREAD

**Issue by Qining** [google/gapid#170]
Keep getting error message:
```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  25
  Current serial number in output stream:  26
RAN: /usr/local/home/qining/gapid/debug/test/test-core-os-device
GOT: 
CMake Error at /usr/local/home/qining/Workspace/gopath/src/github.com/google/gapid/cmake/Modules/GoTest.cmake:25 (message):
  RESULT: 1
```

`./do build generate` does not help
Removing build directory does not help

**Comment by Qining** [comment]
Error disappears after rebooting.

**Comment by ben-clayton** [comment]
Exciting. That test is making sure that the deviceinfo cgo code is doing something sensible. Part of this work is creating a GL context to query the renderer name. Looks like the driver got into a bad state.
I'm not sure this is a bug for GAPID.

**Comment by ben-clayton** [comment]
Closing. Please reopen if seen again.
