### ISSUE TITLE
The gapis server has exited with an error code of: 2

### ISSUE THREAD

**Issue by cdotstout** [google/gapid#1716]
GAPID Version: 1.1.0:76966beae5023f52e2f0dd3878c34a24d0428054
OS: linux amd64

Set my vulkan app to trace 10 frames.  I think that worked, then it killed my app.  I hit Stop Tracing then this error:

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x177352b]

goroutine 11 [running]:
github.com/google/gapid/core/app/crash.Crash(0x225fce0, 0x3eda4b0)
	core/app/crash/crash.go:89 +0xb4
github.com/google/gapid/core/app/crash.handler()
	core/app/crash/crash.go:56 +0x52
panic(0x225fce0, 0x3eda4b0)
	GOROOT/src/runtime/panic.go:491 +0x283
github.com/google/gapid/gapis/api/vulkan.(*ImageObject).IsResource(...)
	gapis/api/vulkan/resources.go:40
github.com/google/gapid/gapis/api/vulkan.(*ImageObject).OnAccess(0x0, 0xc4202b41e0, 0x558b00000000)
	bazel-out/k8-opt/genfiles/gapis/api/vulkan/api.go:114011 +0x2b
github.com/google/gapid/gapis/api/vulkan.(*VkDestroyDevice).mutate(0xc4204b9200, 0x3f329e0, 0xc42067d140, 0x7fffffffffffffff, 0xc4202b41e0, 0xc422f60f00, 0x24f3da0, 0x0)
	bazel-out/k8-opt/genfiles/gapis/api/vulkan/mutate.go:5391 +0x1c7
github.com/google/gapid/gapis/api/vulkan.(*VkDestroyDevice).Mutate(0xc4204b9200, 0x3f329e0, 0xc42067d140, 0x7fffffffffffffff, 0xc4202b41e0, 0xc422f60f00, 0x524538, 0x40)
	gapis/api/vulkan/custom_replay.go:333 +0x7f
github.com/google/gapid/gapis/replay.(*adapter).MutateAndWrite(0xc422c75090, 0x3f329e0, 0xc42067d140, 0x7fffffffffffffff, 0x3f69520, 0xc4204b9200)
	gapis/replay/batch.go:213 +0xcf
github.com/google/gapid/gapis/api/vulkan.(*destroyResourcesAtEOS).Flush(0x48c40d0, 0x3f329e0, 0xc42067d140, 0x3f01460, 0xc422c75090)
	gapis/api/vulkan/replay.go:443 +0x1948
github.com/google/gapid/gapis/api/transform.Transforms.Transform(0xc4210dc880, 0x6, 0x8, 0x3f329e0, 0xc42067d140, 0x48c40d0, 0x0, 0x0, 0x3f01460, 0xc422c75090)
	gapis/api/transform/transforms.go:44 +0x376
github.com/google/gapid/gapis/api/vulkan.API.Replay(0x3f329e0, 0xc42067d140, 0xc4225fe258, 0xc4225fe250, 0x24f5a80, 0xc42034c390, 0xc42018e0f0, 0xa, 0xa, 0x3fc39c0, ...)
	gapis/api/vulkan/replay.go:638 +0xef6
github.com/google/gapid/gapis/api/vulkan.(*API).Replay(0x48c40d0, 0x3f329e0, 0xc42067d140, 0xc4225fe258, 0xc4225fe250, 0x24f5a80, 0xc42034c390, 0xc42018e0f0, 0xa, 0xa, ...)
	<autogenerated>:1 +0xef
github.com/google/gapid/gapis/replay.(*Manager).execute.func1()
	gapis/replay/batch.go:149 +0x18c
github.com/google/gapid/core/app/benchmark.(*DurationCounter).Time(0xc4201b9820, 0xc42036c250)
	core/app/benchmark/counter.go:163 +0x7d
github.com/google/gapid/gapis/replay.(*Manager).execute(0xc420286b80, 0x3f329e0, 0xc42067d140, 0x3f05a60, 0xc420047e60, 0x9dbd4029ba59403c, 0x2dbc2b775850d44d, 0x4de19af19bf321b4, 0x7084a179d7b0bacf, 0xe30f8cf18b052b1, ...)
	gapis/replay/batch.go:148 +0x9fb
github.com/google/gapid/gapis/replay.(*Manager).batch.func1(0x3f05a60, 0xc420047e60, 0xc42036c5e0, 0xd7b0bacf4de19af1, 0x18b052b17084a179, 0xba59403c0e30f8cf, 0x5850d44d9dbd4029, 0x9bf321b42dbc2b77, 0x24f5a80, 0xc42034c390, ...)
	gapis/replay/batch.go:83 +0x487
github.com/google/gapid/gapis/replay.(*Manager).batch(0xc420286b80, 0x3f329e0, 0xc42067ced0, 0xc422f60dc0, 0xa, 0xa, 0x245f540, 0x29122e0, 0x249d700, 0xc4231af770, ...)
	gapis/replay/batch.go:84 +0x33a
github.com/google/gapid/gapis/replay.(*Manager).(github.com/google/gapid/gapis/replay.batch)-fm(0x3f329e0, 0xc42037c120, 0xc422f60dc0, 0xa, 0xa, 0x245f540, 0x29122e0, 0x249d700, 0xc4231af770, 0x1)
	gapis/replay/manager.go:126 +0x93
github.com/google/gapid/gapis/replay/scheduler.(*bin).exec(0xc420051180, 0x3f329e0, 0xc42037c120, 0xc420047e90)
	gapis/replay/scheduler/scheduler.go:243 +0x2e6
github.com/google/gapid/gapis/replay/scheduler.(*Scheduler).run(0xc420286ec0, 0x3f329e0, 0xc42037c120)
	gapis/replay/scheduler/scheduler.go:176 +0x36c
github.com/google/gapid/gapis/replay/scheduler.New.func1()
	gapis/replay/scheduler/scheduler.go:73 +0x3c
github.com/google/gapid/core/app/crash.Go.func1(0xc420286ee0)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

**Comment by Qining** [comment]
Fixed in #1727
