### ISSUE TITLE
test/integration/service tests failing

### ISSUE THREAD

**Issue by ianthehat** [google/gapid#175]
Test output for //test/integration/service:go_default_xtest:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcc739d]

**Comment by ben-clayton** [comment]
Humm. This test passes with the CMake build. Is bazel running this test without an X display by any chance?

**Comment by ianthehat** [comment]
Not sure, but it used to pass, I will look into it.

**Comment by ben-clayton** [comment]
Fixed. Yay
