### ISSUE TITLE
Enable OGL trace playback on remote device

### ISSUE THREAD

**Issue by tobine** [google/gapid#1762]
If I capture an OGL trace from an Android device, is there any way to play back the trace on the device? If the capability is already there, please let me know how to use it.
If not, can it be added?

**Comment by ben-clayton** [comment]
Hi Tobin, for GL, not currently, but it is likely this will be looked at very soon.

**Comment by tobine** [comment]
Great, thanks, Ben. Let's keep this as tracking issue. We're looking fwd to using this capability. If "very soon" is sometime in the month of April that would be ideal :)

**Comment by tobine** [comment]
May for "very soon" is great as well.

**Comment by ben-clayton** [comment]
I started poking at this today: https://github.com/google/gapid/pull/1856

Basic GLES apps now work, more complex ones can crash GAPIR - likely to be more GLES -> GL compat shenanigans. The PR has examples of what sort of tests need to be done (i.e. don't tamper with the stream if the target device is actually ES)

Depth and stencil buffer read-back needs implementing (unlike GL, GLES does not directly support reading of these with `glReadPixels`). Depth buffer probably needs copying to a color buffer with a fancy custom shader. Stencil likely needs some clunky repeatedly drawn fullscreen quad with varying stencil-tests.

This is a good seeding point if there's someone else who can look into continuing this. If there's nobody to pick this up, I'll try looking into this again after my optimization work.

**Comment by AWoloszyn** [comment]
On-device replay is now working. Feel free to open more bugs if you have specific issues with it.
