### ISSUE TITLE
Instead of inserting synthetic "GetPhysicalDeviceProperties" use an Extra

### ISSUE THREAD

**Issue by AWoloszyn** [google/gapid#1766]
We currently add synthetic GetPhysicalDeviceProperties after calls to VkEnumeratePhysicalDevices. Instead of doing this, Embed the important data into an extra attached to VkEnumeratePhysicalDevices.

**Comment by Qining** [comment]
This requires the use of extern functions. In the CPP side, extern is needed so we have access to the CallObserver. In the Go side, extern is needed to manually get the data from extra
