### ISSUE TITLE
Ensure commands that cause a crash are captured in a trace

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#1776]
Add a test that exercises this case, ensuring that a sequence of commands that reliably cause a crash are fully captured in the trace file.

**Comment by AWoloszyn** [comment]
We should also try and cover the case where the program terminates "normally"

**Comment by AWoloszyn** [comment]
This can now at least partially be done with the "disable buffering" option. It slows down trace, but it does capture everything up to and including the offending command.
