### ISSUE TITLE
Crash on Note 5 - GL error:  Out of memory

### ISSUE THREAD

**Issue by ZubairAkber** [google/gapid#1778]
**Device Name : Note 5**
**Operating System : 7.0**

App just crashes while opening browser from app using intent it is already reported #1456 for `Samsung S7` and is not replicating on S7 but for Note 5 it is easily replicated, please look into this

GL error:  Out of memory!
GL errors! frameworks/base/libs/hwui/renderthread/CanvasContext.cpp:544

**Comment by AWoloszyn** [comment]
This should be fixed by some of the new GLES changes.
