### ISSUE TITLE
<gapit> Failed to connect to the application

### ISSUE THREAD

**Issue by liuchunyu524** [google/gapid#1813]
1）gapid log：

02:19:48.592 I: <gapit> Device list:
02:19:48.592 I: <gapit>   GSLDU17B22002839
02:19:49.226 I: <gapit> Device is rooted
02:19:49.384 I: [start] <gapit> Turning device screen on
02:19:49.472 I: [start] <gapit> Checking for lockscreen
02:19:49.562 I: [start] <gapit> Checking gapid.apk is installed
02:19:49.562 I: [gapidapk.EnsureInstalled⇒start] <gapit> Examining gapid.apk on host...
02:19:49.565 I: [gapidapk.EnsureInstalled⇒start] <gapit> Looking for gapid.apk...
02:19:50.143 I: [gapidapk.EnsureInstalled⇒start] <gapit> Found gapid package...
02:19:50.143 I: [start] <gapit> Forwarding
02:19:50.260 I: [start] <gapit> Starting activity in debug mode
02:19:51.102 I: [start] <gapit> Forwarding TCP port 48956 -> JDWP pid 31888
02:19:51.143 I: [start] <gapit> Connecting to JDWP
02:19:52.144 I: [start] <gapit> Failed to connect to the application: read tcp 127.0.0.1:48965->127.0.0.1:48956: wsarecv: An existing connection was forcibly closed by the remote host.. Retrying...
02:19:54.147 I: [start] <gapit> Failed to connect to the application: read tcp 127.0.0.1:48978->127.0.0.1:48956: wsarecv: An existing connection was forcibly closed by the remote host.. Retrying...
02:20:21.257 E: <gapit> Main failed
Error: Connecting to JDWP
   Cause: dial tcp [::1]:48956: connectex: No connection could be made because the target machine actively refused it.

2）debug apk is relese
3）Android system is root

**Comment by liuchunyu524** [comment]
”GAPID can trace any Android debuggable application, or if you have root access to the device any application can be traced. ”  but，my phone is rooted

**Comment by AWoloszyn** [comment]
Sorry this has languished for almost a year, it got buried, it looks like you may have Android Studio open. If this is still a problem please open a new bug.
