### ISSUE TITLE
GAPIS uses a large and unbounded amount of memory.

### ISSUE THREAD

**Issue by cyberkm** [google/gapid#1817]
The process takes too much memory, unable to capture/debug anything longer than 4-5 minutes.
it can easily go over 32gb of memory.

I can't even connect to process at any given time, everytime the capture starts from beginning,
so i need to play for several minutes before i reach the place that needed inspection.

So everytime i am hitting 32gb memory limit that i have. The swap starts to work and the program becomes unusable.

**Comment by AWoloszyn** [comment]
Thanks for your report.

We are aware of the memory/performance issues, and are currently working on this exact problem.

If you are running a Vulkan application, then you should be able to start the trace part of the way through the run of the application, if you are running GLES, #1197 is open to track the progress of the feature.

**Comment by AWoloszyn** [comment]
This is even more of a problem with a Windows Host. 

On Windows Golang has a hard 32GB limit on the amount of memory you can use, regardless of how much is available. This means GAPIS will crash eventually. For large traces this can happen quickly.

**Comment by AWoloszyn** [comment]
This was recently addressed. We can still use a large amount of memory, but Mid-Execution capture exists for both GLES and Vulkan now, and should be used instead of taking multiple minute traces.
