### ISSUE TITLE
App hangs at trace start

### ISSUE THREAD

**Issue by tobine** [google/gapid#1834]
When attempting to trace my application GAPID stops at "Connecting to JDWP" while the target device stops at "Waiting For Debugger" dialog.

**Comment by ben-clayton** [comment]
Hi Tobin,

A few questions to help me figure out the problem:

* What version of GAPID are you using?
* What build of Android are you using? 
* Does this happen for any other applications?

Cheers,
Ben

**Comment by tobine** [comment]
Hi @ben-clayton,
 
GAPID ver is from yesterday morning. Build 241 from internal build system.
It's Android P custom build.
I've successfully traced 10+ other apps with this GAPID/Android combo. Hang is unique to Angry Birds 2 so far.

**Comment by ben-clayton** [comment]
Thanks Tobin, I'll check it out now.

**Comment by ben-clayton** [comment]
Unable to reproduce. I can successfully trace and replay this app on latest P.
