### ISSUE TITLE
GAPIS crashes in deviceinfo on Windows with AMD cards.

### ISSUE THREAD

**Issue by AWoloszyn** [google/gapid#1867]
I am not sure exactly what set of AMD cards are failing, but I have run into this on windows.

The issue looks to be here:
https://github.com/google/gapid/blob/master/core/os/device/deviceinfo/cc/windows/query.cpp#L77

Commenting out the lines fixes it, but obviously is not the right choice. I have tried a number of fixes, and have not managed to figure out what the root cause is.

**Comment by farnoy** [comment]
@AWoloszyn I'm not sure I have this exact issue, but are you certain this blacklist works? `query::osName()` is backed by Window's GetVersionEx, which is deprecated and not supposed to report anything above major version 8, unless you set special [assembly](https://msdn.microsoft.com/en-us/library/windows/desktop/dn481241(v=vs.85).aspx).

**Comment by AWoloszyn** [comment]
I have tested this on 2 separate Windows 10 machines, and both have returned Windows 10 as their OS string. That being said I am not 100% confident that this will work in every case.

The symptom of this bug is that the UI will just fail to open. You can run gapid --console, and see the server trying to start up, and then crashing immediately.

This fix only exists in the latest master, and not in any shipped binary, but we are trying to get a build together soon.

**Comment by farnoy** [comment]
Fair enough, my issue is a different one.

**Comment by AWoloszyn** [comment]
There are a ton of changes in 1.1 so it may be hard to pinpoint exactly what fixed your issue, but regardless that is great to hear.
Thanks for taking the time to let us know!
