### ISSUE TITLE
Can GAPID capture instrument tests? 

### ISSUE THREAD

**Issue by Brady31027** [google/gapid#1868]
I'd like to use GAPID to capture my instrument tests. However, when I type am commands in the package/action, GAPID shows the following error message.

19:52:12.530 E: <gapit> Main failed
Error: No actions matching am instrument -e class '_xxx_' -w _yyy_ found

Is that possible to use GAPID to capture instrument tests?

**Comment by AWoloszyn** [comment]
Not currently.

**Comment by AWoloszyn** [comment]
You can now specify command-line arguments to start up your application.

**Comment by Brady31027** [comment]
I will try it out, thanks AWoloszyn.

**Comment by vvavrychuk** [comment]
@AWoloszyn I see that it is possible to add additional application arguments in GAPID but I do not understand how it should help with running instrument tests.

I run instrument test with next command
```
am instrument -w -e class 'org.skia.skqp.SkQPRunner#gles_colorwheelnative' org.skia.skqp
```
Could you please suggest how to run it under GAPID?
