### ISSUE TITLE
ImportCapture/ExportCapture can not handle captures > 2GB.

### ISSUE THREAD

**Issue by AWoloszyn** [google/gapid#1874]
We don't really use ImportCapture anywhere, but we use ExportCapture to save the capture from the UI. This means we cannot save a modified capture that is > 2GB.

**Comment by ben-clayton** [comment]
This might be possible to solve by using streaming RPCs - stream multiple fixed size chunks < 2GB.

**Comment by AWoloszyn** [comment]
Duplicate of #403
