### ISSUE TITLE
Warn when app is using an extension that isn't supported by GAPID

### ISSUE THREAD

**Issue by sjfricke** [google/gapid#1876]
I was trying to debug an application with `vkCmdPushDescriptorSetKHR()` and realized that it was never called in GAPID. I didn't see any issues/PR on Vulkan extensions and curious about the state of them.

Regardless of implementing them, I feel there should be at least some notice that extension call is not currently supported when replaying the capture.

**Comment by sjfricke** [comment]
Thanks! I was trying to find this support list.

**Comment by AWoloszyn** [comment]
This is now fixed. We also have a flag that will hide unknown extensions.
