### ISSUE TITLE
GL_LUMINANCE / GL_UNSIGNED_BYTE textures appear corrupted

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#1879]
These textures display with 3 / 4 texels as black, and the 4th as the correct luminance value.

**Comment by pmuetschard** [comment]
Do you have a trace / apk where you see this? I tested my sample app and the luminance texture appears correctly. It's initialized thusly:
```
glTexImage2D(target:GL_TEXTURE_2D, level:0,
  internalformat:GL_LUMINANCE, width:256, height:256, border:0,
  format:GL_LUMINANCE, type:GL_UNSIGNED_BYTE, data:1995583500)
```

**Comment by ben-clayton** [comment]
Might only occur on textures used as render targets.

**Comment by AWoloszyn** [comment]
Cannot reproduce.
