### ISSUE TITLE
Make it possible to disable the thumbnails

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#188]
Either through command line option or configuration or menu item.

I am trying to debug specific issue, but the thumbnails dominate the logs.  I would like to be able to focus just what am I doing.

**Comment by ben-clayton** [comment]
Instead of polluting the client with debug flags, why not use `gapit`?

**Comment by dsrbecky** [comment]
Doesn't this take us on the path expanding gapit unil we have alternative command line based client?
At the moment my problem is that all seems good, but the framebuffer is garbage.... ASCII art?

**Comment by dsrbecky** [comment]
...but maybe the answer is to be able to manage the logs better instead.

**Comment by ben-clayton** [comment]
> Doesn't this take us on the path expanding gapit unil we have alternative command line based client?

It takes us on the path to building a powerful command line tool that can be used to invoke individual commands. 

> At the moment my problem is that all seems good, but the framebuffer is garbage.... ASCII art?

We've talked about adding `gapit frame` before. Should be easy.

**Comment by dsrbecky** [comment]
All right :-)
