### ISSUE TITLE
Inconsistent "status bar" for framebuffer and texture data

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#189]
Framebuffer shows the current colour as hex, Texture as float.  Shall we pick one?  Or preferably both if we have space?
Also, my vote would be RGBA order, rather than ARGB - but that is just preference.

**Comment by ben-clayton** [comment]
I thought the hex / float string was based on the format?

**Comment by dsrbecky** [comment]
I will just stay silent for today... :-)

**Comment by pmuetschard** [comment]
It uses floats for any HDR format, where HDR means > 8 bits for any channel.
