### ISSUE TITLE
Logo proposal for gapid

### ISSUE THREAD

**Issue by baranpirincal** [google/gapid#1903]
Hey. I can contribute on your project with making logo design. What do you think about that? Do you need a logo for Gapid? If you interested I can show you my portfolio. I'm waiting your feedback, have a nice day!

Best Regards
Baran Pirinçal

**Comment by ben-clayton** [comment]
Hi @baranpirincal,

Thank you for the offer, but we already have a logo we're happy with:

![logo](https://raw.githubusercontent.com/google/gapid/master/gapic/res/icons/logo_256.png)

Many thanks!
Ben
