### ISSUE TITLE
SIGSEGV in gapil_free_pool

### ISSUE THREAD

**Issue by hysw** [google/gapid#1916]
The nullptr assigned to pool->buffer in [prepareGPUBuffers](https://github.com/google/gapid/blob/3d6f11c4ce78bc670bb1ca3c2508f29169df5e39/gapii/cc/vulkan_mid_execution.cpp#L293) caused a segfault in [Arena::free](https://github.com/google/gapid/blob/3d6f11c4ce78bc670bb1ca3c2508f29169df5e39/core/memory/arena/cc/arena.cpp#L231) called from [gapil_free_pool](
https://github.com/google/gapid/blob/3d6f11c4ce78bc670bb1ca3c2508f29169df5e39/gapil/runtime/cc/runtime.cpp#L155).

**Comment by ben-clayton** [comment]
Thank you for the very thorougher description @hysw.

@AWoloszyn - this looks like a virtual pool getting replaced by a real one. Is this expected behavior? If so, we can just guard the line `arena->free(pool->buffer);`. I don't want to do this if there's unexpected behavior though.

**Comment by AWoloszyn** [comment]
This does certainly look like a bug. I think what is happening is that all references to the virtual pool are being dropped, which will cause this. I am surprised we have not seen this before.

I will put up a fix today.
