### ISSUE TITLE
Re-enable optimization of priming UNDEFINED image layers.

### ISSUE THREAD

**Issue by AWoloszyn** [google/gapid#1936]
See: https://github.com/google/gapid/pull/1935

If an image layer was marked as undefined, then we tried to elide the priming. This was causing some issues with some applications. Remove this for now, and figure out how to re-add the optimization.

**Comment by Qining** [comment]
This should have been fixed also:
https://github.com/google/gapid/blob/master/gapis/api/vulkan/state_rebuilder.go#L1414
