### ISSUE TITLE
We should use subImageSubresourceLayerCount in vulkan_extras.cpp

### ISSUE THREAD

**Issue by AWoloszyn** [google/gapid#1951]
We will not crash in `walkImageSubRng`, but we should definitely be using 
`subImageSubresourceLayerCount` and `subImageSubresourceLevelCount` so that we don't loop over the next 4B things.

**Comment by Qining** [comment]
This should have been fixed on master:
https://github.com/google/gapid/blob/master/gapii/cc/vulkan_extras.cpp#L721
https://github.com/google/gapid/blob/master/gapii/cc/vulkan_extras.cpp#L723

**Comment by AWoloszyn** [comment]
Thank you!
