### ISSUE TITLE
Capture a trace from running process

### ISSUE THREAD

**Issue by maunvz** [google/gapid#2009]
Is it possible to capture a trace from a running process instead of having to start the process through gapid? Similar to the Android Profiler being able to record memory allocations, but for OpenGL ES calls instead.

**Comment by AWoloszyn** [comment]
It is not currently possible to do this. And will likely never become possible to run without starting through GAPID. However something that is being added currently (for OpenGL ES) is the ability to run through gapid, but in a lower-cost mode.

This means that commands will not be recorded or processed until the user requests it. Then only commands from that time on will be recorded.

This functionality already exists for Vulkan.

**Comment by AWoloszyn** [comment]
This functionality will likely never exist. There is no way to add the hooks necessary on Android. Closing.
