### ISSUE TITLE
VulkanTerminator doesn't handle subcommand indices changing between Add and Transform

### ISSUE THREAD

**Issue by iburinoc** [google/gapid#2010]
When using dead code elimination in vulkan replays, the subcommand index for the last subcommand in the replay request can change if commands in the buffer were removed.  This means the terminator can end up including extra commands in the buffer.

**Comment by AWoloszyn** [comment]
IIRC (And @Qining , please correct me if I am wrong) the DCE keeps all commands in the last queue submission alive.
