### ISSUE TITLE
Feature request: check the ADB path specified

### ISSUE THREAD

**Issue by jimblackler** [google/gapid#2055]
I was a bit confused, because on first run I specified the path to the folder containing adb.exe (this is what other tools have trained me to do, specify path to SDK folders etc). 

Before I realized my mistake (and specified the path including the "adb.exe") the app simply didn't show any devices - no other error.

Could the preferences check that the user has specified something that looks a valid adb.exe, not (for example) a folder?

**Comment by ben-clayton** [comment]
Good suggestion.
