### ISSUE TITLE
Capture of Vulkan Quake3 Kenny Edition extremely slow

### ISSUE THREAD

**Issue by MarkY-LunarG** [google/gapid#2085]
Using GAPID version 1.1.0 on Windows 10 64-bit on a Dell XPS 15 with 16GB RAM.

The [Kenny Edition](https://github.com/kennyalive/Quake-III-Arena-Kenny-Edition) of Quake3 enables Vulkan support.

Capturing the replay of a demo using GAPID runs at 1/48th the framerate as the demo does normally.
With no overhead, the quake3 demo "four" runs at >480 fps on my system.  With GAPID enabled, the demo runs at <10fps. 

To reproduce:

1. Install Steam on Windows
   * This can be using Steam or some other method
2. Build an EXE from the [Kenny Edition Repo](https://github.com/kennyalive/Quake-III-Arena-Kenny-Edition) 
   * Or download the EXE in this zip [quake3.zip](https://github.com/google/gapid/files/2225322/quake3.zip)
3. Place the EXE in the same folder where the installed "quake3.exe" is placed.
4. Run the demo using the following command-line:

```
quake3-ke.exe + set r_renderAPI 1 + timedemo 1 + stopsound + demo four
```

5. To see the framerate after the demo completes, hit the "~/`" key.

**Comment by ben-clayton** [comment]
Hi @MarkY-LunarG,

I've spent most of today looking into where our time is going - it appears that the majority is spent reading the geometry buffer data each frame (we first hash to see if we need to send, then a copy is made for the send). This buffer is averaging around 4.5MB per frame, and as far as I can tell, may reside on the GPU, hence the slow performance.

We are seeing significant speed improvements (~ 5x) if we add the flag `VK_MEMORY_PROPERTY_HOST_CACHED_BIT` [to this line](https://github.com/kennyalive/Quake-III-Arena-Kenny-Edition/blob/master/src/engine/renderer/vk.cpp#L1137).

Do you have any theories to why VkTrace does not have the same performance hit when reading this buffer? Do you write the observed buffers directly to file / socket without any pre-processing?

Many thanks,
Ben

**Comment by davidlunarg** [comment]
When vktrace traces an application, device memory that is allocated is shadowed, and the shadow memory is made non-writable so that a SIGSEGV is generated when the application writes to it, and a signal handler is installed. When the app writes to device memory, the signal handler is invoked and it marks that page as dirty and makes the page writeable again. Dirty memory is copied to the tracefile and to the GPU during the next call to vkQueueSubmit (and possibly others api calls, but that's the one that comes to mind right now).

During replay, memory buffers that were saved to the trace file are simply copied to the device memory buffer.

**Comment by AWoloszyn** [comment]
@davidlunarg I just investigated this a bit more deeply. I think this is the main difference between GAPID and vktrace. We considered a shadow memory region for mapped memory, for exactly the reasons as stated in vktrace (basically not all GPU memory will respect page protections).

However we came to the conclusion that shadowing the memory can completely violate the spec. Specifically if the GPU and Host both write to the same page, we have to merge the writes. Most shadowing techniques I have seen will cause the writes from either the CPU or GPU to be discarded, thus causing memory corruption.

Please let me know if you disagree with this assessment.

**Comment by AWoloszyn** [comment]
I will expand this with, we do use a page-fault system if we detect at runtime that it will work. But fall back to slower methods if it is not reliable.

**Comment by davidlunarg** [comment]
@AWoloszyn : Yes, you are correct. vktrace will not correctly handle the GPU and host writing to the same page. The Windows implementation of vktrace can trace an app that has the GPU writing to mapped device memory, but not if the same page is written by the host. vktrace on Linux does not yet support writing of mapped device memory.

In all the Vulkan apps  I have traced, I have not found an instance of the app counting on the GPU writing to mapped memory. I do know, however, that an IHV I have been working with has worked with several apps that do, but not to the same page, and they have successfully traced those apps.

vktrace solves the most common problem (the host writing to GPU) with good performance. If an app were to need to read and write from the same page, a more accurate (but slower performing) solution could be added to vktrace. Up to now, this hasn't been a priority.

**Comment by AWoloszyn** [comment]
@davidlunarg Thank you for the detailed response. I was hoping I had missed something in the spec that guaranteed the behavior in such cases. I am investigating some options for a slightly different shadow memory approach that should be spec-compliant. If I can get it working (and it performs reasonably well) I will update this thread accordingly.

**Comment by AWoloszyn** [comment]
@davidlunarg I finally got a chance to take a look at this case, and just pushed a change that should significantly help the performance.
