### ISSUE TITLE
Framebuffer is often black

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#209]
When the full framebuffer gets loaded, it is often completely black for me until I move mouse over it.

**Comment by ben-clayton** [comment]
Needs repro case.

**Comment by dsrbecky** [comment]
Still happens all the time on my laptop (with Cinnamon)

**Comment by ben-clayton** [comment]
We should add to the release notes that Cinnamon is not supported.

**Comment by pmuetschard** [comment]
It's cinnamon that's (mostly) working and gnome unity that is broken. However, before making any claims, we should verify on a non-corp machine.
