### ISSUE TITLE
Client: Changing a field collapses all views

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#21]
When changing a parameter, we should transparently change captures while keeping all the view states the same.
We don't want to have to re-find the context, re-expand the tree view, re-select the textures etc.

**Comment by pmuetschard** [comment]
I'm pretty sure this is/will be again broken in the new proto world. Re-opening, just to be safe and check.

**Comment by ben-clayton** [comment]
@pmuetschard - this now fixed?

**Comment by ben-clayton** [comment]
> @pmuetschard - this now fixed?

Nope.
