### ISSUE TITLE
Creating Video for trace of Vulkan SDK Cube on Windows doesn't work

### ISSUE THREAD

**Issue by MarkY-LunarG** [google/gapid#2103]
GAPID 1.1.0
Windows 10 64-bit
Dell XPS 15 w/ 16GB RAM
Intel Integrated and Nvidia 960M
[ffmpeg-20180723-0bb5cd8-win64-shared](https://ffmpeg.zeranoe.com/builds/)

I created the following trace and when I try to create a video of it, it fails.  it doesn't fail with an error message, it seems to execute correctly, but the MP4 plays nothing.

The command-line I use is:

```
gapit video -out C:\temp\cube.mp4 C:\temp\cube.gfxtrace
```

I've attached [cube.zip](https://github.com/google/gapid/files/2243107/cube.zip) containing the trace and mp4.

**Comment by MarkY-LunarG** [comment]
FYI, unlike #2089, this is not because the GAPIT ran out of memory.

**Comment by MarkY-LunarG** [comment]
Here's the output of my 2nd attempt: [cube.txt](https://github.com/google/gapid/files/2243147/cube.txt)

**Comment by AWoloszyn** [comment]
I tried the video from your zip file. The Windows 10 "FIlms & TV" app does not play the video correctly. The output is completely black. However if I open it with chrome, it plays as expected. (I just dragged it into chrome).

Let me know if this helps you.

**Comment by AWoloszyn** [comment]
I am going to close this in favor of the related bug:
https://github.com/google/gapid/issues/2126
