### ISSUE TITLE
Need active replay to desktop framebuffer

### ISSUE THREAD

**Issue by MarkY-LunarG** [google/gapid#2104]
GAPID 1.1.0
Windows 10 64-bit
Dell XPS 15 w/ 16GB RAM
Intel Integrated and Nvidia 960M

In order to properly simulate desktop rendering of Vulkan applications, we require GAPID to support replaying a trace on the Vulkan framebuffer/swapchain of the underlying graphics driver.  Currently, GAPID renders to a offscreen buffer, but performing this instead of actually using the swapchain can adjust timing and behavior enough that a trace is no longer sufficient to reproduce the behavior of the application original captured.

**Comment by AWoloszyn** [comment]
There is now a flag on gapit report that does this.
