### ISSUE TITLE
"Select Application To Trace" dialog does behave as expected for Android

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#2129]
Previously we would list all the packages, with intents nested under these.
If the package had a main (default launch) intent, we would allow the package to be selected. This implicitly selected the main intent, letting you quickly trace.

With the reimplementation, there are a number of issues:

1. Selecting the package only builds a malformed trace URI of just the application. Attempting to trace this fails.
2. All packages, when selected, enable the 'OK' button. Only the packages with a default launch intent should be confirmable.
3. The packages are no longer sorted. Combined with the lack of filter, this makes finding a package very hard.

**Comment by AWoloszyn** [comment]
The UI can use the "trace_uri" returned from the package node to fill in the URI field. If the trace_uri returned is "" then that node of the tree cannot be traced.

**Comment by pmuetschard** [comment]
Fixed by #2143
