### ISSUE TITLE
Error: getting package list

### ISSUE THREAD

**Issue by divya-burgose** [google/gapid#2133]
E: <gapit> Main failed
Error: getting package list
   Cause: Starting service
   Cause: Process returned error
   Cause: exit status 255

Steps: 
1. Launch gapid tool 
2. select capture trace option
3. select api, device
4. select package list option

Host: ubuntu 14.04
device: android device (samsung galaxy s7)
Gapid Tool code base : tags - V1.1.0 

[gapic.log](https://github.com/google/gapid/files/2265945/gapic.log)

**Comment by AWoloszyn** [comment]
This should be fixed in 1.2 please re-open if this is still happening.
