### ISSUE TITLE
how can i run without getting the image of texture or framebuffer?

### ISSUE THREAD

**Issue by CatDroid** [google/gapid#2144]
does it support ? because I just want to know when the texture is created and destroyed .

**Comment by CatDroid** [comment]
add more ,  when i trace my app on machine with GAPID, it will much slow, so i want GAPID does not get the image,  only get the command instead , maybe it will more faster ,
I use UI tool ,   i'am not sure if there is a command tool to do so .

**Comment by AWoloszyn** [comment]
In the package there is a tool called "gapit".
It  can be used to investigate a trace, without using the UI. 

There are a bunch of verbs available in gapit, and you can run `gapit --help` to get a list of all of them.
It sounds like you may want `gapit commands`.

**Comment by CatDroid** [comment]
good idea to use gapit instead of the UI tool

**Comment by AWoloszyn** [comment]
`gapit --help` is your best bet. It describes the usage of every command. There is no high-level documentation unfortunately.
