### ISSUE TITLE
GLES ODR  issue with cube maps.

### ISSUE THREAD

**Issue by pmuetschard** [google/gapid#2147]
Replaying the attached trace (on a Pixel) does not correctly render the cube map. Compare with replaying on desktop.

[trace.zip](https://github.com/google/gapid/files/2303616/trace.zip)

**Comment by pmuetschard** [comment]
Looks like an MEC bug. Tracing the same app in non-MEC, produces correct replay frames.

**Comment by AWoloszyn** [comment]
So for tracking down the source of the issue:

If the texture view shows the right thing then it is likely a state rebuilder issue
If the texture view is broken, then it is likely a capturing-the-wrong-data problem

**Comment by pmuetschard** [comment]
Since it replays fine on Desktop, I think it's most likely a state rebuilder issue. The texture data in the texture view looks correct. I'm using `config.LogTransformsToCapture` to look at what is actually sent to the replay.

**Comment by pmuetschard** [comment]
Root cause of the issue is that the texture is initialized with `GL_LUMINANCE8` as the internal format, which GLES does not actually support.

```
[0]glTexImage2D(0x8517, 0, 32832, 128, 128, 0, 0x1909, 0x1401, 0x0)
[0]glGetError()
[0]glGetError returned 0x501
```
