### ISSUE TITLE
Cannot detect My phone

### ISSUE THREAD

**Issue by AtwoodDeng** [google/gapid#2162]
I have a Samsung Galaxy S8 (Mali-G71) and I'm using a windows 64 desktop to run gapid.exe.  However, After I click Capture Graphics Trace, I cannot find any device in the drop-down. I also tried to manually install the gapid-armeabi.apk but nothing happened. I cannot even open the apk. I checked the official document but the both the https://google.github.io/gapid/trace/desktop and https://google.github.io/gapid/trace/android show 404. 

Did I miss anything? How can I actually use the amazing features you provide?

**Comment by AWoloszyn** [comment]
Have you built this yourself, or 1.1.0 release.

Since 1.1.0 our tracing has changed slightly, the new documentation is here:
https://google.github.io/gapid/trace/

Even if you are using 1.1.0 for android, they should be fairly similar.

If you run "adb devices" do you see your device in that drop-down?

**Comment by CatDroid** [comment]
is that possible to get texture and fbo only ? not include the picture on texture and fbo ,because it run much slower if catpure picture on fbo and texture

**Comment by pmuetschard** [comment]
Sorry for the late reply. Can you make sure the path to adb in the application's settings is correct? It needs to be the path to the actual adb executable, not the directory containing it. In version 1.2, we now check this and show a warning message.

**Comment by AWoloszyn** [comment]
Closing, please re-open if this is still an issue.
