### ISSUE TITLE
Error: getting package list

### ISSUE THREAD

**Issue by kerrytazi** [google/gapid#2198]
gapid version: v1.1.0
host: Windows 7 x64 
device: xiaomi Redmi 4A

Error every time I open _Select Activity_ window.

The gapit command failed:
19:45:05:428 E: <gapit> Main failed
Error: getting package lsit
Cause: Unable to install GAPID.

I've tried to install `gapid-aarch64.apk` manually on the device and then got new error:

The gapit command failed:
19:52:57:817 E: <gapit> Main failed
Error: getting package list
Cause: Connecting to service port
Cause:
Cause: Timeout connecting to service

**Comment by ben-clayton** [comment]
Hi @kerrytazi,

Is there any error messages when you look at `adb logcat`?

**Comment by kerrytazi** [comment]
warnings only
`09-14 22:33:43.798  1491 11113 W ActivityManager: Background start not allowed: service Intent { act=com.google.android.gapid.action.SEND_DEV_INFO cmp=com.google.android.gapid.aarch64/com.google.android.gapid.DeviceInfoService } to com.google.android.gapid.aarch64/com.google.android.gapid.DeviceInfoService from pid=32304 uid=2000 pkg=com.android.shell`

**Comment by AWoloszyn** [comment]
This should be fixed in 1.2.
