### ISSUE TITLE
Any timeline for new features implemenation into gapid?

### ISSUE THREAD

**Issue by gittmi** [google/gapid#2200]
Hi, 
    It seems you have a plan to implement many new features into gapid as said in Android Game Developer Summit 2018. (https://www.youtube.com/watch?v=nx9IUa56v7U) 

Any timeline(roughly) you guys have for integrating these features into gapid tool? The reason for asking this is I am also planning to start implementing some of the features like API statistics and pixel history. How long do you think these may take?
May be we can avoid duplication of work here. How can I contribute in developing the specific feature?

Thanks.

**Comment by AWoloszyn** [comment]
We have no specific time-line for these extra features. Feel free to reach out about specific features (which you already have) and we can let you know if we have any plans to look at them in the short term.
