### ISSUE TITLE
can't start gapid on Win10 X64

### ISSUE THREAD

**Issue by cryptofbc** [google/gapid#2208]
Following is the output of `gapid --console`, version 1.1.0, downloaded from this git release

```
Starting D:\Tools\gapid\jre\bin\java.exe D:\Tools\gapid\lib\gapic.jar
I20180914-144431401[main][server.GapiPaths.checkForTools] Looking for GAPID in D:\Tools\gapid -> D:\Tools\gapid\gapis.exe
I20180914-144431436[server.ChildProcess-gapis][server.ChildProcess.runProcess] Starting gapis as [D:\Tools\gapid\gapis.exe, -enable-local-files, -log-file, C:\Users\xxx\AppData\Local\Temp\gapis.log, -log-level, Info, -gapir-args, --log C:\\Users\\xxx\\AppData\\Local\\Temp\\gapir.log --log-level I, --strings, D:\Tools\gapid\strings, --gapis-auth-token, hlz0T3Sj, --idle-timeout, 60000ms]
I20180914-144431801[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$0] gapis: 06:44:31.801 I: <gapis> Logging to: C:\Users\xxx\AppData\Local\Temp\gapis.log
W20180914-144432982[server.ChildProcess-gapis][server.ChildProcess.onExit] The gapis process exited with a non-zero exit value: -1073741819
I20180914-144432983[server.ChildProcess-gapis][server.ChildProcess.shutdown] Shutting down gapis
W20180914-144432982[main][server.GapisProcess.connect] Failed while waiting for gapis
W20180914-144432982[main][server.GapisProcess.connect] java.util.concurrent.ExecutionException: com.google.gapid.server.ChildProcess$EarlyExitException: gapis has exited with exit code -1073741819
W20180914-144432982[main][server.GapisProcess.connect]  at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500)
W20180914-144432982[main][server.GapisProcess.connect]  at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:401)
W20180914-144432982[main][server.GapisProcess.connect]  at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83)
W20180914-144432982[main][server.GapisProcess.connect]  at com.google.gapid.server.GapisProcess.connect(GapisProcess.java:179)
W20180914-144432982[main][server.GapisProcess.connect]  at com.google.gapid.Server.createConnection(Server.java:116)
W20180914-144432982[main][server.GapisProcess.connect]  at com.google.gapid.Server.connectToServer(Server.java:98)
W20180914-144432982[main][server.GapisProcess.connect]  at com.google.gapid.Server.connect(Server.java:71)
W20180914-144432982[main][server.GapisProcess.connect]  at com.google.gapid.Main.main(Main.java:66)
W20180914-144432982[main][server.GapisProcess.connect] Caused by: com.google.gapid.server.ChildProcess$EarlyExitException: gapis has exited with exit code -1073741819
W20180914-144432982[main][server.GapisProcess.connect]  at com.google.gapid.server.ChildProcess.runProcess(ChildProcess.java:102)
W20180914-144432982[main][server.GapisProcess.connect]  at com.google.gapid.server.ChildProcess$1.run(ChildProcess.java:73)
Uncaught exception in thread Thread[main,5,main]:
com.google.gapid.Server$GapisInitException: Failed to connect to the graphics debugger
        at com.google.gapid.Server.connectToServer(Server.java:100)
        at com.google.gapid.Server.connect(Server.java:71)
        at com.google.gapid.Main.main(Main.java:66)
```

**Comment by pmuetschard** [comment]
Is there anything interesting in `gapis.log`? Can you try with `gapid --console --log-level ALL`?

(-1073741819 looks like a memory access violation)

**Comment by cryptofbc** [comment]
Thanks for your reply,
following is the output of command : gapid --console --log-level ALL
and 
the file gapis.log is a zero byte file, no any log content in it... 

Starting D:\Tools\gapid\jre\bin\java.exe D:\Tools\gapid\lib\gapic.jar
I20180918-094909099[main][server.GapiPaths.checkForTools] Looking for GAPID in D:\Tools\gapid -> D:\Tools\gapid\gapis.exe
I20180918-094909165[server.ChildProcess-gapis][server.ChildProcess.runProcess] Starting gapis as [D:\Tools\gapid\gapis.exe, -enable-local-files, -log-file, C:\Users\xxx\AppData\Local\Temp\gapis.log, -log-level, Debug, -gapir-args, --log C:\\Users\\xxx\\AppData\\Local\\Temp\\gapir.log --log-level V, --strings, D:\Tools\gapid\strings, --gapis-auth-token, WQEhPBSZ, --idle-timeout, 60000ms]
I20180918-094910025[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$0] gapis: 01:49:10.024 I: <gapis> Logging to: C:\Users\xxx\AppData\Local\Temp\gapis.log
W20180918-094911286[server.ChildProcess-gapis][server.ChildProcess.onExit] The gapis process exited with a non-zero exit value: -1073741819
I20180918-094911287[server.ChildProcess-gapis][server.ChildProcess.shutdown] Shutting down gapis
W20180918-094911286[main][server.GapisProcess.connect] Failed while waiting for gapis
W20180918-094911286[main][server.GapisProcess.connect] java.util.concurrent.ExecutionException: com.google.gapid.server.ChildProcess$EarlyExitException: gapis has exited with exit code -1073741819
W20180918-094911286[main][server.GapisProcess.connect]  at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500)
W20180918-094911286[main][server.GapisProcess.connect]  at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:401)
W20180918-094911286[main][server.GapisProcess.connect]  at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83)
W20180918-094911286[main][server.GapisProcess.connect]  at com.google.gapid.server.GapisProcess.connect(GapisProcess.java:179)
W20180918-094911286[main][server.GapisProcess.connect]  at com.google.gapid.Server.createConnection(Server.java:116)
W20180918-094911286[main][server.GapisProcess.connect]  at com.google.gapid.Server.connectToServer(Server.java:98)
W20180918-094911286[main][server.GapisProcess.connect]  at com.google.gapid.Server.connect(Server.java:71)
W20180918-094911286[main][server.GapisProcess.connect]  at com.google.gapid.Main.main(Main.java:66)
W20180918-094911286[main][server.GapisProcess.connect] Caused by: com.google.gapid.server.ChildProcess$EarlyExitException: gapis has exited with exit code -1073741819
W20180918-094911286[main][server.GapisProcess.connect]  at com.google.gapid.server.ChildProcess.runProcess(ChildProcess.java:102)
W20180918-094911286[main][server.GapisProcess.connect]  at com.google.gapid.server.ChildProcess$1.run(ChildProcess.java:73)
Uncaught exception in thread Thread[main,5,main]:
com.google.gapid.Server$GapisInitException: Failed to connect to the graphics debugger
        at com.google.gapid.Server.connectToServer(Server.java:100)
        at com.google.gapid.Server.connect(Server.java:71)
        at com.google.gapid.Main.main(Main.java:66)

Press enter to continue

**Comment by AWoloszyn** [comment]
Are you trying to run this is a virtual machine by any chance?

**Comment by cryptofbc** [comment]
No, I have always run GAPID tool in my real physical machine, its os version is win10 x64, and in adminstration priviledge

**Comment by pmuetschard** [comment]
when you run with `--log-level ALL`, is there anything interesting in `C:\Users\xxx\AppData\Local\Temp\gapis.log`?

It's strange, there seems to be some kind of memory exception in gapis starting up, or possibly when gapic is trying to connect to it.

Can you also try running
`D:\Tools\gapid\gapis.exe -log-level Debug --strings D:\Tools\gapid\strings` and see if at least gapis without a connection runs without crashing right away?

**Comment by cryptofbc** [comment]
And after I updated the Nvidia display driver to the newest version(https://www.geforce.cn/drivers/results/138453), I can see the GAPID's UI...
