### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by Eren121** [google/gapid#2209]
This pages in the documentation are broken :
- https://google.github.io/gapid/trace/android
- https://google.github.io/gapid/trace/desktop

In [this](https://google.github.io/gapid/tutorials/capturetrace) page

Can you please fix it ? Thank you

**Comment by AWoloszyn** [comment]
Thanks for the report. They have been replaced by https://google.github.io/gapid/trace/  which covers all APIs. However the new changes are not reflected in the current release, so it may be slightly different, but should suffice.

I will update the documentation.

**Comment by AWoloszyn** [comment]
Fixed by #2210

**Comment by Eren121** [comment]
Yep, thank you :)
