### ISSUE TITLE
Why GAPID can't find my device?

### ISSUE THREAD

**Issue by xwolf47** [google/gapid#2221]
I'm work on Win10 64, with Intel core i5 cpu.
Android studio can find my device. I closed android studio gapid still can't find device(Motorola xt1079)
This is the screen shot:
![m 2 _ 1 j wj6tmk k8d](https://user-images.githubusercontent.com/38414230/45603436-925c1300-ba5e-11e8-8e83-a16c82923ac2.png)

**Comment by pmuetschard** [comment]
GAPID does not need to be run as administrator.

Can you check that the path to adb is correct in the settings? Make sure it points to the actual `adb.exe` executable, not just the directory that contains it. See #2055

**Comment by xwolf47** [comment]
@pmuetschard Ok, thanks, it's work!
