### ISSUE TITLE
The gapis server has exited with an error code of: 2

### ISSUE THREAD

**Issue by divya-burgose** [google/gapid#2251]
GAPID Version: 1.1.0:874eed8e0372b54db789835e1ad36cb641e9fbea
OS: linux amd64
Application : cube (vulkan SDK example )

Captured trace with the released version of GAPID. After capture the trace file has loaded and visible in GAPIC. But when select any command from comandpane it is throwing an error as below.
=====================================================================
panic: Range ([0x00007f9d973a2000-0x00007f9d973a24bf]) was not mapped [recovered]
	panic: Range ([0x00007f9d973a2000-0x00007f9d973a24bf]) was not mapped

goroutine 36 [running]:
github.com/google/gapid/core/app/crash.Crash(0x226e9e0, 0xc4209c3270)
	core/app/crash/crash.go:89 +0xa7
github.com/google/gapid/core/app/crash.handler()
	core/app/crash/crash.go:56 +0x52
panic(0x226e9e0, 0xc4209c3270)
	GOROOT/src/runtime/panic.go:505 +0x229
github.com/google/gapid/gapis/replay/builder.(*Builder).UnmapMemory(0xc42122ab40, 0x7f9d973a2000, 0x4c0)
	gapis/replay/builder/builder.go:532 +0x2c6
github.com/google/gapid/gapis/api/vulkan.externs.unmapMemory(0x2ab0a40, 0xc420fb5320, 0x2ae33c0, 0xc42127ba00, 0x7fffffffffffffff, 0xc4210852c0, 0xc42122ab40, 0x2abb1c0, 0xc4220cf020)
	gapis/api/vulkan/externs.go:168 +0x8a
github.com/google/gapid/gapis/api/vulkan.(*VkFreeMemory).Mutate(0xc42127ba00, 0x2ab0a40, 0xc420fb5320, 0x7fffffffffffffff, 0xc4210852c0, 0xc42122ab40, 0x0, 0xc422b0ced8)
	bazel-out/k8-opt/genfiles/gapis/api/vulkan/mutate.go:7236 +0x3b4
github.com/google/gapid/gapis/replay.(*adapter).MutateAndWrite(0xc420303940, 0x2ab0a40, 0xc420fb5320, 0x7fffffffffffffff, 0x2ae33c0, 0xc42127ba00)
	gapis/replay/batch.go:213 +0xcf
github.com/google/gapid/gapis/api/vulkan.(*destroyResourcesAtEOS).Flush(0x4a753a0, 0x2ab0a40, 0xc420fb5320, 0x2a7bf80, 0xc420303940)
	gapis/api/vulkan/replay.go:433 +0x1727
github.com/google/gapid/gapis/api/transform.Transforms.Transform(0xc420e46300, 0x6, 0x8, 0x2ab0a40, 0xc420fb5320, 0x4a753a0, 0x0, 0x0, 0x2a7bf80, 0xc420303940)
	gapis/api/transform/transforms.go:44 +0x33c
github.com/google/gapid/gapis/api/vulkan.API.Replay(0x2ab0a40, 0xc420fb5320, 0xc421152188, 0xc4203e66d8, 0x2614580, 0xc4212a4ab0, 0xc422be7c20, 0x1, 0x1, 0x41b6100, ...)
	gapis/api/vulkan/replay.go:642 +0xdc1
github.com/google/gapid/gapis/replay.(*Manager).execute.func1()
	gapis/replay/batch.go:149 +0x18b
github.com/google/gapid/core/app/benchmark.(*DurationCounter).Time(0xc42021b7a0, 0xc421cea0f8)
	core/app/benchmark/counter.go:163 +0x7d
github.com/google/gapid/gapis/replay.(*Manager).execute(0xc4203c40c0, 0x2ab0a40, 0xc420fb5320, 0x2a80ac0, 0xc4203ce160, 0x916b25f31c866acd, 0x8e9b62cd3cd1dcdb, 0x7bdf25d611742460, 0xe2306827d110341d, 0xcf8d2f46f416fbdf, ...)
	gapis/replay/batch.go:148 +0x964
github.com/google/gapid/gapis/replay.(*Manager).batch.func1(0x2a80ac0, 0xc4203ce160, 0xc421cea458, 0xd110341d7bdf25d6, 0xf416fbdfe2306827, 0x1c866acdcf8d2f46, 0x3cd1dcdb916b25f3, 0x117424608e9b62cd, 0x2614580, 0xc4212a4ab0, ...)
	gapis/replay/batch.go:83 +0x444
github.com/google/gapid/gapis/replay.(*Manager).batch(0xc4203c40c0, 0x2ab0a40, 0xc4212a4b40, 0xc422be7c00, 0x1, 0x1, 0x2575640, 0x2a63130, 0x25b6e80, 0xc421f44190, ...)
	gapis/replay/batch.go:84 +0x2d4
github.com/google/gapid/gapis/replay.(*Manager).(github.com/google/gapid/gapis/replay.batch)-fm(0x2ab0a40, 0xc4203c8870, 0xc422be7c00, 0x1, 0x1, 0x2575640, 0x2a63130, 0x25b6e80, 0xc421f44190, 0x1)
	gapis/replay/manager.go:126 +0x93
github.com/google/gapid/gapis/replay/scheduler.(*bin).exec(0xc420a11800, 0x2ab0a40, 0xc4203c8870, 0xc4203ce1a0)
	gapis/replay/scheduler/scheduler.go:243 +0x26d
github.com/google/gapid/gapis/replay/scheduler.(*Scheduler).run(0xc4203c4400, 0x2ab0a40, 0xc4203c8870)
	gapis/replay/scheduler/scheduler.go:176 +0x370
github.com/google/gapid/gapis/replay/scheduler.New.func1()
	gapis/replay/scheduler/scheduler.go:73 +0x3c
github.com/google/gapid/core/app/crash.Go.func1(0xc4203c4420)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

**Comment by AWoloszyn** [comment]
Thank you for your report. I ha e an idea of what the cause may be, but I will be out of town until Monday. I can try to get a fix together for then. In the meantime, you can try to disable repay optimization. 

`Edit->preferences->disable replay optimization` then restart gapis.

Also: are you able to share a trace that rwproduxes the issue?

Thanks

**Comment by divya-burgose** [comment]
Thanks Andrew, I am able to replay by selecting disable replay optimization. Please find attached trace file. 
[traceFile.zip](https://github.com/google/gapid/files/2427108/traceFile.zip)

**Comment by AWoloszyn** [comment]
Thanks, I am glad the workaround worked for you. I will investigate and let you know when the issue is fixed properly.

**Comment by AWoloszyn** [comment]
We have release version 1.2.0 which should hopefully solve your issue.

**Comment by pmuetschard** [comment]
Please re-open if you still see this on version 1.2.
