### ISSUE TITLE
Gapid Support on ubuntu 18.04

### ISSUE THREAD

**Issue by divya-burgose** [google/gapid#2252]
Can I build gapid on ubuntu 18.04?
I followed build document, I was unable to install "libncurses5-dev libgl1-mesa-dev".
Apart from that I have set up environment as mentioned in the build document.
My build is getting failed, saying "gcc: error: libVkLayer_VirtualSwapchain.ldscript: No such file or directory"

**Comment by AWoloszyn** [comment]
That sounds like it might be a bazel version related issue.
Would you mind pasting the output of 
`bazel version` ?

**Comment by divya-burgose** [comment]
Hi Andrew,
bazel version output:
=====================
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/home/testuser/.cache/bazel/_bazel_testuser/install/792a28b07894763eaa2bd870f8776b23/_embedded_binaries/A-server.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Build label: 0.17.2
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Sep 21 10:31:42 2018 (1537525902)
Build timestamp: 1537525902
Build timestamp as int: 1537525902

**Comment by AWoloszyn** [comment]
0.17.1 broke something in this area, and it looks like 0.17.2 may have as well.

Unfortunately baxel does not guarantee forward compatibility as of yet. While we look into what is wrong you could try with 0.16.1 which we have tested extensively, or 0.17.1 which should be working.

**Comment by divya-burgose** [comment]
Thanks Andrew, I have updated bazel to 0.16.1 version, I could progress further.
But I am getting "/usr/bin/x86_64-linux-gnu-ld.gold: error: cannot find -lcurses" error now. I think , As I could not install "libncurses5-dev libgl1-mesa-dev" these on 18.04. Could you please help me in resolving it?

**Comment by divya-burgose** [comment]
HI Pascal,
libncurses5-dev and libgl1-mesa-dev lib packages are available but while installing it used to say some dependent libs are not going to be installed, and I could able to install. But still I am facing build fails. I have taken v1.1.0 released source. Event tried multiple combinations of gapid versions(latest , V1.1.0) and bazel versions(0.17.02, 0.17.01, 0.16.01, 0.15.02) , no luck. 

BUILD ERROR:  apic compiling gapis/api/gvr/gvr.api for x86 failed (Exit 1): apic failed: error executing command
CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options

I could able to build latest git and released build on 14.04 with bazel 15.02(haven't tried any other combination )

**Comment by AWoloszyn** [comment]
```
BUILD ERROR: apic compiling gapis/api/gvr/gvr.api for x86 failed (Exit 1): apic failed: error executing command
CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

That is a scary issue:
Out of curious what GPU / driver are you running. We had some problems with MESA exporting llvm symbols into our application, this could certainly be related.

**Comment by pmuetschard** [comment]
I think @AWoloszyn is correct and this issue is stemming from multive LLVMs of different versions colliding.

**Comment by AWoloszyn** [comment]
I just checked the MESA driver, and it now requires llvm up to 7.0, so I will expand our Mesa, llvm "fix" to include versions up to 7

**Comment by AWoloszyn** [comment]
I have put in a fix that should stop newer Mesa drivers from interfering with our version of LLVM.
