### ISSUE TITLE
'No device bound for GPU texture read' log spam

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#2278]
```
W 11:30:38.397 gapis No device bound for GPU texture read
W 11:30:38.397 gapis No device bound for GPU texture read
W 11:30:38.398 gapis No device bound for GPU texture read
W 11:30:38.398 gapis No device bound for GPU texture read
W 11:30:38.398 gapis No device bound for GPU texture read
W 11:30:38.399 gapis No device bound for GPU texture read
...
```

There's a mutate run that apparently has no device bound for GPU texture read. This spam occurs for most GLES traces I've tried.

We should make sure that there's a device bound, or shut this up after the first warning. The log spam stalls the client.

**Comment by pmuetschard** [comment]
I'm wondering if instead of putting the device into the `ReadGPUTextureDataResolveable` we just get it from the config when we do the resolve?

**Comment by ben-clayton** [comment]
The resolve is done on a 'clean' context (via one stored in the database) - there is nothing to get.

**Comment by pmuetschard** [comment]
Sorry I put the comment here, instead of the PR. Ok, I just realized my mistake. The resolve config is not presented during the resolve, but is actually part of the resolvable.

**Comment by jimmy12day** [comment]
This problem still exists in the latest release. Can you fix it?
