### ISSUE TITLE
Is there any guide to trace code of GAPID? 

### ISSUE THREAD

**Issue by AwinHuang** [google/gapid#2286]
Hi,
I want to know how to parse gfxtrace file, and convert it to other format.
Where is the code to define the binary file of gfxtrace file?
I download the source code of GAPID, but too many files to trace.

Thanks.

**Comment by AWoloszyn** [comment]
A good starting point to look at the data format would be

https://github.com/google/gapid/blob/master/cmd/gapit/unpack.go

`gapit unpack file.gfxtrace`
Is a simple command-line tool that prints out the contents of a trace file.

If you are looking for a mid-execution capture (a capture that does not start at time 0), then there is a big data-blob that lives at the start of the trace. In this case there are a number of initial memory blocks, and a state block encoded before the commands. This is the same state block that you will see in the GUI.

If you would like to not have to handle that state block, there is a utility you can build 
https://github.com/google/gapid/blob/master/cmd/linearize_trace
that will turn that state block into a set of commands needed to set up your replay.

The file itself is self-describing proto. Meaning we encode the proto definition for any type before the first time you see it. You can see
https://github.com/google/gapid/core/data/pack/README.MD
for a more well-defined description of the format.

**Comment by AwinHuang** [comment]
Hi, I parsed gfxtrace by C++. After parse the header, which proto file I  could use for decode the chunk?
According to [https://github.com/google/gapid/tree/master/core/data/pack](https://github.com/google/gapid/tree/master/core/data/pack), read the header is easy.

```c++
FILE* pFile = fopen(a_gfxtrace_file, "rb");
if (pFile) {
	char header[16] = {0};
	fread(header, 1, 16, pFile);
}
```

The  header is equal to `"ProtoPack\r\n2.0\n\0"`
And then I try to decode the chunk, I didn't find the C++ function like `DecodeVarint()` or `unmarshal()` in Go, where can I find these functions?

**Comment by AwinHuang** [comment]
Hi, thanks for answer.
Yes I want to use proto compiler, but I don't known how each chunks in gfxtrace mapping to ptoro files in GAPID.
Is it capture.proto, gfxtrace.proto or memory.proto?

**Comment by ben-clayton** [comment]
Is could be any of those.

Before the first time a [object instance chunk](https://github.com/google/gapid/blob/master/core/data/pack/README.MD#object-instance-chunk-size0) of a new type is encoded, [its full type information is encoded](https://github.com/google/gapid/blob/master/core/data/pack/README.MD#type-definition-chunk-size0) as a [`DescriptorProto`](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.proto#L93).
This `DescriptorProto` fully describes the object structure (so you could deserialize the object without the GAPID .proto files), and/or can be used to link back to the `protoc` generated decoders.

**Comment by AwinHuang** [comment]
Hi, thank you. But it is really hard to understand.
Any tutorial about this?
I found some article about dynamic message(e.g. [Extending Protobuf: dynamic messages](http://giorgio.azzinna.ro/2017/07/extending-protobuf-dynamic-messages/#about-protobuf)), is these help?
