### ISSUE TITLE
Texture decompression crashes

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#230]
The recent change seems to be crashing for me when testing SkyCastle.

23:49:20.326 F: <gapit> Main failed
Error: Failed to acquire the capture's report
   Cause: rpc error: code = 13 desc = transport is closing

This is all that I have managed to extract from the logs - mysteriously there is no other crash message

**Comment by ben-clayton** [comment]
I can't reproduce this, nor can I do anything with this little information.

**Comment by dsrbecky** [comment]
The code was passing (GL_ETC1_RGB8_OES, GL_NONE)
but the switch was expecting (GL_NONE, GL_ETC1_RGB8_OES)
which raised a panic.  Fixed in #223

**Comment by ben-clayton** [comment]
Yeah, I saw that it was broken before your CL - but I thought you raised this bug _after_ you checked in your CL.
:confused:

**Comment by dsrbecky** [comment]
Correct - sadly the fixing CL also introduced another crash, which made it a bit more tricky to track down.  Both should be fixed now...
