### ISSUE TITLE
Too many Textures with same ID

### ISSUE THREAD

**Issue by KimiKiwi** [google/gapid#2305]
Hi,
I get many texture items that have same ID listed in the Textures tab. just like:
Texture<152> XXXXX
Texture<153> XXXXX
Texture<154> XXXXX
Texture<152> XXXXX
Texture<153> XXXXX
......

I want to understand what's the reason  and what does it mean.

Thanks a lot.

**Comment by pmuetschard** [comment]
It means either:
 - your application used multiple contexts and the contexts used the same identifiers see #1025 
 - your application deleted textures and GL re-used identifiers of deleted textures when creating new ones see #2303
