### ISSUE TITLE
Tracing Failed   Cause: Could not start trace   Cause: loadGAPII   Cause: Passed thread is null, is not a valid thread or has exited.

### ISSUE THREAD

**Issue by kaizer1** [google/gapid#2315]
GAPID Version: 1.2.0:493d1ed1849d2196c5548268b041488e69f38479
OS: mac os x x86_64

Gapid log: 
08:53:55.003 I: <gapis> Adding new device
08:53:55.003 I: <gapis> New trace scheduler for device: f745ebe5cbda8a3471acbb39b2524633367d046e SergeiLkovsMini.Dlink
08:53:55.003 I: <gapis> New scheduler for device: f745ebe5cbda8a3471acbb39b2524633367d046e
08:53:55.010 I: <gapis> Starting grpc server
08:54:04.260 I: [Try ABI: armeabi-v7a⇒gapidapk.EnsureInstalled] <gapis> Examining gapid.apk on host...
08:54:04.268 I: [Try ABI: armeabi-v7a⇒gapidapk.EnsureInstalled] <gapis> Looking for gapid.apk...
08:54:04.954 I: [Try ABI: armeabi-v7a⇒gapidapk.EnsureInstalled] <gapis> Found gapid package...
08:54:04.954 I: [startDevInfoService] <gapis> Attempt to start service: com.google.android.gapid.DeviceInfoService
08:54:05.543 I: <gapis> Adding new device
08:54:05.543 I: <gapis> Adding new device
08:54:05.543 I: <gapis> New scheduler for device: 73ec8cc750f076880a53a6c2943ce7bc58914cef
08:54:05.543 I: <gapis> New trace scheduler for device: 73ec8cc750f076880a53a6c2943ce7bc58914cef samsung SM-T710
08:58:25.902 I: <gapis> Clearing package cache
08:58:26.990 I: <gapis> Starting with options {ObserveFrameFrequency:0 ObserveDrawFrequency:0 StartFrame:0 FramesToCapture:0 APIs:10 Flags:1 AdditionalFlags:}
08:58:27.022 I: [start] <gapis> Turning device screen on
08:58:27.065 I: [start] <gapis> Checking for lockscreen
08:58:27.188 W: [start] <gapis> Couldn't determine lockscreen state: 
   Cause: Couldn't get lockscreen state
08:58:27.188 I: [start] <gapis> Checking gapid.apk is installed
08:58:27.188 I: [gapidapk.EnsureInstalled⇒start] <gapis> Examining gapid.apk on host...
08:58:27.220 I: [gapidapk.EnsureInstalled⇒start] <gapis> Looking for gapid.apk...
08:58:27.821 I: [gapidapk.EnsureInstalled⇒start] <gapis> Found gapid package...
08:58:27.821 I: [start] <gapis> Forwarding
08:58:27.832 I: [start] <gapis> Starting activity in debug mode
08:58:39.050 I: [start] <gapis> Forwarding TCP port 52464 -> JDWP pid 8448
08:58:39.061 I: [start] <gapis> Connecting to JDWP
08:58:39.069 I: [start] <gapis> Waiting for ApplicationLoaders.getClassLoader()
08:58:39.137 W: [start] <gapis> Couldn't break in ApplicationLoaders.getClassLoader. Vulkan will not be supported.
08:58:39.137 I: [start] <gapis> Waiting for Application Creation
08:58:39.139 I: [start] <gapis>    Waiting for Application.<init>()
08:58:42.656 I: [start] <gapis>    Waiting for android.app.Application.onCreate()
08:58:43.927 I: [start] <gapis> Installing interceptor libraries
08:58:44.048 I: [start] <gapis> GVR library not found
08:58:44.201 I: [start] <gapis> Waiting for connection to localhost:52430...
08:58:44.312 W: [start] <gapis> Failed to read packet. Error: read tcp 127.0.0.1:52469->127.0.0.1:52464: use of closed network connection

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

p.s. 
  Version 1.2 not working same as previous version =))

**Comment by AWoloszyn** [comment]
Closing, not enough information

**Comment by kaizer1** [comment]
Oh, and I did not understand what information is needed now from my logcat
