### ISSUE TITLE
gapit does not report crashes

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#233]
Add panic to gles.Replay(...)
run "gapit report ..."
It terminates with just Cause: rpc error: code = 13 desc = transport is closing
And as far as I can tell the panic is not logged anywhere.

**Comment by dsrbecky** [comment]
This is not duplicate #244.  That ones is about impossibility of getting any crash info from gapir (C++)

This bug is about gapit/gapis somehow hiding all Go panics.

**Comment by ben-clayton** [comment]
> This bug is about gapit/gapis somehow hiding all Go panics.

The problem is simply that gapis's stderr is not logged by gapit.
I suspect adding this line to [gapis/client/process.go](https://github.com/google/gapid/blob/master/gapis/client/process.go#L91-L93) would work:
```go
cfg.Port, err = process.Start(ctx, cfg.Path.System(), process.StartOptions{
	Args:   cfg.Args,
	Stderr: log.From(log.PutProcess(ctx, "gapis")).Writer(log.Error),
})
```

**Comment by ben-clayton** [comment]
I believe this to be fixed.
