### ISSUE TITLE
Tracing Failed   Cause: Could not start trace   Cause: Getting pid   Cause: Process not found

### ISSUE THREAD

**Issue by thuyumeng** [google/gapid#2333]
GAPID Version: 1.2.0:493d1ed1849d2196c5548268b041488e69f38479
OS: mac os x x86_64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

**Comment by AWoloszyn** [comment]
Can you provide the output of your log as well as the device.

**Comment by AWoloszyn** [comment]
Closing, due to lack of further information.
