### ISSUE TITLE
App crashes with GL_INVALID_OPERATION

### ISSUE THREAD

**Issue by thuyumeng** [google/gapid#2334]
here is the logcat:
10-31 19:18:39.342 14733 14787 W GAPID   : [gapii/cc/gles_spy_externs.cpp:77] Error calling glGenRenderbuffersOES: GL_INVALID_OPERATION
10-31 19:18:39.354 14733 14787 W GAPID   : [gapii/cc/gles_spy_externs.cpp:77] Error calling glBindRenderbufferOES: GL_INVALID_OPERATION
10-31 19:18:39.355 14733 14787 W GAPID   : [gapii/cc/gles_spy_externs.cpp:77] Error calling glRenderbufferStorageOES: GL_INVALID_OPERATION
10-31 19:18:43.413 14733 14787 I GAPID   : [gapii/cc/spy.cpp:377] Framebuffer config: R8 G8 B8 A0 D24 S8
10-31 19:18:43.424 14733 14787 I GAPID   : [gapii/cc/spy.cpp:377] Framebuffer config: R8 G8 B8 A0 D24 S8
10-31 19:18:43.594 14733 14787 W GAPID   : [gapii/cc/gles_spy_externs.cpp:77] Error calling glGenFramebuffersOES: GL_INVALID_OPERATION
10-31 19:18:43.594 14733 14787 W GAPID   : [gapii/cc/gles_spy_externs.cpp:77] Error calling glBindFramebufferOES: GL_INVALID_OPERATION
10-31 19:18:43.595 14733 14787 W GAPID   : [gapii/cc/gles_spy_externs.cpp:77] Error calling glFramebufferTexture2DOES: GL_INVALID_OPERATION
10-31 19:18:43.596 14733 14787 W GAPID   : [gapii/cc/gles_spy_externs.cpp:77] Error calling glCheckFramebufferStatusOES: GL_INVALID_OPERATION
10-31 19:18:43.597 14733 14787 W GAPID   : [gapii/cc/gles_spy_externs.cpp:77] Error calling glGenFramebuffersOES: GL_INVALID_OPERATION
10-31 19:18:43.597 14733 14787 W GAPID   : [gapii/cc/gles_spy_externs.cpp:77] Error calling glBindFramebufferOES: GL_INVALID_OPERATION
10-31 19:18:43.597 14733 14787 W GAPID   : [gapii/cc/gles_spy_externs.cpp:77] Error calling glFramebufferTexture2DOES: GL_INVALID_OPERATION
10-31 19:18:43.598 14733 14787 W GAPID   : [gapii/cc/gles_spy_externs.cpp:77] Error calling glFramebufferTexture2DOES: GL_INVALID_OPERATION
10-31 19:18:43.598 14733 14787 W GAPID   : [gapii/cc/gles_spy_externs.cpp:77] Error calling glCheckFramebufferStatusOES: GL_INVALID_OPERATION
10-31 19:18:43.620 14733 14787 F GAPID   : [./gapil/runtime/cc/slice.inc:182] Assert: <index < count()>: slice index out of bounds

**Comment by AWoloszyn** [comment]
This bug should be fixed in latest

Assert: <index < count()>: slice index out of bounds

**Comment by pmuetschard** [comment]
This is a dupe of #2332
