### ISSUE TITLE
Build Problem on Windows

### ISSUE THREAD

**Issue by wzhfantastic** [google/gapid#234]
I'm new here. Just meet the build error on windows:

`CMake Error at xxx/CMake/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
Could NOT find Threads (missing: Threads_FOUND)`

It seems that CMake cannot find win32 style thread.
Anyone knows how to fix this error? Thanks!

**Comment by ben-clayton** [comment]
Hi @wzhfantastic - sorry we didn't get to reply to your issue. Did you solve it?

**Comment by wzhfantastic** [comment]
@ben-clayton - Yeah, I have solved it, thanks! It's my fault. It's caused by a "space" in my NDK path.
