### ISSUE TITLE
Stuck in infinite loop loading trace (Linux, desktop)

### ISSUE THREAD

**Issue by ShabbyX** [google/gapid#2348]
I tried to trace an ANGLE perftest to test GAPID with (on Linux, Nvidia, Vulkan), which seems to have worked in the sense that there is a .gfxtrace file generated. However, when opening the trace, the interface is seemingly stuck in an infinite loop trying to load the file:

![gapid-stuck](https://user-images.githubusercontent.com/1067408/47936229-6a602c00-deb3-11e8-9af6-b43d3798d70a.png)

This happens regardless of if I trace from the beginning or not.

I tried to verify functionality by tracing vulkan-smoketest, which does work (even though capturing ~15 frames does take a large amount of time to fully load).

Running gapid from the command line, loading the trace just gets stuck at:

I20181102-152642029[main][models.Capture.loadCapture] Loading capture /path/to/trace.gfxtrace...

What can I do to debug this issue?

**Comment by ShabbyX** [comment]
Perhaps. I was thinking also it may be that Angle does a "try vulkan" on init to see if it's supported (i.e. create a device and swapchain), then recreates everything and that may be confusing GAPID. I'm saying this because I notice a 16KB acquisition in the beginning even if I don't trace from the start.

I'll send you the trace tomorrow.

**Comment by AWoloszyn** [comment]
The data sent at the start is a header. This will happen for any trace.

**Comment by y-novikov** [comment]
I suspect the issue here might have been that ANGLE links statically with Vulkan loader by default, which GAPID can't intercept, thus the trace is empty.
Shabby, could you try building ANGLE with "angle_shared_libvulkan = true", and if you get > 16KB trace, this is WAI.

**Comment by pau-baiget** [comment]
@ShabbyX , did you get any results from @y-novikov 's suggestion?

**Comment by ShabbyX** [comment]
@pau-baiget Yes, I tried it just yesterday and I can confirm that using angle_shared_libvulkan=true works.
