### ISSUE TITLE
Tracer should default to MFC and short traces

### ISSUE THREAD

**Issue by pau-baiget** [google/gapid#2367]
In order to ensure an average best user experience, the default capture options should be set to MFC (Mid Frame Capture) and number of frames to be captured should default to a low number between 5 and 10. This bug tracks the modifications in the UI required to express those default values.

**Comment by pmuetschard** [comment]
... so what should the exact default value be for the frame count?

**Comment by AWoloszyn** [comment]
Split the difference and call it 7? (Roughly a full film-strip view is probably about right).

**Comment by pau-baiget** [comment]
Sounds good to me.
