### ISSUE TITLE
Failed to load image

### ISSUE THREAD

**Issue by lengxuegang** [google/gapid#2397]
Environment:
MacOS: 10.14.1
GAPID: 1.2.1
Device: XiaoMi Mix2S Android 9

After i captured a trace and open it, i got this error msg:
`W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] Failed to load image
W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] com.google.gapid.server.Client$InternalServerErrorException: Couldn't get framebuffer attachment
   Cause: Communicating with gapir
   Cause: Recv
   Cause: rpc error: code = 13 desc = transport is closing
`

and followed by many exceptions like this:

`W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] Caused by: com.google.gapid.server.Client$Stack: For request: RPC->get(blob { ID { data: 062e1d06e0d75cfcd1445293c6777074164f8b2a } }, ID { data: 033fe98c3dad49925b656c97134c859ea3cda4df })
W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] 	at com.google.gapid.server.Client.call(Client.java:274)
W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] 	at com.google.gapid.server.Client.get(Client.java:90)
W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] 	at com.google.gapid.image.FetchedImage$SingleFacedLevel.doLoad(FetchedImage.java:394)
W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] 	at com.google.gapid.image.FetchedImage$Level.get(FetchedImage.java:323)
W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] 	at com.google.gapid.image.FetchedImage$Layer.getImage(FetchedImage.java:282)
W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] 	at com.google.gapid.image.FetchedImage.getImage(FetchedImage.java:257)
W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] 	at com.google.gapid.image.FetchedImage.lambda$loadImage$6(FetchedImage.java:117)
W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653)
W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.setResult(AbstractTransformFuture.java:245)
W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:177)
W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractFuture.setFuture(AbstractFuture.java:711)
W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.setResult(AbstractTransformFuture.java:221)
W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.setResult(AbstractTransformFuture.java:200)
W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] 	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:177)
W20181126-220407801[grpc-default-executor-48][util.Logging.throttleLogRpcError] 	... 20 more
`

**Comment by AWoloszyn** [comment]
This sounds like the replay crashing:
 Communicating with gapir Cause: Recv Cause: rpc error: code = 13 desc = transport is closing

Is there anything notable in `adb locat`?
Also was this replaying an OpenGL ES or Vulkan trace?

**Comment by danielrobledo** [comment]
I'm having the same issue with my Galaxy Note 9 (OpenGL).

Here's the logcat https://gist.github.com/danielrobledo/9a2671c650444e8a563be5044ee7f6bb.

**Comment by AWoloszyn** [comment]
```
adbd    : failed to connect to socket 'localfilesystem:/data/data/com.google.android.gapid.armeabi/files/gapir-arm': Permission denied 
```

That looks like it is the same thing that https://github.com/google/gapid/pull/2388 just fixed.

This should be now fixed, and released with the next build.

**Comment by AWoloszyn** [comment]
If you still run into this, please leave a comment and I will re-open.
