### ISSUE TITLE
Tidy the GLES state block

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#24]
Add a global for `CurrentState` so we don't have to always go though the `map!(ThreadID, ref!Context) Contexts` global at the root of the state tree (ensure you update all Link() logic in gles/links.go).

Find a way to hide `GLXContexts`, `WGLContexts`, `CGLContexts`, `EGLContexts`.

Try navigating the state block in GAPIC, make changes to the API file to try and make state navigation not suck.

**Comment by dsrbecky** [comment]
+1 for the global.  Do we want to introduce the concept of thread-local storage, or we just update it before each command?

UI wise:  How about moving all globals to combo box?

**Comment by ben-clayton** [comment]
Given that the state reflects the currently selected command, then the state should probably reflect the current thread of that command.

**Comment by dsrbecky** [comment]
Do we consider this done now?

**Comment by ben-clayton** [comment]
I think we should probably implement `@hidden` first to hide fields we shouldn't be showing.
Then it can probably be removed from the milestone. After that there's still polish I'd like to do.

**Comment by ben-clayton** [comment]
Also - filter to currently selected context.
