### ISSUE TITLE
Compilation issue due to breakpad not found

### ISSUE THREAD

**Issue by rishi-rranjan** [google/gapid#2417]
I am using master branch. I have all the steps in setup done. 

> C:\sw\Temp\gapid>bazel build pkg
> WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
> c:\sw\temp\gapid/.bazelrc
> Starting local Bazel server and connecting to it...
> WARNING: The major revision of the Android NDK referenced by android_ndk_repository rule 'androidndk' is 18. The major revisions supported by Bazel are [10, 11, 12, 13, 14, 15, 16, 17]. Bazel will attempt to treat the NDK as if it was r17. This may cause compilation and linkage problems. Please download a supported NDK version.
> INFO: SHA256 (https://codeload.github.com/google/protobuf/zip/2761122b810fe8861004ae785cc3ab39f384d342) = b7dddc57db5825e0ae2843a173dfbe4b6c447d20c6b6cb3268d7c92287f0f29d
> INFO: SHA256 (https://codeload.github.com/grpc/grpc/zip/bd44e485f69d70ca4095cea92decd98de3892aa6) = 486ed046515f167e0e818442df9eaf91658b1bb29804eb2cf7caf276b4720083
> INFO: SHA256 (https://codeload.github.com/llvm-mirror/llvm/zip/e562960fe303c0ffab6f3458fcdb1544b56fd81e) = 3ef3d905849d547b6481b16d8e7b473a84efafbe90131e7bc90a0c6aae4cd8e6
> INFO: SHA256 (https://chromium.googlesource.com/breakpad/breakpad/+archive/a61afe7a3e865f1da7ff7185184fe23977c2adca.tar.gz) = c465b636d54c499cac8e16216c1ac9f4441c3769e713f438c2279770c87fb6e6
> INFO: SHA256 (https://chromium.googlesource.com/breakpad/breakpad/+archive/a61afe7a3e865f1da7ff7185184fe23977c2adca.tar.gz) = f6dbf8a9869b4f0c81f0282f1d61ef667328ac72f16bdaf60a9cd1a80eecd575
> INFO: SHA256 (https://chromium.googlesource.com/breakpad/breakpad/+archive/a61afe7a3e865f1da7ff7185184fe23977c2adca.tar.gz) = ed089118fbe98240c7f44d874b2a861051abadd2f5a1a28938d3ebe2476c2af7
> ERROR: C:/sw/temp/gapid/core/cc/BUILD.bazel:17:1: no such package '@breakpad//': Failed to apply patch: (1)
> /usr/bin/bash: line 0: cd: too many arguments
>  and referenced by '//core/cc:cc'
> ERROR: Analysis of target '//:pkg' failed; build aborted: no such package '@breakpad//': Failed to apply patch: (1)
> /usr/bin/bash: line 0: cd: too many arguments
> INFO: Elapsed time: 296.115s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (301 packages loaded, 12193 targets configured)

**Comment by rishi-rranjan** [comment]
print(repository_ctx.path(".")) gives following: 

`DEBUG: C:/users/rishi ranjan/_bazel_rishi ranjan/xppgjrnc/external/gapid/tools/build/third_party/breakpad.bzl:32:7: C:/users/rishi ranjan/_bazel_rishi ranjan/xppgjrnc/external/breakpad`


In `tools/build/third_party/breakpad.bzl` on line 33, changing the `cd {} `part to `cd \"{}\"` fixes this.

**Comment by pmuetschard** [comment]
Thanks for confirming. I've sent out a PR to fix this in the repo.
