### ISSUE TITLE
Can I replace gapir/cc/linux/gles_renderer.cpp to EGL version?

### ISSUE THREAD

**Issue by AwinHuang** [google/gapid#2430]
I want to run GAPIR with `EGL`, not `GLX` on Linux.
So I replace `gapir/cc/linux/gles_renderer.cpp` by `gapir/cc/android/gles_renderer.cpp` , but it doesn't work.
The first error is `eglCreateContext()`, return `0x3006` at the second call of `GlesRendererImpl::setBackbuffer()`. When `mSharedContext` is not NULL.

```c++
void GlesRendererImpl::setBackbuffer(Backbuffer backbuffer) {
...
    if (mContext == nullptr) {
        // Create an EGL context.
        const int contextAttribList[] = {
            // clang-format off
            EGL_CONTEXT_CLIENT_VERSION, 2,
            EGL_NONE
            // clang-format on
    };
    ↓Fail if mSharedContext != NULL
    mContext = eglCreateContext(mDisplay, mConfig, mSharedContext, contextAttribList); 
    EGL_CHECK_ERROR("Failed to create EGL context");
    mNeedsResolve = true;
  }
...
}
```

If I just assign `mContext = mSharedContext;` to avoid this error. Next error will occur when `eglMakeCurrent()`, the return code still `0x3006`.

I make sure that `EGL` was work on my system, the `MESA` example `es2gears` and `es2tri` were runable.
How do I trace this error? 
Thanks for your help.

**Comment by AWoloszyn** [comment]
Closing as discussion is happening in #2651
