### ISSUE TITLE
The gapis server has exited with an error code of: 2

### ISSUE THREAD

**Issue by LksWonder** [google/gapid#2520]
GAPID Version: 1.2.1:9acb3d602489c7389134f043d4a1e9c12b6e3ff5
OS: windows 10 amd64

panic: GLfloat(0xcda9c118@0)[4].Slice(1, 2) - out of bounds [recovered]
	panic: Panic at command 52745:glTexParameterfv(target: GL_TEXTURE_2D, pname: GL_TEXTURE_BORDER_COLOR, params: 0xcda9c114):
GLfloat(0xcda9c118@0)[4].Slice(1, 2) - out of bounds [recovered]
	panic: 
--- *resolve.ResourcesResolvable ---

**Comment by AWoloszyn** [comment]
This is fixed now.
