### ISSUE TITLE
Tracing Failed   Cause: Could not start trace   Cause: Failed to restart ADB as root: Process returned error   Cause: exit status 1

### ISSUE THREAD

**Issue by charick** [google/gapid#2546]
GAPID Version: 1.2.1:9acb3d602489c7389134f043d4a1e9c12b6e3ff5
OS: mac os x x86_64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

**Comment by AWoloszyn** [comment]
Closing for now.
https://github.com/google/gapid/releases/tag/v1.3.1 was released that may fix your issue.
