### ISSUE TITLE
what's meaning of 'show deleted textures'

### ISSUE THREAD

**Issue by CatDroid** [google/gapid#2547]
i want to know how GAPID can get the deleted textures from device ? or it is record the textures list that used before , and when glDeleteTextures is called ,then mark it as 'deleted' status ?

**Comment by CatDroid** [comment]
'show deleted textures'  is displayed on GAPID 1.2.1

**Comment by AWoloszyn** [comment]
This is only for textures that were deleted during the trace execution.
For example, if a texture was deleted at the start of a trace, you can use "show deleted textures" to see what the contents were even if you click on the last command in the trace.
