### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by jgavris** [google/gapid#2566]
Just wondering when the next release will be cut? The last was in November 2018. There are some important bug fixes I need and this project apparently takes hours to compile, even on an 18 core Xeon!

**Comment by AWoloszyn** [comment]
Thanks for your interest. I will look into getting a release together in the near future. 


Your build times seem long, however. A clean build on my fairly modest laptop, takes ~1h.
FYI: If you are on windows, Windows Defender / most AV products trash the build time

**Comment by jgavris** [comment]
I'm on an iMac Pro 18 core, running 36 actions. About 2 hours so far. Do you have remote caching / execution setup locally?

**Comment by AWoloszyn** [comment]
I do not have either set up. 

One thing that may help, if you only need a sub-set of the Android ABIs 
`gapid/BUILD.bazel` you can comment out the unneeded apks. That can shave quite a bit of time off.

FYI: We have started the release process, and should have a build up reasonably soon.

**Comment by jgavris** [comment]
Ah, yes of course, I only need ARM64. Thanks!

**Comment by AWoloszyn** [comment]
The next release will be based off this branch

https://github.com/google/gapid/tree/1.3.x
once some testing/validation is done.

**Comment by AWoloszyn** [comment]
https://github.com/google/gapid/releases/tag/v1.3.1 Was just released. Closing this.
