### ISSUE TITLE
NDK r19 not supported

### ISSUE THREAD

**Issue by stolk** [google/gapid#2582]
Trying to build with NDK r19 (latest NDK) the following warning is issued:

WARNING: The major revision of the Android NDK referenced by android_ndk_repository rule 'androidndk' is 19. The major revisions supported by Bazel are [10, 11, 12, 13, 14, 15, 16, 17, 18]. Bazel will attempt to treat the NDK as if it was r18. This may cause compilation and linkage problems. Please download a supported NDK version.

**Comment by AWoloszyn** [comment]
Does the build finish successfully? Or is this causing a build failure.

**Comment by AWoloszyn** [comment]
This is just a bazel warning, NDK 19 should not cause build failures.
