### ISSUE TITLE
How to capture with command line?

### ISSUE THREAD

**Issue by ShabbyX** [google/gapid#2606]
I'm trying to investigate why exactly it's no longer possible to trace ANGLE's Vulkan backend with GAPID. A suspicion is that it's related to ANGLE's recent change to dynamically load its libEGL.so and libGLESv2.so files.

In order to understand what's going on, I need to see logs from ANGLE, which means I would need to run gapid from the command line. It looks like `gapit trace` should be it, but the help (`gapit trace --help`) does not very well specify how things should be done. I tried what my instinct said:

```
/opt/gapid/gapit trace ./executable --executable-flags
```

which resulted in an error saying "Expected application name". What's the proper way of taking traces from the command line?

**Comment by AWoloszyn** [comment]
Thanks for the bug, we should try and figure out how to clean up the help text.
The trick here is the executable name must always be the **last** argument to the tool.
`/opt/gapid/gapit trace -additionalargs "--executable -flags" ./executable`

**Comment by ShabbyX** [comment]
Thanks for the info
