### ISSUE TITLE
Can't capture trace for any system process such as com.android.systemui

### ISSUE THREAD

**Issue by liangpengfei** [google/gapid#2607]
I want to capture trace for RecentsActivity in com.android.systemui process, but when I click capture button, the tool's status is always initializing... And my phone turn into black screen. It seems like that GAPID need to kill the target process and relaunch it, but if you kill systemui process, you get black screen.

So, is there any way that I can get my trace? 

Thank you for help!

**Comment by AWoloszyn** [comment]
It is not currently possible to attach to an already-running process. There is too much information that we need that is only available at process start-up.
