### ISSUE TITLE
Couldn't scan devices: Connecting to service port

### ISSUE THREAD

**Issue by geobeans** [google/gapid#2612]
great tool！ But I cannot find my devices when I capture trace in the UI dialog.The log list as:
15:34:37.015 I: <gapis> Adding new device
15:34:37.015 I: <gapis> New trace scheduler for device: 98323d676134a623111868fb373b7bf2dec24d52 LAPTOP-15FTH711
15:34:37.015 I: <gapis> New scheduler for device: 98323d676134a623111868fb373b7bf2dec24d52
15:34:37.023 I: <gapis> Starting grpc server
15:34:38.006 I: [Try ABI: armeabi-v7a⇒gapidapk.EnsureInstalled] <gapis> Examining gapid.apk on host...
15:34:38.014 I: [Try ABI: armeabi-v7a⇒gapidapk.EnsureInstalled] <gapis> Looking for gapid.apk...
15:34:39.034 I: [Try ABI: armeabi-v7a⇒gapidapk.EnsureInstalled] <gapis> Found gapid package...
15:34:39.036 I:
 [startDevInfoService] <gapis> Attempt to start service: com.google.android.gapid.DeviceInfoService
15:35:13.067 I: [Try ABI: armeabi-v7a⇒gapidapk.EnsureInstalled] <gapis> Examining gapid.apk on host...
15:35:13.073 I: [Try ABI: armeabi-v7a⇒gapidapk.EnsureInstalled] <gapis> Looking for gapid.apk...
15:35:14.199 I: [Try ABI: armeabi-v7a⇒gapidapk.EnsureInstalled] <gapis> Found gapid package...
15:35:14.200 I: [startDevInfoService] <gapis> Attempt to start service: com.google.android.gapid.DeviceInfoService
15:35:47.209 E: <gapis> Couldn't scan devices: Connecting to service port
   Cause: 
   Cause: Timeout connecting to service
15:35:51.207 I: [Try ABI: armeabi-v7a⇒gapidapk.EnsureInstalled] <gapis> Examining gapid.apk on host...
15:35:51.212 I: [Try ABI: armeabi-v7a⇒gapidapk.EnsureInstalled] <gapis> Looking for gapid.apk...
15:35:52.307 I: [Try ABI: armeabi-v7a⇒gapidapk.EnsureInstalled] <gapis> Found gapid package...
15:35:52.307 I: [startDevInfoService] <gapis> Attempt to start service: com.google.android.gapid.DeviceInfoService

please help me!

**Comment by hevrard** [comment]
You can try to:
1. uninstall the existing gapid app which is on your device
2. check that your device is listed when you run `adb devices`
3. restart gapid

It looks like there is already a gapid app installed on the device. Uninstalling it will force gapid to reinstall the relevant app version, which may fix your problem.

**Comment by AWoloszyn** [comment]
This is a possibility if you have Android Studio open this could happen.

What is the android version of the device you are running? If a previous trace has failed, this may technically happen as well. You can try restarting the device to see if that helps.

**Comment by geobeans** [comment]
I restarted my device,restart gapid,and uninstall gapid in my device,the problem is same.
android version is 6.0. I have tried other devices, most can not find devices,only one device is good!
by the way, the devices must be rooted, isn't it?
