### ISSUE TITLE
On the shader list we should annotate the context each shader belongs to

### ISSUE THREAD

**Issue by pau-baiget** [google/gapid#2613]
There are repeated IDs in the list of shaders to inspect. See "shader 23" being repea in the trace taken from Maps:
![screenshot from 2019-02-18 15-01-06](https://user-images.githubusercontent.com/44697583/52959533-4f47f800-338e-11e9-860d-cebe32a1ecd3.png)

**Comment by AWoloszyn** [comment]
This is as expected. It is normal (and legal) in GLES to have the same ID as long as it comes from a different context. This is why the ID is annotated with the command-id that created it, so that we can disambiguate between the ids.

It might be good to annotate with the context as well so it is easier.

**Comment by pau-baiget** [comment]
>>> It might be good to annotate with the context as well so it is easier.

That was the bit that confused me. We can change this to be an enhancement but i'm afraid it will never get done.

**Comment by stellama0208** [comment]
The way I think of doing the enhancement is to, add additional hint.
Like, we can change the first line of "Select a shader." to "Select a shader. Shader<shader_id><cmd_id>".
It is a simple change, but it can solve the ambiguity.

Do you think this design is OK and can I do it in this way?

**Comment by AWoloszyn** [comment]
The main problem is that we can't identify which context the ID is from we are missing another piece of data. The VERY simplest would be 

Shader<shader_id><cmd_id><ctx_id>  which we would have to plumb through from GAPIS.

But we might also want some more flexibility here.

**Comment by stellama0208** [comment]
Fixed in PR #2833 .
