### ISSUE TITLE
GAPID build failed in Windows 7.

### ISSUE THREAD

**Issue by hans0527** [google/gapid#265]
GAPID build failed in Windows 7. Please check the error message.

[0/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/hans0527/gapid/release
[2/385] Linking Go executable bin\dump-manifest.exe
FAILED: bin/dump-manifest.exe
cmd.exe /C "cd . && "C:/Program Files (x86)/CMake/bin/cmake.exe" -DGO_ENV=C:/Use
rs/hans0527/gapid/release/go/goenv.cmake -DBUILDBOT=OFF -DGO_BUILD=bin\dump-mani
fest.exe -static   -DGO_PACKAGE=github.com/google/gapid/cmd/dump-manifest -P D:/
GoCode/src/github.com/google/gapid/cmake/Modules/GoCompile.cmake && cmd.exe /C "
cd /D C:\Users\hans0527\gapid\release && "C:\Program Files (x86)\CMake\bin\cmake
.exe" -DGO_ENV=C:/Users/hans0527/gapid/release/go/goenv.cmake -DGO_PACKAGE=githu
b.com/google/gapid/cmd/dump-manifest -DGO_DEPS_FILE=C:/Users/hans0527/gapid/rele
ase/go/deps/cmd-dump-manifest.cmake -P D:/GoCode/src/github.com/google/gapid/cma
ke/Modules/GoDeps.cmake""
# github.com/google/gapid/core/os/android/binaryxml
D:\GoCode\src\github.com\google\gapid\core\os\android\binaryxml\string_pool.go:2
06: constant 4294967295 overflows int
CMake Error at D:/GoCode/src/github.com/google/gapid/cmake/Modules/GoCompile.cma
ke:37 (message):
  2

[7/385] Linking Go static library go\tags\core-video.tag
ninja: build stopped: subcommand failed.
Error running d:\ninja.exe [install]: Process returned error
   Cause: exit status 1
exit status 1

**Comment by AWoloszyn** [comment]
Curious that we have not seen this on other platforms.
#266 Should fix this. Please let me know if  that works for you.

**Comment by ben-clayton** [comment]
This smells like we're attempting to compile a 32-bit executable. This will never work.

**Comment by AWoloszyn** [comment]
Good point.
@hans0527  Would you be able to try with 64-bit golang, and see if that fixes your issue instead, my fix will likely not solve your problem if you are building with 32-bit golang.

**Comment by hans0527** [comment]
Replace with 64 golang and have been resolved.Thank you very much.

**Comment by Eric1732** [comment]
Same issue here on Windows 7_x64 Pro. Please advise how to "replace with 64-bit golang" , isn't the Go 1.8 downloaded from here already 64-bit ? 

***error message below

[1/10] Linking CXX executable bin\gapir.exe
FAILED: bin/gapir.exe 
cmd.exe /C "cd . && C:\msys64\mingw64\bin\x86_64-w64-mingw32-g++.exe  -Wa,-mbig-obj -std=c++0x -O3 -DNDEBUG  -static CMakeFiles/gapir.dir/cmd/gapir/cc/main.cpp.obj  -o bin\gapir.exe -Wl,--out-implib,libgapir.dll.a -Wl,--major-image-version,0,--minor-image-version,0  libgapir.a libcc-core.a libcityhash.a "C:/Program Files (x86)/Microsoft Visual Studio/VC98/Lib/WS2_32.LIB" "C:/Program Files (x86)/Microsoft Visual Studio/VC98/Lib/OPENGL32.LIB" -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
libgapir.a(gles_renderer.cpp.obj):gles_renderer.cpp:(.text+0x63): undefined reference to `__imp_wglDeleteContext'
libgapir.a(gles_renderer.cpp.obj):gles_renderer.cpp:(.text+0x13b): undefined reference to `__imp_wglMakeCurrent'
libgapir.a(gles_renderer.cpp.obj):gles_renderer.cpp:(.text+0x43f): undefined reference to `__imp_wglCreateContext'
libgapir.a(gles_renderer.cpp.obj):gles_renderer.cpp:(.text+0x6b0): undefined reference to `__imp_wglMakeCurrent'
libgapir.a(gles_renderer.cpp.obj):gles_renderer.cpp:(.text+0x9db): undefined reference to `__imp_wglMakeCurrent'
libgapir.a(gles_renderer.cpp.obj):gles_renderer.cpp:(.text+0xb20): undefined reference to `__imp_wglMakeCurrent'
libgapir.a(gles_renderer.cpp.obj):gles_renderer.cpp:(.text+0xe30): undefined reference to `__imp_wglCreateContext'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0xd): undefined reference to `__imp_send'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x30): undefined reference to `__imp_recv'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x46): undefined reference to `__imp_WSAGetLastError'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0xc7): undefined reference to `__imp_select'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0xfa): undefined reference to `__imp_accept'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x11e): undefined reference to `__imp_WSAGetLastError'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x174): undefined reference to `__imp_closesocket'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x197): undefined reference to `__imp_WSACleanup'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x1b3): undefined reference to `__imp_WSAStartup'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x233): undefined reference to `__imp_WSAGetLastError'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x358): undefined reference to `__imp_closesocket'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x367): undefined reference to `__imp_WSACleanup'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x40c): undefined reference to `__imp_getaddrinfo'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x424): undefined reference to `__imp_WSAGetLastError'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x474): undefined reference to `__imp_WSACleanup'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x4a1): undefined reference to `__imp_socket'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x4dd): undefined reference to `__imp_setsockopt'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x4f8): undefined reference to `__imp_WSAGetLastError'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x53e): undefined reference to `__imp_closesocket'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x55f): undefined reference to `__imp_WSAStartup'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x5ae): undefined reference to `__imp_WSAGetLastError'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x5f4): undefined reference to `__imp_freeaddrinfo'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x612): undefined reference to `__imp_bind'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x632): undefined reference to `__imp_getsockname'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x651): undefined reference to `__imp_WSAGetLastError'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x6a2): undefined reference to `__imp_WSAGetLastError'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x6eb): undefined reference to `__imp_listen'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x706): undefined reference to `__imp_WSAGetLastError'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x74c): undefined reference to `__imp_ntohs'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x7b3): undefined reference to `__imp_WSAStartup'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x7f2): undefined reference to `__imp_closesocket'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x7fb): undefined reference to `__imp_freeaddrinfo'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x80a): undefined reference to `__imp_WSACleanup'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x873): undefined reference to `__imp_WSACleanup'
collect2.exe: error: ld returned 1 exit status
[2/10] Linking CXX executable test\gapir-tests.exe
FAILED: test/gapir-tests.exe 
cmd.exe /C "cd . && C:\msys64\mingw64\bin\x86_64-w64-mingw32-g++.exe  -Wa,-mbig-obj -std=c++0x -O3 -DNDEBUG  -static CMakeFiles/gapir-tests.dir/gapir/cc/context_test.cpp.obj CMakeFiles/gapir-tests.dir/gapir/cc/interpreter_test.cpp.obj CMakeFiles/gapir-tests.dir/gapir/cc/memory_manager_test.cpp.obj CMakeFiles/gapir-tests.dir/gapir/cc/post_buffer_test.cpp.obj CMakeFiles/gapir-tests.dir/gapir/cc/replay_request_test.cpp.obj CMakeFiles/gapir-tests.dir/gapir/cc/resource_in_memory_cache_test.cpp.obj CMakeFiles/gapir-tests.dir/gapir/cc/resource_requester_test.cpp.obj CMakeFiles/gapir-tests.dir/gapir/cc/server_connection_test.cpp.obj CMakeFiles/gapir-tests.dir/gapir/cc/server_listener_test.cpp.obj CMakeFiles/gapir-tests.dir/gapir/cc/stack_test.cpp.obj CMakeFiles/gapir-tests.dir/gapir/cc/test_utilities_test.cpp.obj  -o test\gapir-tests.exe -Wl,--out-implib,libgapir-tests.dll.a -Wl,--major-image-version,0,--minor-image-version,0  libgtest_main.a libgapir.a libgmock.a libcc-core.a libcityhash.a "C:/Program Files (x86)/Microsoft Visual Studio/VC98/Lib/WS2_32.LIB" "C:/Program Files (x86)/Microsoft Visual Studio/VC98/Lib/OPENGL32.LIB" -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
libgapir.a(gles_renderer.cpp.obj):gles_renderer.cpp:(.text+0x63): undefined reference to `__imp_wglDeleteContext'
libgapir.a(gles_renderer.cpp.obj):gles_renderer.cpp:(.text+0x13b): undefined reference to `__imp_wglMakeCurrent'
libgapir.a(gles_renderer.cpp.obj):gles_renderer.cpp:(.text+0x43f): undefined reference to `__imp_wglCreateContext'
libgapir.a(gles_renderer.cpp.obj):gles_renderer.cpp:(.text+0x6b0): undefined reference to `__imp_wglMakeCurrent'
libgapir.a(gles_renderer.cpp.obj):gles_renderer.cpp:(.text+0x9db): undefined reference to `__imp_wglMakeCurrent'
libgapir.a(gles_renderer.cpp.obj):gles_renderer.cpp:(.text+0xb20): undefined reference to `__imp_wglMakeCurrent'
libgapir.a(gles_renderer.cpp.obj):gles_renderer.cpp:(.text+0xe30): undefined reference to `__imp_wglCreateContext'
collect2.exe: error: ld returned 1 exit status
[3/10] Gradle: armeabi-gradle-gapid-apk
FAILED: armeabi/gapid-apk/app/build/outputs/apk/app-debug.apk 
cmd.exe /C "cd /D G:\GAPID_out\release\armeabi\gapid-apk && "C:\Program Files (x86)\CMake\bin\cmake.exe" -DGRADLE_ENV=G:/GAPID_out/release/gradleenv.cmake -DGRADLE_ARGS="-Pfilehash=G:/GAPID_out/release/bin/filehash.exe -Pinputs=G:/GAPID_out/release/armeabi/gapid-apk/app/src/main/jniLibs/armeabi//libgapir.so,G:/GAPID_out/release/armeabi/gapid-apk/app/src/main/jniLibs/armeabi//libgapii.so,G:/GAPID_out/release/armeabi/gapid-apk/app/src/main/jniLibs/armeabi//libinterceptor.so,G:/GAPID_out/release/armeabi/gapid-apk/app/src/main/jniLibs/armeabi//libdeviceinfo.so,G:/GAPID_out/release/armeabi/gapid-apk/app/src/main/jniLibs/armeabi//libVkLayerGraphicsSpy.so,G:/GAPID_out/release/armeabi/gapid-apk/app/src/main/jniLibs/armeabi//libVkLayer_VirtualSwapchain.so,G:/GAPID_out/release/armeabi/gapid-apk/app/build.gradle,G:/GAPID_out/release/armeabi/gapid-apk/app/src/main/java/com/google/android/gapid/DeviceInfoService.java,G:/GAPID_out/release/armeabi/gapid-apk/app/src/main/java/com/google/android/gapid/PackageInfoService.java,G:/GAPID_out/release/armeabi/gapid-apk/app/src/main/java/com/google/android/gapid/SocketWriter.java,G:/GAPID_out/release/armeabi/gapid-apk/app/src/main/res/drawable-xxxhdpi/logo.png,G:/GAPID_out/release/armeabi/gapid-apk/build.gradle,G:/GAPID_out/release/armeabi/gapid-apk/gradle.properties,G:/GAPID_out/release/armeabi/gapid-apk/gradle/wrapper/gradle-wrapper.jar,G:/GAPID_out/release/armeabi/gapid-apk/gradle/wrapper/gradle-wrapper.properties,G:/GAPID_out/release/armeabi/gapid-apk/gradlew,G:/GAPID_out/release/armeabi/gapid-apk/gradlew.bat,G:/GAPID_out/release/armeabi/gapid-apk/settings.gradle,G:/GAPID_out/release/armeabi/gapid-apk/app/src/main/res/values/strings.xml,G:/GAPID_out/release/armeabi/gapid-apk/app/src/main/AndroidManifest.xml" -P C:/Users/USER/go/src/github.com/google/gapid/cmake/Modules/RunGradle.cmake"


FAILURE: Build failed with an exception.



* What went wrong:

A problem occurred configuring project ':app'.

> failed to find target with hash string 'android-21' in: D:\0-Intek\OpenGL\GAPID\AndroidSDK_tools_r25.2.3-windows



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.



BUILD FAILED



Total time: 4.488 secs

CMake Error at C:/Users/USER/go/src/github.com/google/gapid/cmake/Modules/RunGradle.cmake:32 (message):
  1


[4/10] Gradle: x86-gradle-gapid-apk
FAILED: x86/gapid-apk/app/build/outputs/apk/app-debug.apk 
cmd.exe /C "cd /D G:\GAPID_out\release\x86\gapid-apk && "C:\Program Files (x86)\CMake\bin\cmake.exe" -DGRADLE_ENV=G:/GAPID_out/release/gradleenv.cmake -DGRADLE_ARGS="-Pfilehash=G:/GAPID_out/release/bin/filehash.exe -Pinputs=G:/GAPID_out/release/x86/gapid-apk/app/src/main/jniLibs/x86//libgapir.so,G:/GAPID_out/release/x86/gapid-apk/app/src/main/jniLibs/x86//libgapii.so,G:/GAPID_out/release/x86/gapid-apk/app/src/main/jniLibs/x86//libinterceptor.so,G:/GAPID_out/release/x86/gapid-apk/app/src/main/jniLibs/x86//libdeviceinfo.so,G:/GAPID_out/release/x86/gapid-apk/app/src/main/jniLibs/x86//libVkLayerGraphicsSpy.so,G:/GAPID_out/release/x86/gapid-apk/app/src/main/jniLibs/x86//libVkLayer_VirtualSwapchain.so,G:/GAPID_out/release/x86/gapid-apk/app/build.gradle,G:/GAPID_out/release/x86/gapid-apk/app/src/main/java/com/google/android/gapid/DeviceInfoService.java,G:/GAPID_out/release/x86/gapid-apk/app/src/main/java/com/google/android/gapid/PackageInfoService.java,G:/GAPID_out/release/x86/gapid-apk/app/src/main/java/com/google/android/gapid/SocketWriter.java,G:/GAPID_out/release/x86/gapid-apk/app/src/main/res/drawable-xxxhdpi/logo.png,G:/GAPID_out/release/x86/gapid-apk/build.gradle,G:/GAPID_out/release/x86/gapid-apk/gradle.properties,G:/GAPID_out/release/x86/gapid-apk/gradle/wrapper/gradle-wrapper.jar,G:/GAPID_out/release/x86/gapid-apk/gradle/wrapper/gradle-wrapper.properties,G:/GAPID_out/release/x86/gapid-apk/gradlew,G:/GAPID_out/release/x86/gapid-apk/gradlew.bat,G:/GAPID_out/release/x86/gapid-apk/settings.gradle,G:/GAPID_out/release/x86/gapid-apk/app/src/main/res/values/strings.xml,G:/GAPID_out/release/x86/gapid-apk/app/src/main/AndroidManifest.xml" -P C:/Users/USER/go/src/github.com/google/gapid/cmake/Modules/RunGradle.cmake"


FAILURE: Build failed with an exception.



* What went wrong:

A problem occurred configuring project ':app'.

> failed to find target with hash string 'android-21' in: D:\0-Intek\OpenGL\GAPID\AndroidSDK_tools_r25.2.3-windows



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.



BUILD FAILED



Total time: 5.18 secs

CMake Error at C:/Users/USER/go/src/github.com/google/gapid/cmake/Modules/RunGradle.cmake:32 (message):
  1


[5/10] Gradle: aarch64-gradle-gapid-apk
FAILED: aarch64/gapid-apk/app/build/outputs/apk/app-debug.apk 
cmd.exe /C "cd /D G:\GAPID_out\release\aarch64\gapid-apk && "C:\Program Files (x86)\CMake\bin\cmake.exe" -DGRADLE_ENV=G:/GAPID_out/release/gradleenv.cmake -DGRADLE_ARGS="-Pfilehash=G:/GAPID_out/release/bin/filehash.exe -Pinputs=G:/GAPID_out/release/aarch64/gapid-apk/app/src/main/jniLibs/arm64-v8a//libgapir.so,G:/GAPID_out/release/aarch64/gapid-apk/app/src/main/jniLibs/arm64-v8a//libgapii.so,G:/GAPID_out/release/aarch64/gapid-apk/app/src/main/jniLibs/arm64-v8a//libinterceptor.so,G:/GAPID_out/release/aarch64/gapid-apk/app/src/main/jniLibs/arm64-v8a//libdeviceinfo.so,G:/GAPID_out/release/aarch64/gapid-apk/app/src/main/jniLibs/arm64-v8a//libVkLayerGraphicsSpy.so,G:/GAPID_out/release/aarch64/gapid-apk/app/src/main/jniLibs/arm64-v8a//libVkLayer_VirtualSwapchain.so,G:/GAPID_out/release/aarch64/gapid-apk/app/build.gradle,G:/GAPID_out/release/aarch64/gapid-apk/app/src/main/java/com/google/android/gapid/DeviceInfoService.java,G:/GAPID_out/release/aarch64/gapid-apk/app/src/main/java/com/google/android/gapid/PackageInfoService.java,G:/GAPID_out/release/aarch64/gapid-apk/app/src/main/java/com/google/android/gapid/SocketWriter.java,G:/GAPID_out/release/aarch64/gapid-apk/app/src/main/res/drawable-xxxhdpi/logo.png,G:/GAPID_out/release/aarch64/gapid-apk/build.gradle,G:/GAPID_out/release/aarch64/gapid-apk/gradle.properties,G:/GAPID_out/release/aarch64/gapid-apk/gradle/wrapper/gradle-wrapper.jar,G:/GAPID_out/release/aarch64/gapid-apk/gradle/wrapper/gradle-wrapper.properties,G:/GAPID_out/release/aarch64/gapid-apk/gradlew,G:/GAPID_out/release/aarch64/gapid-apk/gradlew.bat,G:/GAPID_out/release/aarch64/gapid-apk/settings.gradle,G:/GAPID_out/release/aarch64/gapid-apk/app/src/main/res/values/strings.xml,G:/GAPID_out/release/aarch64/gapid-apk/app/src/main/AndroidManifest.xml" -P C:/Users/USER/go/src/github.com/google/gapid/cmake/Modules/RunGradle.cmake"


FAILURE: Build failed with an exception.



* What went wrong:

A problem occurred configuring project ':app'.

> failed to find target with hash string 'android-21' in: D:\0-Intek\OpenGL\GAPID\AndroidSDK_tools_r25.2.3-windows



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.



BUILD FAILED



Total time: 5.823 secs

CMake Error at C:/Users/USER/go/src/github.com/google/gapid/cmake/Modules/RunGradle.cmake:32 (message):
  1


[6/10] Linking CXX shared library bin\libgapii.dll
FAILED: bin/libgapii.dll libgapii.dll.a 
cmd.exe /C "cd . && C:\msys64\mingw64\bin\x86_64-w64-mingw32-g++.exe   -Wa,-mbig-obj -std=c++0x -O3 -DNDEBUG   -shared -o bin\libgapii.dll -Wl,--out-implib,libgapii.dll.a -Wl,--major-image-version,0,--minor-image-version,0 CMakeFiles/gapii.dir/gapii/cc/call_observer.cpp.obj CMakeFiles/gapii.dir/gapii/cc/connection_header.cpp.obj CMakeFiles/gapii.dir/gapii/cc/connection_stream.cpp.obj CMakeFiles/gapii.dir/gapii/cc/core_imports.cpp.obj CMakeFiles/gapii.dir/gapii/cc/core_spy_0.cpp.obj CMakeFiles/gapii.dir/gapii/cc/core_spy_1.cpp.obj CMakeFiles/gapii.dir/gapii/cc/core_spy_2.cpp.obj CMakeFiles/gapii.dir/gapii/cc/core_spy_3.cpp.obj CMakeFiles/gapii.dir/gapii/cc/core_spy_4.cpp.obj CMakeFiles/gapii.dir/gapii/cc/core_spy_5.cpp.obj CMakeFiles/gapii.dir/gapii/cc/core_spy_6.cpp.obj CMakeFiles/gapii.dir/gapii/cc/core_spy_7.cpp.obj CMakeFiles/gapii.dir/gapii/cc/core_spy_subroutines_0.cpp.obj CMakeFiles/gapii.dir/gapii/cc/core_spy_subroutines_1.cpp.obj CMakeFiles/gapii.dir/gapii/cc/gles_context.cpp.obj CMakeFiles/gapii.dir/gapii/cc/gles_exports.cpp.obj CMakeFiles/gapii.dir/gapii/cc/gles_extras.cpp.obj CMakeFiles/gapii.dir/gapii/cc/gles_imports.cpp.obj CMakeFiles/gapii.dir/gapii/cc/gles_spy_0.cpp.obj CMakeFiles/gapii.dir/gapii/cc/gles_spy_1.cpp.obj CMakeFiles/gapii.dir/gapii/cc/gles_spy_2.cpp.obj CMakeFiles/gapii.dir/gapii/cc/gles_spy_3.cpp.obj CMakeFiles/gapii.dir/gapii/cc/gles_spy_4.cpp.obj CMakeFiles/gapii.dir/gapii/cc/gles_spy_5.cpp.obj CMakeFiles/gapii.dir/gapii/cc/gles_spy_6.cpp.obj CMakeFiles/gapii.dir/gapii/cc/gles_spy_7.cpp.obj CMakeFiles/gapii.dir/gapii/cc/gles_spy_externs.cpp.obj CMakeFiles/gapii.dir/gapii/cc/gles_spy_subroutines_0.cpp.obj CMakeFiles/gapii.dir/gapii/cc/gles_spy_subroutines_1.cpp.obj CMakeFiles/gapii.dir/gapii/cc/pack_encoder.cpp.obj CMakeFiles/gapii.dir/gapii/cc/pool.cpp.obj CMakeFiles/gapii.dir/gapii/cc/spy.cpp.obj CMakeFiles/gapii.dir/gapii/cc/spy_base.cpp.obj CMakeFiles/gapii.dir/gapii/cc/spy_disable_precompiled_shaders.cpp.obj CMakeFiles/gapii.dir/gapii/cc/vulkan_VkCommandBuffer_exports.cpp.obj CMakeFiles/gapii.dir/gapii/cc/vulkan_VkDevice_exports.cpp.obj CMakeFiles/gapii.dir/gapii/cc/vulkan_VkInstance_exports.cpp.obj CMakeFiles/gapii.dir/gapii/cc/vulkan_VkPhysicalDevice_exports.cpp.obj CMakeFiles/gapii.dir/gapii/cc/vulkan_VkQueue_exports.cpp.obj CMakeFiles/gapii.dir/gapii/cc/vulkan_exports.cpp.obj CMakeFiles/gapii.dir/gapii/cc/vulkan_imports.cpp.obj CMakeFiles/gapii.dir/gapii/cc/vulkan_mid_execution.cpp.obj CMakeFiles/gapii.dir/gapii/cc/vulkan_spy_0.cpp.obj CMakeFiles/gapii.dir/gapii/cc/vulkan_spy_1.cpp.obj CMakeFiles/gapii.dir/gapii/cc/vulkan_spy_2.cpp.obj CMakeFiles/gapii.dir/gapii/cc/vulkan_spy_3.cpp.obj CMakeFiles/gapii.dir/gapii/cc/vulkan_spy_4.cpp.obj CMakeFiles/gapii.dir/gapii/cc/vulkan_spy_5.cpp.obj CMakeFiles/gapii.dir/gapii/cc/vulkan_spy_6.cpp.obj CMakeFiles/gapii.dir/gapii/cc/vulkan_spy_7.cpp.obj CMakeFiles/gapii.dir/gapii/cc/vulkan_spy_helpers.cpp.obj CMakeFiles/gapii.dir/gapii/cc/vulkan_spy_subroutines_0.cpp.obj CMakeFiles/gapii.dir/gapii/cc/vulkan_spy_subroutines_1.cpp.obj CMakeFiles/gapii.dir/gapii/cc/windows/opengl32_resolve.cpp.obj CMakeFiles/gapii.dir/gapii/cc/windows/wgl.cpp.obj CMakeFiles/gapii.dir/proto_cc/core/data/pack/pack.pb.cc.obj CMakeFiles/gapii.dir/proto_cc/core/os/device/device.pb.cc.obj CMakeFiles/gapii.dir/proto_cc/gapis/atom/atom_pb/atom.pb.cc.obj CMakeFiles/gapii.dir/proto_cc/gapis/memory/memory.pb.cc.obj CMakeFiles/gapii.dir/proto_cc/gapis/memory/memory_pb/memory.pb.cc.obj CMakeFiles/gapii.dir/proto_cc/gapis/capture/capture.pb.cc.obj CMakeFiles/gapii.dir/proto_cc/gapis/gfxapi/core/core_pb/api.pb.cc.obj CMakeFiles/gapii.dir/proto_cc/gapis/gfxapi/vulkan/vulkan_pb/api.pb.cc.obj CMakeFiles/gapii.dir/proto_cc/gapis/gfxapi/gles/gles_pb/api.pb.cc.obj CMakeFiles/gapii.dir/proto_cc/gapis/gfxapi/gles/gles_pb/extras.pb.cc.obj  libcc-core.a libcc-memory-tracker.a libprotobuf.a "C:/Program Files (x86)/Microsoft Visual Studio/VC98/Lib/OPENGL32.LIB" libcityhash.a "C:/Program Files (x86)/Microsoft Visual Studio/VC98/Lib/WS2_32.LIB" libprotobuf_lite.a -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0xd): undefined reference to `__imp_send'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x30): undefined reference to `__imp_recv'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x46): undefined reference to `__imp_WSAGetLastError'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0xc7): undefined reference to `__imp_select'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0xfa): undefined reference to `__imp_accept'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x11e): undefined reference to `__imp_WSAGetLastError'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x174): undefined reference to `__imp_closesocket'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x197): undefined reference to `__imp_WSACleanup'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x1b3): undefined reference to `__imp_WSAStartup'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x233): undefined reference to `__imp_WSAGetLastError'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x358): undefined reference to `__imp_closesocket'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x367): undefined reference to `__imp_WSACleanup'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x40c): undefined reference to `__imp_getaddrinfo'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x424): undefined reference to `__imp_WSAGetLastError'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x474): undefined reference to `__imp_WSACleanup'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x4a1): undefined reference to `__imp_socket'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x4dd): undefined reference to `__imp_setsockopt'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x4f8): undefined reference to `__imp_WSAGetLastError'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x53e): undefined reference to `__imp_closesocket'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x55f): undefined reference to `__imp_WSAStartup'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x5ae): undefined reference to `__imp_WSAGetLastError'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x5f4): undefined reference to `__imp_freeaddrinfo'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x612): undefined reference to `__imp_bind'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x632): undefined reference to `__imp_getsockname'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x651): undefined reference to `__imp_WSAGetLastError'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x6a2): undefined reference to `__imp_WSAGetLastError'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x6eb): undefined reference to `__imp_listen'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x706): undefined reference to `__imp_WSAGetLastError'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x74c): undefined reference to `__imp_ntohs'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x7b3): undefined reference to `__imp_WSAStartup'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x7f2): undefined reference to `__imp_closesocket'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x7fb): undefined reference to `__imp_freeaddrinfo'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x80a): undefined reference to `__imp_WSACleanup'
libcc-core.a(socket_connection.cpp.obj):socket_connection.cpp:(.text+0x873): undefined reference to `__imp_WSACleanup'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
Error running D:\0-Intek\OpenGL\GAPID\ninja-win\ninja.exe [install]: Process returned error
   Cause: exit status 1
