### ISSUE TITLE
Trying to let GAPID replay gfxtrace file in sequence & native API.

### ISSUE THREAD

**Issue by AwinHuang** [google/gapid#2651]
First, thank every one for give me answers.
According to this [discuss](https://github.com/google/gapid/issues/2615). I will try to do it by myself.

For replay the gfxtrace file in native API, I use `gapit video` command for my init step.(Because I didn't know other command/function that can replay gfxtrace file frame by frame automatically.)

But I need some helps.

1. `gapit video` command will replace `eglCreateWindowSurface()` by `eglCreatePbuffers()`.
	Thanks for pmuetschard's answer, I can solve this problem by hacking `gapir/cc/linux/gles_renderer.cpp` & `gapis/api/gles/version.go`.
2. `gapit video` command will skip `eglSwapBuffers()`.
	I need to know where does GAPIS ignore this function.

3. `gapit video` command will create new process(GAPIR) for every frame rendering. 
	For full gfxtrace replay, there should be one GAPIR to render all functions in sequence except for gfxtrace records has new thread requirement. 
	for example, if I have a draw flow like below:

```c
		eglInitialize()
		eglCreateContext()
		eglCreateWindowSurface()
		glDrawArray() // 1
		eglSwapBuffers() 
		glDrawArray() // 2
		eglSwapBuffers() 
		glDrawArray() // 3
		eglSwapBuffers() 
		eglDestroyResource()
```

In `gapit video` replay, they will become

```c
		// Frame 1
		eglInitialize()
		eglCreateContext()
		eglCreateWindowSurface()
		glDrawArray() // 1
		eglSwapBuffers() 
		eglDestroyResource()
		// Frame 2
		eglInitialize()
		eglCreateContext()
		eglCreateWindowSurface()
		glDrawArray() // 2
		eglSwapBuffers() 
		eglDestroyResource()
		// Frame 3
		eglInitialize()
		eglCreateContext()
		eglCreateWindowSurface()
		glDrawArray() // 3
		eglSwapBuffers() 
		eglDestroyResource()
```

Will you please give me some hints(or code position) about above question? 
Hope I can do that, and I will contribute the code.
Thank you very much.

**Comment by AWoloszyn** [comment]
I would suggest using `gapit report`, it makes fewer modifications to the command-stream.
It still  modifies `eglCreateWindowSurface` but should not skip eglSwapBuffers() (This is my understanding). It will also play the entire capture in a single replay.

**Comment by AwinHuang** [comment]
Hi, AWoloszyn, thank you very much.
But unfortunately the `gapit report` still skip `eglSwapBuffers()`.
The problem is I don't know where is the code that GAPIS skip `eglSwapBuffers()`. Would you please give me a hint? thanks.

**Comment by AWoloszyn** [comment]
This is done in
https://github.com/google/gapid/blob/master/gapis/api/gles/api/egl.api

The `@no_replay` annotation stops it from appearing in the replay.

**Comment by AwinHuang** [comment]
Thank you, AWoloszyn
Remove `@no_replay` of `eglSwapBuffers()` and It works(on `gapit report` command).
But `eglCreateWindowSurface()` was still replaced by `eglCreatePBuffer()`, can I modify it with the same way?
Or where is code that I can add `eglCreateWindowSurface()` back?

Thank you very much!

**Comment by AWoloszyn** [comment]
So you can remove @no_replay from eglCreateWindowSurface.
That will allow that call through, however we would still be adding the eglCreatePBuffer.

This is done in a combination of https://github.com/google/gapid/blob/master/gapis/api/gles/custom_replay.go where we replace calls to *CreateContext with calls to ReplayCreateRenderer().

ReplayCreateRenderer is defined here:
https://github.com/google/gapid/blob/master/gapir/cc/context.cpp (Line 204)

which ends up calling
```c++
mRootGlesRenderer->setBackbuffer(GlesRenderer::Backbuffer(
                8, 8, core::gl::GL_RGBA8, core::gl::GL_DEPTH24_STENCIL8,
                core::gl::GL_DEPTH24_STENCIL8));
```

SetBackbuffer is defined (for Android) in https://github.com/google/gapid/blob/master/gapir/cc/android/gles_renderer.cpp, which actually creates the surface.

**Comment by AwinHuang** [comment]
Thank you, AWoloszyn.
For `gapit report` and `gapit video`, if I just remove `@no_replay` from `eglCreateWindowSurface()`, the `eglCreateWindowSurface()` still doesn't appear in GAPIR.
And I need to add some code in `gapis/api/gles/state_builder.go: stateBuilder->contextObject()`,
Original code:

```
func (sb *stateBuilder) contextObject(ctx context.Context, handle EGLContext, c Contextʳ, representative map[ShareListʳ]EGLContext) {

	...skipped...

	// TODO: Record the arguments in state.
	write(ctx, cb.EglCreateContext(memory.Nullptr, memory.Nullptr, sharedCtx, memory.Nullptr, handle))
	write(ctx, api.WithExtras(cb.EglMakeCurrent(memory.Nullptr, memory.Nullptr, memory.Nullptr, handle, EGLBoolean(1)),
		sb.contextExtras(ctx, c)...))
```

I modified:

```
func (sb *stateBuilder) contextObject(ctx context.Context, handle EGLContext, c Contextʳ, representative map[ShareListʳ]EGLContext) {

	...skipped...

	// TODO: Record the arguments in state.
	write(ctx, cb.EglCreateContext(memory.Nullptr, memory.Nullptr, sharedCtx, memory.Nullptr, handle))

        // <-- Add cb.EglCreateWindowSurface
	write(ctx, cb.EglCreateWindowSurface(memory.Nullptr, memory.Nullptr, sharedCtx, memory.Nullptr, handle))

	write(ctx, api.WithExtras(cb.EglMakeCurrent(memory.Nullptr, memory.Nullptr, memory.Nullptr, handle, EGLBoolean(1)),
		sb.contextExtras(ctx, c)...))
```
This looks like force to add `eglCreateWindowSurface` to the state flow, not follow the original APIs recorded in gfxtrace file.
Can I just pass the `eglCreateWindowSurface`(or others) that from gfxtrace direct to GAPIR?

**Comment by AWoloszyn** [comment]
If you take a full trace (From the beginning) then this should not be necessary,
The flow in state_builder.go is used when you start a trace after the beginning of the application.

**Comment by AWoloszyn** [comment]
We are looking into show to replay on the original surface/swapchain. I will close this specific bug, but will open another one to track that process.

**Comment by AWoloszyn** [comment]
#2784
