### ISSUE TITLE
Unhandled exception in the UI thread.

### ISSUE THREAD

**Issue by joshgi** [google/gapid#2660]
GAPID Version: 1.4.0:5f4620616cbea20dca03ecf0ea29dfcd824114e3
OS: mac os x x86_64
[gapis.log](https://github.com/google/gapid/files/2942104/gapis.log)
[gapic.log](https://github.com/google/gapid/files/2942105/gapic.log)

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

**Comment by AWoloszyn** [comment]
This should be fixed in 1.5.0
