### ISSUE TITLE
Vulkan: Image layout is not tracked correctly for MEC

### ISSUE THREAD

**Issue by Qining** [google/gapid#268]
So multisampled attachment won't show in UI correctly.

**Comment by Qining** [comment]
Turns out the multisampled attachment issue is caused by other problems. But the incorrectness of layout tracking is still there.

**Comment by Qining** [comment]
Turns out the problem is caused by failing to recreate image data for multisampled image.

**Comment by AWoloszyn** [comment]
This should already be fixed. Please re-open if you see it continues to be an issue.
