### ISSUE TITLE
OSX builds broken: missing SWT?

### ISSUE THREAD

**Issue by hevrard** [google/gapid#2695]
CI builds fail with:
```
ERROR: /Volumes/BuildData/tmpfs/tmp/bazel_out/external/gapic_third_party/BUILD.bazel:73:1: no such package '@swt//': java.io.IOException: thread interrupted and referenced by '@gapic_third_party//:swt'
```

**Comment by AWoloszyn** [comment]
Is this consistent or intermittent. I have seen flakes on the Mac builds, but it does not always happen

**Comment by hevrard** [comment]
I am not sure about it being consistent, I will update here when it reproduces.

**Comment by pmuetschard** [comment]
this looks like it was a kokoro issue.
