### ISSUE TITLE
Tracing Failed   Cause: Could not start trace   Cause: Connecting to JDWP   Cause: read tcp 127.0.0.1:56731->127.0.0.1:56669: wsarecv: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by pickonpig** [google/gapid#2710]
GAPID Version: 1.5.0:b33134fa99c398ce81dffd642aa11ea53c660518
OS: windows 7 amd64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

**Comment by AWoloszyn** [comment]
Do you have any information about the device in question or the contents of gapis.log/gapic.log?
