### ISSUE TITLE
Failed to create an OpenGL context when viewing a trace on Linux

### ISSUE THREAD

**Issue by kzaikin** [google/gapid#2719]
I have an Ubuntu Linux 18.10.
When I record an Android trace I want to view the trace and I am not able to see the frame images.
Frames are successfully recorded but I see the message "Failed to create an OpenGL context. OpenGL is required to use this application." when I am trying to view the framebuffer.

➜  ~ glxinfo | grep version                            
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.2.8
OpenGL core profile shading language version string: 4.50
OpenGL version string: 3.0 Mesa 18.2.8
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.2.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

**Comment by AWoloszyn** [comment]
I have not seen this before, although I have not run 18.10 yet. Do you happen to know if 18.10 is on wayland, we had a known issue where we would fail on 17.10 with Wayland.

Here is the bug that describes it.
https://github.com/google/gapid/issues/1701
