### ISSUE TITLE
`gapit benchmark` should stop the app once benchmark capture has been traced

### ISSUE THREAD

**Issue by hevrard** [google/gapid#2724]
Currently the app keeps on running, and may be using the GPU quite a lot.

**Comment by AWoloszyn** [comment]
IIRC the App gets backgrounded when the replay starts. This means it should no longer be actively running?

**Comment by hevrard** [comment]
When the replay terminates, the app comes back to foreground apparently. I'll have a go at completely stopping the App once the capture is complete.
