### ISSUE TITLE
GAPID build fail

### ISSUE THREAD

**Issue by byumjin** [google/gapid#2727]
Hello all,

When I tried to build GAPID with below settings, it failed.
Is there any missing thing?

Thank you.

**Env**
GAPID Branch: master, last commit id: 4f00997
OS: Windows 10
NDK version use: tools/bin/sdkmanager "platforms;android-26" "build-tools;26.0.1" ndk-bundle
Bazel: 0.23.1

**Command**
`bazel build pkg`

**Result**
![Capture_2019_04_23_12_26_55_802](https://user-images.githubusercontent.com/22266515/56609904-211baa00-65c3-11e9-91d4-c7f1a1a162ba.png)

**Comment by AWoloszyn** [comment]
If I had to guess, the line 
`/usr/bin/bash: line 5: rm: command not found`
Is probably the cuprit. 

Do you have `BAZEL_SH` set?

**Comment by AWoloszyn** [comment]
Otherwise can you add msys usr/bin directory to the path. That should work.
