### ISSUE TITLE
GLES Shader attachments must be preserved when doing MEC

### ISSUE THREAD

**Issue by pau-baiget** [google/gapid#2728]
Some apps destroy shaders after they've been attached to a program. A Mid-Execution Capture of these apps (starting after the shaders have been attached) doesn't currently store those shaders and therefore can't be modified (and pushed).

**Comment by AWoloszyn** [comment]
I thought I remembered @pmuetschard  already fixing this.

**Comment by pmuetschard** [comment]
Dupe of #398
