### ISSUE TITLE
Gapid as a rendering profiler?

### ISSUE THREAD

**Issue by wzhfantastic** [google/gapid#273]
Is it possible to use gapid as a rendering efficiency profiler? 
I just want to inspect detailed costs(cpu, memory, gpu etc) in drawing each frame.

**Comment by ben-clayton** [comment]
Not yet. We have plans to take a look at adding GPU performance metrics later this year.
Statistics such as number of draw calls, vertices per frame, etc are also planned, but we don't have an ETA for this right now.

**Comment by wzhfantastic** [comment]
OK. Thanks!

**Comment by zettdaymond** [comment]
Are there still any plans to add GPU performance metrics?

**Comment by ben-clayton** [comment]
Hi @zettdaymond,

It's in the roadmap, but is still unfortunately still some way off.

**Comment by zettdaymond** [comment]
OK. Thanks for the answer.
