### ISSUE TITLE
How can I debug the code like 'gapis'?

### ISSUE THREAD

**Issue by bingeli** [google/gapid#2737]
I want to learn the code in detail, and modify the output capture file, and save the replay frames as video.
**First, how can I debug the gapis in IDE? Or can I achieve my propose?**

What I have done:
1. The project has been successfully built using bazel on windows 7.
2. I learn the code architecture approximately.
2. I open the project in goland to run 'cmd/gapis', and put the generated *.pb.go into project.
3. Now I have trouble in the cgo step, **how can I use arena.go without bazel?**
```
# github.com/google/gapid/core/memory/arena
src\github.com\google\gapid\core\memory\arena\arena.go:28:11: fatal error: core/memory/arena/cc/arena.h: No such file or directory
 // #include "core/memory/arena/cc/arena.h"
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
New problem occurs when I fix the path.
```
# github.com/google/gapid/core/memory/arena
C:\Users\bingeli\AppData\Local\Temp\go-build327089106\github.com\google\gapid\core\memory\arena\_obj\arena.cgo2.o: In function `_cgo_c6a3014a6615_Cfunc_arena_alloc':
/tmp/go-build\github.com\google\gapid\core\memory\arena\_obj/cgo-gcc-prolog:42: undefined reference to `arena_alloc'
C:\Users\bingeli\AppData\Local\Temp\go-build327089106\github.com\google\gapid\core\memory\arena\_obj\arena.cgo2.o: In function `_cgo_c6a3014a6615_Cfunc_arena_create':
/tmp/go-build\github.com\google\gapid\core\memory\arena\_obj/cgo-gcc-prolog:58: undefined reference to `arena_create'
C:\Users\bingeli\AppData\Local\Temp\go-build327089106\github.com\google\gapid\core\memory\arena\_obj\arena.cgo2.o: In function `_cgo_c6a3014a6615_Cfunc_arena_realloc':
/tmp/go-build\github.com\google\gapid\core\memory\arena\_obj/cgo-gcc-prolog:103: undefined reference to `arena_realloc'
C:\Users\bingeli\AppData\Local\Temp\go-build327089106\github.com\google\gapid\core\memory\arena\_obj\arena.cgo2.o: In function `_cgo_c6a3014a6615_Cfunc_arena_destroy':
/tmp/go-build\github.com\google\gapid\core\memory\arena\_obj/cgo-gcc-prolog:72: undefined reference to `arena_destroy'
C:\Users\bingeli\AppData\Local\Temp\go-build327089106\github.com\google\gapid\core\memory\arena\_obj\arena.cgo2.o: In function `_cgo_c6a3014a6615_Cfunc_arena_free':
/tmp/go-build\github.com\google\gapid\core\memory\arena\_obj/cgo-gcc-prolog:85: undefined reference to `arena_free'
C:\Users\bingeli\AppData\Local\Temp\go-build327089106\github.com\google\gapid\core\memory\arena\_obj\arena.cgo2.o: In function `_cgo_c6a3014a6615_Cfunc_arena_stats':
/tmp/go-build\github.com\google\gapid\core\memory\arena\_obj/cgo-gcc-prolog:119: undefined reference to `arena_stats'
```
my go env:
```
$ go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\gopath
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\bingeli\AppData\Local\Temp\go-build859442823=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
```

**Comment by bingeli** [comment]
I found 'gapit' can replay gles or vulkan in video, but I still cannot solve the 'cgo' problem. The problem has bothered me for days.
Another question: why replay is not supported on a new device?

**Comment by AWoloszyn** [comment]
`Now I have trouble in the cgo step, how can I use arena.go without bazel?`
We don't currently support building gapid outside of bazel.

That being said, some of us have had some luck debugging GAPIS with delve. (And maybe the golang plugin for visual studio code will work). 
https://github.com/google/gapid/issues/2352

**Comment by AWoloszyn** [comment]
`Another question: why replay is not supported on a new device?`
If this is "why can't we replay on a different device than we traced on?"
The short answer is there are too many features/capabilities/differences between devices to make this practically useful.

It can work for some simpler applications, (and we can replay MANY OpenGLES applications on Desktop) but as the applications get more complicated, we either have to change the trace so much that it is not usefully close enough to the original, or we will be simply unable to make the appropriate transformations.

**Comment by bingeli** [comment]
Thanks a lot, debugging with delve really works for me.
It cannot work with vscode. exe file can run, but breakpoints can not take effect. vscode warns unverified breakpoints. Here is my vscode configuration in launch.json:
```
        {
            "name": "Launch executable",
            "type": "go",
            "request": "launch",
            "mode": "exec",
            "program": "${workspaceFolder}/bazel-bin/pkg/gapis.exe"
        },
```
