### ISSUE TITLE
Make DataUnavailableException a "soft error"

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#275]
I frequently get a lot of messages like this in the stdout with full callstack:
E20170418-143055880[grpc-default-executor-8][util.UiCallback.onFinish] error in UiCallback.onRpcThread
E20170418-143055880[grpc-default-executor-8][util.UiCallback.onFinish] com.google.gapid.server.Client$DataUnavailableException: No texture data has been associated with texture Texture<49> at this point in the trace.
E20170418-143055880[grpc-default-executor-8][util.UiCallback.onFinish] 	at com.google.gapid.server.Client.throwIfError(Client.java:212)
E20170418-143055880[grpc-default-executor-8][util.UiCallback.onFinish] 	at com.google.gapid.server.Client.lambda$get$1(Client.java:87)
E20170418-143055880[grpc-default-executor-8][util.UiCallback.onFinish] 	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)

There is generally one for each texture without explicitly loaded data.
This can happen either if the the data was not loaded yet, or if the texture is used as render target.
Either way, I do not feel like this is an error that should be logged - it is expected behavior.

**Comment by pmuetschard** [comment]
See the discussion on service.proto here: https://github.com/ben-clayton/gapid/pull/19

**Comment by pmuetschard** [comment]
oops.

**Comment by dsrbecky** [comment]
I do not see the discussion... :-/

**Comment by pmuetschard** [comment]
Look harder?? :) 

In Ben's first comment (the one with the big red X), click on "show outdated" next to service.proto (the first file)

**Comment by dsrbecky** [comment]
Ops.... I was clicking on the filename which is of no use...

I do not feel strongly about any of the discussed solutions.  As long as the log does not get spammed with errors which are not really errors, I am happy.

As a side note, I personally categorize log messages as Error for cases where unexpected behavior has happened.  Error in the log or UI for me means something has gone wrong - either a bug, or hardware failure.  There should be no errors under normal usage.  Anything that is expected under normal use gets logged as warning.

To extend that though, should rename "soft errors" into warnings?  Eg. WarnDataUnavailable.  Just a though.

**Comment by pmuetschard** [comment]
Everything specific to this bug is done. There are separate bugs open (i.e. #401, #403, and #407) to deal with error handling.
