### ISSUE TITLE
State for Vulkan `Instance` objects should include `VkApplicationInfo`

### ISSUE THREAD

**Issue by bjoeris** [google/gapid#2757]
These fields in this struct should be visible since they can affect driver behaviour--particularly `pApplicationName` and `pEngineName`.

**Comment by bjoeris** [comment]
Fixed by #2761

**Comment by AWoloszyn** [comment]
I am going to re-open. We should be using this in state reconstruction as well.

**Comment by AWoloszyn** [comment]
Fixed!
