### ISSUE TITLE
Tracing Failed   Cause: Could not start trace   Cause: Connecting to JDWP   Cause: read tcp 127.0.0.1:32039->127.0.0.1:32005: wsarecv: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by thaihoangduylinh** [google/gapid#2770]
GAPID Version: 1.5.0:b33134fa99c398ce81dffd642aa11ea53c660518
OS: windows 10 amd64
Android Device: sony z3 - 6.0.1 rooted

seems to only be on armeabi
armv8a normally

**Comment by pau-baiget** [comment]
Thanks for reporting this issue. Are you trying to trace a debug build of an application?

**Comment by AWoloszyn** [comment]
Closing. If you have any more information please leave a comment.
