### ISSUE TITLE
Bazel build error on MacOS: Unhandled CPU type in strip rule: darwin

### ISSUE THREAD

**Issue by stellama0208** [google/gapid#2795]
GAPID version: Version 1.6.0. most updated version of goog/master on May 31, 3c7767d
OS: macOS Mojave 10.14.5 (Pro 15-inch, 2018)
Bazel version:  0.25.2
Xcode version: 10.2.1(10E1001)

Call-stack:
Starting local Bazel server and connecting to it...
ERROR: /Users/stellama/work/gapid/core/vulkan/vk_virtual_swapchain/cc/BUILD.bazel:73:1: in strip rule //core/vulkan/vk_virtual_swapchain/cc:libVkLayer_VirtualSwapchain_stripped.dylib: 
Traceback (most recent call last):
	File "/Users/stellama/work/gapid/core/vulkan/vk_virtual_swapchain/cc/BUILD.bazel", line 73
		strip(name = 'libVkLayer_VirtualSwapchain_stripped.dylib')
	File "/Users/stellama/work/gapid/tools/build/rules/cc.bzl", line 59, in _strip_impl
		fail(("Unhandled CPU type in strip ru...))
Unhandled CPU type in strip rule: darwin
ERROR: Analysis of target '//:gapid' failed; build aborted: Analysis of target '//core/vulkan/vk_virtual_swapchain/cc:libVkLayer_VirtualSwapchain_stripped.dylib' failed; build aborted
INFO: Elapsed time: 5.695s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (171 packages loaded, 3856 targets configured)
FAILED: Build did NOT complete successfully (171 packages loaded, 3856 targets configured)

Can't build successfully on my macOS, seems that my CPU type isn't recognized. (gapid/tools/build/rules/cc.bzl line59 deals with cpu type "darwin_x86_64", but not with "darwin"), there might be some linking issue on macOS platform.

**Comment by stellama0208** [comment]
Get around with this problem with git repo "bazelbuild/rules_apple". https://github.com/bazelbuild/rules_apple

It works on my macOS to followed the Quick setup part, adding the snippet to WORKSPACE file and can build afterwards. (make sure to do bazel clean and then redo bazel build pkg.)
After the first successful build, even if the WORKSPACE is reverted back, the build can still work afterwards. (I suppose the linking issue is resolved on my macOS environment.)

If you are also a macOS user meeting the same problem, maybe you can try it out.

**Comment by pau-baiget** [comment]
@stellama0208 any advance on this one?

**Comment by hevrard** [comment]
Fixed by https://github.com/google/gapid/pull/2915
