### ISSUE TITLE
[Build Failure on Win] failed to find target with hash string 'android-21'

### ISSUE THREAD

**Issue by zfk0531** [google/gapid#280]
[778/834] Gradle: aarch64-gradle-gapid-apk
FAILED: aarch64/gapid-apk/app/build/outputs/apk/app-debug.apk
cmd.exe /C "cd /D C:\Users\zfk\gapid\release\aarch64\gapid-apk && "C:\Program Files\CMake\bin\cmake.exe" -DGRADLE_ENV=C:/Users/zfk/gapid/release/gradleenv.cmake -DGRADLE_ARGS="-Pfilehash=C:/Users/zfk/gapid/release/bin/filehash.exe -Pinputs=C:/Users/zfk/gapid/release/aarch64/gapid-apk/app/src/main/jniLibs/arm64-v8a//libgapir.so,C:/Users/zfk/gapid/release/aarch64/gapid-apk/app/src/main/jniLibs/arm64-v8a//libgapii.so,C:/Users/zfk/gapid/release/aarch64/gapid-apk/app/src/main/jniLibs/arm64-v8a//libinterceptor.so,C:/Users/zfk/gapid/release/aarch64/gapid-apk/app/src/main/jniLibs/arm64-v8a//libdeviceinfo.so,C:/Users/zfk/gapid/release/aarch64/gapid-apk/app/src/main/jniLibs/arm64-v8a//libVkLayerGraphicsSpy.so,C:/Users/zfk/gapid/release/aarch64/gapid-apk/app/src/main/jniLibs/arm64-v8a//libVkLayer_VirtualSwapchain.so,C:/Users/zfk/gapid/release/aarch64/gapid-apk/app/build.gradle,C:/Users/zfk/gapid/release/aarch64/gapid-apk/app/src/main/java/com/google/android/gapid/DeviceInfoService.java,C:/Users/zfk/gapid/release/aarch64/gapid-apk/app/src/main/java/com/google/android/gapid/PackageInfoService.java,C:/Users/zfk/gapid/release/aarch64/gapid-apk/app/src/main/java/com/google/android/gapid/SocketWriter.java,C:/Users/zfk/gapid/release/aarch64/gapid-apk/app/src/main/res/drawable-xxxhdpi/logo.png,C:/Users/zfk/gapid/release/aarch64/gapid-apk/build.gradle,C:/Users/zfk/gapid/release/aarch64/gapid-apk/gradle.properties,C:/Users/zfk/gapid/release/aarch64/gapid-apk/gradle/wrapper/gradle-wrapper.jar,C:/Users/zfk/gapid/release/aarch64/gapid-apk/gradle/wrapper/gradle-wrapper.properties,C:/Users/zfk/gapid/release/aarch64/gapid-apk/gradlew,C:/Users/zfk/gapid/release/aarch64/gapid-apk/gradlew.bat,C:/Users/zfk/gapid/release/aarch64/gapid-apk/settings.gradle,C:/Users/zfk/gapid/release/aarch64/gapid-apk/app/src/main/res/values/strings.xml,C:/Users/zfk/gapid/release/aarch64/gapid-apk/app/src/main/AndroidManifest.xml" -P D:/GoProjects/src/github.com/google/gapid/cmake/Modules/RunGradle.cmake"

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> failed to find target with hash string 'android-21' in: D:\Android\platforms\android-21

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.662 secs
CMake Error at D:/GoProjects/src/github.com/google/gapid/cmake/Modules/RunGradle.cmake:32 (message):
  1

[781/834] Linking Go executable bin\gfxtrace.exe
ninja: build stopped: subcommand failed.
Error running D:\Downloads\ninja-win\ninja.exe [install]: Process returned error
   Cause: exit status 1
exit status 1

**Comment by ben-clayton** [comment]
Please follow the [building instructions](https://github.com/google/gapid/blob/master/BUILDING.md#install-android-sdk), which asks you to install Android SDK Build-tools 21.1.2.

**Comment by ben-clayton** [comment]
Please reopen if you're still having issues.

**Comment by zfk0531** [comment]
I have installed Android SDK Build-tools 21.1.2, as shown in the following image:
![androidsdkinstall](https://cloud.githubusercontent.com/assets/20858648/25221215/e0e1936e-25e6-11e7-8b36-f2f3f809f7a7.png)

And I also have set the config path properly:
> {
    "Flavor": "release",
    "OutRoot": "C:\\Users\\zfk\\gapid",
    "JavaHome": "C:\\Program Files\\Java\\jdk1.8.0_111",
    "AndroidSDKRoot": "D:\\Android\\platforms\\android-21",
    "AndroidNDKRoot": "D:\\Android\\android-ndk-r13b",
    "CMakePath": "C:\\Program Files\\CMake\\bin\\cmake.exe",
    "NinjaPath": "D:\\Downloads\\ninja-win\\ninja.exe",
    "PythonPath": "C:\\Users\\zfk\\AppData\\Local\\Programs\\Python\\Python36\\python.exe",
    "MSYS2Path": "C:\\msys64"
}

But I still got the same building error:

> -- Setting install path to C:\Users\zfk/gapid
-- Found STL: D:/Android/android-ndk-r13b/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/libgnustl_static.a
-- Found NDK: D:/Android/android-ndk-r13b/platforms/android-21/arch-x86/usr/lib/libandroid.so
-- Found Log: D:/Android/android-ndk-r13b/platforms/android-21/arch-x86/usr/lib/liblog.so
-- Found GL: D:/Android/android-ndk-r13b/platforms/android-21/arch-x86/usr/lib/libGLESv2.so
-- Found EGL: D:/Android/android-ndk-r13b/platforms/android-21/arch-x86/usr/lib/libEGL.so
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/zfk/gapid/release/x86/src/x86-build
[781/834] Gradle: x86-gradle-gapid-apk
FAILED: x86/gapid-apk/app/build/outputs/apk/app-debug.apk
cmd.exe /C "cd /D C:\Users\zfk\gapid\release\x86\gapid-apk && "C:\Program Files\CMake\bin\cmake.exe" -DGRADLE_ENV=C:/Users/zfk/gapid/release/gradleenv.cmake -DGRADLE_ARGS="-Pfilehash=C:/Users/zfk/gapid/release/bin/filehash.exe -Pinputs=C:/Users/zfk/gapid/release/x86/gapid-apk/app/src/main/jniLibs/x86//libgapir.so,C:/Users/zfk/gapid/release/x86/gapid-apk/app/src/main/jniLibs/x86//libgapii.so,C:/Users/zfk/gapid/release/x86/gapid-apk/app/src/main/jniLibs/x86//libinterceptor.so,C:/Users/zfk/gapid/release/x86/gapid-apk/app/src/main/jniLibs/x86//libdeviceinfo.so,C:/Users/zfk/gapid/release/x86/gapid-apk/app/src/main/jniLibs/x86//libVkLayerGraphicsSpy.so,C:/Users/zfk/gapid/release/x86/gapid-apk/app/src/main/jniLibs/x86//libVkLayer_VirtualSwapchain.so,C:/Users/zfk/gapid/release/x86/gapid-apk/app/build.gradle,C:/Users/zfk/gapid/release/x86/gapid-apk/app/src/main/java/com/google/android/gapid/DeviceInfoService.java,C:/Users/zfk/gapid/release/x86/gapid-apk/app/src/main/java/com/google/android/gapid/PackageInfoService.java,C:/Users/zfk/gapid/release/x86/gapid-apk/app/src/main/java/com/google/android/gapid/SocketWriter.java,C:/Users/zfk/gapid/release/x86/gapid-apk/app/src/main/res/drawable-xxxhdpi/logo.png,C:/Users/zfk/gapid/release/x86/gapid-apk/build.gradle,C:/Users/zfk/gapid/release/x86/gapid-apk/gradle.properties,C:/Users/zfk/gapid/release/x86/gapid-apk/gradle/wrapper/gradle-wrapper.jar,C:/Users/zfk/gapid/release/x86/gapid-apk/gradle/wrapper/gradle-wrapper.properties,C:/Users/zfk/gapid/release/x86/gapid-apk/gradlew,C:/Users/zfk/gapid/release/x86/gapid-apk/gradlew.bat,C:/Users/zfk/gapid/release/x86/gapid-apk/settings.gradle,C:/Users/zfk/gapid/release/x86/gapid-apk/app/src/main/res/values/strings.xml,C:/Users/zfk/gapid/release/x86/gapid-apk/app/src/main/AndroidManifest.xml" -P D:/GoProjects/src/github.com/google/gapid/cmake/Modules/RunGradle.cmake"

> FAILURE: Build failed with an exception.

>*What went wrong:
>A problem occurred configuring project ':app'.
> failed to find target with hash string 'android-21' in: D:\Android\platforms\android-21

>*Try:
>Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

>BUILD FAILED

>Total time: 25.995 secs
>CMake Error at D:/GoProjects/src/github.com/google/gapid/cmake/Modules/RunGradle.cmake:32 (message):
  1


>[784/834] Performing gapii step for 'aarch64'
ninja: build stopped: subcommand failed.
Error running D:\Downloads\ninja-win\ninja.exe [install]: Process returned error
   Cause: exit status 1
exit status 1

**Comment by ben-clayton** [comment]
Hi @zfk0531,

`AndroidSDKRoot` should be pointing to `D:\Android`

Please let me know if this fixes your problem.

**Comment by zfk0531** [comment]
ok，thanks very much. I will have a try.

**Comment by zfk0531** [comment]
This issue have been solved. But I got another one. The error log said that the GBK encoding can not be recognized:

> Building gapic for windows ...
D:\GoProjects\src\github.com\google\gapid\gapic\src\main\com\google\gapid\models\Strings.java:85: 错误: 编码GBK的不可映射字符
          getString(n, sb.append("鈥? "), arguments).append('\n');
                                   ^
D:\GoProjects\src\github.com\google\gapid\gapic\src\main\com\google\gapid\widgets\CopySources.java:113: 错误: 编码GBK的不可映射字符
    private static final String INDENT = "鈹?   ";
                                           ^
D:\GoProjects\src\github.com\google\gapid\gapic\src\main\com\google\gapid\widgets\CopySources.java:115: 错误: 编码GBK的不可映射字符
    private static final String BRANCH = "鈹溾攢鈹? ";
                                              ^
D:\GoProjects\src\github.com\google\gapid\gapic\src\main\com\google\gapid\widgets\CopySources.java:116: 错误: 编码GBK的不可映射字符
    private static final String BRANCH_LAST = "鈹斺攢鈹? ";
                                                   ^

**Comment by ben-clayton** [comment]
It is possible we may need [to tell Javac to always use UTF-8](http://docs.oracle.com/javase/6/docs/technotes/tools/windows/javac.html), as the _"platform default converter is used"_ if we're not explicit.

Please can you try changing this [parameter list for `javac` in `cmd/do/gapic.go`](https://github.com/google/gapid/blob/master/cmd/do/gapic.go#L108-L112):

```golang
		run(ctx, e.out, e.javacExe, nil,
			"-d", e.mkdirCleanOrExit(javaOut).System(),
			"@"+srcTxt.System(),
			"-classpath", "@"+jarTxt.System(),
			"-encoding", "UTF-8",
			"-source", "1.8", "-target", "1.8")
```

**Comment by zfk0531** [comment]
ok, thanks for your help. I will try this later.

**Comment by zfk0531** [comment]
Done：）

**Comment by zfk0531** [comment]
Is there any document for user guide? I am not sure how to use it.

**Comment by zfk0531** [comment]
I found a new issue:

> BUILD SUCCESSFUL

>Total time: 28.846 secs
[833/834] Install the project...
-- Install configuration: "Release"
-- Installing: C:/Users/zfk/gapid/release/pkg/./gapir.exe
-- Installing: C:/Users/zfk/gapid/release/pkg/./gapis.exe
-- Installing: C:/Users/zfk/gapid/release/pkg/./libwinpthread-1.dll
-- Installing: C:/Users/zfk/gapid/release/pkg/./libstdc++-6.dll
-- Installing: C:/Users/zfk/gapid/release/pkg/./libgcc_s_seh-1.dll
-- Installing: C:/Users/zfk/gapid/release/pkg/./gapit.exe
-- Up-to-date: C:/Users/zfk/gapid/release/pkg/./libwinpthread-1.dll
-- Up-to-date: C:/Users/zfk/gapid/release/pkg/./libstdc++-6.dll
-- Up-to-date: C:/Users/zfk/gapid/release/pkg/./libgcc_s_seh-1.dll
-- Installing: C:/Users/zfk/gapid/release/pkg/./lib/VirtualSwapchainLayer.json
-- Installing: C:/Users/zfk/gapid/release/pkg/./lib/libVkLayer_VirtualSwapchain.dll
-- Installing: C:/Users/zfk/gapid/release/pkg/./lib/libgapii.dll
-- Installing: C:/Users/zfk/gapid/release/pkg/./lib/GraphicsSpyLayer.json
-- Installing: C:/Users/zfk/gapid/release/pkg/./strings/en-us.stb
-- Installing: C:/Users/zfk/gapid/release/pkg/./gapid-aarch64.apk
-- Installing: C:/Users/zfk/gapid/release/pkg/./gapid-armeabi.apk
-- Installing: C:/Users/zfk/gapid/release/pkg/./gapid-x86.apk
-- Installing: C:/Users/zfk/gapid/release/pkg/./build.properties
Building gapic for windows ...
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: D:\GoProjects\src\github.com\google\gapid\gapic\src\rpclib\com\google\gapid\rpclib\binary\BitField.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
Building gapic JAR for windows ...

The Chinese characters said "Some input files use deprecated API, please use -Xlint:deprecation parameter to rebuild." and "BitField.java uses uncheck or unsafe operation, please use -Xlint:unchecked to rebuild". And I cound not find gapic.exe in "/bin" directory under "/release". I think maybe there are some error when Building for windows?

**Comment by zfk0531** [comment]
Ok, I find "/java/gapic-windows.jar" which is a executable java program, and I try to capture some data from a game app on Android device with it. I have used Tracer for OpenGL ES in Android Studio 2.2 before. GAPID looks like a much more powerful profiler than Android Studio GL Tracer.

 But there are still some problem when using GAPID and Android Studio GL Tracer. 
- First, I always can not get captured image for framebuffer and texture when profiling game apps. I do not know what is the problem. 
- Second, the VBO data looks like 16bit float, and I do not know how to parse these data bytes.

Thanks again for your help. GAPID is an amazing profiling tool. I think it is very useful for game app profiling in GPU bound cases.

**Comment by zfk0531** [comment]
Hi, I am confused by "wall time" and "thread time" in Tracer for OpenGL ES (GL Tracer for short). The unit of them is "ns" (nanosecond), and 1 mimisecond equals 1,000,000 nanoseconds. However, the cost time in GL Tracer is much larger than the cost time in Unity profiler.  When I was profiling, I got 29013686 ns for 999 GL calls with GL Tracer in one frame, but I got 1.2ms for Camera.Render which is the main render function with Unity profiler in the same frame. On the other hand, 29013686 ns which equals 29 ms is too long for one frame with 60fps frame rate. Therefore, I want to ask how to understand the "wall time" and "threadtime" in Tracer for OpenGL ES?

**Comment by ben-clayton** [comment]
Hi @zfk0531,

> * First, I always can not get captured image for framebuffer and texture when profiling game apps. I do not know what is the problem.

It's hard for me to know why without looking at the trace or app. If you're happy to share the APK and/or .gfxtrace file with me, I could take a look to see if there's a bug. Please see my github profile for an email address. I would also need a description of what you're expecting to see.

> * Second, the VBO data looks like 16bit float, and I do not know how to parse these data bytes.

I've added a feature request for half-float support [here](https://github.com/google/gapid/issues/311).

> Hi, I am confused by "wall time" and "thread time" in Tracer for OpenGL ES (GL Tracer for short).

I believe [this post on SO](http://stackoverflow.com/questions/25255870/what-is-the-difference-between-wall-time-and-thread-time-in-tracer-for-open) may answer your question.

> Thanks again for your help. GAPID is an amazing profiling tool.

Thank you, but we don't actually support any profiling... yet ;)

**Comment by zfk0531** [comment]
I can not see your email address in your github profile. Do you open it for me?

**Comment by ben-clayton** [comment]
Sorry, this should be visible now.

**Comment by ben-clayton** [comment]
We have now switched build systems to Bazel. Marking this as obsolete.
