### ISSUE TITLE
[Try ABI: unknown⇒gapidapk.EnsureInstalled] Device does not support requested abi: unknown

### ISSUE THREAD

**Issue by pemgithub** [google/gapid#2830]
When I click the refresh button in GAPID GUI, I get the following error in gapis.log:

01:28:33.072 I: [Try ABI: unknown⇒gapidapk.EnsureInstalled] Device does not support requested abi: unknown
01:28:33.072 W: Couldn't find gapid.apk for device. Error: Unable to install GAPID

**Comment by AWoloszyn** [comment]
What device / ABI are you running?

**Comment by pemgithub** [comment]
@AWoloszyn Pixel 3a XL that I rooted using Magisk.  Android version 9.

Note GAPID is able to see the Pixel 3a XL on my home desktop, office laptop, and a teammate's office desktop.  The non-detection error only happens on my office desktop (Windows 10).

**Comment by pemgithub** [comment]
As another data point, I ran GAPID on my Win10 laptop.  My laptop detects the Pixel 3a XL and installs gapid apk.  Then when I move the Pixel 3a XL back to my desktop, I can still see the APK installed.

$ ./adb shell cmd package list packages | grep gapid
package:com.google.android.gapid.aarch64

On my desktop, adb devices sees the Pixel 3a XL.  But GAPID does not.  When I click refresh in GAPID GUI, desktop's gapis.log gets aforementioned error.

To me, the error seems misleading.  It says "Couldn't find gapid.apk for device".  However, GAPID detects the Pixel 3a XL from other Win10 PC's.  So I think the problem is something related to my Win10 desktop... 
 Like a USB driver or some other program trying to access the device.  Android Studio isn't open...

**Comment by AWoloszyn** [comment]
Its worth checking, what version of ADB is being used in each case.
`adb version`. It could be that something is being parsed incorrectly between the versions.

**Comment by pemgithub** [comment]
I'm using the same version of adb in both cases.  Win10 laptop works.  Win10 desktop broken.  Both using 29.0.0 from https://developer.android.com/studio/releases/platform-tools

$ ./adb --version
Android Debug Bridge version 1.0.41
Version 29.0.0-5611747
Installed as D:\Programs\platform-tools_r29.0.0-windows\adb.exe

**Comment by pemgithub** [comment]
I also tried "C:\Programs\Android\SDK\platform-tools\adb.exe".  Same problem.

"gapit devices" also gives an error:

$ gapit devices
22:22:59.139 I: <gapit> Exec: D:\Programs\gapid\gapis.exe --enable-local-files --idle-timeout 1m --log-level Info --log-style brief --gapis-auth-token itkJiaG+
22:23:00.155 I: <gapis.exe> 22:23:00.154 I: <gapis> Adding new device
22:23:00.155 I: <gapis.exe> 22:23:00.154 I: <gapis> New scheduler for device: ac54a06e73875b62a8bf136eff4c9f14e02c72fc
22:23:00.155 I: <gapis.exe> 22:23:00.154 I: <gapis> New trace scheduler for device: ac54a06e73875b62a8bf136eff4c9f14e02c72fc [censored]
22:23:00.163 I: <gapis.exe> Bound on port '63094'
22:23:00.163 I: <gapis.exe> 22:23:00.163 I: <gapis> Starting grpc server
15:23:02.626 I: [Try ABI: unknown⇒gapidapk.EnsureInstalled] <gapis> Device does not support requested abi: unknown
15:23:02.626 W: <gapis> Couldn't find gapid.apk for device. Error: Unable to install GAPID
-- Device 0: ac54a06e73875b62a8bf136eff4c9f14e02c72fc --

**Comment by pemgithub** [comment]
This morning my company laptop (Win10) was able able to detect my Pixel 3a XL:
![gapid-detect](https://user-images.githubusercontent.com/13956322/59312036-6a51b700-8c60-11e9-9ca4-405ad1499604.png)

Though I never was able to actually record a trace from the Pixel 3a XL.

Currently, neither my company laptop nor desktop (both Win10) see the Pixel 3a XL.  They get the same error.  Maybe I should try a different device, eg order a Pixel 2 from Amazon (and root it with Magisk)?

Is it feasible that GAPID only supports certain devices?  Is there a list of what devices GAPID supports?

**Comment by pemgithub** [comment]
I get the error with a moto xt1681 m2672 (moto g5 plus) and Pixel 3a XL.  On both my company Win10 laptop and my company Win10 desktop.

**Comment by AWoloszyn** [comment]
There is currently no list. 
We will investigate to see if something changed re: tracing non-debuggable applications.

**Comment by pemgithub** [comment]
@AWoloszyn I think the problem is that the device being captured needs a userdebug build of Android.

https://source.android.com/setup/develop/new-device#build-variants – refers to eng, user, userdebug, says: userdebug: The same as user, except:
* Also installs modules tagged with debug.
* ro.debuggable=1
* adb is enabled by default.

Unfortunately, I don't think I can just build Android from source, because that will only work for Pixel and Nexus devices.  For other devices, drivers are not publicly available.  According to http://blog.udinic.com/2014/06/04/aosp-part-2-build-variants/ - Every device needs to have its own build of our ROM ... because different devices need different drivers ... Not all manufacturers are willing to give away their precious drivers.

I tried setting ro.debuggable=1 in /system/build.props, but that didn't work.  I'm curious what GAPID needs from "Also installs modules tagged with debug", why GAPID needs that, and whether there's a way to hack a rooted user build to add whatever GAPID needs.

**Comment by AWoloszyn** [comment]
There are 2 main things that we do that typically only work on userdebug builds (or debuggable applications). These are: 
1) Connect to your application with JDWP.
2) Use some properties to enable layers. `debug.vulkan.layers`

These both require that PR_SET_DUMPABLE is true.
My understanding of `ro.debuggable` is that it is readonly, and cannot be modified.

**Comment by pemgithub** [comment]
@AWoloszyn I tried modifying ro.debuggable, on a rooted device, using BuildProp Editor app, which lets you edit /system/build.prop.  This does in fact add a ro.debugguable=1 line to the file /system/build.prop, but after restarting the device, "adb shell getprop ro.debuggable" returns 0.  I assume trying to set ro.debugguable=1 for user build is evil, but...

I'm trying to hack GAPID to work on a rooted user build.  For any GLES app (including GLES app store games).  I don't know enough to know whether this is futile, which is why I was curious about what specifically GAPID needs userdebug build for.

I also tried hacking APK's to debuggable by using apktool to edit AndroidManifest.xml <application android:debuggable="true">.  However, this breaks most app store games (I'm guessing it's because any edit changes the APK signature, and most games verify signature).

My understanding of how to create a userdebug build is that after you unlock bootloader, root device, then...  You have to build the OS from source code.  For Nexus or Pixel, you can build AOSP.  For other devices, you can build LineageOS for a particular supported device.  So I was investigating whether there is a less involved generic hack to enable GAPID on rooted user build (for non-debug GLES apps).

**Comment by AWoloszyn** [comment]
As far as I know there is nothing less intrusive. If you are able to do something similar to LD_PRELOAD on an application, you could in theory load a library, and call `prctl(pr_set_dumpable, 1)` But I am not sure about how possible that will end up being.

**Comment by AWoloszyn** [comment]
I am going to close, as we have no intention in GAPID to go down this route.
