### ISSUE TITLE
#911 error with GSI (userdebug) on Pixel 3a XL

### ISSUE THREAD

**Issue by pemgithub** [google/gapid#2852]
Pixel 3a XL using GSI (generic system image), I get the #911 error when trying to OpenGLES trace calculator, angry birds, clash of clans.
...
Tracing Failed
   Cause: Could not start trace
   Cause: Unable to connect to the application.

This can happen when another debugger or IDE is running in the background, such as Android Studio.
Please close any running Android debuggers and try again.

See https://github.com/google/gapid/issues/911 for more information
...
GSI is userdebug:
![GSI-user-debug-small](https://user-images.githubusercontent.com/13956322/59884502-6a8f3800-936d-11e9-8728-7bb6e68becba.png)

Reference - I installed GSI per directions here:
https://developer.android.com/topic/generic-system-image/
https://source.android.com/setup/build/gsi#flashing-gsis

**Comment by pmuetschard** [comment]
Can you test, whether you can run the Java debugger with such a build? Simplest way to test would be to try and debug a Java sample app in Android Studio. This error shows up when, after starting the app in debug mode, we cannot connect to it via the debug port.

**Comment by pemgithub** [comment]
@pmuetschard I tried Android GSI on a Pixel 3, and I still get #911 for OpenGLES (clash of clans, com.android.calculator2) (GAPID 1.6.0 release).

I'm not trying to capture OpenGLES traces of debug apps (APK).  Rather, I'm trying to capture OpenGLES traces of release build apps such as unmodified Clash of Clans APK from Play Store, or com.android.calculator2.

To capture non-debug app, I installed Android GSI system.img, which is a userdebug build:
https://source.android.com/setup/build/gsi#flashing-gsis
-> Downloading GSIs
-> For example, to flash a GSI to any Pixel device:

Note I am able to trace debug APK's.

I don't have Android Studio installed, but I will try your suggestion to install Android Studio, then attempt to debug a Java sample app in Android Studio.

**Comment by pemgithub** [comment]
@pmuetschard I setup MediaEffects sample in Android Studio, and I'm able to step with F8:
![image](https://user-images.githubusercontent.com/13956322/59970508-f09db100-951c-11e9-9cab-8f7209bf96a1.png)

In GAPID, I can capture a trace for debug APK:
![image](https://user-images.githubusercontent.com/13956322/59970523-42ded200-951d-11e9-8af2-e431602a04ae.png)

However, non-debug APK (such as Clash of Clans) gets #911 error

**Comment by pemgithub** [comment]
Apparently GSI does not enable GAPID, despite allegedly being userdebug.  I instead built AOSP userdebug from source (lunch aosp_blueline-userdebug) (android-9.0.0_r41) (PQ3A.190605.004.A1), and I can record GAPID GLES traces on my Pixel 3.

However, AOSP is missing Google Apps, which I think is required for many Play Store games.  And I've been unable to install Google Apps (or Open GApps).  I tried (adb sideload open_gapps-arm64-9.0-stock-20190627.zip) from Recovery Mode, but it gives an error: E:Failed to find META-INF/com/android/metadata.

So my experience so far is that userdebug is non-trivial to get working (on any device) with Google Apps.

Anyway, it's not a GAPID issue except that (GAPID requires userdebug) (GSI says userdebug but apparently it's missing whatever GAPID needs).
