### ISSUE TITLE
The gapis server has exited with an error code of: -42

### ISSUE THREAD

**Issue by eon-yogiwp** [google/gapid#2871]
GAPID Version: 1.6.0:c0b6cac1c33fab1db1a9d3938201bea8ad581b45
OS: windows 10 amd64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

Just starting the program.

**Comment by Tring-green** [comment]
Open your log file in /tmp/gapic.log or /tmp/gapis.log

1. 
find is there have a message like this:
`libstdc++.so.6: version `GLIBCXX3.4.22’ not found`

then install GLBCXX3.4.22:

`
sudo apt-get install libstdc++6
sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
# below command will show your really version
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
`

2. 
if your GLIBCXX versions have 3.4.22 or newer, but can not open gapid. Close your android studio and input "sudo adb kill-server && sudo adb start-server". 

3. 
if your gapid can not still open , find out your hosts. is there mapping your localhost with 127.0.0.1 or others? please comments them and restart gapid again.

i have tried these three steps, and success to opening gapid.XD

**Comment by hevrard** [comment]
Could you provide the `/tmp/gapic.log` and `/tmp/gapis.log` files produced when you try to launch GAPID?

**Comment by AWoloszyn** [comment]
If you have any more information please add it here. Closing for now.
