### ISSUE TITLE
GAPID should prefer the Java from `$JAVA_HOME` over `$PATH`

### ISSUE THREAD

**Issue by ShabbyX** [google/gapid#2878]
Running GAPID on gLinux fails with this error:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-pi3-gtk-4919 in java.library.path
```

I tried this with any version from 1.2.1 to 1.6. It looks like the libraries are in `~/.swt/lib/linux/x86_64/`, but doing `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/.swt/lib/linux/x86_64/ /opt/gapid/gapid` still fails:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	~/.swt/lib/linux/x86_64/libswt-pi3-gtk-4919.so: /usr/grte/v4/lib64/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0)
```

**Comment by hevrard** [comment]
A known workaround is to use:
`PATH=/usr/lib/jvm/java-11-openjdk-amd64/bin:$PATH ./path/to/gapid`

**Comment by ShabbyX** [comment]
I can verify that this works, but it sure isn't a user friendly experience. In the very least it should be visible in the README.

**Comment by pau-baiget** [comment]
Thanks for reporting this, however it's been identified as not a problem in GAPID.

**Comment by pmuetschard** [comment]
Re-opening this, but with a different request:
`cmd/gapid` should give higher priority to `$JAVA_HOME` than `$PATH`.
