### ISSUE TITLE
Incorrect executable path detection on Linux

### ISSUE THREAD

**Issue by ShabbyX** [google/gapid#2879]
Assuming the hack in #2878 is done, run GAPID like this:

```
~$ export PATH=$PATH:/opt/gapid
~$ gapid
```

This fails with the following error message:

    GAPIC JAR '~/lib/gapic.jar' not found

If you run it as such:

```
~$ /opt/gapid/gapid
```

It works. It looks like GAPID is parsing argv[0] to get to the executable path. This is incorrect. On Linux, the executable path can be queried by doing a `readlink(2)` on `/proc/self/exe`.

**Comment by pmuetschard** [comment]
We should be using https://tip.golang.org/pkg/os/#Executable in `cmd/gapid/main.go`
