### ISSUE TITLE
Tracing Failed   Cause: Could not start trace   Cause: Connecting to JDWP   Cause: read tcp 127.0.0.1:6246->127.0.0.1:6230: wsarecv: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by LeonWen** [google/gapid#2891]
GAPID Version: 1.6.0:c0b6cac1c33fab1db1a9d3938201bea8ad581b45
OS: windows 7 amd64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

**Comment by pau-baiget** [comment]
Thanks for reporting this issue. Could you please more information on how to reproduce the issue? Please also provide the gapi*.log files you can find in the %TEMP% folder.

**Comment by AWoloszyn** [comment]
If you have any more information, please provide it. Closing for now.
