### ISSUE TITLE
Tracing Failed   Cause: Could not start trace   Cause: Could not find package 

### ISSUE THREAD

**Issue by yingnierxiao** [google/gapid#2950]
GAPID Version: 1.6.0:c0b6cac1c33fab1db1a9d3938201bea8ad581b45
OS: mac os x x86_64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

**Comment by pau-baiget** [comment]
@yingnierxiao thanks for reporting this issue. Can you please provide more information so we can prioritize it accordingly?

**Comment by pau-baiget** [comment]
Closing after more than 2 weeks since needs-more-information label was added. @yingnierxiao please re-open if you are able to provide more information, thanks!
