### ISSUE TITLE
Android trace validation errors and no framebuffer on replay

### ISSUE THREAD

**Issue by kudaba** [google/gapid#2958]
I have two issues trying to trace and replay on my android device (Pixel 3).

First, when I trace I get a lot of validation errors where my app has none normally.

Second, when I replay I don't get any framebuffer rendering. I see screen shots on the frames, but not while I'm actually stepping through render calls.

![Screenshot](https://user-images.githubusercontent.com/22896740/61111284-147a5580-a43e-11e9-8bbb-649d05efcaf2.jpg)

I've attached logs of the trace and replay as well as the capture itself if it helps at all. I hope I can figure out why my objects aren't rendering without the framebuffer, but no luck so far.

Details:
OS: Windows 10
Device: Pixel 3 (Android 9 api 28)
App: Compiled with visual studio against platform r16b
Version 1.6.0:c0b6cac1c33fab1db1a9d3938201bea8ad581b45

[com.GameExample_20190712_0030.gfxtrace.zip](https://github.com/google/gapid/files/3385469/com.GameExample_20190712_0030.gfxtrace.zip)
[Trace-logcat.txt](https://github.com/google/gapid/files/3385473/Trace-logcat.txt)
[Replay-logcat.txt](https://github.com/google/gapid/files/3385474/Replay-logcat.txt)

**Comment by kudaba** [comment]
So I posted a similar issue with renderdoc and on advice from baldurk I made a build without the validation errors and all of a sudden everything worked perfectly! It turns out the validation layers from r15c and r16b are pretty much completely broken.

**Comment by hevrard** [comment]
Glad to hear you got that fixed, thanks for the follow-up here which can benefit other users!
