### ISSUE TITLE
The gapis server has exited with an error code of: 2

### ISSUE THREAD

**Issue by zhangpaopao0215** [google/gapid#2972]
GAPID Version: 1.7.0:developer
OS: linux amd64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

**Comment by zhangpaopao0215** [comment]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: Panic at command 48941:glDrawElementsInstanced(draw_mode: GL_TRIANGLES, indices_count: 6, indices_type: GL_UNSIGNED_SHORT, indices: 0, instance_count: 33):
runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: 
--- *resolve.ResourcesResolvable ---
 capture:<ID:<data:"r\357BV\310\302\004f\332\365\205\251\303\223H|]\337\253v" > > config:<replay_device:<ID:<data:"\306\207\330\375h J\234\337\365C\177\225\202\010\035\010C(\034" > > > 
 Store():
  gapis/database/database.go:56  github.com/google/gapid/gapis/database.Build
  gapis/resolve/resources.go:33  github.com/google/gapid/gapis/resolve.Resources
  gapis/resolve/resolve.go:340  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:270  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:137  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:241  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

 Build() #0:
  gapis/database/database.go:60  github.com/google/gapid/gapis/database.Build
  gapis/resolve/resources.go:33  github.com/google/gapid/gapis/resolve.Resources
  gapis/resolve/resolve.go:340  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:270  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:137  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:241  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

--- *resolve.GetResolvable ---
 path:<resources:<capture:<ID:<data:"r\357BV\310\302\004f\332\365\205\251\303\223H|]\337\253v" > > > > config:<replay_device:<ID:<data:"\306\207\330\375h J\234\337\365C\177\225\202\010\035\010C(\034" > > > 
 Store():
  gapis/database/database.go:56  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:389  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:214  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:8918  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:8920  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:971  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:1250  google.golang.org/grpc.(*Server).handleStream

 Build() #0:
  gapis/database/database.go:60  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:389  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:214  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:8918  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:8920  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:971  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:1250  google.golang.org/grpc.(*Server).handleStream
 [recovered]
	panic: 
--- *resolve.ResourcesResolvable ---
 capture:<ID:<data:"r\357BV\310\302\004f\332\365\205\251\303\223H|]\337\253v" > > config:<replay_device:<ID:<data:"\306\207\330\375h J\234\337\365C\177\225\202\010\035\010C(\034" > > > 
 Store():
  gapis/database/database.go:56  github.com/google/gapid/gapis/database.Build
  gapis/resolve/resources.go:33  github.com/google/gapid/gapis/resolve.Resources
  gapis/resolve/resolve.go:340  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:270  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:137  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:241  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

 Build() #0:
  gapis/database/database.go:60  github.com/google/gapid/gapis/database.Build
  gapis/resolve/resources.go:33  github.com/google/gapid/gapis/resolve.Resources
  gapis/resolve/resolve.go:340  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:270  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:137  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:241  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

--- *resolve.GetResolvable ---
 path:<resources:<capture:<ID:<data:"r\357BV\310\302\004f\332\365\205\251\303\223H|]\337\253v" > > > > config:<replay_device:<ID:<data:"\306\207\330\375h J\234\337\365C\177\225\202\010\035\010C(\034" > > > 
 Store():
  gapis/database/database.go:56  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:389  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:214  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:8918  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:8920  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:971  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:1250  google.golang.org/grpc.(*Server).handleStream

 Build() #0:
  gapis/database/database.go:60  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:389  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:214  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:8918  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:8920  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:971  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:1250  google.golang.org/grpc.(*Server).handleStream

[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x150ed36]

goroutine 406 [running]:
github.com/google/gapid/core/app/crash.Crash(0x5215f40, 0xc01b2fdc10)
	core/app/crash/crash.go:89 +0xa7
github.com/google/gapid/core/app/crash.handler()
	core/app/crash/crash.go:56 +0x52
panic(0x5215f40, 0xc01b2fdc10)
	GOROOT/src/runtime/panic.go:522 +0x1b5
github.com/google/gapid/gapis/database.(*memory).resolvePanicHandler(0xc00000fec0, 0x68588a0, 0xc013a7a1b0)
	gapis/database/debug.go:106 +0x76e
panic(0x5260340, 0xc01b2fd6f0)
	GOROOT/src/runtime/panic.go:522 +0x1b5
github.com/google/gapid/gapis/api.ForeachCmd.func1(0xc01746fa90, 0xc01746fad0)
	gapis/api/cmd_foreach.go:43 +0x179
panic(0x53c1e20, 0xb924670)
	GOROOT/src/runtime/panic.go:522 +0x1b5
github.com/google/gapid/gapis/api/gles.Imageʳ.Dataʷ(0x0, 0x0, 0x68588a0, 0xc013a7b590, 0x0, 0x0, 0x44101, 0x0, 0x0, 0x0, ...)
	bazel-out/k8-fastbuild/bin/gapis/api/gles/api_amrp.go:15923 +0x56
github.com/google/gapid/gapis/api/gles.subDependencyReadTexture(0x68588a0, 0xc013a7b590, 0x688ddc0, 0xc007f04600, 0xbf2d, 0x0, 0xc017474c40, 0xc0080eb420, 0xc1a19970, 0x0, ...)
	bazel-out/k8-fastbuild/bin/gapis/api/gles/mutate.go:2110 +0xfe
github.com/google/gapid/gapis/api/gles.subDrawCommandDependencies(0x68588a0, 0xc013a7b590, 0x688ddc0, 0xc007f04600, 0xbf2d, 0x0, 0xc017474c40, 0xc0080eb420, 0xc1a19970, 0x0, ...)
	bazel-out/k8-fastbuild/bin/gapis/api/gles/mutate.go:2174 +0x1329
github.com/google/gapid/gapis/api/gles.subDrawElements(0x68588a0, 0xc013a7b590, 0x688ddc0, 0xc007f04600, 0xbf2d, 0x0, 0xc017474c40, 0xc0080eb420, 0xc1a19970, 0x0, ...)
	bazel-out/k8-fastbuild/bin/gapis/api/gles/mutate.go:1956 +0x4e3
github.com/google/gapid/gapis/api/gles.subDrawElementsInstanced(0x68588a0, 0xc013a7b590, 0x688ddc0, 0xc007f04600, 0xbf2d, 0x0, 0xc017474c40, 0xc0080eb420, 0xc1a19970, 0x0, ...)
	bazel-out/k8-fastbuild/bin/gapis/api/gles/mutate.go:1980 +0x1e2
github.com/google/gapid/gapis/api/gles.(*GlDrawElementsInstanced).Mutate(0xc007f04600, 0x68588a0, 0xc013a7b590, 0xbf2d, 0xc017474c40, 0x0, 0x0, 0x0, 0x0, 0x0)
	bazel-out/k8-fastbuild/bin/gapis/api/gles/mutate.go:17598 +0x228
github.com/google/gapid/gapis/resolve.(*ResourcesResolvable).Resolve.func6(0x68588a0, 0xc013a7b590, 0xbf2d, 0x688ddc0, 0xc007f04600, 0x0, 0x0)
	gapis/resolve/resources.go:112 +0x10f
github.com/google/gapid/gapis/api.ForeachCmd(0x68588a0, 0xc013a7a360, 0xc01549c000, 0x960f2, 0xad800, 0xc01b359c90, 0x0, 0x0)
	gapis/api/cmd_foreach.go:54 +0x264
github.com/google/gapid/gapis/resolve.(*ResourcesResolvable).Resolve(0xc013a7a090, 0x68588a0, 0xc013a7a360, 0xc013a7a2a0, 0xc000328700, 0x2, 0x2)
	gapis/resolve/resources.go:107 +0x5b6
github.com/google/gapid/gapis/database.(*record).resolve(0xc016adca80, 0x68588a0, 0xc013a7a2a0, 0x0, 0x0)
	gapis/database/memory.go:137 +0x222
github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1()
	gapis/database/memory.go:241 +0x134
github.com/google/gapid/core/app/crash.Go.func1(0xc013a7a150)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

**Comment by zhangpaopao0215** [comment]
i try to capture the zen Garden from unreal engine. when playback, it show there is error

thanks

Harry

**Comment by pau-baiget** [comment]
Thanks for reporting this issue. Would it be possible for you to share the trace file?

**Comment by pau-baiget** [comment]
@zhangpaopao0215 do you have any update on this issue? Can you please try our latest developer release?

It would be really useful if we could share the gapi*.log files you can find in the O.S.'s temporary folder (e.g. /tmp in linux, c:\temp in windows). Also, a full logcat capture will be very useful. Thanks!

**Comment by pau-baiget** [comment]
Closing this issue since it's been waiting for more information for a few months already. @zhangpaopao0215 please re-open if you're able to provide more information in the future. Thank you!
