### ISSUE TITLE
Two replays triggered when selecting a command.

### ISSUE THREAD

**Issue by stellama0208** [google/gapid#2983]
GAPID version: v1.6.0
OS: Linux
Reproduce procedure: Run gapid with gapis logging at DEBUG mode. Open framebuffer tab, select a command, look into gapis.log, can see two batches of replay executed, and the framebuffer image was shown after these two replays finish. 

Worth to note that each replay doesn't take too long, but there's noticeable gap between them. Can look into it to see whether it slow down the replay time.

**Comment by pau-baiget** [comment]
Thanks for reporting this. Did you look further towards the reason for the second replay?

**Comment by stellama0208** [comment]
It turns out that it should be an expected behavior. We sometimes separate a replay into two parts with the first part being some "warm-up replay". I think we can close this issue. ^_^
