### ISSUE TITLE
UI - MEC: let user start/stop using keyboard

### ISSUE THREAD

**Issue by hevrard** [google/gapid#3007]
When doing MEC via the UI, the user typically watch her device before having to click on start/stop button on the dialogue windown. It is hard to make sure we click on the button while looking at the device screen. A keyboard interaction, like pressing space bar, would be a good alternative to hacing to click the button.

**Comment by hevrard** [comment]
Space bar already works for this! :man_facepalming: 

Just add some text by the start/stop button to say one can use space bar as an alternative.

**Comment by AWoloszyn** [comment]
I am not sure that is striclty necessary, as this is an OS-level concept. Every button, when in focus can be activated with the space bar as far as I am aware.

**Comment by hevrard** [comment]
OK that's just me who don't interact with GUI stuff in a regular basis.
