### ISSUE TITLE
Integration tests are broken

### ISSUE THREAD

**Issue by hevrard** [google/gapid#3012]
Running `bazel test tests --test_tag_filters=-needs_gpu` leads to:

```
/[...]/gapid/test/integration/replay/postback_test.go:68:18: not enough arguments in call to builder.New
	have (*device.MemoryLayout, nil)
	want (*device.MemoryLayout, *builder.Builder, id.ID)
```

**Comment by hevrard** [comment]
@stellama0208 the recent change to add a replay status bar introduce a new deviceID argument to builder.New()

https://github.com/google/gapid/commit/4df3d56a144af151e7bdd75ad87d5807d182a13f#diff-5f113e8936e8f77f101964a65294d6a9R130

This seems to break the tests. These tests are run on a machine that does not require a GPU. It would be great to fix the tests without having to require a GPU -- I am not sure whether a deviceID does require a GPU underneath.

**Comment by stellama0208** [comment]
Hi Hugues, just opened a new PR to address this problem. Changed the signature back and do what I wanted to do in another way. I have tested it on my local machine and `bazel test tests --test_tag_filters=-needs_gpu` will no longer get these arguments errors, it will give the same result as what is like before my PR (some test still fails in //core/java/jdbg:go_default_test and .../api/test/api_slices.go).

And btw may I ask what are the tests that can be run locally before code submission? Is there anything other than 
`./kokoro/presubmit/presubmit.sh` and 
`bazel test tests --test_tag_filters=-needs_gpu` ?
Thanks for pointing out this test for me, it is always better to run possible tests before code submission!

**Comment by hevrard** [comment]
Thanks for the nice fix!

On your local machine, you can use `bazel test tests` to run all tests before you submit.

On Kokoro, we restrict to `bazel test tests --test_tag_filters=-needs_gpu` because we cannot rely on Kokoro VMs to have any kind of GPU. This is done in the "CI-linux-test" entry of Kokoro.

Unfortunately this is currently failing for various reasons. You just fixed one, thanks! I'm going to chase the root cause of other test failures.

In general, we want to keep this "CI-linux-test" Kokoro entry green before submitting.
