### ISSUE TITLE
Replay outputs for some traces are not deterministic  (from SaschaWillems' Vulkan sample)

### ISSUE THREAD

**Issue by RenfengLiu** [google/gapid#3021]
Replay the  trace  MEC captured from SaschaWillems' Vulkan sample  generates different output (framebuffer images)  each replay. 
Not sure if this is caused by the samples themselves or caused by the capture/replay of GAPID.

At least following samples have this problem
 - pushconstants
- inputattachments
- computeraytracing

**Comment by bjoeris** [comment]
I also found non-determinism in some of the the SaschaWillems samples (the raytracing sample, at least) when I was working on the dead code elimination a few months ago. As I recall, it looked like a data race in the sample, and not a gapid issue.

**Comment by pau-baiget** [comment]
Thanks @bjoeris . Can we then close this?

**Comment by RenfengLiu** [comment]
yes, let's close this since it's the problem of the implementation of the sample application.
