### ISSUE TITLE
Support Hex and help with endianness in Goto→Memory location

### ISSUE THREAD

**Issue by hevrard** [google/gapid#3030]
The top-level menu Goto -> Memory location prompts for a Memory Address which supports only a decimal value, while the user may want to refer to an hex value. Also, it would be great to help the user with endianness.

### Example user story

`glShaderSource()` take a `char**` as third argument named "sourced", the user wants to see the actual shader source in memory. Note that the "source" argument value is displayed as a decimal:

![screenshot2](https://user-images.githubusercontent.com/6726747/62620208-94e28800-b910-11e9-8171-637982139896.png)

But clicking on the "source" argument leads to the memory tab to an address displayed in hex:

![screenshot](https://user-images.githubusercontent.com/6726747/62619996-05d57000-b910-11e9-8bb1-ba74b10ba555.png)

So `4b 0c 88 ea 72 00 00 00` is a `char *`, the user wants to see the memory location at this address. She uses the Goto->Memory location feature, and prints `4b 0c 88 ea 72 00 00 00`. This does not work (nothing happens).

She then realize `4b 0c 88 ea 72 00 00 00` is probably in little endian, and convert it to big endian: `00000072ea880c4b` and try this in Goto->Memory location, without success.

Then she remembers than the source argument was in decimal, so she converts the big endian representation to a decimal `493561056331`. This one works, and jumps to the relevant memory location:

![screenshot](https://user-images.githubusercontent.com/6726747/62620381-1803de00-b911-11e9-842d-bd7cc9a993be.png)

We probably want an easier way to jump around in the memory pool. Maybe have a "right-click -> jump to this address" when highligting some pointer value in the memory?

**Comment by AWoloszyn** [comment]
So the Vulkan structs change should help with this, as it keeps track of the types of everything that is read.

**Comment by pau-baiget** [comment]
Since the Vulkan Structs UI is already checked in, can we close this as fixed? @hevrard

**Comment by hevrard** [comment]
No, Vulkan structs are good, but the Goto->Memory menu is still broken in the sense that it does not support addresses in Hex format.

**Comment by pmuetschard** [comment]
It does, actually. If the address starts with `0x` it's parsed as hex.
