### ISSUE TITLE
UI: "Help->Show Welcome Screen" should not open an pop-up window

### ISSUE THREAD

**Issue by hevrard** [google/gapid#3047]
We recently made the "welcome screen" be integrated into the main screen. Still, the "Help->Show Welcome Screen" still leads to a pop-up windows.

@stellama0208 what do you think? Is this expected behavior, or should we fix this to have this button lead to the integrated welcome screen in the main window?

**Comment by stellama0208** [comment]
Since all the interact-able widgets in the pop-up window is included in the welcoming screen, and we can open new traces through "File->..." menu, I think it's reasonable to remove the "Help->Show Welcome Screen".

I will open a PR to address that, thanks for noticing that!

**Comment by hevrard** [comment]
Sounds good, thanks for the prompt fix!
