### ISSUE TITLE
The gapis server has exited with an error code of: -42

### ISSUE THREAD

**Issue by koushikDeb** [google/gapid#3055]
GAPID Version: 1.6.1:338bb67b0fe291f56f31d69f11ea1a45ed7cfeb6
OS: linux amd64

every time when try to start the application 

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

com.google.gapid.Server$GapisInitException: Failed to connect to the graphics debugger
	at com.google.gapid.Server.connectToServer(Server.java:103)
	at com.google.gapid.Server.connect(Server.java:71)
	at com.google.gapid.Main$UI.startup(Main.java:135)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by hevrard** [comment]
Thanks for reporting. Can you provide the content of `/tmp/gapis.log` ?

**Comment by koushikDeb** [comment]
I20190814-175247036[pool-1-thread-1][server.GapiPaths.checkForTools] Looking for GAPID in /opt/gapid -> /opt/gapid/gapis
I20190814-175247051[server.ChildProcess-gapis][server.ChildProcess.runProcess] Starting gapis as [/opt/gapid/gapis, -enable-local-files, -log-file, /tmp/gapis.log, -log-level, Info, -gapir-args, --log /tmp/gapir.log --log-level I, --strings, /opt/gapid/strings, --gapis-auth-token, bYsgfVA1, --idle-timeout, 60000ms]
W20190814-175247057[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$0] gapis: /opt/gapid/gapis: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /opt/gapid/gapis)
W20190814-175247058[server.ChildProcess-gapis][server.ChildProcess.onExit] The gapis process exited with a non-zero exit value: 1
I20190814-175247058[server.ChildProcess-gapis][server.ChildProcess.shutdown] Shutting down gapis
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] Failed while waiting for gapis
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] java.util.concurrent.ExecutionException: com.google.gapid.server.ChildProcess$EarlyExitException: gapis has exited with exit code 1
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:552)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:431)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:89)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at com.google.gapid.server.GapisProcess.connect(GapisProcess.java:181)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at com.google.gapid.Server.createConnection(Server.java:119)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at com.google.gapid.Server.connectToServer(Server.java:101)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at com.google.gapid.Server.connect(Server.java:71)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at com.google.gapid.Main$UI.startup(Main.java:135)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at java.lang.Thread.run(Thread.java:748)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] Caused by: com.google.gapid.server.ChildProcess$EarlyExitException: gapis has exited with exit code 1
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at com.google.gapid.server.ChildProcess.runProcess(ChildProcess.java:102)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at com.google.gapid.server.ChildProcess$1.run(ChildProcess.java:73)

**Comment by koushikDeb** [comment]
> Thanks for reporting. Can you provide the content of `/tmp/gapis.log` ?

Thank you for responding below  is the content of requested file:

I20190814-175247036[pool-1-thread-1][server.GapiPaths.checkForTools] Looking for GAPID in /opt/gapid -> /opt/gapid/gapis
I20190814-175247051[server.ChildProcess-gapis][server.ChildProcess.runProcess] Starting gapis as [/opt/gapid/gapis, -enable-local-files, -log-file, /tmp/gapis.log, -log-level, Info, -gapir-args, --log /tmp/gapir.log --log-level I, --strings, /opt/gapid/strings, --gapis-auth-token, bYsgfVA1, --idle-timeout, 60000ms]
W20190814-175247057[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$0] gapis: /opt/gapid/gapis: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /opt/gapid/gapis)
W20190814-175247058[server.ChildProcess-gapis][server.ChildProcess.onExit] The gapis process exited with a non-zero exit value: 1
I20190814-175247058[server.ChildProcess-gapis][server.ChildProcess.shutdown] Shutting down gapis
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] Failed while waiting for gapis
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] java.util.concurrent.ExecutionException: com.google.gapid.server.ChildProcess$EarlyExitException: gapis has exited with exit code 1
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:552)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:431)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:89)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at com.google.gapid.server.GapisProcess.connect(GapisProcess.java:181)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at com.google.gapid.Server.createConnection(Server.java:119)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at com.google.gapid.Server.connectToServer(Server.java:101)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at com.google.gapid.Server.connect(Server.java:71)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at com.google.gapid.Main$UI.startup(Main.java:135)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at java.lang.Thread.run(Thread.java:748)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] Caused by: com.google.gapid.server.ChildProcess$EarlyExitException: gapis has exited with exit code 1
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at com.google.gapid.server.ChildProcess.runProcess(ChildProcess.java:102)
W20190814-175247059[pool-1-thread-1][server.GapisProcess.connect] 	at com.google.gapid.server.ChildProcess$1.run(ChildProcess.java:73)

**Comment by AWoloszyn** [comment]
```
gapis: /opt/gapid/gapis: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /opt/gapid/gapis)
```

**Comment by koushikDeb** [comment]
> ```
> gapis: /opt/gapid/gapis: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /opt/gapid/gapis)
> ```

Thank you .. 
but it's there .. please chk the screenshot


![Screenshot from 2019-08-14 20-10-43](https://user-images.githubusercontent.com/9639720/63030661-503a8c00-bed0-11e9-8d1b-c78ceee28d4f.png)

**Comment by AWoloszyn** [comment]
It looks like the version of libstdc++6 is older than GAPID expects. You should be able to update your version of libstdc++.

What ubuntu version are you running?

**Comment by koushikDeb** [comment]
> It looks like the version of libstdc++6 is older than GAPID expects. You should be able to update your version of libstdc++.
> 
> What ubuntu version are you running?

i already updated the version of libstdc++6 still its not working.

my ubuntu versin is 16.04 LTS

**Comment by pau-baiget** [comment]
Closing after 2 weeks since the needs-more-information label was added. @koushikDeb Please re-open if you can provide more information. Thanks!
