### ISSUE TITLE
Tracing purely native executable on Android

### ISSUE THREAD

**Issue by hardc0der** [google/gapid#3056]
Is there any way to trace a purely native executable on Android, i.e. something that is not an Android APK? For example, would it be possible to trace `surfaceflinger` GLES calls?

**Comment by AWoloszyn** [comment]
This is not something we support. However you may have some luck by using "LD_PRELOAD" on libgapii.so. However we have not tested this in a very long time, and it is certainly not guaranteed to work.

**Comment by pemgithub** [comment]
@hardc0der were you able to trace native executable using GAPID?  I want to do the same thing.  Though in my case it's not surfaceflinger; it's an exe (with EGL + GLES) I built myself that I run on the device using adb shell.

**Comment by pau-baiget** [comment]
@hardc0der @pemgithub any updates on your end? Since we don't actively support this we will be closing this issue soon.

**Comment by pau-baiget** [comment]
Closing after 2 weeks since the needs-more-information label was added. @hardc0der  Please re-open if you can provide more information. Thanks!
