### ISSUE TITLE
Setup a dogfooding option that can auto-update on a dogfood release 

### ISSUE THREAD

**Issue by hevrard** [google/gapid#3065]

**Comment by natduca** [comment]
Please add a description of the engineering plan to this, or link a design doc.

**Comment by hevrard** [comment]
See go/gapid-dogfood

**Comment by hevrard** [comment]
After discussion, the plan is:
1. Reuse the existing update mechanism to check the special "nightly" release on GitHub
   a. Let user decide to follow-up nightly release (UI)
   b. use the commit SHA of the currently running app and the one of the nightly release to detect a new nightly release
2. Have Kokoro update the nightly release on GitHub

**Comment by hevrard** [comment]
Step 1.b is  #3104

**Comment by hevrard** [comment]
#3104 and the subsequent #3226 setup a proper "include pre-release" option in updates.
