### ISSUE TITLE
Fix gapir crash reporting.

### ISSUE THREAD

**Issue by AWoloszyn** [google/gapid#3067]
Our crash reporting is not working correctly.

**Comment by natduca** [comment]
@pmuetschard will add some technical details and concrete steps to fix this shortly

**Comment by pmuetschard** [comment]
- Get the minidump export to work properly again
- Make sure they get uploaded to the crash server
- Make uploading the symbols part of the release
- Investigate if we can get crash reporting when tracing working? should we?

**Comment by yalcinmelihyasin** [comment]
#3503 ensures that the crash report uploaded correctly.

**Comment by yalcinmelihyasin** [comment]
#3686 for building symbol files

**Comment by chrisforbes** [comment]
What remains to be done here?

**Comment by yalcinmelihyasin** [comment]
Actually uploading them

**Comment by yalcinmelihyasin** [comment]
Fixed! b/139480214

**Comment by yalcinmelihyasin** [comment]
Merged into this repo by #3787
