### ISSUE TITLE
If the replay service crashes, we should restart gapir.

### ISSUE THREAD

**Issue by AWoloszyn** [google/gapid#3068]
Ideally we don't crash gapir at all, but that is a longer term problem.

**Comment by pau-baiget** [comment]
Tracked internally.

**Comment by yalcinmelihyasin** [comment]
Fixed #3411

**Comment by yalcinmelihyasin** [comment]
The fix is actually fixing if only communication is broken not when crashed.

**Comment by yalcinmelihyasin** [comment]
Suggested but rejected : #3613

**Comment by yalcinmelihyasin** [comment]
b/139480352

**Comment by yalcinmelihyasin** [comment]
PR: #3675

**Comment by yalcinmelihyasin** [comment]
Fixed with #3675
