### ISSUE TITLE
Gapid does not include camera frames

### ISSUE THREAD

**Issue by DMalonas** [google/gapid#3079]
Hello,

I have been trying to record a gapid file of a chatting app.
The part that interests me is the camera button in the chat
menu. I want to create a recording starting from the moment
I click the camera button, till the moment I stop using the
camera. Strangely enough, the frames before I enter and
after I exit the camera menu are present in the final gapid
file but there are no frames to show what happened
during the duration the app was using the camera.
Could that be a bug? Or is there maybe a feature
that I have not enabled?

Thank you.

Regards,
Dimitrios

**Comment by AWoloszyn** [comment]
Hi! Thanks for the report.

Some uses of the camera that was have made work in the past, but there are some interesting issues related to that.

1) What API is your application using. (I am going to assume OpenGLES).
2) As for the camera frames itself, this really depends on how the application is handling the camera itself. There is a good chance the camera is being presented directly to the screen and bypassing OpenGLES entirely. If this is the case, then GAPID will not be able to trace it. If the frame is being ingested into OpenGLES then GAPID should be able to process it.
3) If your are simply invoking a separate application on the system for the camera, I do not think that will be captured either.

**Comment by DMalonas** [comment]
Hi AWoloszyn,

Thank you very much for the prompt response.
- the application is using the OpenGLES API.

Regards,
Dimitrios

**Comment by pau-baiget** [comment]
Closing after 2 weeks since the needs-more-information label was added. @DMalonas  Please re-open if you can provide more information. Thanks!
