### ISSUE TITLE
The red labels for filling in fields sometimes do not go away if it is already filled in

### ISSUE THREAD

**Issue by AWoloszyn** [google/gapid#3082]

**Comment by hevrard** [comment]
@hliatis this is related to your recent change, can you have a look?

I guess this may happen when some fields are pre-filled with data already used before?

**Comment by hliatis** [comment]
I need a specific example

**Comment by AWoloszyn** [comment]
The labels in question are red, but the content is already filled.

<img width="1508" alt="Screen Shot 2019-08-19 at 2 56 37 PM" src="https://user-images.githubusercontent.com/9043212/63291600-db7d9e00-c291-11e9-8c38-6a6fa036421e.png">

**Comment by hliatis** [comment]
Do you have any more contextual information?
