### ISSUE TITLE
The new prefetching breaks the on-disk cache.

### ISSUE THREAD

**Issue by AWoloszyn** [google/gapid#3083]
The on-disk cache no longer prefetches everything. This seems to be related to the new prefetching scheme.

**Comment by AWoloszyn** [comment]
I have a workaround so this does not need to be fixed over this weekend or anything, but should be handled asap next week.

**Comment by purvisa-at-google-com** [comment]
Fixed

**Comment by purvisa-at-google-com** [comment]
Fixed by #3097
