### ISSUE TITLE
Perfetto raises Warnings with GCC 8

### ISSUE THREAD

**Issue by hevrard** [google/gapid#3099]
1. Update perfetto to latest, see if the warnings are still there
2. If so, get them to fix it

I tried to compile perfetto stand-alone in debug mode, it does not raise any issue.
https://android.googlesource.com/platform/external/perfetto/
commit 5817e8e9b2880d4fe03117def2f4ed5e2d95ab58

**Comment by hevrard** [comment]
They seem to have fixed this issues by their commit e0d8eab
https://android.googlesource.com/platform/external/perfetto/+/e0d8eab313374bb164a309d3ffb27688ef0413bc

**Comment by lpy** [comment]
This is fixed by #3101, please feel free to reopen if this is still an issue

**Comment by hevrard** [comment]
https://github.com/google/gapid/blob/2b4d1ac50eb06dffaa17f28fbd1837c009e573a2/tools/build/third_party/perfetto/perfetto.BUILD#L28

This should probably be removed now, @yalcinmelihyasin can you have a look?

**Comment by lpy** [comment]
I think @pmuetschard has removed it
