### ISSUE TITLE
Can not find shader input parameters

### ISSUE THREAD

**Issue by realboy1977** [google/gapid#3125]
Hi there,
I'm using GAPID to debug shader and I can find uniform value in Programs tab.
However I can not find the value of input variable.
Below is an example of vertex shader:

#version 320 es

precision mediump float;
uniform highp vec4 sk_RTAdjust;
uniform highp mat3 uCoordTransformMatrix_0_Stage0;
in highp vec2 inPosition;
in mediump vec4 inColor;
in highp vec2 inLocalCoord;
out mediump vec4 vcolor_Stage0;
out highp vec2 vTransformedCoords_0_Stage0;
void main() {
    mediump vec4 color = inColor;
    vcolor_Stage0 = color;
    highp vec2 pos2 = inPosition;
    vTransformedCoords_0_Stage0 = (uCoordTransformMatrix_0_Stage0 * vec3(inLocalCoord, 1.0)).xy;
    gl_Position = vec4(pos2.x, pos2.y, 0.0, 1.0);
    gl_Position = vec4(gl_Position.x * sk_RTAdjust.x + gl_Position.w * sk_RTAdjust.y, gl_Position.y * sk_RTAdjust.z + gl_Position.w * sk_RTAdjust.w, 0.0, gl_Position.w);
}

For the input variable inPosition, inColor and inLocalCoord.
Can you please guide where to find the value?
Many thanks.

**Comment by pau-baiget** [comment]
Please see https://www.khronos.org/registry/OpenGL/specs/es/3.2/GLSL_ES_Specification_3.20.pdf section 4.3.4 for an explanation on shader input variables. The "in" qualifier relates to values that are input per-vertex (in the vertex shader) or per-fragment (in the fragment shader). In the first case (your shader above), these input values usually passed as part of vertex buffer objects (VBO) bound while  glVertexAttrib* calls (see https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glVertexAttribPointer.xhtml).  To inspect the VBOs you can use the State view (https://gapid.dev/inspect/state).

I'm going to close this issue for now. Please let us know if you have any further questions.
