### ISSUE TITLE
GAPID capture always in Initializing status when capture on Windows

### ISSUE THREAD

**Issue by RenfengLiu** [google/gapid#3135]
GAPID version:1.7.0:developer
The application is https://github.com/google/vulkan_test_applications/tree/master/application_sandbox/dispatch

The capture didn't start and always in initializing status

**Comment by RenfengLiu** [comment]
screenshot:
![dispatch](https://user-images.githubusercontent.com/1320650/64034618-07641380-cb1d-11e9-8ee0-5330a8b847e6.png)

**Comment by RenfengLiu** [comment]
command shows 
```shell
bazel-bin\pkg\gapit.exe trace -capture-frames=10 -start-at-frame=10 -out=C:\Users\renfeng\traces\123.gfxtrace -api=vulkan -device=host  C:\Users\renfeng\src\vulkan_test_applications\bin\Debug\dispatch.exe
16:02:46.014 I: <gapit> Exec: C:\Users\renfeng\gapid\bazel-bin\pkg\gapis.exe --enable-local-files --idle-timeout 1m --log-level Info --log-style brief --gapis-auth-token EG/Gtc8R
16:02:47.249 I: <gapis.exe> 16:02:47.249 I: <gapis> Adding new device
16:02:47.249 I: <gapis.exe> 16:02:47.249 I: <gapis> New scheduler for device: 237c3cb3e8c67f1fa9f45bdd5d16435a479df96b
16:02:47.249 I: <gapis.exe> 16:02:47.249 I: <gapis> New trace scheduler for device: 237c3cb3e8c67f1fa9f45bdd5d16435a479df96b RENFENG0-W
16:02:47.270 I: <gapis.exe> Bound on port '60783'
16:02:47.270 I: <gapis.exe> 16:02:47.270 I: <gapis> Starting grpc server
Tracing C:\Users\renfeng\src\vulkan_test_applications\bin\Debug\dispatch.exe
16:02:47.611 I: <gapit> Trace Status status:Initializing
12:02:47.619 I: <gapis> Exec: C:\Users\renfeng\src\vulkan_test_applications\bin\Debug\dispatch.exe
12:02:48.511 W: <gapis> Could not scan for remote GGP devices. Error: Process returned error
   Cause: exit status 255
```

**Comment by RenfengLiu** [comment]
Turns out the MS solution file for https://github.com/google/vulkan_test_applications  need to be generated with `cmake -G "Visual Studio 14 2015 Win64"` installed of `cmake /path/to/source` on x64 Windows

**Comment by AWoloszyn** [comment]
Aha, that would do it. We do not support 32-bit applications on Desktop.

**Comment by bruce520-lee** [comment]
I meet the same problem as @RenfengLiu, the detailed software information as below. Could someone help to have a comment here if meet same problem or know it?

GAPID version: 1.7.0:developer
Application: vkcube (64bit)
OS version: Windows server 2016

The capture didn't start and always in initializing status
