### ISSUE TITLE
Remove perfetto output file tracing performance

### ISSUE THREAD

**Issue by hevrard** [google/gapid#3137]
As mentioned by Pascal in b/140064402

File /data/misc/perfetto-traces/gapis-trace should be remove before tracing.

This is likely in `core/os/android/adb/perfetto.go`, function `StartPerfettoTrace()`.

Not sure if it is needed on Desktop also?

**Comment by pau-baiget** [comment]
According to the internal ticket, it seems https://github.com/google/gapid/pull/3198 fixed this. @hevrard can we close this?

**Comment by hevrard** [comment]
Fixed by #3198
