### ISSUE TITLE
Pressing "Push Changes" nothing happened but an error

### ISSUE THREAD

**Issue by ja3son** [google/gapid#3161]
like title, error in log:
W 03:22:02.843 gapic error in com.google.gapid.models.Resources$1.onRpcThread
W 03:22:02.843 gapic error in com.google.gapid.models.Resources$1.onRpcThread
└──    [pool-1-thread-2][util.Logging.throttleLogRpcError]
W 03:22:02.843 gapic error in com.google.gapid.models.Resources$1.onRpcThread
└──    com.google.gapid.server.Client$InternalServerErrorException: No command to set data in
W 03:22:02.843 gapic error in com.google.gapid.models.Resources$1.onRpcThread
└──    Caused by: com.google.gapid.server.Client

**Comment by AWoloszyn** [comment]
We fixed some issues related to this recently. It is possible that it is fixed in the newest version. (if you build from source)

**Comment by ja3son** [comment]
i try to build from latest source, not success. here is the error log:
[[ 
no such package '@breakpad//': java.io.IOException: thread interrupted and referenced by '//core/cc:cc' 
 Analysis of target '//:pkg' failed; build aborted: no such package '@breakpad//': java.io.IOException: thread interrupted
Build did NOT complete successfully (134 packages loaded, 7851 targets configured)
]]
how can i fix it?

**Comment by ja3son** [comment]
> i try to build from latest source, not success. here is the error log:
> [[
> no such package '@breakpad//': java.io.IOException: thread interrupted and referenced by '//core/cc:cc'
> Analysis of target '//:pkg' failed; build aborted: no such package '@breakpad//': java.io.IOException: thread interrupted
> Build did NOT complete successfully (134 packages loaded, 7851 targets configured)
> ]]
> how can i fix it?

env:macos

**Comment by hevrard** [comment]
Are you using bazel version `0.25.1` ?

**Comment by pau-baiget** [comment]
Hi @ja3son could you please check @hevrard's question?

**Comment by ja3son** [comment]
> Are you using bazel version `0.25.1` ?

yes, do as wiki

**Comment by hevrard** [comment]
@ja3son we are actively working on updating to bazel 1.0.0 (you can track progress in #3243 )

In the meantime, you can use a developer-release for a recent build, e.g.:
https://github.com/google/gapid/releases/tag/v1.7.0-dev-20191011

Can you try this build and let us know if you are still facing the Push Changes issue?

**Comment by ja3son** [comment]
> @ja3son we are actively working on updating to bazel 1.0.0 (you can track progress in #3243 )
> 
> In the meantime, you can use a developer-release for a recent build, e.g.:
> https://github.com/google/gapid/releases/tag/v1.7.0-dev-20191011
> 
> Can you try this build and let us know if you are still facing the Push Changes issue?

OK, i'll try it

**Comment by pau-baiget** [comment]
Hi @ja3son did you manage to try the dev build? Any updates?

**Comment by pau-baiget** [comment]
Closing this issue since it's been under "needs more information" for two months. @ja3son please re-open if you have tried a latest dev release and still face this issue. Thanks!
