### ISSUE TITLE
[UI] Capture doesn't  start at the specified frame number

### ISSUE THREAD

**Issue by RenfengLiu** [google/gapid#3178]
When select `Frame` for the `Start at` option and input a number in the capture UI, the capture(Vulkan application) didn't start at the specified frame number. 

The application is built from the [latest source code.](https://github.com/google/gapid/commit/730849a13c7f0c93e08401e299a22b9e0a85d1a8) and is tested on gLinux

**Comment by AWoloszyn** [comment]
Was this an off-by-1 error? or did it just not start at all or what?

**Comment by RenfengLiu** [comment]
The capute did not started at all

**Comment by RenfengLiu** [comment]
Update on this one. I thought the capture should automatically start after press the `ok` button. 
So there're two problems:
1. I need to click the start button, which will be hidden because the traced application window popped out. 
2. As the traced application is already running before I press the `Start` button, I think there's no way it could start at the frame specified in the input box. Maybe it calculated the frame number started at the time I press the `Start` button.
