### ISSUE TITLE
Upgrade to bazel 1.0.0

### ISSUE THREAD

**Issue by lpy** [google/gapid#3235]
Our internal environment upgraded bazel to 1.0, looks like bazel 1.0 deprecated a bunch of proto provider related fields that we are using. https://blog.bazel.build/2019/10/10/bazel-1.0.html

**Comment by lpy** [comment]
grpc is upgrading to bazel 1.0.0: https://github.com/grpc/grpc/pull/20558

**Comment by lpy** [comment]
Fixed

**Comment by lpy** [comment]
Not actually done, there are changes like AAPT2 usage as well. Going through this list now: https://github.com/bazelbuild/bazel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Abreaking-change-1.0

**Comment by lpy** [comment]
development is not blocked by this now, lower to P1, we need to update Kokoro

**Comment by pau-baiget** [comment]
@johnplate any updates on this issue?

**Comment by johnplate** [comment]
This is currently blocked as bazel 0.26.1 until 1.1.0 are incompatible with
mingw-gcc compiler on Windows. I managed to push the Bazel developers to
include a fix into version 1.2.0, which should be released today.

**Comment by johnplate** [comment]
Upgraded to Bazal 1.2.0 with #3432
