### ISSUE TITLE
"cc1plus: error: -Werror=class-memaccess: no option -Wclass-memaccess" when build 1.7.0-dev-20191004

### ISSUE THREAD

**Issue by balanice** [google/gapid#3242]
Hi, I'm building gapid, failed times. Error is:
`ERROR: /home/force/.cache/bazel/_bazel_force/3732e61f7a2e185ab83ba6a53c139b6f/external/glslang/BUILD.bazel:17:1: C++ compilation of rule '@glslang//:glslang' failed (Exit 1) gcc failed: error executing command 
  (cd /home/force/.cache/bazel/_bazel_force/3732e61f7a2e185ab83ba6a53c139b6f/sandbox/linux-sandbox/7594/execroot/gapid && \
  exec env - \
    PATH=/home/force/software/protoc-3.10.0/bin:/home/force/anaconda3/condabin:/usr/share/sbt/bin:/opt/spring-2.0.5.RELEASE/bin:/home/force/software/apache-maven-3.5.4/bin:/usr/local/bin/julia-1.0.0/bin:/home/force/software/gradle-4.10.3/bin:/home/force/Android/Sdk/platform-tools/:/usr/lib/jvm/jdk1.8.0_161/bin:/usr/lib/jvm/jdk1.8.0_161/jre/bin:/home/force/bin:/home/force/.local/bin:/home/force/.npm-global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/force/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/k8-fastbuild/bin/external/glslang/_objs/glslang/SpvBuilder.pic.d '-frandom-seed=bazel-out/k8-fastbuild/bin/external/glslang/_objs/glslang/SpvBuilder.pic.o' -fPIC -iquote external/glslang -iquote bazel-out/k8-fastbuild/bin/external/glslang -Ibazel-out/k8-fastbuild/bin/external/glslang/_virtual_includes/glslang '-std=c++11' -Werror -DTARGET_OS_LINUX -DNV_EXTENSIONS -Wno-unused-variable '-Wno-error=class-memaccess' -Wno-maybe-uninitialized -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/glslang/SPIRV/SpvBuilder.cpp -o bazel-out/k8-fastbuild/bin/external/glslang/_objs/glslang/SpvBuilder.pic.o)
Execution platform: @bazel_tools//platforms:host_platform

Use --sandbox_debug to see verbose messages from the sandbox: gcc failed: error executing command 
  (cd /home/force/.cache/bazel/_bazel_force/3732e61f7a2e185ab83ba6a53c139b6f/sandbox/linux-sandbox/7594/execroot/gapid && \
  exec env - \
    PATH=/home/force/software/protoc-3.10.0/bin:/home/force/anaconda3/condabin:/usr/share/sbt/bin:/opt/spring-2.0.5.RELEASE/bin:/home/force/software/apache-maven-3.5.4/bin:/usr/local/bin/julia-1.0.0/bin:/home/force/software/gradle-4.10.3/bin:/home/force/Android/Sdk/platform-tools/:/usr/lib/jvm/jdk1.8.0_161/bin:/usr/lib/jvm/jdk1.8.0_161/jre/bin:/home/force/bin:/home/force/.local/bin:/home/force/.npm-global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/force/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/k8-fastbuild/bin/external/glslang/_objs/glslang/SpvBuilder.pic.d '-frandom-seed=bazel-out/k8-fastbuild/bin/external/glslang/_objs/glslang/SpvBuilder.pic.o' -fPIC -iquote external/glslang -iquote bazel-out/k8-fastbuild/bin/external/glslang -Ibazel-out/k8-fastbuild/bin/external/glslang/_virtual_includes/glslang '-std=c++11' -Werror -DTARGET_OS_LINUX -DNV_EXTENSIONS -Wno-unused-variable '-Wno-error=class-memaccess' -Wno-maybe-uninitialized -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/glslang/SPIRV/SpvBuilder.cpp -o bazel-out/k8-fastbuild/bin/external/glslang/_objs/glslang/SpvBuilder.pic.o)
Execution platform: @bazel_tools//platforms:host_platform

Use --sandbox_debug to see verbose messages from the sandbox
cc1plus: error: -Werror=class-memaccess: no option -Wclass-memaccess
Target //:pkg failed to build
INFO: Elapsed time: 5483.969s, Critical Path: 310.91s
INFO: 7642 processes: 7590 linux-sandbox, 52 worker.
FAILED: Build did NOT complete successfully
`
The environment is:
**gapid source**
gapid-1.7.0-dev-20191004
**OS**
Linux Mint 18.3 64bit (Ubuntu 16.04)
**GCC**
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1\~16.04\~ppa1)
**bazel**
Build label: 0.25.1

Does anyone know how to fix it?

**Comment by hevrard** [comment]
The issue is due to using gcc 7, which does not know about  -Wclass-memaccess.

You can fix this issue by using gcc 8.

Please re-open if the build is still failing with gcc 8.
