### ISSUE TITLE
-disable-coherentmemorytracker only available through command line tool

### ISSUE THREAD

**Issue by chrisforbes** [google/gapid#3257]
This needs to be possible through the GUI tool, otherwise it is impossible to reliably capture through the GUI against drivers which upset the coherent memory tracking (eg SwiftShader)

**Comment by AWoloszyn** [comment]
This should fix those issues:
`https://github.com/google/gapid/pull/3454`

**Comment by pau-baiget** [comment]
Closing as fixed.
