### ISSUE TITLE
Unhandled exception in the UI thread.

### ISSUE THREAD

**Issue by peitong** [google/gapid#3261]
GAPID Version: 1.7.0:dev-1110Fri-03bb3d5927cd91e3b9bb4730ef7094164211f56b
OS: windows 7 amd64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

**Comment by pau-baiget** [comment]
Thanks for reporting this issue. Please provide more details about the specific crash: stacktrace, full logcat, and contents of the tmp/gapi*.log files.

**Comment by pau-baiget** [comment]
Closing this since more than 2 weeks passed after adding the needs-more-information label.
