### ISSUE TITLE
Tracing Failed   Cause: Could not start trace   Cause: Installing gapid.apk   Cause: Installing gapid.apk   Cause: Process returned error   Cause: exit status 1

### ISSUE THREAD

**Issue by peitong** [google/gapid#3262]
GAPID Version: 1.6.1:338bb67b0fe291f56f31d69f11ea1a45ed7cfeb6
OS: windows 7 amd64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

**Comment by hevrard** [comment]
Thanks for reporting!

Can you confirm all requirements listed there are met: https://gapid.dev/trace/

Can you try to remove any gapid package from the device, and restart gapid, would you still have the issue?

**Comment by pau-baiget** [comment]
Closing this issue since it's been 2 weeks since the label needs-more-information was added. @peitong  please feel free to re-open if you can provide more information about the issue. Thanks!
