### ISSUE TITLE
`launch_producer` tool for profiling is not built as PIE for arm32

### ISSUE THREAD

**Issue by chrisforbes** [google/gapid#3265]
From discussion with @rschiu yesterday:
- Needs to be built as PIE (-fPIE, -pie to linker)
- We should choose which version of the producer host to run based on the primary ABI of the device, not on the ABI of the target app?

**Comment by pau-baiget** [comment]
Required because this is blocking all the producer plumbing if the app is 32 bit.

**Comment by pmuetschard** [comment]
> Needs to be built as PIE

We already are:
```
external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang '-D__ANDROID_API__=23' -isystemexternal/androidndk/ndk/sysroot/usr/include/arm-linux-androideabi -target armv7-none-linux-androideabi '-march=armv7-a' '-mfloat-abi=softfp' '-mfpu=vfpv3-d16' -gcc-toolchain external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes '' -MD -MF bazel-out/android-armeabi-v7a-fastbuild/bin/cmd/launch_producer/_objs/launch_producer-bin/main.pic.d '-frandom-seed=bazel-out/android-armeabi-v7a-fastbuild/bin/cmd/launch_producer/_objs/launch_producer-bin/main.pic.o' -fPIC -iquote . -iquote bazel-out/android-armeabi-v7a-fastbuild/bin -iquote external/bazel_tools -iquote bazel-out/android-armeabi-v7a-fastbuild/bin/external/bazel_tools '-std=c++11' '--sysroot=external/androidndk/ndk/platforms/android-23/arch-arm' -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++abi/include -isystem external/androidndk/ndk/sources/android/support/include -isystemexternal/androidndk/ndk/sysroot/usr/include -c cmd/launch_producer/main.cpp -o bazel-out/android-armeabi-v7a-fastbuild/bin/cmd/launch_producer/_objs/launch_producer-bin/main.pic.o
```

> We should choose which version of the producer host to run based on the primary ABI of the device.

That's what we're doing. The producer is launched, when the device is connected, before we ever know what app will be traced.

What exactly is the request here and what is the issue encountered?

**Comment by rschiu** [comment]
We need PIE not PIC.

> That's what we're doing. The producer is launched, when the device is connected, before we ever know what app will be traced.

It looks like this is happening in during replay.  GAPID will try to launch the 32-bit version of the launch_producer.  User will see an error log message saying the executable needs to be built with PIE.

**Comment by pmuetschard** [comment]
> It looks like this is happening in during replay. GAPID will try to launch the 32-bit version of the launch_producer.

Is this true? I thought the launch_producer binary is only run once on gapis start?
