### ISSUE TITLE
gapic stores gapis log at /tmpgapis.log instead of /tmp/gapis.log on Linux

### ISSUE THREAD

**Issue by Qining** [google/gapid#33]
Error message is "permission denial", but the real issue is wrong log file paths.

Caused by `gapic/src/main/com/google/gapid/server/GapisProcess.java`, line 77 and line 81

In commit: 07201a74, we removed the `File.separator` from the code, this causes this issue on Linux.

**Comment by ben-clayton** [comment]
I think this was fixed by https://github.com/google/gapid/pull/36, please can you confirm?

**Comment by pmuetschard** [comment]
Indeed, that change fixed it.
