### ISSUE TITLE
Save entire replay

### ISSUE THREAD

**Issue by JDeuce** [google/gapid#3314]
Hi I have used gapid it works really great. But e.g. if I capture on a android phone and then try to view it later, I need to have the device connected. This makes sense as a default but is problematic if I try to share the capture with colleagues who might not have a capable device. Is there a workflow where I can export a hydrated replay for this type of use case?

**Comment by hevrard** [comment]
Hi @JDeuce , replaying a trace does need a similar device to the one on which this trace was captured. GAPID makes no guarantee of being able to replay anywhere else.

(While this could be possible in principles, it is a minefield that we decided not to explore.)
