### ISSUE TITLE
Unhandled exception in the UI thread.

### ISSUE THREAD

**Issue by Beelkic** [google/gapid#3322]
GAPID Version: 1.7.0:dev-20191021-b198af2dc0ae304eb7531ad2e23ff570ae2ead9e
OS: mac os x x86_64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

**Comment by hevrard** [comment]
@Beelkic could you check your logs to see if it is a duplicate of #3343 ?

**Comment by pau-baiget** [comment]
Closing this ticket since it's been in "needs more information" for more than a month. @Beelkic please re-open if you're able to provide more information, thank you!
