### ISSUE TITLE
Using Gapit to run CTS tests

### ISSUE THREAD

**Issue by rominoushana** [google/gapid#3330]
Is it possible to run Android CTS tests with gapit? I've been trying to figure this out for the past couple of days, but have not able to run any CTS unless I use the cts-tradefd terminal.

**Comment by hevrard** [comment]
I am not sure what you want to achieve here: do you want to trace a dEQP test-case?

(Capturing a dEQP test case proved difficult in the past, because of the client-server architecture of dEQP.)

**Comment by rominoushana** [comment]
> I am not sure what you want to achieve here: do you want to trace a dEQP test-case?
> 
> (Capturing a dEQP test case proved difficult in the past, because of the client-server architecture of dEQP.)

I'm trying to run Compatibility tests that google offers: https://source.android.com/compatibility/cts

There is a graphics test that is failing on my side and I have to debug it through Gapit in order to find the issue.

**Comment by pau-baiget** [comment]
@chrisforbes could you please reply whether there's a way to run a specific CTS test as an independent APK? Otherwise we run into the problem of tracing a process spawned by the application (which we can't support at the moment).

**Comment by chrisforbes** [comment]
Being able to directly launch a test (without the separate process) would require some hacks inside dEQP itself.

**Comment by pau-baiget** [comment]
Based on Chris' comment, this (tracing a spawned process) is a functionality that we won't be able to support anytime soon. I will be closing this issue as Won't fix.
