### ISSUE TITLE
Are there old versions that support Android 4.x devices?

### ISSUE THREAD

**Issue by zwcloud** [google/gapid#3344]
I know current release of gapid require Android 6.0, but I need to debug shaders running on a Galaxy Tab 3 8.0 (SM-T311, ARM Mali 400), which uses Android 4.2.2. (I cannot upgrade it)
Which [release ](https://github.com/google/gapid/releases) should I use? Could you please lead me to the download link?

**Comment by hevrard** [comment]
Hi @zwcloud , unfortunately GAPID does not support such old versions of Android.

You may try the first release v1.0.0 (https://github.com/google/gapid/releases/tag/v1.0.0), but we do not guarantee it would be working with Android 4, and we won't be able to offer maintenance to such old Android versions.

**Comment by zwcloud** [comment]
@hevrard I think in about 2012-2014, there is also some opengles2.0 based android app running on an Android 4.x devices and there must exists some inspector that has the same function as gapid.

Do you have any ideas on how to find these old tools? I think, maybe you had worked on an opengles 2.0 app with a android 4.x phone at 2012, sir, then how did you debug the shaders then?

**Comment by hevrard** [comment]
Apologies, but I did not work in graphics back in those years!

Maybe Intel GPA, which dates from around 2014, could be working for you?
https://software.intel.com/en-us/android/articles/using-the-intel-gpa-system-analyzer-to-improve-android-apps

**Comment by zwcloud** [comment]
Thank you! I will have a look on that.
