### ISSUE TITLE
gapis server crash（ gapis -enable-local-files -persist -rpc localhost:40000）  when gapit replace_resource, server report out of memory ，

### ISSUE THREAD

**Issue by cntown2016** [google/gapid#3345]
OS: Win10
GAPID：1.7.0 
09:48:50.042 I: [Try ABI: arm64-v8a⇒gapidapk.EnsureInstalled] <gapis> Examining gapid.apk on host...
09:48:50.076 I: [Try ABI: arm64-v8a⇒gapidapk.EnsureInstalled] <gapis> Looking for gapid.apk...
09:48:50.232 I: [Try ABI: arm64-v8a⇒gapidapk.EnsureInstalled] <gapis> Found gapid package...
09:48:50.233 I: [startDevInfoService] <gapis> Attempt to start service: com.google.android.gapid.DeviceInfoService
09:48:50.460 I: <gapis> Adding new device
09:48:50.460 I: <gapis> Adding new device
09:48:50.460 I: <gapis> New scheduler for device: 464d6909825f9520c00cc7eb5de4395318a83e27
09:48:50.460 I: <gapis> New trace scheduler for device: 464d6909825f9520c00cc7eb5de4395318a83e27 unknown 
**runtime: VirtualAlloc of 381681664 bytes failed with errno=1455
fatal error: out of memory**

runtime stack:
runtime.throw(0x655a5be, 0xd)
        GOROOT/src/runtime/panic.go:617 +0x79
runtime.sysMap(0xc3c7800000, 0x16c00000, 0xc189cb8)
        GOROOT/src/runtime/mem_windows.go:122 +0x138
runtime.(*mheap).sysAlloc(0xc16f640, 0x16b5e000, 0xc16f650, 0xb5af)
        GOROOT/src/runtime/malloc.go:633 +0x1d4
runtime.(*mheap).grow(0xc16f640, 0xb5af, 0x0)
        GOROOT/src/runtime/mheap.go:1222 +0x49
runtime.(*mheap).allocSpanLocked(0xc16f640, 0xb5af, 0xc189cc8, 0xc16f648)
        GOROOT/src/runtime/mheap.go:1150 +0x3a9
runtime.(*mheap).alloc_m(0xc16f640, 0xb5af, 0x473d0101, 0x473d4bd8)
        GOROOT/src/runtime/mheap.go:977 +0xd0
runtime.(*mheap).alloc.func1()
        GOROOT/src/runtime/mheap.go:1048 +0x53
runtime.(*mheap).alloc(0xc16f640, 0xb5af, 0xc010101, 0x473d4b48)
        GOROOT/src/runtime/mheap.go:1047 +0x91
runtime.largeAlloc(0x16b5dd6a, 0x450101, 0x473d4b48)
        GOROOT/src/runtime/malloc.go:1055 +0xa0
runtime.mallocgc.func1()
        GOROOT/src/runtime/malloc.go:950 +0x4d
runtime.systemstack(0x4)
        GOROOT/src/runtime/asm_amd64.s:351 +0x6b
runtime.mstart()
        GOROOT/src/runtime/proc.go:1153

goroutine 17335 [running]:
runtime.systemstack_switch()
        GOROOT/src/runtime/asm_amd64.s:311 fp=0xc29b39c490 sp=0xc29b39c488 pc=0x45bf60
runtime.mallocgc(0x16b5dd6a, 0x565c7a0, 0xc29b39c501, 0xc29b39c568)
        GOROOT/src/runtime/malloc.go:949 +0x8b1 fp=0xc29b39c530 sp=0xc29b39c490 pc=0x40dfa1
runtime.makeslice(0x565c7a0, 0x16b5dd6a, 0x16b5dd6a, 0x5e71b5)
        GOROOT/src/runtime/slice.go:49 +0x73 fp=0xc29b39c560 sp=0xc29b39c530 pc=0x446893
bytes.makeSlice(0x16b5dd6a, 0x0, 0x0, 0x0)
        GOROOT/src/bytes/buffer.go:232 +0x74 fp=0xc29b39c590 sp=0xc29b39c560 pc=0x514dc4
bytes.(*Buffer).grow(0xc331912e10, 0x80000a, 0x4)
        GOROOT/src/bytes/buffer.go:145 +0x176 fp=0xc29b39c5e0 sp=0xc29b39c590 pc=0x5146c6
bytes.(*Buffer).Write(0xc331912e10, 0xc336bb2000, 0x80000a, 0xa35c49, 0x4, 0x0, 0x0)
        GOROOT/src/bytes/buffer.go:175 +0xed fp=0xc29b39c610 sp=0xc29b39c5e0 pc=0x5149ed
github.com/google/gapid/core/data/pack.(*Writer).flushChunk(0xc331912f00, 0x6eb1e00, 0xc3c75b3d80, 0x0)
        core/data/pack/writer.go:151 +0x11f fp=0xc29b39c658 sp=0xc29b39c610 pc=0xac642f
github.com/google/gapid/core/data/pack.(*Writer).writeMessage(0xc331912f00, 0x6f69fe0, 0xc331912f90, 0x6eb1ee0, 0xc3c75b3d80, 0x55cf400, 0x0, 0x0, 0x0, 0x5c8aa00)
        core/data/pack/writer.go:118 +0x1ba fp=0xc29b39c6d0 sp=0xc29b39c658 pc=0xac5eda
github.com/google/gapid/core/data/pack.(*Writer).Object(...)
        core/data/pack/writer.go:76
github.com/google/gapid/gapis/capture.(*encoder).RemapID(0xc331916620, 0x6f69fe0, 0xc331912f90, 0x1e0448a787b97f88, 0x313b270886002861, 0xc323028f38, 0xc29b39c848, 0x496273, 0x5ef8680)
        gapis/capture/encoder.go:195 +0x22d fp=0xc29b39c768 sp=0xc29b39c6d0 pc=0xacfa1d
github.com/google/gapid/gapis/api.init.4.func1(0x6f69fe0, 0xc331912f90, 0x74770f, 0x0, 0x800000, 0x1e0448a787b97f88, 0x313b270886002861, 0x23028f38, 0x0, 0x0, ...)
        gapis/api/cmd_observations.go:107 +0xc4 fp=0xc29b39c7c8 sp=0xc29b39c768 pc=0xa743f4
runtime.call128(0xc01c786210, 0x66147f8, 0xc3bc09d860, 0x4000000058)
        GOROOT/src/runtime/asm_amd64.s:521 +0x59 fp=0xc29b39c858 sp=0xc29b39c7c8 pc=0x45c459
reflect.Value.call(0x5897020, 0x66147f8, 0x13, 0x6549c26, 0x4, 0xc29b39cbe0, 0x2, 0x2, 0x0, 0x4acc1a0, ...)
        GOROOT/src/reflect/value.go:447 +0x468 fp=0xc29b39ca78 sp=0xc29b39c858 pc=0x48dc98
reflect.Value.Call(0x5897020, 0x66147f8, 0x13, 0xc29b39cbe0, 0x2, 0x2, 0x0, 0x0, 0x2)
        GOROOT/src/reflect/value.go:308 +0xab fp=0xc29b39cae0 sp=0xc29b39ca78 pc=0x48d6fb
github.com/google/gapid/core/data/protoconv.ToProto(0x6f69fe0, 0xc331912f90, 0x5ef8680, 0xc333f8b260, 0xc3c75b3d00, 0xc3c75b3d00, 0xc29b39cc78, 0xf5)
        core/data/protoconv/protoconv.go:139 +0x2b3 fp=0xc29b39cc20 sp=0xc29b39cae0 pc=0x96eb83
github.com/google/gapid/gapis/capture.(*encoder).initialState(0xc331916620, 0x6f69fe0, 0xc331912f90, 0x6eb1e20, 0xc331802cc0)
       gapis/capture/encoder.go:68 +0x1c5 fp=0xc29b39cd70 sp=0xc29b39cc20 pc=0xace6e5
github.com/google/gapid/gapis/capture.(*encoder).encode(0xc331916620, 0x6f69fe0, 0xc331912f90, 0xc331916620, 0x6f69fe0)
        gapis/capture/encoder.go:38 +0x27e fp=0xc29b39cdf8 sp=0xc29b39cd70 pc=0xace4be
github.com/google/gapid/gapis/capture.(*GraphicsCapture).Export(0xc33185e360, 0x6f69fe0, 0xc1d98951d0, 0x6d9e460, 0xc331912e10, 0x40bb1a, 0x5c8aa00)
        gapis/capture/graphics.go:214 +0x16e fp=0xc29b39ce68 sp=0xc29b39cdf8 pc=0xad127e
github.com/google/gapid/gapis/capture.toProto(0x6f69fe0, 0xc1d98951d0, 0x6eb1de0, 0xc33185e360, 0xc16a140, 0xc29b39cf78, 0x4157b5)
        gapis/capture/capture.go:215 +0x95 fp=0xc29b39cf18 sp=0xc29b39ce68 pc=0xacb515
github.com/google/gapid/gapis/capture.toProtoWrapped(0x6f69fe0, 0xc1d98951d0, 0x6eb1de0, 0xc33185e360, 0x0, 0x0, 0x0)
        gapis/capture/capture.go:299 +0x50 fp=0xc29b39cf60 sp=0xc29b39cf18 pc=0xacc3f0
runtime.call64(0xc01c6fd620, 0x661d1e0, 0xc331802d40, 0x2000000038)
        GOROOT/src/runtime/asm_amd64.s:520 +0x42 fp=0xc29b39cfb0 sp=0xc29b39cf60 pc=0x45c3b2
reflect.Value.call(0x58efd60, 0x661d1e0, 0x13, 0x6549c26, 0x4, 0xc29b39d338, 0x2, 0x2, 0x0, 0x4acc1a0, ...)
        GOROOT/src/reflect/value.go:447 +0x468 fp=0xc29b39d1d0 sp=0xc29b39cfb0 pc=0x48dc98
reflect.Value.Call(0x58efd60, 0x661d1e0, 0x13, 0xc29b39d338, 0x2, 0x2, 0xc29b39d2a0, 0x4fec4f, 0xc000333c80)
        GOROOT/src/reflect/value.go:308 +0xab fp=0xc29b39d238 sp=0xc29b39d1d0 pc=0x48d6fb
github.com/google/gapid/core/data/protoconv.ToProto(0x6f69fe0, 0xc1d98951d0, 0x5c4cba0, 0xc33190c550, 0x0, 0x6cd0900, 0x5e9ebc0, 0xc0002a8f60)
        core/data/protoconv/protoconv.go:139 +0x2b3 fp=0xc29b39d378 sp=0xc29b39d238 pc=0x96eb83
github.com/google/gapid/gapis/database.toProto(0x6f69fe0, 0xc1d98951d0, 0x5c4cba0, 0xc33190c550, 0x5e9ebc0, 0xc0002a8f60, 0xc29b39d498, 0x4fec4f)
        gapis/database/to_proto.go:36 +0xd9 fp=0xc29b39d430 sp=0xc29b39d378 pc=0x97dfb9
github.com/google/gapid/gapis/database.(*memory).Store(0xc0002a8f60, 0x6f69fe0, 0xc1d98951d0, 0x5c4cba0, 0xc33190c550, 0x0, 0x0, 0x0, 0x0, 0x0)
        gapis/database/memory.go:170 +0x61f fp=0xc29b39d518 sp=0xc29b39d430 pc=0x97cb8f
github.com/google/gapid/gapis/database.Store(0x6f69fe0, 0xc1d98951d0, 0x5c4cba0, 0xc33190c550, 0x0, 0x0, 0x0, 0x0, 0x57da600)
        gapis/database/database.go:45 +0xe1 fp=0xc29b39d590 sp=0xc29b39d518 pc=0x97a701
github.com/google/gapid/gapis/capture.New(0x6f69fe0, 0xc1d98951d0, 0x6eb1de0, 0xc33185e360, 0x44, 0xc08106b180, 0xc3317c94a0)
        gapis/capture/capture.go:60 +0x9c fp=0xc29b39d630 sp=0xc29b39d590 pc=0xaca16c
github.com/google/gapid/gapis/resolve.changeResources(0x6f69fe0, 0xc1d98951d0, 0xcf81060, 0xc1d9891000, 0xc07cff44a8, 0x1, 0x1, 0xc29b39db80, 0x1, 0x1, ...)
        gapis/resolve/set.go:354 +0x522 fp=0xc29b39d738 sp=0xc29b39d630 pc=0xb55282
github.com/google/gapid/gapis/resolve.change(0x6f69fe0, 0xc1d98951d0, 0xcf81060, 0x6f6b420, 0xc1d9894ab0, 0x6174560, 0xc1d9894b40, 0x0, 0x40d1, 0xc19f7c9e60, ...)
        gapis/resolve/set.go:92 +0x36f6 fp=0xc29b39dde8 sp=0xc29b39d738 pc=0xb54976
github.com/google/gapid/gapis/resolve.(*SetResolvable).Resolve(0xc1d98910c0, 0x6f69fe0, 0xc1d98951d0, 0xc1d98950e0, 0xc19f7c9f00, 0x2, 0x2)
        gapis/resolve/set.go:55 +0x1d0 fp=0xc29b39de70 sp=0xc29b39dde8 pc=0xb511c0
github.com/google/gapid/gapis/database.(*record).resolve(0xc07cfcd860, 0x6f69fe0, 0xc1d98950e0, 0x0, 0x0)
        gapis/database/memory.go:137 +0x229 fp=0xc29b39df30 sp=0xc29b39de70 pc=0x97c289
github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1()
        gapis/database/memory.go:241 +0x13b fp=0xc29b39dfb8 sp=0xc29b39df30 pc=0x97e5ab
github.com/google/gapid/core/app/crash.Go.func1(0xc1d9894ff0)
        core/app/crash/crash.go:65 +0x4a fp=0xc29b39dfd8 sp=0xc29b39dfb8 pc=0x543fca
runtime.goexit()
        GOROOT/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc29b39dfe0 sp=0xc29b39dfd8 pc=0x45e111
created by github.com/google/gapid/core/app/crash.Go
        core/app/crash/crash.go:63 +0x46

goroutine 1 [select, 3 minutes]:
github.com/google/gapid/gapis/server.NewWithListener(0x6f69fe0, 0xc000333d10, 0x6eb67e0, 0xc00038c008, 0xc000388000, 0xc186270, 0x0, 0x0, 0x1, 0x0, ...)
        gapis/server/grpc.go:84 +0x3cd
github.com/google/gapid/gapis/server.Listen(0x6f69fe0, 0xc000333d10, 0xc0000ac100, 0xf, 0xc000388000, 0xc186270, 0x0, 0x0, 0x1, 0x0, ...)
        gapis/server/grpc.go:50 +0x106
main.run(0x6f69fe0, 0xc000333d10, 0xc000306880, 0x6f69fe0)
       cmd/gapis/main.go:141 +0x76b
github.com/google/gapid/core/app.doRun(0x661dc08, 0x0)
        core/app/run.go:283 +0x3ea
github.com/google/gapid/core/app.Run(0x661dc08)
        core/app/run.go:176 +0x32
main.main()
        cmd/gapis/main.go:71 +0x7c

goroutine 5 [syscall, 4 minutes]:
os/signal.signal_recv(0x0)
        GOROOT/src/runtime/sigqueue.go:139 +0xa3
os/signal.loop()
        GOROOT/src/os/signal/signal_unix.go:23 +0x29
created by os/signal.init.0
        GOROOT/src/os/signal/signal_unix.go:29 +0x48

goroutine 35 [chan receive, 3 minutes]:
github.com/google/gapid/core/log.Channel.func1()
        core/log/channel.go:30 +0xae
github.com/google/gapid/core/app/crash.Go.func1(0xc000333620)
        core/app/crash/crash.go:65 +0x4a
created by github.com/google/gapid/core/app/crash.Go
        core/app/crash/crash.go:63 +0x46

goroutine 36 [chan receive, 4 minutes]:
github.com/google/gapid/core/app.handleAbortSignals.func1()
        core/app/atexit.go:95 +0x70
github.com/google/gapid/core/app/crash.Go.func1(0xc000333950)
        core/app/crash/crash.go:65 +0x4a
created by github.com/google/gapid/core/app/crash.Go
        core/app/crash/crash.go:63 +0x46

goroutine 37 [chan receive, 4 minutes]:
github.com/google/gapid/core/app.AddCleanup.func1()
        core/app/atexit.go:59 +0x92
github.com/google/gapid/core/app/crash.Go.func1(0xc000333ad0)
        core/app/crash/crash.go:65 +0x4a
created by github.com/google/gapid/core/app/crash.Go
        core/app/crash/crash.go:63 +0x46

goroutine 8 [select, 3 minutes]:
reflect.rselect(0xc000330080, 0x2, 0x2, 0xc000330080, 0xc0001146d8)
        GOROOT/src/runtime/select.go:542 +0x394
reflect.Select(0xc0001149a0, 0x2, 0x64, 0xc0003b0090, 0x0, 0x0, 0x0, 0x6f69fe0)
        GOROOT/src/reflect/value.go:2165 +0x178
github.com/google/gapid/gapis/replay/scheduler.(*Scheduler).run(0xc0001e78c0, 0x6f69fe0, 0xc0001e7890)
        gapis/replay/scheduler/scheduler.go:200 +0x7f7
github.com/google/gapid/gapis/replay/scheduler.New.func1()
        gapis/replay/scheduler/scheduler.go:78 +0x43
github.com/google/gapid/core/app/crash.Go.func1(0xc0003011e0)
        core/app/crash/crash.go:65 +0x4a
created by github.com/google/gapid/core/app/crash.Go
        core/app/crash/crash.go:63 +0x46

goroutine 9 [select]:
github.com/google/gapid/core/os/android/adb.Monitor(0x6f69fe0, 0xc000333d10, 0xc000333a10, 0xb2d05e00, 0x0, 0x0)
        core/os/android/adb/device.go:92 +0x2f2
main.monitorAndroidDevices(0x6f69fe0, 0xc000333d10, 0xc000333a10, 0xc00032df98)
        cmd/gapis/main.go:172 +0x80
main.run.func1()
        cmd/gapis/main.go:124 +0x6a
github.com/google/gapid/core/app/crash.Go.func1(0xc0001e78f0)
        core/app/crash/crash.go:65 +0x4a
created by github.com/google/gapid/core/app/crash.Go
        core/app/crash/crash.go:63 +0x46

**Comment by AWoloszyn** [comment]
How large is your trace? (# of frames).

**Comment by pau-baiget** [comment]
Ping @cntown2016 :)

**Comment by pau-baiget** [comment]
@cntown2016 please answer the question. If we don't hear back we'll be closing this issue soon. Thanks!
