### ISSUE TITLE
Allow a user to capture after a delay.

### ISSUE THREAD

**Issue by AWoloszyn** [google/gapid#3391]
For desktop platforms, many games pause when they lose focus. So if we can allow the user to specify a delay when trying to capture, this means that they can trigger the capture, enter the game, close the menus, and then get the capture.

**Comment by chrisforbes** [comment]
Andrew, How important is this for your platform? It's not a factor for Android.

**Comment by AWoloszyn** [comment]
It is quite important. I know its less needed on android, but it's very necessary on Desktop.

**Comment by ronaldfw** [comment]
Agree on the importance of this. Would be great to have. Right now, captures on desktop have a useless portion of ~1 second at the beginning of the trace.

**Comment by AWoloszyn** [comment]
@ronaldfw : Specifically performance profiling captures correct?
It is even worse on Graphics Captures.

**Comment by ronaldfw** [comment]
Yes, I meant performance profiling captures, but I can see that would be a lot worse for frame debugging.
