### ISSUE TITLE
Tracing Failed   Cause: Could not start trace   Cause: Starting activity in debug mode   Cause: Process returned error   Cause: exit status 1

### ISSUE THREAD

**Issue by ls306196689** [google/gapid#3458]
GAPID Version: 1.6.1:338bb67b0fe291f56f31d69f11ea1a45ed7cfeb6
OS: windows 10 amd64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

**Comment by AWoloszyn** [comment]
Do you have any more information? gapis.log or an adb logcat would be helpful.

**Comment by pau-baiget** [comment]
Closing as the issue has been open for two weeks now without further info. @ls306196689 please re-open if you're able to provide more details. Thank you!!
