### ISSUE TITLE
The ggp tracing command uses deprecated --env flag, should use --vars

### ISSUE THREAD

**Issue by ronaldfw** [google/gapid#3465]
Code location is here:
https://github.com/google/gapid/blob/9983d617c8b1bd2de0c04e45694eece14fb92968/gapis/trace/desktop/ggp_trace.go#L162

Obviously, this is a minor issue (for now) but should be fixed eventually. I can make the change and submit a PR for this.

**Comment by AWoloszyn** [comment]
@ronaldfw That would be great!

**Comment by ronaldfw** [comment]
Fixed by https://github.com/google/gapid/pull/3504
