### ISSUE TITLE
The gapis server has exited with an error code of: 2

### ISSUE THREAD

**Issue by chraac** [google/gapid#3475]
GAPID Version: 1.7.0:dev-2110Mon-b198af2dc0ae304eb7531ad2e23ff570ae2ead9e
OS: windows 10 amd64
Device: Pixel 2XL

Following is error info:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x7ac030]

goroutine 955 [running]:
github.com/google/gapid/core/app/crash/reporting.Reporter.sendReport(0x654a86c, 0x5, 0xc0000aeb40, 0x3a, 0xc0000abea0, 0xa, 0xc00021a460, 0xb, 0x6d9e440, 0xc0022966c0, ...)
	core/app/crash/reporting/reporting.go:111 +0x4e0
github.com/google/gapid/core/app/crash/reporting.Reporter.reportStacktrace(0x654a86c, 0x5, 0xc0000aeb40, 0x3a, 0xc0000abea0, 0xa, 0xc00021a460, 0xb, 0xc006e42000, 0x24, ...)
	core/app/crash/reporting/reporting.go:133 +0x2d4
github.com/google/gapid/core/app/crash/reporting.Enable.func1(0x5822a60, 0xc007eb7520, 0xc006e42000, 0x24, 0x32)
	core/app/crash/reporting/reporting.go:66 +0x1b7
github.com/google/gapid/core/app/crash.Crash.func1.1(0xc0002cfcd0, 0xc00036b940, 0x5822a60, 0xc007eb7520, 0xc006e42000, 0x24, 0x32)
	core/app/crash/crash.go:84 +0x89
created by github.com/google/gapid/core/app/crash.Crash.func1
	core/app/crash/crash.go:82 +0x179
```

How to reproduce:

1. Open this trace: [trace_20191202_1124.zip](https://github.com/google/gapid/files/3909358/trace_20191202_1124.zip)

2. Select "OpenGL ES context 9"

3. Double click draw call in "Frame 3" repeatedly

**Comment by hevrard** [comment]
Thanks for reporting, I can see you are using an unstable developer release: can you try with the latest developer release available here:
https://github.com/google/gapid-dev-releases/releases/latest

**Note: you will need to re-capture your trace, as the trace format has changed.**

Please let us know if the latest dev-release fixes your issue!

**Comment by chraac** [comment]
> Thanks for reporting, I can see you are using an unstable developer release: can you try with the latest developer release available here:
> https://github.com/google/gapid-dev-releases/releases/latest
> 
> **Note: you will need to re-capture your trace, as the trace format has changed.**
> 
> Please let us know if the latest dev-release fixes your issue!

Hi, I have test with gapid 1.6.1 stable release, and it show up same error.

**Comment by hevrard** [comment]
Thanks for trying with the latest stable. Can you try with the latest unstable preview release:
https://github.com/google/gapid-dev-releases/releases/tag/v1.7.0-dev-20191204

**Comment by pau-baiget** [comment]
Closing this issue since it's been with "needs more information" for a month. @chraac  please re-open if you see this issue again and are able to provide the information requested in the previous comment. Thank you!|
