### ISSUE TITLE
GLSL parser: Cannot cope with parameter names sharing type names.

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#348]
Given:

```C
struct Bar { int i; }; void Foo(Bar Bar) {}
```

You get the error:

```1:37: Unexpected token (Bar), was expecting one of: [, )]```

While I'm not entirely sure that this is legal GLSL, I've encountered captures that do this. We should support this case.

**Comment by AWoloszyn** [comment]
From what I have read of the GLSL spec, this is legal (It is definitely legal in C).

```
int f( /* nested scope begins here */ int k)
{
 int k = k + 3; // redeclaration error of the name k
 ...
}

If a nested scope redeclares a name used in an outer scope,
it hides all existing uses of that name. There is no way to access the hidden
name or make it unhidden, without exiting the scope that hid it
```

**Comment by ben-clayton** [comment]
Yeah, I just checked section "4.2 Scoping" in [the spec too](https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.50.pdf).

It seems like this should be legal, however I've now found a driver that gives a similar error to our parser. :/
