### ISSUE TITLE
Optimize codergen for structs containing arrays

### ISSUE THREAD

**Issue by pmuetschard** [google/gapid#356]
Consider the following struct as defined in an API file:
```
class Foo {
  // ...
  Bar[42] bars
  // ...
}
```
When generating go code, a type ```Barː42ᵃ``` struct containing a single filed called ```Elements``` is created. This extra indirection pollutes the state tree and should be removed.

**Comment by ben-clayton** [comment]
Example:

```go

type VkMemoryTypeː32ᵃ struct {
	Elements [32]VkMemoryType
}

```
