### ISSUE TITLE
Refresh device list for tracing

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#358]
I often connect a device after I've launched GAPIC. I go to take a trace and find there's no device in the list, and have to restart GAPIC.
We should periodically poll for a new device list.

**Comment by pmuetschard** [comment]
GAPIC refreshes the devices every time the trace dialog is opened (i.e. by calling the getDevices RPC without caching the result). I think it is GAPIS that needs to check for changes in the connected devices. Let me know if that is not what you find.

**Comment by ben-clayton** [comment]
I actually created this bug before I found more issues preventing the device from appearing that were fixed [with this PR](https://github.com/google/gapid/pull/360). Let's assume I was wrong for now. I'll reopen if I still have issues.
