### ISSUE TITLE
Can not capture trace for conservativeraster in SaschaWillems' sample

### ISSUE THREAD

**Issue by RenfengLiu** [google/gapid#3617]
use latest version of gapid, the capture got stuck and no trace is captured, either from beginning or from certain frame. 

 However, using the cmd can do the capture, e.g
```bazel-bin/pkg/gapit trace -capture-frames 10 -start-at-frame 95 -out ~/traces/conservativeraster_1234.gfxtrace -api vulkan -device host -workingdir ~/project/SaschaWillems/Vulkan/build -no-buffer ~/project/SaschaWillems/Vulkan/build/bin/conservativeraster```

**Comment by AWoloszyn** [comment]
We do not support conservative raster yet IIRC

**Comment by RenfengLiu** [comment]
close this since we don't support conservative raster
