### ISSUE TITLE
Tracing Failed   Cause: Could not start trace   Cause: Waiting for Application Creation   Cause: 0 classes found with the signature 'Landroid/app/Application;'

### ISSUE THREAD

**Issue by AJ2014** [google/gapid#3626]
GAPID Version: 1.6.1:338bb67b0fe291f56f31d69f11ea1a45ed7cfeb6
OS: windows 7 amd64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

**Comment by AWoloszyn** [comment]
Do you have any additional information?
How did you try adn start the trace, and what re the outputs of gapis.log and gapic.log?

**Comment by pau-baiget** [comment]
@AJ2014 we are closing this issue since it's been waiting for more information for a few weeks now. Please re-open if you are able to provide more details about the issue. Thank you!!
