### ISSUE TITLE
Redirect logging to stdlog (stderr)

### ISSUE THREAD

**Issue by mattyclarkson** [google/gapid#3659]
It would be very useful to be able to do

    gapit devices --os android | jq '.devices[].configuration.perfetto_capability'

This would require two changes:

  * Logging can be redirected to `stderr`
  * Devices are dumped as part of the JSON structure, rather than under `-- Device <id>: <hash> --` headers

Effectively, by adding a new `-log-to-stderr` flag (or `-log-to-stdlog`, or whatever else)

    $ gapit -log-to-stderr devices --os android 2>/dev/null
    {
      devices: [
        { ... },
        { ... }
      ]
    }

The other option is to change logging to `stdlog` (i.e. `stderr`) by default

**Comment by hevrard** [comment]
Hi @mattyclarkson , thanks for this feedback.

Regarding the log output, you can get rid of noisy Information-level logs by imposing a "Fatal" log-level:
`./bazel-bin/pkg/gapit -log-level Fatal devices`

Regarding the addition of "device" in the JSON, that sounds like a reasonable thing to do by changing the output layout somewhere around:
https://github.com/google/gapid/blob/fd707b2bfc85a95a24b9a9667e8b22fb6fc36ec6/cmd/gapit/devices.go#L54

We do not have the bandwidth to address this right now, but we are very open to accept relevant contributions.

**Comment by mattyclarkson** [comment]
I can have a look. Would really help scripting. Currently fighting fires :fire: :man_firefighter: :fire_engine: but will have time in the future to look into it.
