### ISSUE TITLE
Be graceful if `libgpudataproducer.so` does not output to `stderr`

### ISSUE THREAD

**Issue by mattyclarkson** [google/gapid#3728]
We've been cleaning up our code. As part of that we removed all debugging from our `libgpudataproducer.so`.

I've been trying to figure out why our `gpu.counters` doesn't work with GAPID/`gapit` anymore.

It was because we don't output anything on `stderr` so the [StartFunc](https://github.com/google/gapid/blob/571246c744f5f3c2d148434cfcd6390d684f3aa5/gapidapk/deviceinfo.go#L214-L216) never gets invoked. This makes GAPID/`gapis`/`gapit` hang.

Reverse engineering that took a bit of time 🤦‍♂️

Is there documentation for `libgpudataproducer.so`? Make sure to add that you must print something to `stderr` before sleeping!

Might be worth putting a bit of defensive programming in there. If nothing is received in 5(?) seconds, it errors out and puts a helpful hint explaining that GAPID needs to receive something on `stderr` from `libgpudataproducer.so`.

**Comment by lpy** [comment]
Fixed in #3732
