### ISSUE TITLE
System Trace with vkreplay

### ISSUE THREAD

**Issue by mattyclarkson** [google/gapid#3729]
**Environment information:**
 - GAPID version:1.7.0-dev-20200203
 - Host OS: Linux/Windows
 If tracing on Android:
 - Device model: Makalu GED
 - Android Version: 10

**Bug description**
Additional arguments do not get passed to `vkreplay`

**Reproduction steps**
Install `vkreplay` on device, attempt to perform a system replay with the following settings

Application: `android.intent.action.MAIN:com.example.vkreplay/android.app.NativeActivity`
Additional Arguments: `--EnablePortabilityTableSupport true --SelfManageMemoryAllocation true -o /data/local/tmp/lineage2.vktrace`

`adb logcat '*.S' 'vkreplay:V'` will output
```
01-03 10:16:19.492 15604 15627 I vkreplay: argc = 1
01-03 10:16:19.492 15604 15627 I vkreplay: argv[0] = vkreplay
01-03 10:16:19.492 15604 15627 V vkreplay: Replaying with v1.11
01-03 10:16:19.492 15604 15627 E vkreplay: No trace file specified.
01-03 10:16:19.492 15604 15627 D vkreplay: vkreplay_main returned -1
```

The arguments do not seem to get passed through the executable. The following does work:

```
adb shell am start \
  -a android.intent.action.MAIN \
  -n com.example.vkreplay/android.app.NativeActivity \
  --es args "'--EnablePortabilityTableSupport true
              --SelfManageMemoryAllocation    true
               -o                              /data/local/tmp/lineage2.vktrace'"
```

```
01-03 10:18:10.951 15826 15849 I vkreplay: argc = 7
01-03 10:18:10.951 15826 15849 I vkreplay: argv[0] = vkreplay
01-03 10:18:10.951 15826 15849 I vkreplay: argv[1] = --EnablePortabilityTableSupport
01-03 10:18:10.951 15826 15849 I vkreplay: argv[2] = true
01-03 10:18:10.951 15826 15849 I vkreplay: argv[3] = --SelfManageMemoryAllocation
01-03 10:18:10.951 15826 15849 I vkreplay: argv[4] = true
01-03 10:18:10.951 15826 15849 I vkreplay: argv[5] = -o
01-03 10:18:10.951 15826 15849 I vkreplay: argv[6] = /data/local/tmp/lineage2.vktrace
01-03 10:18:10.951 15826 15849 V vkreplay: Replaying with v1.11
```

**Comment by hevrard** [comment]
Can you try including the `--es args` in the "Additional Arguments" field?

**Comment by mattyclarkson** [comment]
No dice. Still get:
```
01-03 10:36:39.200 19886 19909 I vkreplay: argc = 1
01-03 10:36:39.200 19886 19909 I vkreplay: argv[0] = vkreplay
01-03 10:36:39.200 19886 19909 V vkreplay: Replaying with v1.11
01-03 10:36:39.200 19886 19909 E vkreplay: No trace file specified.
01-03 10:36:39.200 19886 19909 D vkreplay: vkreplay_main returned -1
```

**Comment by hevrard** [comment]
When I put the following string in "Additional Arguments" in the UI:

`--es args "--EnablePortabilityTableSupport true --SelfManageMemoryAllocation true -o /data/local/tmp/lineage2.vktrace"`

It gets passed on to vkreplay:
```
02-05 11:02:31.135 10706 10731 I vkreplay: argc = 7
02-05 11:02:31.135 10706 10731 I vkreplay: argv[0] = vkreplay
02-05 11:02:31.135 10706 10731 I vkreplay: argv[1] = --EnablePortabilityTableSupport
02-05 11:02:31.135 10706 10731 I vkreplay: argv[2] = true
02-05 11:02:31.135 10706 10731 I vkreplay: argv[3] = --SelfManageMemoryAllocation
02-05 11:02:31.135 10706 10731 I vkreplay: argv[4] = true
02-05 11:02:31.135 10706 10731 I vkreplay: argv[5] = -o
02-05 11:02:31.135 10706 10731 I vkreplay: argv[6] = /data/local/tmp/lineage2.vktrace
```

Screenshot:
![screenshot](https://user-images.githubusercontent.com/6726747/73836556-739f1d80-4807-11ea-8d39-79a155c32f62.png)

With gapit, you must escape the whole additional args string with single quotes. e.g.:
```
gapit trace -api vulkan -additionalargs '--es args "--EnablePortabilityTableSupport true --SelfManageMemoryAllocation true -o /data/local/tmp/lineage2.vktrace"' com.example.vkreplay/android.app.NativeActivity
```

@mattyclarkson can you give this a try and confirm it works on your side?

**Comment by mattyclarkson** [comment]
The `gapit` command works. `gapid` doesn't though.

![gapid-additional-arguments](https://user-images.githubusercontent.com/1081113/73839845-d3e58d80-480e-11ea-92a9-64925ae4c54b.png)

I double checked on another Linux box with the latest GAPID.

Are you on Windows by any chance? Does GAPIS do a `shell` call which could change the quoting?

The `gapit` command does a graphics trace (`.gfxtrace`) not a Perfetto trace (`.perfetto`), I'm not sure if that follows a different code path.

**Comment by hevrard** [comment]
To take a perfetto trace with gapit, use `-api perfetto`, but you'll also probably want other flags for the duration, etc.

With the UI: I confirm the [v1.7.0-dev-20200205](https://github.com/google/gapid-dev-releases/releases/tag/v1.7.0-dev-20200205) release from this morning , on Linux, works for me with the instructions above.

In the `/tmp/gapis.log` file, I can see the arguments being passed:
```
13:58:08.642 I: <gapis> Starting with options {ObserveFrameFrequency:0 ObserveDrawFrequency:0 StartFrame:0 FramesToCapture:3 APIs:4 Flags:80 AdditionalFlags:--es args "--EnablePortabilityTableSupport true --SelfManageMemoryAllocation true -o /data/local/tmp/lineage2.vktrace" PipeName:}
```

Can you try the same dev release, with the UI, and share the `/tmp/gapis.log` file here?

**Comment by hevrard** [comment]
Oh, the UI way also fails for me when trying a System Profile. Let me look into this.

**Comment by hevrard** [comment]
See fix in: https://github.com/google/gapid/pull/3751
