### ISSUE TITLE
Add master version config file

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#373]
We have a couple of places where we declare executable / build versions. There's [version.go](https://github.com/google/gapid/blob/master/cmd/gapis/version.go) which is parsed by the build system to label the packages, [Version.java](https://github.com/google/gapid/blob/master/gapic/src/main/com/google/gapid/server/Version.java), [build.gradle](https://github.com/google/gapid/blob/master/gapidapk/android/app/build.gradle#L24-L25), and a [bunch of other version declarations](https://github.com/google/gapid/blob/master/cmd/gapit/main.go#L23) knocking around.

As we prepare to release prebuilt binaries, I'd like us to unify the versions of all executables so they are consistent for a given package.

I propose we add a `version.cmake` file at the root of the repo, and declare the major, minor, point versions for the GAPID codebase (replacing the [parsing in Package.cmake](https://github.com/google/gapid/blob/master/cmake/Package.cmake#L20-L33)). We then use [`configure_file`](https://cmake.org/cmake/help/v3.0/command/configure_file.html) to generate all the go, java, gradle version codes.

**Comment by pmuetschard** [comment]
At this time GAPIC only verifies that the major/minor versions match with GAPIS, and I've been using the kokoro build number as the micro version. Having the build number be part of the version is beneficial, so it kind of made sense. Except that on kokoro every build type (release vs continuous vs ... & platform) has its own sequence. I propose using the **first six hex chars of the commit sha as the micro version.**

**Comment by ben-clayton** [comment]
I like the idea of using the SHA in the build. We should also consider marking developer builds as such, maybe in the micro version field. That way we won't confuse 'official' builds with local builds.

**Comment by AWoloszyn** [comment]
I agree on the SHA for the minor of the build. The major advantage is that anyone can look at a build, find the source that generated said build, and re-build that specific version, rather than an arbitrary number. Using the entire sha as the micro would mitigate collisions, rather than only a part of it.

**Comment by pmuetschard** [comment]
Yes! I've been doing that by putting "SNAPSHOT" as the micro version in build.properties, as well as for a few of the other fields there, for local builds.

**Comment by pmuetschard** [comment]
I just noticed that convention seems to be to use the first **seven** hex chars of the sha. I think that is enough to avoid collisions. If it's ever not specific enough, I think it'll either be pretty obvious which one it is, or specific enough combined with the major & minor version.

**Comment by AWoloszyn** [comment]
What we do in SHADERC is we format the version as tag + number of commits since the last tag + sha

**Comment by AWoloszyn** [comment]
So if we had a major.minor tag (every time we rev major / minor) we could always have builds be 
<tag>.<commits_since_tag>.<sha> where tag is <major>.<minor>.
