### ISSUE TITLE
Tracing broken on Linux

### ISSUE THREAD

**Issue by AWoloszyn** [google/gapid#3760]
Cannot trace any application on Linux, the application simply dies immediately.

**Comment by pmuetschard** [comment]
I think this is because we did not destroy the created devices, nor were we destroying the instance. Since we request the device info at the beginning of a trace this is, unsurprisingly, causing issues. Would the fix be to just destroy the devices and instance?

**Comment by AWoloszyn** [comment]
Unless we sure also destroying the instance, I think this is actually fine. I was walking the code and the crash was in create device. It might be the fact that we are not setting the dispatch table when creating from inside a layer
