### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by alexfs** [google/gapid#3804]
panic: uint8(0x0@2790714143)[3145728].Slice(3141632, 3146752) - out of bounds [recovered]
	panic: Panic at command 226:vkQueueSubmit(queue: 94204541566104, submitCount: 1, pSubmits: 0x00007ffc80e7cc70, fence: 0) → VK_SUCCESS:
uint8(0x0@2790714143)[3145728].Slice(3141632, 3146752) - out of bounds [recovered]
	panic: 
--- *resolve.ContextListResolvable ---
 capture:<ID:<data:"\260\264\032\222\233?d\323\033\316\376\363\334,\215\352|k\221\177" > > config:<replay_device:<ID:<data:"\315\301\274fJ\270\231\014JR\3772ER\350\302\210\2568-" > > > 
 Store():
  gapis/database/database.go:56  github.com/google/gapid/gapis/database.Build
  gapis/resolve/contexts.go:35  github.com/google/gapid/gapis/resolve.Contexts
  gapis/resolve/resolve.go:308  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:270  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:137  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:241  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

 Build() #0:
  gapis/database/database.go:60  github.com/google/gapid/gapis/database.Build
  gapis/resolve/contexts.go:35  github.com/google/gapid/gapis/resolve.Contexts
  gapis/resolve/resolve.go:308  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:270  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:137  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:241  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

--- *resolve.GetResolvable ---
 path:<contexts:<capture:<ID:<data:"\260\264\032\222\233?d\323\033\316\376\363\334,\215\352|k\221\177" > > > > config:<replay_device:<ID:<data:"\315\301\274fJ\270\231\014JR\3772ER\350\302\210\2568-" > > > 
 Store():
  gapis/database/database.go:56  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:389  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:214  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/k8-opt/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:8914  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/k8-opt/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:8916  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:971  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:1250  google.golang.org/grpc.(*Server).handleStream

 Build() #0:
  gapis/database/database.go:60  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:389  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:214  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/k8-opt/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:8914  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/k8-opt/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:8916  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:971  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:1250  google.golang.org/grpc.(*Server).handleStream
 [recovered]
	panic: 
--- *resolve.ContextListResolvable ---
 capture:<ID:<data:"\260\264\032\222\233?d\323\033\316\376\363\334,\215\352|k\221\177" > > config:<replay_device:<ID:<data:"\315\301\274fJ\270\231\014JR\3772ER\350\302\210\2568-" > > > 
 Store():
  gapis/database/database.go:56  github.com/google/gapid/gapis/database.Build
  gapis/resolve/contexts.go:35  github.com/google/gapid/gapis/resolve.Contexts
  gapis/resolve/resolve.go:308  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:270  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:137  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:241  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

 Build() #0:
  gapis/database/database.go:60  github.com/google/gapid/gapis/database.Build
  gapis/resolve/contexts.go:35  github.com/google/gapid/gapis/resolve.Contexts
  gapis/resolve/resolve.go:308  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:270  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:137  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:241  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

--- *resolve.GetResolvable ---
 path:<contexts:<capture:<ID:<data:"\260\264\032\222\233?d\323\033\316\376\363\334,\215\352|k\221\177" > > > > config:<replay_device:<ID:<data:"\315\301\274fJ\270\231\014JR\3772ER\350\302\210\2568-" > > > 
 Store():
  gapis/database/database.go:56  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:389  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:214  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/k8-opt/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:8914  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/k8-opt/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:8916  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:971  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:1250  google.golang.org/grpc.(*Server).handleStream

 Build() #0:
  gapis/database/database.go:60  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:389  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:214  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/k8-opt/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:8914  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/k8-opt/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:8916  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:971  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:1250  google.golang.org/grpc.(*Server).handleStream

goroutine 316 [running]:
github.com/google/gapid/core/app/crash.Crash(0x4a85ae0, 0xc001ea4c30)
	core/app/crash/crash.go:89 +0xa7
github.com/google/gapid/core/app/crash.handler()
	core/app/crash/crash.go:56 +0x52
panic(0x4a85ae0, 0xc001ea4c30)
	GOROOT/src/runtime/panic.go:522 +0x1b5
github.com/google/gapid/gapis/database.(*memory).resolvePanicHandler(0xc000252120, 0x60b1c60, 0xc000385e30)
	gapis/database/debug.go:106 +0x76e
panic(0x4acfba0, 0xc001ea4710)
	GOROOT/src/runtime/panic.go:522 +0x1b5
github.com/google/gapid/gapis/api.ForeachCmd.func1(0xc0019fbb08, 0xc0019fbb48)
	gapis/api/cmd_foreach.go:43 +0x179
panic(0x4acfba0, 0xc001ea4700)
	GOROOT/src/runtime/panic.go:522 +0x1b5
github.com/google/gapid/gapis/api/vulkan.U8ˢ.Slice(0x0, 0x0, 0x300000, 0x300000, 0xa656eb1f, 0x2ff000, 0x300400, 0x0, 0x0, 0x0, ...)
	bazel-out/k8-opt/bin/gapis/api/vulkan/api_slices.go:4024 +0x561
github.com/google/gapid/gapis/api/vulkan.subTrackVkCmdCopyImage(0x60b1c60, 0xc00165cae0, 0x6109620, 0xc001616fc0, 0xe2, 0xc001619a70, 0xc0001bde30, 0xc000150900, 0x7f537c8eabc0, 0x0, ...)
	bazel-out/k8-opt/bin/gapis/api/vulkan/mutate.go:1827 +0x740
github.com/google/gapid/gapis/api/vulkan.subDovkCmdCopyImage(0x60b1c60, 0xc00165cae0, 0x6109620, 0xc001616fc0, 0xe2, 0xc001619a70, 0xc0001bde30, 0xc000150900, 0x7f537c8eabc0, 0x0, ...)
	bazel-out/k8-opt/bin/gapis/api/vulkan/mutate.go:1851 +0x572
github.com/google/gapid/gapis/api/vulkan.subCallCommand(0x60b1c60, 0xc00165cae0, 0x6109620, 0xc001616fc0, 0xe2, 0xc001619a70, 0xc0001bde30, 0xc000150900, 0x7f537c8eabc0, 0x0, ...)
	bazel-out/k8-opt/bin/gapis/api/vulkan/mutate.go:5037 +0x574d
github.com/google/gapid/gapis/api/vulkan.subExecPendingCommands(0x60b1c60, 0xc00165cae0, 0x6109620, 0xc001616fc0, 0xe2, 0xc001619a70, 0xc0001bde30, 0xc000150900, 0x7f537c8eabc0, 0x0, ...)
	bazel-out/k8-opt/bin/gapis/api/vulkan/mutate.go:4929 +0x4c4e
github.com/google/gapid/gapis/api/vulkan.(*VkQueueSubmit).Mutate(0xc001616fc0, 0x60b1c60, 0xc00165cae0, 0xe2, 0xc0001bde30, 0x0, 0x0, 0x0, 0x0, 0x0)
	bazel-out/k8-opt/bin/gapis/api/vulkan/mutate.go:16968 +0x4e53
github.com/google/gapid/gapis/resolve.(*ContextListResolvable).Resolve.func1(0x60b1c60, 0xc00165cae0, 0xe2, 0x6109620, 0xc001616fc0, 0x0, 0x0)
	gapis/resolve/contexts.go:104 +0xaa
github.com/google/gapid/gapis/api.ForeachCmd(0x60b1c60, 0xc0002252c0, 0xc00167c000, 0xa0a, 0xe00, 0xc0019fbdb0, 0x0, 0x0)
	gapis/api/cmd_foreach.go:54 +0x264
github.com/google/gapid/gapis/resolve.(*ContextListResolvable).Resolve(0xc000385d40, 0x60b1c60, 0xc0002252c0, 0xc000385f50, 0xc0003c7f00, 0x2, 0x2)
	gapis/resolve/contexts.go:103 +0x1fa
github.com/google/gapid/gapis/database.(*record).resolve(0xc00143f440, 0x60b1c60, 0xc000385f50, 0x0, 0x0)
	gapis/database/memory.go:137 +0x222
github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1()
	gapis/database/memory.go:241 +0x134
github.com/google/gapid/core/app/crash.Go.func1(0xc000385dd0)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

**Comment by pau-baiget** [comment]
Thanks @alexfs for reporting this issue. The GAPID project has been moved to maintenance mode and therefore no active development is done in this repository.

We are focusing our efforts in Android GPU Inspector, Vulkan-based GPU profiling tool. You can check it out here: https://github.com/google/agi
