### ISSUE TITLE
The gapis server has exited with an error code of: 2

### ISSUE THREAD

**Issue by zhanglives** [google/gapid#3815]
GAPID Version: 1.6.1:338bb67b0fe291f56f31d69f11ea1a45ed7cfeb6
OS: windows 7 amd64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x7a89e0]

goroutine 38498 [running]:
github.com/google/gapid/core/app/crash/reporting.Reporter.sendReport(0x61ca461, 0x5, 0xc0000af0b0, 0x2e, 0xc0001d0140, 0x9, 0xc014e5fa64, 0x9, 0x6909440, 0xc00bab6f60, ...)
	core/app/crash/reporting/reporting.go:111 +0x4e0
github.com/google/gapid/core/app/crash/reporting.Reporter.reportStacktrace(0x61ca461, 0x5, 0xc0000af0b0, 0x2e, 0xc0001d0140, 0x9, 0xc014e5fa64, 0x9, 0xc00aee21a0, 0xd, ...)
	core/app/crash/reporting/reporting.go:133 +0x2d4
github.com/google/gapid/core/app/crash/reporting.Enable.func1(0x564ea00, 0x478d200, 0xc00aee21a0, 0xd, 0x32)
	core/app/crash/reporting/reporting.go:66 +0x1b7
github.com/google/gapid/core/app/crash.Crash.func1.1(0xc014e5fa50, 0xc0001d2400, 0x564ea00, 0x478d200, 0xc00aee21a0, 0xd, 0x32)
	core/app/crash/crash.go:84 +0x89
created by github.com/google/gapid/core/app/crash.Crash.func1
	core/app/crash/crash.go:82 +0x179
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x7a89e0]

goroutine 1703 [running]:
github.com/google/gapid/core/app/crash.Crash(0x564ea00, 0x478d200)
	core/app/crash/crash.go:89 +0xae
github.com/google/gapid/core/app/crash.handler()
	core/app/crash/crash.go:56 +0x59
panic(0x564ea00, 0x478d200)
	GOROOT/src/runtime/panic.go:522 +0x1c3
github.com/google/gapid/core/app/crash/reporting.Reporter.sendReport(0x61ca45c, 0x5, 0xc00b65c870, 0x2e, 0xc0001d0140, 0x9, 0xc0110d72d4, 0x9, 0x6909440, 0xc00b912ab0, ...)
	core/app/crash/reporting/reporting.go:111 +0x4e0
github.com/google/gapid/core/app/crash/reporting.Reporter.reportMinidump(0x61ca45c, 0x5, 0xc00b65c870, 0x2e, 0xc0001d0140, 0x9, 0xc0110d72d4, 0x9, 0xc00b65c840, 0x30, ...)
	core/app/crash/reporting/reporting.go:147 +0x2df
github.com/google/gapid/core/app/crash/reporting.ReportMinidump(...)
	core/app/crash/reporting/reporting.go:89
github.com/google/gapid/gapis/replay.(*backgroundConnection).HandleCrashDump(0xc00279f470, 0x6acca40, 0xc00279fc20, 0xc0166eddb0, 0x6af4fa0, 0xc01214a3c0, 0x0, 0x0)
	gapis/replay/replay_connection.go:119 +0x5ed
github.com/google/gapid/gapir/client.(*connection).HandleReplayCommunication(0xc01214a3c0, 0x6acca40, 0xc00279fc20, 0x6adf6a0, 0xc00279f470, 0xc00e010e40, 0x0, 0x0)
	gapir/client/connection.go:220 +0x7c7
github.com/google/gapid/gapis/replay.MakeBackgroundConnection.func1()
	gapis/replay/replay_connection.go:180 +0x162
github.com/google/gapid/core/app/crash.Go.func1(0xc01214a480)
	core/app/crash/crash.go:65 +0x4a
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x46

**Comment by zhanglives** [comment]
How to solve？ help

**Comment by pau-baiget** [comment]
Thanks @zhanglives  for reporting this issue. The GAPID project has been moved to maintenance mode and therefore no active development is done in this repository.

We are focusing our efforts in Android GPU Inspector, Vulkan-based GPU profiling and debugging tool. You can check it out here: https://github.com/google/agi
