### ISSUE TITLE
delve debug error: could not launch process

### ISSUE THREAD

**Issue by official-minister** [google/gapid#3817]
Hello, I get a error when I use delve.
system: windows 10 64-bit
goversion: go1.14.2 windows/amd64
delveversion: 1.4.0
gapid version: master branch

I build a bazel project follow by google project named "gapid". Link: https://github.com/google/gapid;
I use "bazel buid pkg" to build my project, and it's ok. I can use gapid.exe and run the process.

I want to debug process and test my project. Then I fellow the instruction:
https://github.com/google/gapid/blob/master/DEVDOC.md

When I use "dlv exec ./bazel-bin/pkg/gapis -- -enable-local-files -persist -rpc localhost:8888" in cmd, I get a error: could not launch process: decoding dwarf section info at offset 0x0: too short.

I search some solutions and someone said I should update delve. So I use "go get -u -v github.com/go-delve/delve/cmd/dlv". but still has error.

I has setted GOPATH and GOROOT. I run a simple debug process for helloword and it run well.

Then I create an issue on Delve : https://github.com/go-delve/delve/issues/2019. Someone think debug simbol is lost. 

So how can I fix it and run my debug process?

**Comment by pau-baiget** [comment]
Thanks @official-minister for reporting this issue. The GAPID project has been moved to [maintenance mode](https://github.com/google/gapid#maintenance-mode) and therefore no active development is done on this repository.

We are focusing our efforts on the Android GPU Inspector: https://github.com/google/agi
