### ISSUE TITLE
Issue with "gapid screenshot -displaytosurface "

### ISSUE THREAD

**Issue by jimmy28year** [google/gapid#3819]
[On this page](https://gapid.dev/cli/)...

gapid screenshot name.gfxtrace works and phone is black screen.

I used the -displaytosurface wchich suppose to generate render image on screen.

But the result is still black screen.

**Comment by pau-baiget** [comment]
Thanks @jimmy28year for reporting this issue. The GAPID project has been moved to [maintenance mode](https://github.com/google/gapid#maintenance-mode) and therefore no active development is done on this repository.

We are focusing our efforts on the Android GPU Inspector: https://github.com/google/agi
