### ISSUE TITLE
GAPID can't find some application this is not debuggable

### ISSUE THREAD

**Issue by hahahJoey** [google/gapid#3820]
**Environment information:**
 - GAPID version: 1.6.1
 - Host OS: Mac
 - Android Version:8.1.0

"if you have root access to the device any application can be traced."
I hava root access to my device, why GAPID can't find some application this is not debuggable?

**Comment by ShoutTree** [comment]
I met the same problem as you.
From what I found, the android should be built as "user debug" to be able to make GAPID function right.
So either you need to build an android from ASOP using "user debug" mode, or you can flash a custom distribution of "user debug" mode built by others, like lineage.

**Comment by hahahJoey** [comment]
Thanks a lot for your suggestion! I will try it.

**Comment by pau-baiget** [comment]
Thanks @hahahJoey for reporting this issue. The GAPID project has been moved to [maintenance mode](https://github.com/google/gapid#maintenance-mode) and therefore no active development is done on this repository.

We are focusing our efforts on the Android GPU Inspector: https://github.com/google/agi
