### ISSUE TITLE
Question on "trimming" of trace files

### ISSUE THREAD

**Issue by AJcodes** [google/gapid#3825]
Hi,

I'm currently trying to "trim" down an OpenGL ES Trace File, as we have a need to remove unwanted frames and focus only on frames of interest. We've tried to use `gapit trim` but ran into the error

```
Cause: Internal error: Could not build dependency graph for DCE: aborted(glErrorInvalidEnumMsg)
```

Are there any other ways to perform "trimming" via the CLI or perhaps even via C++?

Thanks,
Adel

**Comment by pau-baiget** [comment]
Thanks @AJcodes  for reporting this issue. The GAPID project has been moved to maintenance mode and therefore no active development is done on this repository.

We are focusing our efforts on the Android GPU Inspector: https://github.com/google/agi (Vulkan only).
