### ISSUE TITLE
Tracing Failed   Cause: Could not start trace   Cause: Could not find package matching com.bytedance.labcv.demo

### ISSUE THREAD

**Issue by ruoyewu** [google/gapid#3827]
GAPID Version: 1.6.0:c0b6cac1c33fab1db1a9d3938201bea8ad581b45
OS: mac os x x86_64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

**Comment by pau-baiget** [comment]
Thanks @ruoyewu for reporting this issue. The GAPID project has been moved to maintenance mode and therefore no active development is done on this repository.

We are focusing our efforts on the Android GPU Inspector: https://github.com/google/agi
