### ISSUE TITLE
Capture but end with an error

### ISSUE THREAD

**Issue by rssqian** [google/gapid#3830]
**Environment information:**
 - GAPID version:
 - Host OS: [e.g. Linux]
 If tracing on Android:
 - Device model:
 - Android Version:

**Bug description**

**Reproduction steps**

**Stacktrace**
Please paste a stacktrace here if it's available.

**Screenshots**

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux). 
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since GAPID was started.

**Comment by hevrard** [comment]
Thanks @rssqian  for reporting this issue. The GAPID project has been moved to maintenance mode and therefore no active development is done in this repository.

We are focusing our efforts in Android GPU Inspector, Vulkan-based GPU profiling and debugging tool. You can check it out here: https://github.com/google/agi
