### ISSUE TITLE
Tracing failed on Oculus Quest

### ISSUE THREAD

**Issue by rishi-rranjan** [google/gapid#3831]
**Environment information:**
 - GAPID version: 1.6.1
 - Host OS: Windows 10 Pro, Version 1909, OS Build: 18363.900
 If tracing on Android:
 - Device model: Oculus Quest
 - Android Version: 7.1.1

**Bug description**
Application on Quest crashes if launched from gapid. Trace stops after capturing 36.3 KB. 

**Reproduction steps**
Install ovr_sdk_mobile_1.34.0\VrSamples\VrCubeWorld_SurfaceView from https://developer.oculus.com/downloads/package/oculus-mobile-sdk/ and issue happens everytime. 

**Stacktrace**
Please paste a stacktrace here if it's available.

**Screenshots**
![Annotation 2020-07-01 154120](https://user-images.githubusercontent.com/5673695/86297957-7bde6780-bbb1-11ea-848c-97044f0b865b.jpg)

**Additional debugging information**
- Please attach the generated _gapis.log _ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux). 
[gapis.log](https://github.com/google/gapid/files/4861054/gapis.log)
[gapic.log](https://github.com/google/gapid/files/4861055/gapic.log)

- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since GAPID was started.
[logcat-full.txt](https://github.com/google/gapid/files/4861060/logcat-full.txt)

**Comment by charlie-ht** [comment]
Hi, have you tried https://github.com/google/agi ? It's a fork of this project focusing on Android, and might have some bug fixes for you.

**Comment by pau-baiget** [comment]
Thanks @rishi-rranjan for reporting this issue. The GAPID project has been moved to maintenance mode and therefore no active development is done on this repository.

As @charlie-ht pointed out, we are focusing our efforts on the Android GPU Inspector: https://github.com/google/agi
