### ISSUE TITLE
Can I use rpc interface from remote addr?

### ISSUE THREAD

**Issue by official-minister** [google/gapid#3832]
I have 2 machine, addr A and addr B.
I want to start gapis on A and use RPC interface on B by appointing the addr and port.
How can I do it?

I tried to use "gapis.exe -rpc A:8888" and "telnet A:8888" on B， but failed.
Thank you very much.

**Comment by AWoloszyn** [comment]
IIRC we only listen on to localhost in GAPIS.
I have done this in the past by using ssh port forwarding which works quite well.

**Comment by pmuetschard** [comment]
This should work find. Make sure that you use the public IP/name for the `-rpc` flag when launching gapis and that there is no firewall dropping packets between the hosts.
