### ISSUE TITLE
Tracing Failed   Cause: Could not start trace   Cause: Setting up the layer   Cause: settings put returned error: Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

### ISSUE THREAD

**Issue by JohnnyShu** [google/gapid#3834]
GAPID Version: 1.6.1:338bb67b0fe291f56f31d69f11ea1a45ed7cfeb6
OS: mac os x x86_64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

**Comment by hevrard** [comment]
Thanks for reporting, it looks like the device does not let GAPID set an Android permission via `adb`. If the device does not let GAPID set this permission, there is not much we can do. You may want to double-check that all device prerequisites are validated:
https://gapid.dev/trace/

More generally, the GAPID project has been moved to maintenance mode and therefore no active development is done on this repository.

We are focusing our efforts on the Android GPU Inspector: https://github.com/google/agi
