### ISSUE TITLE
The application encountered an error: The gapis server has exited with an error code of: 2

### ISSUE THREAD

**Issue by qmy1990** [google/gapid#3835]
**Environment information:**
 - GAPID version:
 - Host OS: [e.g. Linux]
 If tracing on Android:
 - Device model:
 - Android Version:

**Bug description**

**Reproduction steps**

**Stacktrace**
Please paste a stacktrace here if it's available.

**Screenshots**

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux). 
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since GAPID was started.

**Comment by hevrard** [comment]
Thanks for reporting this issue. The GAPID project has been moved to maintenance mode and therefore no active development is done on this repository.

We are focusing our efforts on the Android GPU Inspector: https://github.com/google/agi
