### ISSUE TITLE
failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)

### ISSUE THREAD

**Issue by lowest16** [google/gapid#3838]
information:
OS: Android 6.0 7.0 in Huawei
logcat:
08-26 11:34:25.550 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:117] Installing GAPII hooks...
08-26 11:34:25.552 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:147] Interceptor functions resolved
08-26 11:34:25.552 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:149] Calling gInitializeInterceptor at 0xf2fa7664...
08-26 11:34:25.552 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:154] Installing OpenGL ES hooks...
08-26 11:34:25.610 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:576] Now patch each of the functions.
08-26 11:34:25.612 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glWeightPointerOESBounds' at 0xf6a8c6f4 with 0xddeccec8
08-26 11:34:25.614 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a8c6f4 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.614 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glViewport' at 0xf6a7cfdc with 0xddecc620
08-26 11:34:25.615 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7cfdc failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.615 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glViewport' at 0xf6a8c5b0 with 0xddecc620
08-26 11:34:25.616 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a8c5b0 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.616 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glVertexPointerBounds' at 0xf6a8c5ac with 0xddecc550
08-26 11:34:25.618 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a8c5ac failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.618 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glVertexBindingDivisor' at 0xf6a7d2dc with 0xddecc3f0
08-26 11:34:25.619 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d2dc failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.619 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glVertexAttribPointer' at 0xf6a7cfd8 with 0xddecc318
08-26 11:34:25.620 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7cfd8 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.620 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glVertexAttribIPointer' at 0xf6a7d0b4 with 0xddecc250
08-26 11:34:25.621 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d0b4 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.621 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glVertexAttribIFormat' at 0xf6a7d2d4 with 0xddecc198
08-26 11:34:25.623 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d2d4 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.623 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glVertexAttribI4i' at 0xf6a7d0c0 with 0xddecbec8
08-26 11:34:25.624 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d0c0 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.624 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glVertexAttribFormat' at 0xf6a7d2d0 with 0xddecbe00
08-26 11:34:25.625 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d2d0 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.625 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glVertexAttribDivisorNV' at 0xf6a7d680 with 0xddecbd60
08-26 11:34:25.627 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d680 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.629 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glVertexAttribDivisorEXT' at 0xf6a7d4a0 with 0xddecbcc0
08-26 11:34:25.630 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d4a0 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.630 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glVertexAttribDivisorANGLE' at 0xf6a7d3e8 with 0xddecbc20
08-26 11:34:25.632 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d3e8 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.632 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glVertexAttribDivisor' at 0xf6a7d174 with 0xddecbb80
08-26 11:34:25.633 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d174 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.633 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glVertexAttribBinding' at 0xf6a7d2d8 with 0xddecbae0
08-26 11:34:25.634 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d2d8 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.634 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glVertexAttrib4fv' at 0xf6a7cfd4 with 0xddecba40
08-26 11:34:25.635 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7cfd4 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.635 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glVertexAttrib3fv' at 0xf6a7cfcc with 0xddecb8c8
08-26 11:34:25.637 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7cfcc failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.637 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glVertexAttrib2fv' at 0xf6a7cfc4 with 0xddecb764
08-26 11:34:25.638 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7cfc4 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.638 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glVertexAttrib2f' at 0xf6a7cfc0 with 0xddecb6b0
08-26 11:34:25.639 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7cfc0 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.639 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glValidateProgramPipelineEXT' at 0xf6a7d560 with 0xddecb4d8
08-26 11:34:25.640 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d560 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.641 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glValidateProgram' at 0xf6a7cfb4 with 0xddecb3b0
08-26 11:34:25.642 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7cfb4 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.642 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUseProgramStagesEXT' at 0xf6a7d55c with 0xddecb304
08-26 11:34:25.643 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d55c failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.646 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUseProgramStages' at 0xf6a7d1ec with 0xddecb258
08-26 11:34:25.647 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d1ec failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.647 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUseProgram' at 0xf6a7cfb0 with 0xddecb1c4
08-26 11:34:25.649 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7cfb0 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.649 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUnmapBufferOES' at 0xf6a7d334 with 0xddecb128
08-26 11:34:25.650 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d334 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.650 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUnmapBufferOES' at 0xf6a8c6d8 with 0xddecb128
08-26 11:34:25.651 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a8c6d8 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.651 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUnmapBuffer' at 0xf6a7d040 with 0xddecb08c
08-26 11:34:25.652 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d040 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.652 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUniformMatrix4x3fvNV' at 0xf6a7d698 with 0xddecafd4
08-26 11:34:25.654 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d698 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.654 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUniformMatrix4x3fv' at 0xf6a7d060 with 0xddecaf1c
08-26 11:34:25.655 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d060 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.655 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUniformMatrix4fv' at 0xf6a7cfac with 0xddecacf4
08-26 11:34:25.656 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7cfac failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.656 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUniformMatrix3x4fvNV' at 0xf6a7d694 with 0xddecac3c
08-26 11:34:25.657 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d694 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.658 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUniformMatrix3x4fv' at 0xf6a7d05c with 0xddecab84
08-26 11:34:25.659 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d05c failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.659 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUniformMatrix3x2fv' at 0xf6a7d050 with 0xddecaa14
08-26 11:34:25.660 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d050 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.663 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUniformMatrix2x3fvNV' at 0xf6a7d684 with 0xddeca734
08-26 11:34:25.664 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d684 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.664 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUniformBlockBinding' at 0xf6a7d120 with 0xddeca280
08-26 11:34:25.665 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d120 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.665 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUniform4ui' at 0xf6a7d0e4 with 0xddec9f5c
08-26 11:34:25.667 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d0e4 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.667 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUniform3uiv' at 0xf6a7d0f0 with 0xddec9a08
08-26 11:34:25.668 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d0f0 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.668 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUniform3iv' at 0xf6a7cf90 with 0xddec9714
08-26 11:34:25.669 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7cf90 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.669 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUniform3f' at 0xf6a7cf84 with 0xddec935c
08-26 11:34:25.670 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7cf84 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.670 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUniform3ui' at 0xf6a7d0e0 with 0xddec97c0
08-26 11:34:25.672 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d0e0 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.672 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUniform2uiv' at 0xf6a7d0ec with 0xddec92b0
08-26 11:34:25.673 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d0ec failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.673 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUniform2ui' at 0xf6a7d0dc with 0xddec9094
08-26 11:34:25.674 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d0dc failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.674 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUniform2iv' at 0xf6a7cf80 with 0xddec8fe8
08-26 11:34:25.675   461   461 I sf_frame_dur: [com.huawei.android.launcher/com.huawei.android.launcher.Launcher,53,5,6,4,0,0,1063]
08-26 11:34:25.676 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7cf80 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.677 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUniform2i' at 0xf6a7cf7c with 0xddec8dcc
08-26 11:34:25.679 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7cf7c failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.681 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUniform2fv' at 0xf6a7cf78 with 0xddec8d20
08-26 11:34:25.682 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7cf78 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.682 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUniform2f' at 0xf6a7cf74 with 0xddec8c6c
08-26 11:34:25.684 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7cf74 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.684 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUniform1uiv' at 0xf6a7d0e8 with 0xddec8bc0
08-26 11:34:25.685 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d0e8 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.685 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUniform1ui' at 0xf6a7d0d8 with 0xddec89d4
08-26 11:34:25.686 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d0d8 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.686 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUniform1i' at 0xf6a7cf6c with 0xddec873c
08-26 11:34:25.689 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7cf6c failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.689 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glUniform1f' at 0xf6a7cf64 with 0xddec85ec
08-26 11:34:25.690 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7cf64 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.691 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glTranslatex' at 0xf6a8c5a4 with 0xddec8488
08-26 11:34:25.692 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a8c5a4 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.692 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glTransformFeedbackVaryings' at 0xf6a7d0a4 with 0xddec8254
08-26 11:34:25.698 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d0a4 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.698 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glTextureViewEXT' at 0xf6a7d5e8 with 0xddec8064
08-26 11:34:25.699 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d5e8 failed: Unhandled instruction: 	pop	{r4, lr} (OpcodeId: 645)
08-26 11:34:25.699 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glTextureStorage3DEXT' at 0xf6a8c7b4 with 0xddec7f7c
08-26 11:34:25.701 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:614] Replaced function glTextureStorage3DEXT at 0xf6a8c7b4 with 0xddec7f7c (callback 0xf3395000)
08-26 11:34:25.701 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glTextureStorage2DEXT' at 0xf6a8c7b0 with 0xddec7ea4
08-26 11:34:25.702 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a8c7b0 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.702 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glTextureStorage1DEXT' at 0xf6a7d5d4 with 0xddec7ddc
08-26 11:34:25.703 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d5d4 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.703 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glTextureStorage1DEXT' at 0xf6a8c7ac with 0xddec7ddc
08-26 11:34:25.704 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a8c7ac failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.704 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glTexSubImage3D' at 0xf6a7cff4 with 0xddec7b8c
08-26 11:34:25.706 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7cff4 failed: Unhandled instruction: 	pop	{r4, r5, r6, r7, lr} (OpcodeId: 645)
08-26 11:34:25.706 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glTexSubImage2D' at 0xf6a8c598 with 0xddec7a84
08-26 11:34:25.707 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a8c598 failed: Unhandled instruction: 	pop	{r4, r5, lr} (OpcodeId: 645)
08-26 11:34:25.707 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glTexStorage3DMultisampleOES' at 0xf6a7d380 with 0xddec799c
08-26 11:34:25.709 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:614] Replaced function glTexStorage3DMultisampleOES at 0xf6a7d380 with 0xddec799c (callback 0xf3395010)
08-26 11:34:25.709 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glTexStorage3DEXT' at 0xf6a7d5d0 with 0xddec77dc
08-26 11:34:25.710 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a7d5d0 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.712 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glTexStorage3DEXT' at 0xf6a8c7a8 with 0xddec77dc
08-26 11:34:25.714 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a8c7a8 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.714 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glTexStorage2DMultisample' at 0xf6a7d2b0 with 0xddec762c
08-26 11:34:25.715 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:614] Replaced function glTexStorage2DMultisample at 0xf6a7d2b0 with 0xddec762c (callback 0xf3395020)
08-26 11:34:25.715 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glTexStorage2DEXT' at 0xf6a8c7a4 with 0xddec7564
08-26 11:34:25.717 18117 18117 W GAPID   : [gapii/cc/android/installer.cpp:93] Interceptor error: Intercepting function at 0xf6a8c7a4 failed: Unhandled instruction: 	add	r12, pc, #0, #12 (OpcodeId: 544)
08-26 11:34:25.717 18117 18117 I GAPID   : [gapii/cc/android/installer.cpp:611] Patching 'glTexStorage1DEXT' at 0xf6a8c7a0 with 0xddec73e4
.....

**Comment by pmuetschard** [comment]
We are unfortunately no longer maintaining the libinterceptor tracing mechanism. Please try the latest GAPID release. If the issue persists, please use a different/newer device. Recommended is a device with Android 10 or later, as there tracing has platform support and uses layers rather than libinterceptor.
