### ISSUE TITLE
Tracing Failed   Cause: Could not start trace   Cause: Device is not rooted

### ISSUE THREAD

**Issue by interboboy** [google/gapid#3839]
GAPID Version: 1.6.1:338bb67b0fe291f56f31d69f11ea1a45ed7cfeb6
OS: mac os x x86_64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

**Comment by pmuetschard** [comment]
You can only trace APKs that are marked [debuggable](https://developer.android.com/guide/topics/manifest/application-element#debug). See here for more info: [How to mark app as debuggable](https://stackoverflow.com/questions/2952140/android-how-to-mark-my-app-as-debuggable)
