### ISSUE TITLE
UI feels laggy

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#384]
Host: MacBook Pro (Retina, 15-inch, Mid 2015) 

Scrolling around in the command list view using the touchpad (once the commands have cached), looks like it's refreshing at ~10 FPS, with occasional noticeable 300ms+ stutters.

The janky scrolling makes tracking the items with the eye really hard and unpleasant.

**Comment by dsrbecky** [comment]
+1
Even on my desktop, scrolling feels very slow, and the whole command list quickly gets replaced by only "Loading..." texts...

**Comment by dsrbecky** [comment]
A group with just 10000 commands seems to slow down the UI on my laptop to the point it is unusable.

**Comment by ben-clayton** [comment]
Please try pulling latest and testing with https://github.com/google/gapid/pull/1063/commits/fac82c9a419bd0256e5a7c0a7269472cd5d0e365.

**Comment by dsrbecky** [comment]
That helped thanks (still slow, but usable now)

**Comment by pmuetschard** [comment]
Investigation seems to suggest this is due the use of virtual trees. Sigh. Since we already have visibility tracking, I think I can work around it.
