### ISSUE TITLE
The gapis server has exited with an error code of: 2

### ISSUE THREAD

**Issue by likebebop** [google/gapid#3848]
GAPID Version: 1.6.1:338bb67b0fe291f56f31d69f11ea1a45ed7cfeb6
OS: mac os x x86_64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 99 [running]:
github.com/google/gapid/core/app/crash.Crash(0x874f7e0, 0xeab2ce0)
	core/app/crash/crash.go:89 +0xa7
github.com/google/gapid/core/app/crash.handler()
	core/app/crash/crash.go:56 +0x52
panic(0x874f7e0, 0xeab2ce0)
	GOROOT/src/runtime/panic.go:522 +0x1b5
github.com/google/gapid/gapis/resolve/dependencygraph.(*DeadCodeElimination).propagateLiveness(0xc0099e7980, 0x9bd17c0, 0xc021b2eed0, 0xc021b2eed0, 0x0, 0x0)
	gapis/resolve/dependencygraph/dead_code_elimination.go:112 +0x896
github.com/google/gapid/gapis/resolve/dependencygraph.(*DeadCodeElimination).Flush(0xc0099e7980, 0x9bd17c0, 0xc021b2eed0, 0x9adda40, 0xc021b2e780)
	gapis/resolve/dependencygraph/dead_code_elimination.go:94 +0x116
github.com/google/gapid/gapis/api/transform.Transforms.Transform(0xc012202d00, 0x4, 0x4, 0x9bd17c0, 0xc021b2e2d0, 0xc021985938, 0x0, 0x0, 0x9ad7380, 0xc009100c00)
	gapis/api/transform/transforms.go:44 +0x30a
github.com/google/gapid/gapis/api/gles.API.Replay(0x9bd17c0, 0xc021b2e240, 0xc009ef3c20, 0xc009ef38f0, 0x874c900, 0xeb53e90, 0x0, 0x0, 0xeb53e90, 0x0, ...)
	gapis/api/gles/replay.go:296 +0x68c
github.com/google/gapid/gapis/replay.(*manager).execute.func1()
	gapis/replay/batch.go:330 +0x24e
github.com/google/gapid/core/app/benchmark.(*DurationCounter).Time(0xc000292360, 0xc021986118)
	core/app/benchmark/counter.go:163 +0x74
github.com/google/gapid/gapis/replay.(*manager).execute(0xc000139020, 0x9bd17c0, 0xc009ef3cb0, 0x9c2c060, 0xc0001f20c0, 0xf37790282a491f60, 0x379d0d8859c37ff5, 0xcaa9a049232893d4, 0x6ed085c240988dad, 0x8e20e48e0868ff85, ...)
	gapis/replay/batch.go:326 +0xd0c
github.com/google/gapid/gapis/replay.(*manager).batch.func1(0x9c2c060, 0xc0001f20c0, 0xc0219864e8, 0x40988dadcaa9a049, 0x868ff856ed085c2, 0x2a491f608e20e48e, 0x59c37ff5f3779028, 0x232893d4379d0d88, 0x874c900, 0xeb53e90, ...)
	gapis/replay/batch.go:86 +0x3fa
github.com/google/gapid/gapis/replay.(*manager).batch(0xc000139020, 0x9bd17c0, 0xc009ef38c0, 0xc0099e7560, 0x0, 0x1, 0x8ca3c00, 0x9922530, 0x8cd1e80, 0xc008d6f180, ...)
	gapis/replay/batch.go:87 +0x448
github.com/google/gapid/gapis/replay/scheduler.(*bin).exec(0xc000353100, 0x9bd17c0, 0xc0001531a0, 0xc00017e0f0)
	gapis/replay/scheduler/scheduler.go:247 +0x296
github.com/google/gapid/gapis/replay/scheduler.(*Scheduler).run(0xc000290420, 0x9bd17c0, 0xc000274210)
	gapis/replay/scheduler/scheduler.go:180 +0x428
github.com/google/gapid/gapis/replay/scheduler.New.func1()
	gapis/replay/scheduler/scheduler.go:74 +0x3c
github.com/google/gapid/core/app/crash.Go.func1(0xc000290440)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

**Comment by hevrard** [comment]
Thanks for reporting, you might want to try the latest GAPID dev-release:
https://github.com/google/gapid-dev-releases/releases

Note that most of the GAPID team now focuses on [AGI](https://github.com/google/agi)
