### ISSUE TITLE
Error during replay: "Failed to create VkInstance with validation layers and debug report extension, drop them and try again"

### ISSUE THREAD

**Issue by paulogsamsung** [google/gapid#3853]
**Environment information:**
 - GAPID version: 1.6.1
 - Host OS: Windows 10
 - Device model: Galaxy S20 5G
 - Android Version: 10

**Bug description**
The frambebuffer tab never loads for any frame and the frame preview does not display anything for frames higher than 10 on Vulkan app. The report tab shows:
_Error during replay: "Failed to create VkInstance with validation layers and debug report extension, drop them and try again"._

**Reproduction steps**
* Build Vulkan Samples for Android (https://github.com/KhronosGroup/Vulkan-Samples).
* Launch application via GAPID.
* Select Hello Triangle.
* Wait for triangle to be displayed on phone.
* Stop capture.
* Load Data.

**Screenshots**
![gapid-vulkan-hello-triangle](https://user-images.githubusercontent.com/73263411/97625030-3c038180-19e5-11eb-9217-65903df89a0d.PNG)

**Comment by hevrard** [comment]
Thanks @paulogsamsung for reporting this. In general, there is no active development on GAPID, and we recommend to switch to [AGI](https://github.com/google/agi).

Now if you want to stick with GAPID, you might want to try the latest dev-release which may well fix your issue:
https://github.com/google/gapid-dev-releases/releases/tag/v1.7.0-dev-20200211

If you still have issues with this, you can try to edit the vulkan samples source to prevent them from loading any validation layers. During a "report" replay, GAPID try and loads its own version of the validation layers, and there used to be shenanigans on handling the old multiple validation layers and/or the new unified one.

**Comment by paulogsamsung** [comment]
With the latest release the framebuffer tab does load. Thank you :)

**Comment by paulogsamsung** [comment]
Galaxy S20 5G is currently not supported by AGI, so I can't use AGI for this work.
