### ISSUE TITLE
GAPID Status initializing.... and Captured so far 0 Bytes on Huawei Phone

### ISSUE THREAD

**Issue by tshfut** [google/gapid#3860]
I try to capture trace with GAPID on Huawei phone, but it stuck on Status initializing, can someone help me with it?

**Comment by tshfut** [comment]
GAPID Version: 1.6.1

**Comment by Rowandjj** [comment]
same problem here...

**Comment by superpig** [comment]
same problem +1

**Comment by hevrard** [comment]
Thanks for reporting, there is no more active development on GAPID. We recommend, if possible, to switch to [AGI](https://github.com/google/agi) which is under active development.

If you still want to use GAPID, you can checkout its latest dev-release: https://github.com/google/gapid-dev-releases/releases/latest

**Comment by williamtrack** [comment]
same problem
