### ISSUE TITLE
Gapid has no any types ?

### ISSUE THREAD

**Issue by yujintao529** [google/gapid#3862]
**Environment information:**
 - GAPID version: 1.6.1
 - Host OS: mac os 10.15.4
 If tracing on Android:
 - Device model: android 
 - Android Version: 11

**Bug description**
![image](https://user-images.githubusercontent.com/6355153/115986265-f6192600-a5e1-11eb-801b-de91e3d316d7.png)

**Comment by hevrard** [comment]
There's no more active development on GAPID. Please checkout [AGI](https://github.com/google/agi) which is the successor project.

If you still want to use GAPID, you might want to try GAPID's latest dev-release: https://github.com/google/gapid-dev-releases/releases
