### ISSUE TITLE
Add HDR and depth range sliders

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#391]
GAPIC will automatically tonemap, which is a good start. We will want to allow the user to adjust the ranges themselves.

I have no idea how easy it would be to implement in SWT, but [a range-slider](https://www.google.co.uk/search?q=range+slider+widget&tbm=isch) would be ideal for this.

**Comment by dsrbecky** [comment]
Done?

**Comment by ben-clayton** [comment]
Yup. Thanks.
