### ISSUE TITLE
GAPIR logs some GL debug messges at too high a level.

### ISSUE THREAD

**Issue by pmuetschard** [google/gapid#400]
GL_DEBUG_SEVERITY_LOW and GL_DEBUG_SEVERITY_NOTIFICATION should be debug (they're now INFO)

maybe GL_DEBUG_SEVERITY_MEDIUM should be INFO (it's now warning)?

**Comment by dsrbecky** [comment]
I noticed this as well and fixed it a while ago.

I stand by mapping MEDIUM to WARNING though.

Spec: DEBUG_SEVERITY_MEDIUM: Severe performance warnings; GLSL or other shader compiler and linker warnings; use of currently deprecated behavior
