### ISSUE TITLE
Better GAPIC startup and handling of crashing GAPIS

### ISSUE THREAD

**Issue by pmuetschard** [google/gapid#401]
Currently, the client starts GAPIS at startup, before showing anything to the user (i.e. before even creating the main window). For people that don't use the command line, this results int multiple seconds where "nothing is happening".

GAPIC also becomes completely unusable if GAPIS crashes, instead it should give the user the option to try and restart GAPIS and try again, or restart GAPIS and "close" the current trace.

GAPIC needs a UI to allow the user to connect to a remote GAPIS, this can currently only be done via command line flags.

**Comment by ben-clayton** [comment]
Dropping priority, as I'm not sure that restarting GAPIS is going to help much - if it crashed once, it's likely to crash immediately again.
