### ISSUE TITLE
The capture save action needs to either call a SaveCapture RPC or get the bytes as a stream

### ISSUE THREAD

**Issue by pmuetschard** [google/gapid#403]
There's [a TODO](https://github.com/google/gapid/blob/master/gapic/src/main/com/google/gapid/models/Capture.java#L133) in the capture model.

**Comment by AWoloszyn** [comment]
The RPC as it stands will fail for traces > 2GB.

**Comment by AWoloszyn** [comment]
We now have a SaveCapture RPC, we should probably be using it in these cases.
