### ISSUE TITLE
gapis crashed on win10

### ISSUE THREAD

**Issue by awsb322** [google/gapid#414]
I have 3 win10 devices, while gapis crashed on 2 of them. Here is the log:

E:\gapid\debug\java>java -jar gapic-windows.jar
I20170520-092903219[main][server.GapiPaths.checkForTools] Looking for GAPID in C:\Users\Soara\gapid -> C:\Users\Soara\gapid\windows\x86_64\gapis.exe
I20170520-092903247[main][server.GapiPaths.checkForTools] Looking for GAPID in C:\Users\Soara\gapid\pkg -> C:\Users\Soara\gapid\pkg\windows\x86_64\gapis.exe
I20170520-092903577[server.ChildProcess-gapis][server.ChildProcess.runProcess] Starting gapis as [C:\Users\Soara\gapid\pkg\windows\x86_64\gapis.exe, -log-file, C:\Users\Soara\AppData\Local\Temp\gapis.log, -log-level, Info, -gapir-args, --log C:\Users\Soara\AppData\Local\Temp\gapir.log --log-level I, --strings, C:\Users\Soara\gapid\pkg\strings, --gapis-auth-token, n2qM1wUH]
W20170520-092905945[server.ChildProcess-gapis][server.ChildProcess.onExit] The gapis process exited with a non-zero exit value: -1073741701
I20170520-092905945[server.ChildProcess-gapis][server.ChildProcess.shutdown] Shutting down gapis
W20170520-092905945[main][server.GapisProcess.connect] Failed while waiting for gapis
W20170520-092905945[main][server.GapisProcess.connect] java.util.concurrent.ExecutionException: java.lang.Exception: gapis has exited
W20170520-092905945[main][server.GapisProcess.connect]  at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500)
W20170520-092905945[main][server.GapisProcess.connect]  at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:401)
W20170520-092905945[main][server.GapisProcess.connect]  at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83)
W20170520-092905945[main][server.GapisProcess.connect]  at com.google.gapid.server.GapisProcess.connect(GapisProcess.java:135)
W20170520-092905945[main][server.GapisProcess.connect]  at com.google.gapid.Server.createConnection(Server.java:123)
W20170520-092905945[main][server.GapisProcess.connect]  at com.google.gapid.Server.connectToServer(Server.java:102)
W20170520-092905945[main][server.GapisProcess.connect]  at com.google.gapid.Server.connect(Server.java:74)
W20170520-092905945[main][server.GapisProcess.connect]  at com.google.gapid.Main.main(Main.java:59)
W20170520-092905945[main][server.GapisProcess.connect] Caused by: java.lang.Exception: gapis has exited
W20170520-092905945[main][server.GapisProcess.connect]  at com.google.gapid.server.ChildProcess.runProcess(ChildProcess.java:95)
W20170520-092905945[main][server.GapisProcess.connect]  at com.google.gapid.server.ChildProcess$1.run(ChildProcess.java:66)
Exception in thread "main" com.google.gapid.Server$GapisInitException: Failed to connect to the graphics debugger
        at com.google.gapid.Server.connectToServer(Server.java:104)
        at com.google.gapid.Server.connect(Server.java:74)
        at com.google.gapid.Main.main(Main.java:59)

**Comment by AWoloszyn** [comment]
Does
"./do run gapic"  fail in the same way as java -jar gapic-windows.jar.

From what I can find "-1073741701" refers to Windows not being able to find the right dependencies for the application. "./do run gapic" should take care of setting up your path for the dependencies to be found.

If you copies the executables from another machine, you may also have to bring across some of the mingw  dlls into the same directory as gapis. See #17 for more information.

**Comment by awsb322** [comment]
Thanks. 
#17 fixed this issue.
