### ISSUE TITLE
gapir tends to crash in driver due to 0xbadf00d pointers.

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#421]
If any pointer argument is unhanded (e.g. missing observation or remapping), gapir tends to crash inside driver.  Due to inability to debug gapir, this category of errors tends to consume a lot of time just to track down.  Is it possible to catch the problem earlier in gapis and panic there?

**Comment by ben-clayton** [comment]
> Is it possible to catch the problem earlier in gapis and panic there?

Not really, there are the odd functions that take a pointer that is not observed - this is can happen if there's an API that takes a pointer and a zero count. In this case, `0xbadf00d` ensures the real driver doesn't unexpectedly load that address.

The label logic was added just for this reason - so you can tell the `atom.ID` which caused the crash. It's possible this is only displayed with high verbosity. Do you have any suggestions for improving this further?

**Comment by dsrbecky** [comment]
> API that takes a pointer and a zero count

Bummer.  I suppose we could allow zero-sized observations, but I realize that might be non-trivial and have its own quirks.  Oh well...
