### ISSUE TITLE
Ability to pass additional flags to gapit from GAPIC.

### ISSUE THREAD

**Issue by AWoloszyn** [google/gapid#429]
Allowing users to specify additional flags to gapi from the UI.
This is a convenience to allow users to get the additional functionality of gapit without them having to find the gapit executable, and run it from the command-line.

Seems to make sense to make this either a hidden "advanced" section, or enabled by a command-line flag to gapic.

**Comment by ben-clayton** [comment]
Another candidate for the new settings panel.
