### ISSUE TITLE
Gapit does not accept verbose log-level

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#434]
It is not one of the valid values... (?)

**Comment by AWoloszyn** [comment]
Not sure if this WAI.
From "gapit help info"
Debug seems equivalent to "Verbose" to me. Do we support Verbose anywhere else? I thought logging was handled the same everywhere.
```
-log-level value
    	The severity to enable logs at [one of: "Debug", "Info", "Warning", "Error", "Fatal"] (default Info)
```

**Comment by ben-clayton** [comment]
[Probably just missing from this line.](https://github.com/google/gapid/blob/master/core/log/severity.go#L82)
