### ISSUE TITLE
Gapit dump with observations data and replay is not working for Vulkan

### ISSUE THREAD

**Issue by Qining** [google/gapid#439]
The problem is all the dispatchable handles in Vulkan are read/written as Uint64.

In memory/read.go line 48.
When the type is a dispatchable Vulkan handle, for example, VkQueue, the TypeOf VkQueue is not equal to reflect.TypeOf(Size(0)). This means all the dispatchable handles are processed in the default branch below and are considered as Uint64.

The problem is in the commit: 9e4444f97fe8011404e554878d05fd8aefaf3875

**Comment by ben-clayton** [comment]
Sorry for the bug. The simplest fix would be to annotate the memory types with a private dummy function:

```go
func (Size) isSize() {}
```

And then test for this private function via an interface:

```
// IsSize returns true if v is a Size or alias to a Size.
func IsSize(v interface{}) {
    _, ok := v.(type interface{ isSize() })
    return ok
}
```

`IsSize` can just be inlined where ever we check for `tySize`

**Comment by ben-clayton** [comment]
Updated the comment above once I remembered that type aliases don't adopt the aliasee's functions.
