### ISSUE TITLE
Panic in gapis

### ISSUE THREAD

**Issue by ek9852** [google/gapid#445]
Environment: MBP
Version: main truck @ adf1817a26839e81b45c440785c67283f9033890 (May 26 2017)
Log:
panic: runtime error: index out of range
  panic: runtime error: index out of range

goroutine 3928 [running]:
github.com/google/gapid/gapis/resolve.(*CommandTreeResolvable).Resolve.func3(0xbbd41, 0x1)
        /Users/ggl/go/src/github.com/google/gapid/gapis/resolve/command_tree.go:290 +0xca
github.com/google/gapid/gapis/atom.(*Group).AddAtoms.func1(0xbbd42)
        /Users/ggl/go/src/github.com/google/gapid/gapis/atom/group.go:315 +0x72
github.com/google/gapid/gapis/atom.(*Group).AddAtoms(0xc44efae8c0, 0xc420113ef0, 0x7d0, 0xc463c95460, 0x0)
        /Users/ggl/go/src/github.com/google/gapid/gapis/atom/group.go:339 +0x164
github.com/google/gapid/gapis/atom.(*Group).AddAtoms(0xc44efae580, 0xc420113ef0, 0x7d0, 0xc463c95370, 0x0)
        /Users/ggl/go/src/github.com/google/gapid/gapis/atom/group.go:334 +0x404
github.com/google/gapid/gapis/atom.(*Group).AddAtoms(0xc44efae440, 0xc420113ef0, 0x7d0, 0xc463c95290, 0x0)
        /Users/ggl/go/src/github.com/google/gapid/gapis/atom/group.go:334 +0x404
github.com/google/gapid/gapis/atom.(*Group).AddAtoms(0xc44efae340, 0xc420113ef0, 0x7d0, 0xc44efae2c0, 0x0)
        /Users/ggl/go/src/github.com/google/gapid/gapis/atom/group.go:334 +0x404
github.com/google/gapid/gapis/atom.(*Group).AddAtoms(0xc47b2bc7c8, 0xc420113ef0, 0x7d0, 0xc47b2bc7c0, 0xbbd41)
        /Users/ggl/go/src/github.com/google/gapid/gapis/atom/group.go:334 +0x404
github.com/google/gapid/gapis/resolve.(*CommandTreeResolvable).Resolve(0xc44e879730, 0x6b36860, 0xc42a0e9410, 0x11c29348, 0xc44e879730, 0x1, 0x6b112e0)
        /Users/ggl/go/src/github.com/google/gapid/gapis/resolve/command_tree.go:293 +0x6e2
github.com/google/gapid/gapis/database.(*record).resolve(0xc42709e7b0, 0x6b367a0, 0xc4798675c0, 0xc45a032300, 0xc42a0e8de0)
        /Users/ggl/go/src/github.com/google/gapid/gapis/database/memory.go:72 +0x8a
github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1(0xc42709e7b0, 0xc479867600, 0xc420334080)
        /Users/ggl/go/src/github.com/google/gapid/gapis/database/memory.go:144 +0x45
created by github.com/google/gapid/gapis/database.(*memory).resolveLocked
        /Users/ggl/go/src/github.com/google/gapid/gapis/database/memory.go:151 +0x4ff

**Comment by ben-clayton** [comment]
Hi @ek9852 - I've tried to reproduce this panic, but I think its only triggered under certain circumstances. Do you have any reproduction steps, or a particular trace that exhibits this behaviour?

**Comment by ek9852** [comment]
Just use on any Unity game will trigger this. I attached a sample gfxtrace in google drive for your convenience.  gapis panic when you try to open that file.
https://drive.google.com/open?id=0B0S0_4EgiFmcTWFkN0FzR0RHUkE

**Comment by ben-clayton** [comment]
Thank you for the provided trace. Fix up for review.
