### ISSUE TITLE
Weird layout of framebuffer buttons

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#448]
![gapic-overflow](https://cloud.githubusercontent.com/assets/11505236/26575197/1b18fcd0-451c-11e7-9a5a-2f6e708eb45b.png)

**Comment by pmuetschard** [comment]
This is a strange, strange SWT/Windows UI bug.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=517480

I will implement some hacky work around :(
