### ISSUE TITLE
Mouse wheel only affects command tree or state tree

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#453]
Attempting to use the mouse wheel to zoom textures, zoom geometry or scroll through the filmstrip always affects the last used tree view. It's as if these other views cannot gain focus.

**Comment by pmuetschard** [comment]
I cannot reproduce this - I know I saw it happening on your screen, but this is not happening on my windows machine. Can you try this again at head and let me know if there's anything special about the setup?

**Comment by ben-clayton** [comment]
Happens quite reliably on both my Win7 machines. What version of windows are you running?

**Comment by pmuetschard** [comment]
OK. I see. I currently only have access to win 10 machines. I'll look into reproducing using a vm or ...

**Comment by ben-clayton** [comment]
I'll look to dual-booting one of my machines, I could do with testing on Win10.
