### ISSUE TITLE
Use fixed-size names in memory view

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#461]
`Bytes`, `Shorts`, `Ints` are all very Java-centric and are effectively meaningless to most C/C++ applications. Let's use `Int8`, `Int16`, `Int32`, `Float32` etc.

**Comment by pmuetschard** [comment]
They are GL-centric, OK!? ;)

GL_UNSIGNED_BYTE, GL_UNSIGNED_SHORT, GL_UNSIGNED_INT, GL_FLOAT

**Comment by ben-clayton** [comment]
Fair point. ;)
