### ISSUE TITLE
Fix command searching

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#464]
I can not search the command tree.  I assume this has not been implemented yet?

**Comment by ben-clayton** [comment]
I'm also seeing odd / broken behavior here,

**Comment by pmuetschard** [comment]
I need a bit more information here, as it's working for me. What odd / broken behavior are you seeing? What is the search query you are searching on what trace?

**Comment by ben-clayton** [comment]
Let's see if we can find a simple repro together when you're here.

**Comment by ben-clayton** [comment]
Some things we discovered while debugging:
* Hitting enter once in the search box appears to trigger two searches simultaneously.
* The two-search resolves can cause a command tree node to fail to load.
* Once the command tree node fails to load, the search never gets past that node.
* Clicking one past that node lets searching work again.
* Clicking on the magnifying glass does a single search and all works as expected.
