### ISSUE TITLE
ADB devices missing from getDevices()

### ISSUE THREAD

**Issue by pmuetschard** [google/gapid#478]
When launching GAPID from Finder, gapis doesn't return adb devices. Launching from terminal is OK.

To reproduce:
1. Download .dmg image from kokoro macos release build.
2. Open the dmg and drag GAPID to Applications.
3. `vi /Applications/GAPID.app/Contents/MacOS/gapid` and add `-logLevel ALL` just before the `$@` on the last line.
4. Launch GAPID from finder with a phone attached and open the trace dialog.
5. Observe that no device shows up in the dropdown.
6. Close the dialog and look at the log tab, only one device (the local host) is returned and then queried: look at the RPC->get(device ...) calls.
7. Close and re-launch the app from the terminal with `/Applications/GAPID.app/Contents/MacOS/gapid`.
8. Again, open the trace dialog.
9. Observe that the OS asks to allow incoming connections to gapis (unlike when launching from finder) - Don't know if this is a red herring.
10. Observe in the log that 2 calls to RPC->get(device...) are made.

**Comment by ben-clayton** [comment]
OSX has two different environments - one for the command line, one for launcher.
I'm guessing that your launcher environment doesn't contain a PATH for adb.

**Comment by ben-clayton** [comment]
[Relevant link.](https://stackoverflow.com/questions/25385934/setting-environment-variables-via-launchd-conf-no-longer-works-in-os-x-yosemite)

**Comment by ben-clayton** [comment]
I'd argue that may be a duplicate of #14 - we need a setting panel that lets you specify where ADB lives, and clearly warn if ADB cannot be found.

If you rely on PATH, [you're gonna have a bad time](https://www.google.co.uk/search?q=you%27re+gonna+to+have+a+bad+time&tbm=isch).

**Comment by pmuetschard** [comment]
fixed in #593
