### ISSUE TITLE
gapis panic

### ISSUE THREAD

**Issue by ek9852** [google/gapid#479]
gapis panic
Target: Pixel XL, Qualcomm chipset
Reproducible : yes, when select command 317440. Not sure panic triggered by background thread or by user click action.
Gfxtrace: https://drive.google.com/open?id=0B0S0_4EgiFmcTWdvLTlJMmdKcEU

Log:
panic: runtime error: invalid memory address or nil pointer dereference
  panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4970df1]

goroutine 180020 [running]:
github.com/google/gapid/gapis/gfxapi/gles.subApplyDynamicContextState(0x6c8e8e0, 0xc52746e900, 0x6c91880, 0xc4207aca80, 0x0, 0xc480eae8a0, 0xc4acd0ff40, 0x0, 0xc456fd3c00, 0xc420b6a030, ...)
	/Users/ggl/go/src/github.com/google/gapid/gapis/gfxapi/gles/mutate.go:5641 +0x181
github.com/google/gapid/gapis/gfxapi/gles.(*EglMakeCurrent).mutate(0xc4207aca80, 0x6c8e8e0, 0xc52746e900, 0xc480eae8a0, 0x0, 0x2fed2c7f90f72f97, 0xc4a64d1c60)
	/Users/ggl/go/src/github.com/google/gapid/gapis/gfxapi/gles/mutate.go:18016 +0x3f0
github.com/google/gapid/gapis/gfxapi/gles.(*EglMakeCurrent).Mutate(0xc4207aca80, 0x6c8e8e0, 0xc52746e900, 0xc480eae8a0, 0x0, 0x0, 0x0)
	/Users/ggl/go/src/github.com/google/gapid/gapis/gfxapi/gles/custom_replay.go:269 +0x14d
github.com/google/gapid/gapis/resolve.Memory(0x6c8e8e0, 0xc52746e900, 0xc52746e4e0, 0xc4fc49ae68, 0x4010943, 0x597bae0)
	/Users/ggl/go/src/github.com/google/gapid/gapis/resolve/memory.go:44 +0x198
github.com/google/gapid/gapis/resolve.ResolveInternal(0x6c8e8e0, 0xc52746e8a0, 0x6c8f420, 0xc52746e4e0, 0x585ee40, 0xc452376618, 0x6c8f420, 0xc52746e4e0)
	/Users/ggl/go/src/github.com/google/gapid/gapis/resolve/resolve.go:250 +0x9b0
github.com/google/gapid/gapis/resolve.ResolveService(0x6c8e8e0, 0xc52746e8a0, 0x6c8f420, 0xc52746e4e0, 0xc52746e8a0, 0x59dce60, 0x1, 0x6c64760)
	/Users/ggl/go/src/github.com/google/gapid/gapis/resolve/resolve.go:203 +0x4d
github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve(0xc452376630, 0x6c8e8e0, 0xc52746e8a0, 0x6c64760, 0xc452376630, 0x1, 0x6c692e0)
	/Users/ggl/go/src/github.com/google/gapid/gapis/resolve/get.go:35 +0xa9
github.com/google/gapid/gapis/database.(*record).resolve(0xc52746e840, 0x6c8e820, 0xc4acd0fe40, 0xc4e613fc00, 0xc52746e480)
	/Users/ggl/go/src/github.com/google/gapid/gapis/database/memory.go:72 +0x8a
github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1(0xc52746e840, 0xc4acd0fe80, 0xc420371f00)
	/Users/ggl/go/src/github.com/google/gapid/gapis/database/memory.go:144 +0x45
created by github.com/google/gapid/gapis/database.(*memory).resolveLocked
	/Users/ggl/go/src/github.com/google/gapid/gapis/database/memory.go:151 +0x4ff

**Comment by ek9852** [comment]
BTW, using latest code May 31 @0d665517597c02f770a2713c8c3a324347a86b30

**Comment by ben-clayton** [comment]
I also encountered this very same panic tonight.

**Comment by ben-clayton** [comment]
After 12 hours of debugging (and @pmuetschard actually guessing the issue 3 hours ago, which I stupidly ruled out), I've figured out the cause of this - it's request cancellations, that aren't being respected by the state mutator.
Now I know the problem, I can write a fix...
