### ISSUE TITLE
Remove switchThread calls from the command view.

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#482]
They really make the command view difficult to navigate when looking at the all-contexts view.

If we add threadID to each atom, then we can share this information with the client, and optionally color the commands by thread / context.

**Comment by dsrbecky** [comment]
Ultimately, the visualization is difficult in the all-contexts view, as the groupings either get in the way, or are not guaranteed to work.  I was thinking of possibly relaxing the "in capture order" constraint and grouping things from different things from different contexts together.  Basically I was thinking of making dependency DAG of all commands and then fattening that to a list.  Having said that, flat list and colours sounds simpler.

**Comment by dsrbecky** [comment]
Another option is to just abandon the all-contexts view.  Too extreme? :-)

**Comment by ben-clayton** [comment]
Fixed by https://github.com/google/gapid/commit/bf926c1f59069bf1a1a54bf040d18dabb16fd6d7
