### ISSUE TITLE
Using vcvars64.bat breaks the build

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#494]
It pulls in environment variables that makes CMake pick the wrong libraries.
`do` should be cleaning up the environment so that external vars don't break the build, but something is creeping in. 
Investigate and fix.

**Comment by pmuetschard** [comment]
I ran `vcvarsall.bat`, which did indeed cause the build to pick up the wrong OpenGL libs.
I then cleared `%LIB%` and `%LIBPATH%` and the build picked up the correct libraries and was fine.
Steps:
```
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

gapid>"c:\Program Files (x86)\Visual Studio\VC\vcvarsall.bat"
gapid>set LIB=
gapid>set LIBPATH=
gapid>do clean
gapid>do build
```
