### ISSUE TITLE
glGenXXX functions can corrupt default objects.

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#498]
As discussed in #492, there's an unusual case where `glGenXXX` functions can corrupt the default objects (0) if the pointer read returns 0.

In #492, this happened due to a context cancellation - but this can also occur if the user modifies the pointer or memory.

I believe that if #18 is fixed, then this becomes a non-issue, as the `glGenXXX` functions shouldn't actually touch the underlying object.

Given that context cancellation should now stop state mutation, I'm giving this a low priority.

**Comment by ben-clayton** [comment]
I think this has been fixed. @dsrbecky can you please confirm?

**Comment by dsrbecky** [comment]
Fixed by #544
