### ISSUE TITLE
GAPID config issue

### ISSUE THREAD

**Issue by ZephyroalJC** [google/gapid#502]
Hi there,

I'm using Mac Sierra 10.12.5, and all the requested software already installed.
But after I "**go get github.com/google/gapid**", 
I try to use "**./do config**",
but it stuck on " **• Build flavor. One of: release, debug [Default: release]"**
with no error message, anyone can help?
Thanks a lot!

BR,
Zephyr

**Comment by ZephyroalJC** [comment]
Sorry, I didn't notice the debug/release choice...

**Comment by ben-clayton** [comment]
It is waiting for input - you can either:
1) Type `debug` and press enter for a debug build.
2) Type `release` and press enter for a release build.
3) Press enter for the default (initially `release`, then whatever to picked last time.
