### ISSUE TITLE
gapis crash in decoding Vulkan structs

### ISSUE THREAD

**Issue by Qining** [google/gapid#522]
Crash is observed in multiple places:
* decoding VkBufferCreateInfo
* decoding VkMemoryAllocateInfo
etc.

> panic: ConsumeBytes(4): context canceled
> goroutine 3173 [running]:
> github.com/google/gapid/core/data/binary.ConsumeBytes(0x391aca0, 0xc4215da7c0, 0x4, 0x5)

**Comment by ben-clayton** [comment]
We need to return an error instead of panicing. This is just lazy error handling.

**Comment by Qining** [comment]
So I should have it return error in ConsumeBytes()?

**Comment by ben-clayton** [comment]
Actually the reader holds the error state and the only caller ignores the return value, so the simplest change would be:

```go
// ConsumeBytes reads and throws away a number of bytes from r.
func ConsumeBytes(r Reader, bytes uint64) {
	for i := uint64(0); i < bytes; i++ {
		r.Uint8()
	}
}
```
