### ISSUE TITLE
Is there a way to get an application that can run directly without having to build it

### ISSUE THREAD

**Issue by cxy200927099** [google/gapid#523]
* environment
macOS 10.12.4

* I follow the "BUILDING.md" to do, when i excute:
```
go get github.com/google/gapid
```
after waiting about half-hour, then i get the error:
```
# cd .; git clone https://github.com/google/gapid /Users/chenxingyi/work/go/src/github.com/google/gapid
Cloning into '/Users/chenxingyi/work/go/src/github.com/google/gapid'...
error: RPC failed; curl 56 SSLRead() return error -9806
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
package github.com/google/gapid: exit status 128
```
* So i go to the go path:
```cd /Users/chenxingyi/work/go/src/github.com/google/```
and i use git clone command to clone the source, after done i excute
```
cd gapid
./do config
 ```
then i get the error:

```core/app/run.go:27:2: no buildable Go source files in /Users/chenxingyi/work/go/src/github.com/google/gapid/third_party/src/github.com/pkg/errors```
when i excute the ```./do build```; i also get the same error!!!!

anybody can help me or is there a way get the excuteable application without to build the source!
thank you!

**Comment by pmuetschard** [comment]
If you use `git clone`, you will also need to do a `git submodule update --init` inside the `google/gapid` directory.

We're close to providing prebuilts, but we're not quite ready yet. We expect to be able to provide binaries for Windows / macOS / Linux in the next couple of weeks. If you're keen to get binaries before then, please PM me or @ben-clayton on [gitter](https://gitter.im/google/gapid) with a contact email where we can try to get you a build for the OS of your choice in the next day or so.

**Comment by cxy200927099** [comment]
thank you for replay, i have PM you and @ben-clayton on gitter with my email,Please check and give me binaries of the gapid for macOS thank you

**Comment by cxy200927099** [comment]
Hi @ben-clayton, I have asked you for the third time to get gapid binaries for macOS, But you never response to me, do you mean a joke about gapid binaries?

**Comment by ben-clayton** [comment]
Replied on gitter.
