### ISSUE TITLE
We need proper return statement in the API

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#536]
The lack of return statements makes many things in the API impossible to expresses (i.e. I have not even found feasible work-around).

**Comment by dsrbecky** [comment]
This one on the other hand fairly hurts.

**Comment by ben-clayton** [comment]
IIRC the main reason we don't allow mid-execution returns was due to macros.
While there'll be a fair amount of work getting analysis stages to handle MER, I don't think there's a justifiable reason not to add them.

I'll give this a try.
