### ISSUE TITLE
Error when build test

### ISSUE THREAD

**Issue by xzwszl** [google/gapid#538]
RAN: /XXX/gapid/release/test/test-test-robot-stash-grpc
GOT: --- FAIL: TestMemoryAndGrpcStash (2.58s)
	testing.go:39: 16:28:06.231 Info: Starting grpc server
	assertion.go:248: Error:lookup
		    Got       0
		    Expect == 17
	assertion.go:248: Error:open
		    Got     ⦕entity not ready⦖
		    Expect  success

CMake Error at /XXX/go/src/github.com/google/gapid/cmake/Modules/GoTest.cmake:25 (message):
  RESULT: 2

**Comment by ben-clayton** [comment]
I've also seen this issue on occasion - it's a flakey test. I'll look to fix it.

**Comment by ben-clayton** [comment]
Fixed by #1036
