### ISSUE TITLE
GAPIS: Failed to connect to the graphics debugger

### ISSUE THREAD

**Issue by CoderDawson** [google/gapid#540]
After building locally and attempting to execute `do run gapic` I receive the following error:

```
Exception in thread "main" com.google.gapid.Server$GapisInitException: Failed to connect to the graphics debugger
        at com.google.gapid.Server.connectToServer(Server.java:93)
        at com.google.gapid.Server.connect(Server.java:65)
        at com.google.gapid.Main.main(Main.java:61)
Error running C:\Program Files\Java\jdk1.8.0_102\bin\java.exe [-jar C:\Tools\gapid\release\java\gapic-windows.jar -gapid C:\Tools\gapid\release\pkg]: Process returned error
   Cause: exit status 1
exit status 1
```

I have attached the console output as well as the gapic.log (largely the same).

[do_run_gapic_output.txt](https://github.com/google/gapid/files/1062095/do_run_gapic_output.txt)
[gapic_log.txt](https://github.com/google/gapid/files/1062099/gapic_log.txt)

**Comment by ben-clayton** [comment]
Hi @CoderDawson - I suspect the server is closing after a timeout. Please can you try adding some zeros to the [magic constant on this line](https://github.com/google/gapid/blob/master/gapic/src/main/com/google/gapid/server/GapisProcess.java#L52)?

**Comment by ben-clayton** [comment]
Actually scratch that - this is a major bug.

@pmuetschard - see gapic_log - the client is passing "-adb" without the value, and gapis is erroring.
