### ISSUE TITLE
Fix error message for direct pointer access

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#541]
ptr[1] = ....   fails with "type u64 not valid slicing pointer"
We generally work around the bug by slicing the pointer first.

**Comment by ben-clayton** [comment]
Please can I have a bit more code context? I'm not confident I know the exact issue.

**Comment by dsrbecky** [comment]
cmd void glGenBuffers(GLsizei count, BufferId* buffers) {
  if count < 0 { glErrorInvalidValue() }
  b := buffers[0:count]
  ctx := GetContext()
  for i in (0 .. count) {
    id := as!BufferId(?)
    assert(id != 0)
    ctx.Objects.Shared.GeneratedNames.Buffers[id] = true
    b[i] = id // Why not just buffers[i] = id?
  }
}

**Comment by ben-clayton** [comment]
I see. 

> We generally work around the bug by slicing the pointer first.

Actually this is a conscious design decision as nearly all (if not all?) parameter arrays have a known upper bound, and this forces you to specify it. Without the slice step, it's far easier to accidentally buffer overrun / underrun. By removing raw pointer offsets I caught quite a few issues with this in early development of GAPID.

Does the extra slice step really hurt? @AWoloszyn, any thoughts on this?

**Comment by dsrbecky** [comment]
It does not hurt that much, but I find it odd - at the very least the error message is odd.

**Comment by ben-clayton** [comment]
> at the very least the error message is odd.

Agreed. I'm more than happy to fix that.

**Comment by AWoloszyn** [comment]
I do prefer the explicitly sized slices for things.
The extra slice is a bit cumbersome, but most of the time I have not been annoyed with it.
