### ISSUE TITLE
Try harder to prevent people git cloning the project.

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#55]
We've had a couple of people ask why the build fails.

Turns out they `git cloned` the project instead of using `go get`. `go get` forces the developer to checkout into `../github.com/google/gapid/` which is expected by `do`.

Let's:
* Make it more obvious in [BUILDING.md](https://github.com/google/gapid/blob/master/BUILDING.md)
* Try detecting a bad checkout and giving a sensible error message from `do`

**Comment by mrkane27** [comment]
Can `do` detect where it's being run from and issue an error and/or offer to move itself?

**Comment by ben-clayton** [comment]
Detecting that it sit in a directory structure of `github.com/google/gapid` is certainly possible.
Moving, probably not. Windows likes to lock files when they are executed, and I believe this includes batch files.

**Comment by ianthehat** [comment]
Note that if we decide to switch to bazel, it does not care where it is checked out, and does not use the go path in any way.
It's still a good idea to have it in the right structure so that go tooling (goimports and govet specifically) still work though
