### ISSUE TITLE
Last used link gets followed again when changing commands

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#606]
I click on a parameter link.
Then I collapse all state just for good measure.
I click on a different command.
The link gets followed again and state expands.

**Comment by pmuetschard** [comment]
I have fixed the main issue where user selections were not remembered, only link followed selections.
I have made the code ready to exactly do what it sounds like you want - by passing false for the ```reveal``` parameter when setting the selection. However, the UI frameworks don't actually support selecting a node that is not visible (any of its ancestors are not expanded) and ignore the reveal value. Thus, if you just collapse the tree, it will get re-expanded when you select another atom. A work around is not really possible as the selection gets lost when the tree is collapsed.

I think this is OK for now, so I'm removing it from the milestone. Please let me know what  you think and we can either find another fix or close the bug.

**Comment by dsrbecky** [comment]
As it is, it still messes up the state view when clicking on next command.
I would be happy to just lose selection in the set of circumstances, or select a node whenever it is collapsed (that would help, right?)

I will settle for the state being somewhat preserved, the thing that I really want is #607 :-)  (I expanded it a bit now)
