### ISSUE TITLE
State view changes a lot when clicking on subsequent commands

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#607]
The state view scrolls back to the top whenever a command is clicked, all lines change to "Loading", which results is "flashing", and we seem to be fighting the UI framework on other things as well.  IMHO, clicking on subsequent commands should not have visual effect on the state view, other then changing the fields that differ.

I sympathise with the struggle.  I have tried to do this several times in the past with different UI frameworks, and it is always a great pain. (usually it was local variables pad in debugger, and I wanted to keep it "stable" while stepping over code while variables came in/out of scope, array items were added, etc... )

The only thing that reliably worked for me in the past was updating the tree in-pace, rather than clearing it and then restoring state.  That is, removed nodes should be deleted, new nodes should be added, but the instances of remaining nodes should be kept (with their value potentially being updated).  This should preserve the expansion, selection, and scroll state with no extra work, it doesn't flash, etc.... Basically, if the state before and after doesn't change, the UI doesn't change, and there are no modifying calls to the UI framework.

The only challenge is implementing the recursive node update function.  It is great pain if the keys are not unique, but I think we are lucky and field names should work as unique keys for us.  I think I also usually made each depth level async which is a bit of extra fun to deal with...

PS: I also usually had some form of "Loading" placeholder (I went for animating to grey, but it is the same effect), but I usually delayed it by a second so that for 99% of cases when the server is fast, there is no flashing.  I mm not sure how tricky it is to implement in Java?

PPS: I also liked to change the colour of fields that have changed in value.  That makes sense when stepping in debugger, but it probably makes less sense for us?

**Comment by ben-clayton** [comment]
State view no longer jumps to top, but text does flash.

**Comment by AWoloszyn** [comment]
We do end up in the same place in the state view, so this is probably too low on the priority list to get dealt with any time soon.
