### ISSUE TITLE
gapis panic: Unsupported input format-type pair

### ISSUE THREAD

**Issue by ek9852** [google/gapid#620]
![image](https://user-images.githubusercontent.com/6452203/27274143-06e453c0-5487-11e7-9818-a041d477c297.png)

Select to frame 186
Log:
[log.zip](https://github.com/google/gapid/files/1084138/log.zip)

**Comment by ben-clayton** [comment]
This is the shared exponent texture format:
[Extension](http://developer.download.nvidia.com/opengl/specs/GL_EXT_texture_shared_exponent.txt)

**Comment by ben-clayton** [comment]
I'll have a stab at implementing this - @ek9852 are you able to share a `.gfxtrace` file that uses this format? You can send me a link to my email if that's preferable.

Thanks

**Comment by ben-clayton** [comment]
Duplicate: #239

**Comment by ek9852** [comment]
All I did is create an empty scene in Unity and add two sphere.
Attached pls find the log.
[a.zip](https://github.com/google/gapid/files/1087252/a.zip)
