### ISSUE TITLE
gapit does not propagate log-level to gapir

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#623]
"gapit -log-level Debug" has no effect on gapir

**Comment by ben-clayton** [comment]
Working as intended - use: `gapit <verb> --gapir-args="--log-level D"`

The reason being that tying `gapir` and `gapis` logging together often results in either no information or so much logging that you can't find what you're after.

**Comment by dsrbecky** [comment]
This is inconsistent with gapic though.

I would say that --log-level Debug should request Debug log messages from all systems.

The fact the our log system is spammy is separate issue.

**Comment by ben-clayton** [comment]
I've discussed with Pascal to change the client for this very reason.
We should be able to specify the verbosity of each system independently, preferably in a persisted config view.

**Comment by dsrbecky** [comment]
Sure, should be able to do some filtering based on systems/tags/atomIds, but I think the default should be just global log-level
