### ISSUE TITLE
Some formats have wrong component order

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#632]
It seems like most of the pack formats have their components reversed. Take for example:

```go
case VkFormat_VK_FORMAT_A2B10G10R10_UNORM_PACK32:
	return image.NewUncompressed("VK_FORMAT_A2B10G10R10_UNORM_PACK32", fmts.ABGR_U2U10U10U10_NORM), nil
```

According to [these docs](https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkFormat.html):

> VK_FORMAT_A2B10G10R10_UNORM_PACK32 specifies a four-component, 32-bit packed unsigned normalized format that has a 2-bit A component in bits 30..31, a 10-bit B component in bits 20..29, a 10-bit G component in bits 10..19, and a 10-bit R component in bits 0..9.

The `stream` package always declares the components from lowest bit / lowest byte to highest. That would make `VK_FORMAT_A2B10G10R10_UNORM_PACK32` `fmts.RGBA_U10U10U10U2_NORM` for a little-endian architecture (which is what we currently assume throughout GAPID).

There are many others that have the same issue.

**Comment by AWoloszyn** [comment]
Thanks for noticing this!
