### ISSUE TITLE
Having trouble capturing a trace.

### ISSUE THREAD

**Issue by VS1234** [google/gapid#633]
Hi,

I built the gapid source and am trying to capture a trace. I get an error -- due to the app waiting for a debugger to attach. How do I get past this? Am I missing a configuration step or some paramter(s) in the trace command? 

I am running on a Fire Tablet running FireOS 5 (Android L).

Thanks for your help,

- Vittal

~/gapid/release/pkg$ ./gapit trace   com.amazon.youtube_apk
21:14:17.186 I: [gapidapk.EnsureInstalled] <gapit> Examining gapid.apk on host... (abi: armeabi-v7a)
21:14:17.366 I: [gapidapk.EnsureInstalled] <gapit> Looking at installed packages... (abi: armeabi-v7a, gapid.apk: /home/local/ANT/vittalb/gapid/release/pkg/gapid-armeabi.apk, target-version-code: 1, target-version-name: 0.4.0:0:developer:28aa18)
21:14:19.026 I: [gapidapk.EnsureInstalled] <gapit> Found gapid package... (abi: armeabi-v7a, gapid.apk: /home/local/ANT/vittalb/gapid/release/pkg/gapid-armeabi.apk, installed-version-code: 1, installed-version-name: 0.4.0:0:developer:28aa18, target-version-code: 1, target-version-name: 0.4.0:0:developer:28aa18)
21:14:19.727 I: <gapit> Adding new device (device: 0088080744730ECH)
21:14:19.727 I: <gapit> Device list:
21:14:19.727 I: <gapit>   0088080744730ECH
21:14:20.778 I: <gapit> action: android.intent.action.MAIN:com.amazon.youtube_apk/com.amazon.happygilmore.activities.LauncherActivity
21:14:20.782 I: <gapit> Device is rooted
21:14:20.810 I: [start] <gapit> Turning device screen on (abi: armeabi-v7a, activity: com.amazon.happygilmore.activities.LauncherActivity, on: com.amazon.youtube_apk)
21:14:20.839 I: [start] <gapit> Checking for lockscreen (abi: armeabi-v7a, activity: com.amazon.happygilmore.activities.LauncherActivity, on: com.amazon.youtube_apk)
21:14:20.870 I: [start] <gapit> Checking gapid.apk is installed (abi: armeabi-v7a, activity: com.amazon.happygilmore.activities.LauncherActivity, on: com.amazon.youtube_apk)
21:14:20.870 I: [gapidapk.EnsureInstalled⇒start] <gapit> Examining gapid.apk on host... (abi: armeabi-v7a, abi: armeabi-v7a, activity: com.amazon.happygilmore.activities.LauncherActivity, on: com.amazon.youtube_apk)
21:14:21.008 I: [gapidapk.EnsureInstalled⇒start] <gapit> Looking at installed packages... (abi: armeabi-v7a, abi: armeabi-v7a, activity: com.amazon.happygilmore.activities.LauncherActivity, gapid.apk: /home/local/ANT/vittalb/gapid/release/pkg/gapid-armeabi.apk, on: com.amazon.youtube_apk, target-version-code: 1, target-version-name: 0.4.0:0:developer:28aa18)
21:14:22.558 I: [gapidapk.EnsureInstalled⇒start] <gapit> Found gapid package... (abi: armeabi-v7a, abi: armeabi-v7a, activity: com.amazon.happygilmore.activities.LauncherActivity, gapid.apk: /home/local/ANT/vittalb/gapid/release/pkg/gapid-armeabi.apk, installed-version-code: 1, installed-version-name: 0.4.0:0:developer:28aa18, on: com.amazon.youtube_apk, target-version-code: 1, target-version-name: 0.4.0:0:developer:28aa18)
21:14:22.558 I: [start] <gapit> Forwarding (abi: armeabi-v7a, activity: com.amazon.happygilmore.activities.LauncherActivity, on: com.amazon.youtube_apk, port: 37535)
21:14:22.581 I: [start] <gapit> Starting activity in debug mode (abi: armeabi-v7a, activity: com.amazon.happygilmore.activities.LauncherActivity, on: com.amazon.youtube_apk, port: 37535)
21:14:23.752 I: [start] <gapit> Forwarding TCP port 42499 -> JDWP pid 616 (abi: armeabi-v7a, activity: com.amazon.happygilmore.activities.LauncherActivity, jdwpPort: 42499, on: com.amazon.youtube_apk, pid: 616, port: 37535)
21:14:23.754 I: [start] <gapit> Connecting to JDWP (abi: armeabi-v7a, activity: com.amazon.happygilmore.activities.LauncherActivity, jdwpPort: 42499, on: com.amazon.youtube_apk, pid: 616, port: 37535)
21:14:23.754 I: [start] <gapit> Failed to connect: read tcp 127.0.0.1:59010->127.0.0.1:42499: read: connection reset by peer (abi: armeabi-v7a, activity: com.amazon.happygilmore.activities.LauncherActivity, jdwpPort: 42499, on: com.amazon.youtube_apk, pid: 616, port: 37535)
21:14:24.756 I: [start] <gapit> Failed to connect: read tcp 127.0.0.1:59012->127.0.0.1:42499: read: connection reset by peer (abi: armeabi-v7a, activity: com.amazon.happygilmore.activities.LauncherActivity, jdwpPort: 42499, on: com.amazon.youtube_apk, pid: 616, port: 37535)
21:14:25.757 I: [start] <gapit> Failed to connect: read tcp 127.0.0.1:59014->127.0.0.1:42499: read: connection reset by peer (abi: armeabi-v7a, activity: com.amazon.happygilmore.activities.LauncherActivity, jdwpPort: 42499, on: com.amazon.youtube_apk, pid: 616, port: 37535)
21:14:26.759 I: [start] <gapit> Failed to connect: read tcp 127.0.0.1:59016->127.0.0.1:42499: read: connection reset by peer (abi: armeabi-v7a, activity: com.amazon.happygilmore.activities.LauncherActivity, jdwpPort: 42499, on: com.amazon.youtube_apk, pid: 616, port: 37535)
21:14:27.760 I: [start] <gapit> Failed to connect: read tcp 127.0.0.1:59020->127.0.0.1:42499: read: connection reset by peer (abi: armeabi-v7a, activity: com.amazon.happygilmore.activities.LauncherActivity, jdwpPort: 42499, on: com.amazon.youtube_apk, pid: 616, port: 37535)
21:14:28.761 I: [start] <gapit> Failed to connect: read tcp 127.0.0.1:59022->127.0.0.1:42499: read: connection reset by peer (abi: armeabi-v7a, activity: com.amazon.happygilmore.activities.LauncherActivity, jdwpPort: 42499, on: com.amazon.youtube_apk, pid: 616, port: 37535)
21:14:29.762 I: [start] <gapit> Failed to connect: read tcp 127.0.0.1:59024->127.0.0.1:42499: read: connection reset by peer (abi: armeabi-v7a, activity: com.amazon.happygilmore.activities.LauncherActivity, jdwpPort: 42499, on: com.amazon.youtube_apk, pid: 616, port: 37535)
21:14:30.764 I: [start] <gapit> Failed to connect: read tcp 127.0.0.1:59028->127.0.0.1:42499: read: connection reset by peer (abi: armeabi-v7a, activity: com.amazon.happygilmore.activities.LauncherActivity, jdwpPort: 42499, on: com.amazon.youtube_apk, pid: 616, port: 37535)
21:14:31.766 I: [start] <gapit> Failed to connect: read tcp 127.0.0.1:59030->127.0.0.1:42499: read: connection reset by peer (abi: armeabi-v7a, activity: com.amazon.happygilmore.activities.LauncherActivity, jdwpPort: 42499, on: com.amazon.youtube_apk, pid: 616, port: 37535)
21:14:32.767 I: [start] <gapit> Failed to connect: read tcp 127.0.0.1:59032->127.0.0.1:42499: read: connection reset by peer (abi: armeabi-v7a, activity: com.amazon.happygilmore.activities.LauncherActivity, jdwpPort: 42499, on: com.amazon.youtube_apk, pid: 616, port: 37535)
21:14:33.812 F: <gapit> Main failed
Error: Connecting to JDWP
   Cause: read tcp 127.0.0.1:59032->127.0.0.1:42499: read: connection reset by peer

**Comment by ben-clayton** [comment]
Hi @VS1234 - thank you for reporting the issue. 
Is there anything in logcat that highlights a problem? It is possible that we've accidentally broken tracing on L, as it's been a while since we've tested it. 
Please be aware that logcat may contain personal information, so please be aware of this before uploading any logs. 

I am on vacation for the next week, but I can try to find a similar device to test when I return.

Many thanks.

**Comment by VS1234** [comment]
Thanks for your reply. I will collect the logcat data for L and N device and upload them. I have noticed the problem on Android N device also.

Is there something I need to set up to get past the connection issue? My host machine is Linux. I ee similar message for Android L and N. I changed the source to try 100 connection attempts and that did not help.

Regards,

21:14:32.767 I: [start] Failed to connect: read tcp 127.0.0.1:59032->127.0.0.1:42499: read: connection reset by peer (abi: armeabi-v7a, activity: com.amazon.happygilmore.activities.LauncherActivity, jdwpPort: 42499, on: com.amazon.youtube_apk, pid: 616, port: 37535)

**Comment by VS1234** [comment]
I tried with debugger on and off -- by changing the call in StartOrAttach() to use d.StartActivity() vs d.StartActivityForDebug(). I can now get past the issue of waiting for debugger. I still get the "Failed to connect" message.

Regards

**Comment by ben-clayton** [comment]
Oh - one other thing to try. Is Android Studio running at the same time? If so, please try closing it while taking the trace.

**Comment by ben-clayton** [comment]
Friendly ping.

**Comment by ben-clayton** [comment]
Closing due to lack of info.
