### ISSUE TITLE
Investigate solutions for fmin/fmax issues in the astc library

### ISSUE THREAD

**Issue by AWoloszyn** [google/gapid#636]
As seen in #635, building with gcc 6.3 currently fails, since the astc library defines fmin, fmax, and friends. This results in multiple colliding definitions of fmin and fmax in the global namespace.

**Comment by ben-clayton** [comment]
Ideally, we'd push fixes upstream to https://github.com/ARM-software/astc-encoder, but it appears they're not responding to PRs.

**Comment by pmuetschard** [comment]
Also take a look at this ugly hack for Windows: https://github.com/google/gapid/commit/ab47157a5466720ad1ce0523d0cf55e57b6fb0d8

It "solved" eerily similar sounding issues... Specifically the ugly ```-D_GLIBCXX_INCLUDE_NEXT_C_HEADERS``` fixed the fmin/fmax redefinition issue.

**Comment by baldwinn860** [comment]
This issue seems to have spread over to newer clang versions. I just ran with Apple LLVM 9.0.0 and hit this error.
