### ISSUE TITLE
gapit sometimes leaves an orphan gapis lying around

### ISSUE THREAD

**Issue by AWoloszyn** [google/gapid#637]
Running gapit sometimes leaves an instance of gapis  orphaned.

This can become a problem when too many gapis processes are sitting around on the system, since they take up GL resources, and eventually no more can be successfully opened. (Specifically on Linux, eventually even things like glxgears stop being able to run until you remove the stale processes).

**Comment by dsrbecky** [comment]
I thought Ben fixed it in #515

**Comment by ben-clayton** [comment]
I think I just used the `--idle-timeout` parameter for `gapic`. Feel free to add it to the `gapit` spawning of `gapis`.

**Comment by AWoloszyn** [comment]
I will add it.

**Comment by AWoloszyn** [comment]
Fixed in #640
