### ISSUE TITLE
"Failed read package info" on Windows 8.1

### ISSUE THREAD

**Issue by shikui08** [google/gapid#646]
I followed the instructions and the build process was a success. But when  I run:
1. enter 'do run gapic' in cmd prompt.
2. when GUI shows up, click File->Capture Trace.
3. select my android device.
4. click ... button to the right of 'Package / Action' label as it is activated by step 3).

I got java.lang.RuntimeException, the error information is pasted below.

gapit log:

> Starting gapit as [f:\dev\gapidbin\release\pkg\gapit.exe, packages, --format, proto, --icons, --icondensity, 1.0, --dataheader, ~-~-~-~-, --device, unknown, --adb, F:\adt-bundle-windows-x86-20140624\sdk\platform-tools\adb.exe]
> gapit: 08:12:56.931 F: <gapit> Main failed
> gapit: Error: getting package list
> gapit:    Cause: Listing installed packages
> gapit:    Cause: Process returned error
> gapit:    Cause: exit status 1

The java exception trace:

> Exception in thread "com.google.gapid.server.GapitPkgInfoProcess$1" java.lang.RuntimeException: The gapit command didn't produce the data marker.
>         at com.google.gapid.server.GapitPkgInfoProcess.lambda$createStdoutHandler$166(GapitPkgInfoProcess.java:116)
>         at com.google.gapid.server.GapitPkgInfoProcess$$Lambda$255/1766719779.parse(Unknown Source)
>         at com.google.gapid.server.ChildProcess$BinaryHandler.run(ChildProcess.java:232)
>         at com.google.gapid.server.ChildProcess$OutputHandler.lambda$start$138(ChildProcess.java:143)
>         at com.google.gapid.server.ChildProcess$OutputHandler$$Lambda$17/1550361081.run(Unknown Source)
>         at java.lang.Thread.run(Thread.java:745)
> W20170626-161256991[server.ChildProcess-gapit][views.ActivityPickerDialog$2.onFailure] Failed to read package info

My OS is windows 8.1.  Please tell me what might went wrong? Thanks a lot!

**Comment by ben-clayton** [comment]
Hi @shikui08,

I suspect that the application used to fetch the package lists has thrown an exception.
Is there anything in `adb logcat` that looks like an exception being raised in `com.google.android.gapid.*`?

We've encountered a version of Android that seems to throw an exception when calling a certain function, but we haven't quite pinned down what devices this affects. Do you mind sharing your Android device model / OS version?

Cheers,
Ben

**Comment by shikui08** [comment]
Well for now I debug GPU applications using Android Studio 2.2 and it works.
Every now and then I would give GAPID a try and when I do that, I first uninstall whatever is previously installed by AS 2.2 from my phone and then install gapid-aarch64.apk built along with GAPID.
GAPID still fails getting packages list on my phone, but I get Timeout connecting to service error instead.

And adb logcat prints out things like this:

> 
> 	1614  1659 I ActivityManager: Start proc 1495:com.google.android.gapid.aarch64/u0a158 for service com.google.android.gapid.aarch64/com.google.android.gapid.DeviceInfoService
> 	1495  1512 W linker  : /data/app/com.google.android.gapid.aarch64-1/lib/arm64/libdeviceinfo.so: unused DT entry: type 0xf arg 0x3cbda
> 	1495  3207 E gapid-pkginfo: Error occurred
> 	1495  3207 E gapid-pkginfo: java.util.concurrent.ExecutionException: android.content.res.Resources$NotFoundException: Drawable com.xiaomi.payment:drawable/mibi_ic_milicenter with resource ID #0x7f02003e
> 	1495  3207 E gapid-pkginfo: 	at java.util.concurrent.FutureTask.report(FutureTask.java:94)
> 	1495  3207 E gapid-pkginfo: 	at java.util.concurrent.FutureTask.get(FutureTask.java:164)
> 	1495  3207 E gapid-pkginfo: 	at com.google.android.gapid.SocketWriter.connectAndWrite(SocketWriter.java:45)
> 	1495  3207 E gapid-pkginfo: 	at com.google.android.gapid.SocketWriter.connectAndWrite(SocketWriter.java:45)
> 	1495  3207 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService.handleSendPackageInfo(PackageInfoService.java:153)
> 	1495  3207 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService.handleSendPackageInfo(PackageInfoService.java:153)
> 	1495  3207 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService.onHandleIntent(PackageInfoService.java:116)
> 	1495  3207 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService.onHandleIntent(PackageInfoService.java:116)
> 	1495  3207 E gapid-pkginfo: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
> 	1495  3207 E gapid-pkginfo: 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 	1495  3207 E gapid-pkginfo: 	at android.os.Looper.loop(Looper.java:154)
> 	1495  3207 E gapid-pkginfo: 	at android.os.HandlerThread.run(HandlerThread.java:61)
> 	1495  3207 E gapid-pkginfo: Caused by: android.content.res.Resources$NotFoundException: Drawable com.xiaomi.payment:drawable/mibi_ic_milicenter with resource ID #0x7f02003e
> 	1495  3207 E gapid-pkginfo: Caused by: android.content.res.Resources$NotFoundException: File res/drawable-xhdpi-v4/mibi_ic_milicenter.png from drawable resource ID #0x7f02003e
> 	1495  3207 E gapid-pkginfo: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:748)
> 	1495  3207 E gapid-pkginfo: 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:585)
> 	1495  3207 E gapid-pkginfo: 	at android.content.res.MiuiResourcesImpl.loadDrawable(MiuiResourcesImpl.java:305)
> 	1495  3207 E gapid-pkginfo: 	at android.content.res.Resources.getDrawableForDensity(Resources.java:867)
> 	1495  3207 E gapid-pkginfo: 	at android.content.res.Resources.getDrawableForDensity(Resources.java:824)
> 	1495  3207 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService$IconStore.add(PackageInfoService.java:321)
> 	1495  3207 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService$IconStore.add(PackageInfoService.java:321)
> 	1495  3207 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService.getPackageJson(PackageInfoService.java:241)
> 	1495  3207 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService.getPackageJson(PackageInfoService.java:241)
> 	1495  3207 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService.getPackageInfo(PackageInfoService.java:186)
> 	1495  3207 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService.getPackageInfo(PackageInfoService.java:186)
> 	1495  3207 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService.access$000(PackageInfoService.java:60)
> 	1495  3207 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService.access$000(PackageInfoService.java:60)
> 	1495  3207 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService$2.call(PackageInfoService.java:147)
> 	1495  3207 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService$2.call(PackageInfoService.java:147)
> 	1495  3207 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService$2.call(PackageInfoService.java:144)
> 	1495  3207 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService$2.call(PackageInfoService.java:144)
> 	1495  3207 E gapid-pkginfo: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
> 	1495  3207 E gapid-pkginfo: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
> 	1495  3207 E gapid-pkginfo: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
> 	1495  3207 E gapid-pkginfo: 	at java.lang.Thread.run(Thread.java:761)
> 	1495  3207 E gapid-pkginfo: Caused by: java.io.FileNotFoundException: res/drawable-xhdpi-v4/mibi_ic_milicenter.png
> 	1495  3207 E gapid-pkginfo: 	at android.content.res.AssetManager.openNonAssetNative(Native Method)
> 	1495  3207 E gapid-pkginfo: 	at android.content.res.AssetManager.openNonAsset(AssetManager.java:443)
> 	1495  3207 E gapid-pkginfo: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:738)
> 	1495  3207 E gapid-pkginfo: 	... 14 more
> 	1495  6401 E gapid-pkginfo: Error occurred
> 	1495  6401 E gapid-pkginfo: java.util.concurrent.ExecutionException: android.content.res.Resources$NotFoundException: Drawable com.xiaomi.payment:drawable/mibi_ic_milicenter with resource ID #0x7f02003e
> 	1495  6401 E gapid-pkginfo: 	at java.util.concurrent.FutureTask.report(FutureTask.java:94)
> 	1495  6401 E gapid-pkginfo: 	at java.util.concurrent.FutureTask.get(FutureTask.java:164)
> 	1495  6401 E gapid-pkginfo: 	at com.google.android.gapid.SocketWriter.connectAndWrite(SocketWriter.java:45)
> 	1495  6401 E gapid-pkginfo: 	at com.google.android.gapid.SocketWriter.connectAndWrite(SocketWriter.java:45)
> 	1495  6401 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService.handleSendPackageInfo(PackageInfoService.java:153)
> 	1495  6401 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService.handleSendPackageInfo(PackageInfoService.java:153)
> 	1495  6401 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService.onHandleIntent(PackageInfoService.java:116)
> 	1495  6401 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService.onHandleIntent(PackageInfoService.java:116)
> 	1495  6401 E gapid-pkginfo: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
> 	1495  6401 E gapid-pkginfo: 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 	1495  6401 E gapid-pkginfo: 	at android.os.Looper.loop(Looper.java:154)
> 	1495  6401 E gapid-pkginfo: 	at android.os.HandlerThread.run(HandlerThread.java:61)
> 	1495  6401 E gapid-pkginfo: Caused by: android.content.res.Resources$NotFoundException: Drawable com.xiaomi.payment:drawable/mibi_ic_milicenter with resource ID #0x7f02003e
> 	1495  6401 E gapid-pkginfo: Caused by: android.content.res.Resources$NotFoundException: File res/drawable-xhdpi-v4/mibi_ic_milicenter.png from drawable resource ID #0x7f02003e
> 	1495  6401 E gapid-pkginfo: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:748)
> 	1495  6401 E gapid-pkginfo: 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:585)
> 	1495  6401 E gapid-pkginfo: 	at android.content.res.MiuiResourcesImpl.loadDrawable(MiuiResourcesImpl.java:305)
> 	1495  6401 E gapid-pkginfo: 	at android.content.res.Resources.getDrawableForDensity(Resources.java:867)
> 	1495  6401 E gapid-pkginfo: 	at android.content.res.Resources.getDrawableForDensity(Resources.java:824)
> 	1495  6401 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService$IconStore.add(PackageInfoService.java:321)
> 	1495  6401 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService$IconStore.add(PackageInfoService.java:321)
> 	1495  6401 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService.getPackageJson(PackageInfoService.java:241)
> 	1495  6401 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService.getPackageJson(PackageInfoService.java:241)
> 	1495  6401 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService.getPackageInfo(PackageInfoService.java:186)
> 	1495  6401 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService.getPackageInfo(PackageInfoService.java:186)
> 	1495  6401 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService.access$000(PackageInfoService.java:60)
> 	1495  6401 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService.access$000(PackageInfoService.java:60)
> 	1495  6401 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService$2.call(PackageInfoService.java:147)
> 	1495  6401 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService$2.call(PackageInfoService.java:147)
> 	1495  6401 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService$2.call(PackageInfoService.java:144)
> 	1495  6401 E gapid-pkginfo: 	at com.google.android.gapid.PackageInfoService$2.call(PackageInfoService.java:144)
> 	1495  6401 E gapid-pkginfo: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
> 	1495  6401 E gapid-pkginfo: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
> 	1495  6401 E gapid-pkginfo: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
> 	1495  6401 E gapid-pkginfo: 	at java.lang.Thread.run(Thread.java:761)
> 	1495  6401 E gapid-pkginfo: Caused by: java.io.FileNotFoundException: res/drawable-xhdpi-v4/mibi_ic_milicenter.png
> 	1495  6401 E gapid-pkginfo: 	at android.content.res.AssetManager.openNonAssetNative(Native Method)
> 	1495  6401 E gapid-pkginfo: 	at android.content.res.AssetManager.openNonAsset(AssetManager.java:443)
> 	1495  6401 E gapid-pkginfo: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:738)
> 	1495  6401 E gapid-pkginfo: 	... 14 more
> 	1614  3026 I ActivityManager: Killing 1495:com.google.android.gapid.aarch64/u0a158 (adj 906): empty #17
> 	1614 29252 D ActivityManagerInjector: com.google.android.gapid.aarch64 is killed by AMS with adj 906 ,do not allow restart
> 

My device is xiaomi 6 (Android : 7.1.1 , CPU : Snapdragon 835). 
Hope it helps!

**Comment by ben-clayton** [comment]
@shikui08 - perfect, that's exactly what I was after. Fix up for review.

**Comment by shikui08** [comment]
Checked out the latest code. It works now! Wow! @ben-clayton .

**Comment by ben-clayton** [comment]
@shikui08 thank you for the detailed information! Happy to hear it's now working.
