### ISSUE TITLE
Framebuffer takes a lot of time even if it is already cached

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#655]
I tried to find visual difference between two consecutive commands, so I keep switching between them.
The framebuffer takes non-negligible time to load anyway, and the loading icon eventually show up, which breaks my "human eye diffing algorithm" :-/

**Comment by ben-clayton** [comment]
@dsrbecky - please can you check if this is still an issue for you?

**Comment by ben-clayton** [comment]
**ping**

**Comment by ben-clayton** [comment]
I believe I've exacerbated this issue with the histogram which is built after the image is fetched from the cache.
Maybe we should cache the histogram results too?
