### ISSUE TITLE
Build steps do not work

### ISSUE THREAD

**Issue by AdrianAtGoogle** [google/gapid#66]
get the following error at 'do build' time:

-- Build files have been written to: C:/dev/gapid/release
ninja: error: 'C:/dev/gocode/src/github.com/google/gapid/cc-memory-tracker', needed by 'aarch64/src/aarch64-stamp/aarch64-gapii', missing and no known rule to make it
Error running C:\dev\Ninja\ninja.exe [install]: ⦕exit status 1⦖:Wait
exit status 1

**Comment by Qining** [comment]
Hi Adrian,

May I ask the commit hash on your machine?

**Comment by AdrianAtGoogle** [comment]
Hello: I'm a bit of a GIT newb so excuse me if this isn't what you asked for:

C:\dev\gocode\src\github.com\google\gapid>git rev-parse --verify HEAD
36710fe89983598d0eb03832b7f8143804c45ecd

**Comment by AWoloszyn** [comment]
I have a fix for this on the way, I am just verifying it one an unfortunately slow windows machine.

**Comment by AWoloszyn** [comment]
Let me know if this does not work for you. It should be ok now.
