### ISSUE TITLE
The joining two Great Houses

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#706]
I'm planning on finalizing the file format before our initial beta release. This involves settling on some class paths for types currently in the `gapis/atom/atom_pb` package.

The name `atom` is legacy - the command stream was built from a sequence of atoms, they were small data structures that when combined formed the command. Atoms now have observations, extras and any other sort of metadata. The name doesn't make sense anymore, and I've been asked countless times what they are, or why they have their name. I believe we should rename them.

We also have the `gapis/gfxapi` package. This contains the `API` interface and a whole bunch of other generic stuff relating to graphics APIs (meshes, resources, contexts, etc). In a rather unintuitive way, the `atom` package imports `gfxapi`, making it impossible for the `gfxapi` package to directly reference commands or command ids. Avoiding this cyclic dependency has been a major pain, and I can't justify the separation.

I propose:

* We merge the `atom` and `gfxapi` packages.
* We rename this package to `api` as the directory is already in `gapis` (**g**raphics **api** **s**erver)
* We rename `atom.Atom` to `api.Cmd`.
* We prefix other types currently in `atom` with `Cmd` when moving to `api`. For example `atom.ID` becomes `api.CmdID`.
* We do this now before making any file breaking changes.

Thoughts, questions?

**Comment by dsrbecky** [comment]
I think you mean the 'gapis/gfxapi', not 'gles/gfxapi', right?

Sounds good to me.  I have been generally using 'Command' instead of 'Atom' in comments for a while already.

**Comment by ben-clayton** [comment]
> I think you mean the 'gapis/gfxapi', not 'gles/gfxapi', right?

Yes - stupid muscle memory. Fixed.

**Comment by AWoloszyn** [comment]
I would be very much for this move. I have had to go through some annoying hoops to avoid the cyclic dependency.
Also I agree renaming Atom -> Command will clear up some of the confusion we see.

**Comment by ben-clayton** [comment]
Awesome, I'm happy we seem to be in agreement as I've already started on this, and my fingers are already almost bleeding from the renames.

**Comment by pmuetschard** [comment]
Is it too late to ask for ```Command``` instead of ```Cmd```? At least for types/proto messages...
