### ISSUE TITLE
Enum Program.ActiveUnifroms[0].Type is shown as number

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#709]

**Comment by dsrbecky** [comment]
ActiveUnifrom.Type does not have an name
Unifrom.Type does name
extras.api contains "Uniform(Value: make!u8(0), Type: au.Type)" which should bind those two

**Comment by dsrbecky** [comment]
I keep wondering if it wouldn't be just easier to create the constant set by hand...
...plus maybe use the sets as new types in the api to add a bit more clarity and safety.
We split all the various object IDs into our own types which add type safetly, maybe the same would be good for enums?

**Comment by ben-clayton** [comment]
This is a tricky one. The static analysis is actually working as expected - the types come from the `ProgramInfo` which is an extra and has no metadata describing the acceptable values for the Type field. This get assigned into the Program's uniforms we it's presented.

> I keep wondering if it wouldn't be just easier to create the constant set by hand

In this particular case, we will likely have to something manual as the data just doesn't exist in the API file.
