### ISSUE TITLE
gapit report shows only 1 issue

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#712]
18:53:10.252 W: <gapis> Atom 25 glGetIntegerv(param: GL_MAX_CLIP_PLANES, values: {485288512992 0}): aborted(glErrorInvalidEnum)
18:53:10.269 W: <gapis> Atom 288 glGetIntegerv(param: GL_MAX_CLIP_PLANES, values: {485288512992 0}): aborted(glErrorInvalidEnum)
18:53:10.291 W: <gapis> Atom 2348 glGetIntegerv(param: GL_MAX_CLIP_PLANES, values: {485448269104 0}): aborted(glErrorInvalidEnum)
...
18:53:21.297 I: <gapir> Replay finished successfully
[ErrorLevel] [25] capture:<id:<data:"\213\251\335\211\215\253\225^[\237Y]\270\241\304\2573\326Q\306" > > indices:25  <ERR_INVALID_ENUM_VALUE [value: 0, variable: variable]>
1 issues found

is seems that only the first issue is reported

**Comment by ben-clayton** [comment]
Fixed with https://github.com/google/gapid/commit/9dc3f6bc8240d1fef7533bf13e57294b252db8f0.
