### ISSUE TITLE
Log errors found by find_issues

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#728]
We are mixing two different concepts in it:
 - Problems with user's GL calls - this is something we should show in report and the user needs to fix it
 - Problems with GAPID - bad compat, can not translate GLSL, replay driver complains, etc.  This is our bad, we should show it in log, and we need to fix it.

**Comment by ben-clayton** [comment]
This was a conscious decision. What are you suggesting we change here?

Robot uses the report to find internal errors by looking for those with a severity > error. We could certainly make the client show these as something that should be reported to us.

**Comment by dsrbecky** [comment]
How about we change the internal issues to just log.E(ctx, ... ) ?

**Comment by ben-clayton** [comment]
That would break robot and would hide the issues even more.
I don't understand the problem with having internal issues appear in the report - it's something that shouldn't be happening frequently, and if they do happen we don't want to bury them in logs that nobody reads.

**Comment by dsrbecky** [comment]
The trouble is if things crash, the errors do not get reported.
Or if there is a lot of logging, they will be at the very end, which is too far.
Basically the report check were not very helpful to me recently, so I am thinking how to fix it.
Maybe we could also log them right away then?

**Comment by ben-clayton** [comment]
I'm fine with them **also** going in the log.

**Comment by dsrbecky** [comment]
The original problem and motivation was that panic in ```gapit report``` will cause all the buffered messages to be lost, although they might be essential so solving the crash.

Just logging the issues as we go is probably enough to help.
