### ISSUE TITLE
Missing tailing gapir logs

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#752]
I am running gapit report with debug log level for gapir. Some of the messages at the end are missing.
Maybe when the gapir proccess exits we just drop any messages that have not been propagated yet?
P1 because I have noticed this has tendency to omit crash messages (which are by definition last)

**Comment by ben-clayton** [comment]
Are the messages you're interested in seeing from `gapir` or `gapis`? Is `gapis` possibly panicing?

**Comment by dsrbecky** [comment]
The messages are from gapir.
Gapis seems to be fine.

**Comment by ben-clayton** [comment]
Are you running this through do?

**Comment by dsrbecky** [comment]
No, directly starting the gapit executable - gapit screenshot to be precise
