### ISSUE TITLE
Improve command tree grouping

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#759]
We've had a number of reports now where the generated command groups are less than perfect.

[`resolve/command_tree.go`](https://github.com/google/gapid/blob/master/gapis/resolve/command_tree.go) will apply groups in the following order:

1. API
2. Context
3. Thread
4. User Markers
5. Frames
6. Draw calls

Once a group has been applied, later groups will be discarded if the start and ends overlap (A completely containing B and vice-versa is fine).

For some reason certain games have patterns which result in very sparse or few groups.

Investigate, fix.

**Comment by dsrbecky** [comment]
Closed by #884
