### ISSUE TITLE
Can you release prebuilt binary for use

### ISSUE THREAD

**Issue by digish** [google/gapid#768]
I wasted lot of time building this on windows machine but it always fails for some errors even after following the exact procedure in the build help.

it would be helpful if pre-builts are also included or maintained at some location for use

**Comment by ben-clayton** [comment]
Hi @digish. We plan to put our first pre-release binaries up at the end of next week.
Thank you for your patience.

**Comment by digish** [comment]
Thank you Ben,
will be waiting...

**Comment by ben-clayton** [comment]
Hi @digish - thank you again for your patience. 
[Our first pre-release build can be found here.](https://github.com/google/gapid/releases/tag/v0.5.0)

Please let us know how you get on.
