### ISSUE TITLE
do build error on Windows

### ISSUE THREAD

**Issue by wanjia** [google/gapid#77]
$ sh -x do run gapic
++ dirname do
+ DO_DIR=.
++ cd .
++ pwd
+ DO_DIR=/c/Users/jia.wanj/go/src/github.com/google/gapid
++ cd /c/Users/jia.wanj/go/src/github.com/google/gapid/../../../../
++ pwd
+ export GOPATH=/c/Users/jia.wanj/go/src/github.com/google/gapid/third_party:/c/Users/jia.wanj/go
+ GOPATH=/c/Users/jia.wanj/go/src/github.com/google/gapid/third_party:/c/Users/jia.wanj/go
+ cd /c/Users/jia.wanj/go/src/github.com/google/gapid
+ go run ./cmd/do/build.go ./cmd/do/clean.go ./cmd/do/config.go ./cmd/do/do.go ./cmd/do/gapic.go ./cmd          /do/init.go ./cmd/do/run.go ./cmd/do/upload.go run gapic
[0/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: D:/Download/gapid/release
[1/308] Apic on C:/Users/jia.wanj/go/src/github.com/google/gapid/gapis/gfxapi/vulkan/vulkan.api with c          c_vulkan_api_exports.cpp.tmpl
FAILED: api/cc_vulkan_api_exports.cpp.tmpl.tag C:/Users/jia.wanj/go/src/github.com/google/gapid/gapii/          cc/vulkan_exports.cpp
cmd.exe /C "cd /D C:\Users\jia.wanj\go\src\github.com\google\gapid\gapii\cc && D:\Download\gapid\relea          se\bin\apic.exe template --cmake D:/Download/gapid/release/api/cc_vulkan_api_exports.cpp.tmpl.deps.cma          ke --dir C:/Users/jia.wanj/go/src/github.com/google/gapid/gapii/cc C:/Users/jia.wanj/go/src/github.com          /google/gapid/gapis/gfxapi/vulkan/vulkan.api C:/Users/jia.wanj/go/src/github.com/google/gapid/gapis/gf          xapi/vulkan/templates/api_exports.cpp.tmpl --gopath C:/Users/jia.wanj/go/src/github.com/google/gapid/t          hird_party C:/Users/jia.wanj/go && "C:\Program Files (x86)\CMake\bin\cmake.exe" -E touch D:/Download/g          apid/release/api/cc_vulkan_api_exports.cpp.tmpl.tag"
Critical:Main failed
    ⦕C:/Users/jia.wanj/go/src/github.com/google/gapid/gapis/gfxapi/vulkan/templates/api_exports.cpp.tm          pl: C:/Users/jia.wanj/go/src/github.com/google/gapid/gapis/gfxapi/vulkan/templates/api_exports.cpp.tmp          l: template: C:/Users/jia.wanj/go/src/github.com/google/gapid/gapis/gfxapi/vulkan/templates/api_export          s.cpp.tmpl:42:61: executing "C:/Users/jia.wanj/go/src/github.com/google/gapid/gapis/gfxapi/vulkan/temp          lates/api_exports.cpp.tmpl" at <Write $filename>: error calling Write: open C:\Users\jia.wanj\go\src\g          ithub.com\google\gapid\gapii\cc\vulkan_

_exports.cpp: The filename, directory name, or volume label syntax is incorrect.

Run ⇒ run.go@129
        main ⇒ main.go@24
[2/308] Apic on C:/Users/jia.wanj/go/src/github.com/google/gapid/gapis/gfxapi/core/core.api with cc_co          re_api_spy.h.tmpl
[3/308] Apic on C:/Users/jia.wanj/go/src/github.com/google/gapid/gapis/gfxapi/vulkan/vulkan.api with v          ulkan_pb_vulkan_api.proto.tmpl
[4/308] Apic on C:/Users/jia.wanj/go/src/github.com/google/gapid/gapis/gfxapi/core/core.api with cc_co          re_api_imports.h.tmpl
[5/308] Linking Go executable bin\simplecalc.exe
[6/308] Codergen for gapid
FAILED: C:/Users/jia.wanj/go/src/github.com/google/gapid/signatures.txt C:/Users/jia.wanj/go/src/githu          b.com/google/gapid/gapil/snippets/snippets_binary.go C:/Users/jia.wanj/go/src/github.com/google/gapid/          framework/binary/any/any_binary.go C:/Users/jia.wanj/go/src/github.com/google/gapid/framework/binary/t          est/test_binary.go C:/Users/jia.wanj/go/src/github.com/google/gapid/gapis/atom/atom_binary.go C:/Users          /jia.wanj/go/src/github.com/google/gapid/gapis/atom/test/test_binary.go C:/Users/jia.wanj/go/src/githu          b.com/google/gapid/gapis/gfxapi/core/core_binary.go C:/Users/jia.wanj/go/src/github.com/google/gapid/g          apis/gfxapi/gles/gles_binary.go C:/Users/jia.wanj/go/src/github.com/google/gapid/gapis/gfxapi/test/tes          t_binary.go C:/Users/jia.wanj/go/src/github.com/google/gapid/gapis/gfxapi/test/gfxapi_test_import/gfxa          pi_test_import_binary.go C:/Users/jia.wanj/go/src/github.com/google/gapid/gapis/gfxapi/vulkan/vulkan_b          inary.go C:/Users/jia.wanj/go/src/github.com/google/gapid/gapis/memory/memory_binary.go C:/Users/jia.w          anj/go/src/github.com/google/gapid/gapis/replay/protocol/protocol_binary.go C:/Users/jia.wanj/go/src/g          ithub.com/google/gapid/gapis/resolve/resolve_binary_test.go C:/Users/jia.wanj/go/src/github.com/google          /gapid/test/integration/replay/gles/gles_binary.go C:/Users/jia.wanj/go/src/github.com/google/gapid/co          re/cc/coder/atom.cpp C:/Users/jia.wanj/go/src/github.com/google/gapid/core/cc/coder/atom.h C:/Users/ji          a.wanj/go/src/github.com/google/gapid/core/cc/coder/core.cpp C:/Users/jia.wanj/go/src/github.com/googl          e/gapid/core/cc/coder/core.h C:/Users/jia.wanj/go/src/github.com/google/gapid/core/cc/coder/gles.cpp C          :/Users/jia.wanj/go/src/github.com/google/gapid/core/cc/coder/gles.h C:/Users/jia.wanj/go/src/github.c          om/google/gapid/core/cc/coder/memory.cpp C:/Users/jia.wanj/go/src/github.com/google/gapid/core/cc/code          r/memory.h C:/Users/jia.wanj/go/src/github.com/google/gapid/core/cc/coder/vulkan.cpp C:/Users/jia.wanj          /go/src/github.com/google/gapid/core/cc/coder/vulkan.h
cmd.exe /C "cd /D D:\Download\gapid\release && D:\Download\gapid\release\bin\codergen.exe --gopath C:/          Users/jia.wanj/go/src/github.com/google/gapid/third_party;C:/Users/jia.wanj/go --signatures C:/Users/j          ia.wanj/go/src/github.com/google/gapid/signatures.txt --go -cpp C:/Users/jia.wanj/go/src/github.com/go          ogle/gapid/core/cc/coder -java C:/Users/jia.wanj/go/src/github.com/google/gapid/gapic/src github.com/g          oogle/gapid/..."
Critical:Main failed
    ⦕C:\Users\jia.wanj\go\src\github.com\google\gapid\gapis\gfxapi\vulkan\api.go:27:1: expected declar          ation, found '.' (and 10 more errors)⦖
    Run ⇒ run.go@129
        main ⇒ main.go@48
ninja: build stopped: subcommand failed.
Error running D:\Program Files\ninja-win\ninja.exe [install]: ⦕exit status 1⦖:Wait
exit status 1

**Comment by AWoloszyn** [comment]
I have not seen this error before.
Normally to build on windows, I build from the normal command-prompt instead of the msys shell.
It follows from that, that when you run do config you pass in all of the normal windows paths, rather than the unix-style msys paths.

Let me know if this works for you.

**Comment by ben-clayton** [comment]
Andrew is correct. We use the standard windows paths and environment (+ mingw64 toolchain) for building. Please try running `do.bat config` from the regular windows command line. 

I'll take a look at updating the build instructions to make this clearer.

**Comment by AWoloszyn** [comment]
This specific issue should be fixed by #94 and another Windows build issue by #111.

Let me know if you have any other problems building.
