### ISSUE TITLE
Gapic does not check command line args

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#772]
"gapic --disable-gapis-timeout foo.gfxtrace" essentially silently ignores all arguments

**Comment by pmuetschard** [comment]
WAI: flags by default take an argument, thus your command gives "foo.gfxtrace" as the argument to the disable-gapis-timeout flag. You can either use:

- ```--disable-gapis-timeout true``` or ```--disable-gapis-timeout=true```
- use ```--``` to separate flags from arguments: ```--disable-gapis-timeout -- foo.gfxtrace```

**Comment by dsrbecky** [comment]
I realize that but I would have expected it complain that foo.gfxtrace is not valid value of boolean flag
