### ISSUE TITLE
panic: context canceled

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#800]
panic: context canceled [recovered]
...
github.com/google/gapid/gapis/api/gles.(*GlGetShaderSource).Mutate(0xc4310a9680, 0x33fc8a0, 0xc42059f530, 0xc43696a180, 0x0, 0x0, 0x0)
github.com/google/gapid/gapis/resolve.(*ResourcesResolvable).Resolve(0xc4203880b0, 0x33fc8a0, 0xc42059f530, 0x33d0de0, 0xc4203880b0, 0x1, 0x33d55a0)

Should we add an assert to Mutate to ensure it is running in non-cancellable context?

**Comment by ben-clayton** [comment]
More of the callstack would be useful here.

> Should we add an assert to Mutate to ensure it is running in non-cancellable context?

Sounds too costly to do per-mutate. We could add it locally to try and pick up on places we're missing `api.ForeachCmd`.
