### ISSUE TITLE
Have Wireframe view overlay a colored (red?) wireframe.

### ISSUE THREAD

**Issue by AWoloszyn** [google/gapid#818]
Currently the wireframe is the same color as the mesh, making it more difficult to see. If we re-write the shader to make it red or inverted, we would be able to see which draw-call we are referencing.

**Comment by dsrbecky** [comment]
Alternative would be to provide the client with the screen space vertex positions, and let the client render it.

I am think forward to situation where the client might want to know the raw positions anyway so that can user click the vertex and debug it.

**Comment by ben-clayton** [comment]
Yup, that's the plan.

**Comment by ben-clayton** [comment]
Closing for #817
