### ISSUE TITLE
Windows Build Fail——error: 'build_swapchain_image_data_' was not dec lared in this scope

### ISSUE THREAD

**Issue by stcdalyc** [google/gapid#821]
[1/459] Building CXX object CMakeFiles...virtual_swapchain/cc/swapchain.cpp.obj
FAILED: CMakeFiles/VkLayer_VirtualSwapchain.dir/core/vulkan/vk_virtual_swapchain
/cc/swapchain.cpp.obj
C:\msys64\mingw64\bin\x86_64-w64-mingw32-g++.exe   -DENABLE_HLSL=1 -DTARGET_OS_W
INDOWS -DVkLayer_VirtualSwapchain_EXPORTS -IC:/Users/galoisli/go/src/github.com/
google/gapid/third_party/SPIRV-Headers/include -IC:/Users/galoisli/go/src/github
.com/google/gapid/third_party/SPIRV-Tools/include -IC:/Users/galoisli/go/src/git
hub.com/google/gapid/third_party/SPIRV-Tools/source -IC:/Users/galoisli/go/src/g
ithub.com/google/gapid/third_party/SPIRV-Tools-Generated -IC:/Users/galoisli/go/
src/github.com/google/gapid/third_party/glslang/OGLCompilersDLL -IC:/Users/galoi
sli/go/src/github.com/google/gapid/core/memory_tracker/cc -IC:/Users/galoisli/go
/src/github.com/google/gapid/core/vulkan/cc/include -IC:/Users/galoisli/go/src/g
ithub.com/google/gapid -Wa,-mbig-obj -std=c++0x -O3 -DNDEBUG   -DGAPID_VERSION_A
ND_BUILD=\"0.5.0:0:developer\" -fno-exceptions -fno-rtti -MD -MT CMakeFiles/VkLa
yer_VirtualSwapchain.dir/core/vulkan/vk_virtual_swapchain/cc/swapchain.cpp.obj -
MF CMakeFiles\VkLayer_VirtualSwapchain.dir\core\vulkan\vk_virtual_swapchain\cc\s
wapchain.cpp.obj.d -o CMakeFiles/VkLayer_VirtualSwapchain.dir/core/vulkan/vk_vir
tual_swapchain/cc/swapchain.cpp.obj -c C:\Users\galoisli\go\src\github.com\googl
e\gapid\core\vulkan\vk_virtual_swapchain\cc\swapchain.cpp
In file included from C:\Users\galoisli\go\src\github.com\google\gapid\core\vulk
an\vk_virtual_swapchain\cc\swapchain.cpp:18:0:
C:\Users\galoisli\go\src\github.com\google\gapid\core\vulkan\vk_virtual_swapchai
n\cc\virtual_swapchain.h:184:8: error: 'function' in namespace 'std' does not na
me a template type
   std::function<SwapchainImageData()> build_swapchain_image_data_;
        ^~~~~~~~
C:\Users\galoisli\go\src\github.com\google\gapid\core\vulkan\vk_virtual_swapchai
n\cc\virtual_swapchain.h: In member function 'std::vector<VkImage_T*> swapchain:
:VirtualSwapchain::GetImages(uint32_t, bool)':
C:\Users\galoisli\go\src\github.com\google\gapid\core\vulkan\vk_virtual_swapchai
n\cc\virtual_swapchain.h:59:29: error: 'build_swapchain_image_data_' was not dec
lared in this scope
       image_data_.push_back(build_swapchain_image_data_());
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\galoisli\go\src\github.com\google\gapid\core\vulkan\vk_virtual_swapchai
n\cc\virtual_swapchain.h:59:29: note: suggested alternative: 'SwapchainImageData
'
       image_data_.push_back(build_swapchain_image_data_());
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                             SwapchainImageData
[2/459] Building CXX object CMakeFiles...swapchain/cc/virtual_swapchain.cpp.obj
FAILED: CMakeFiles/VkLayer_VirtualSwapchain.dir/core/vulkan/vk_virtual_swapchain
/cc/virtual_swapchain.cpp.obj
C:\msys64\mingw64\bin\x86_64-w64-mingw32-g++.exe   -DENABLE_HLSL=1 -DTARGET_OS_W
INDOWS -DVkLayer_VirtualSwapchain_EXPORTS -IC:/Users/galoisli/go/src/github.com/
google/gapid/third_party/SPIRV-Headers/include -IC:/Users/galoisli/go/src/github
.com/google/gapid/third_party/SPIRV-Tools/include -IC:/Users/galoisli/go/src/git
hub.com/google/gapid/third_party/SPIRV-Tools/source -IC:/Users/galoisli/go/src/g
ithub.com/google/gapid/third_party/SPIRV-Tools-Generated -IC:/Users/galoisli/go/
src/github.com/google/gapid/third_party/glslang/OGLCompilersDLL -IC:/Users/galoi
sli/go/src/github.com/google/gapid/core/memory_tracker/cc -IC:/Users/galoisli/go
/src/github.com/google/gapid/core/vulkan/cc/include -IC:/Users/galoisli/go/src/g
ithub.com/google/gapid -Wa,-mbig-obj -std=c++0x -O3 -DNDEBUG   -DGAPID_VERSION_A
ND_BUILD=\"0.5.0:0:developer\" -fno-exceptions -fno-rtti -MD -MT CMakeFiles/VkLa
yer_VirtualSwapchain.dir/core/vulkan/vk_virtual_swapchain/cc/virtual_swapchain.c
pp.obj -MF CMakeFiles\VkLayer_VirtualSwapchain.dir\core\vulkan\vk_virtual_swapch
ain\cc\virtual_swapchain.cpp.obj.d -o CMakeFiles/VkLayer_VirtualSwapchain.dir/co
re/vulkan/vk_virtual_swapchain/cc/virtual_swapchain.cpp.obj -c C:\Users\galoisli
\go\src\github.com\google\gapid\core\vulkan\vk_virtual_swapchain\cc\virtual_swap
chain.cpp
In file included from C:\Users\galoisli\go\src\github.com\google\gapid\core\vulk
an\vk_virtual_swapchain\cc\virtual_swapchain.cpp:17:0:
C:\Users\galoisli\go\src\github.com\google\gapid\core\vulkan\vk_virtual_swapchai
n\cc\virtual_swapchain.h:184:8: error: 'function' in namespace 'std' does not na
me a template type
   std::function<SwapchainImageData()> build_swapchain_image_data_;
        ^~~~~~~~
C:\Users\galoisli\go\src\github.com\google\gapid\core\vulkan\vk_virtual_swapchai
n\cc\virtual_swapchain.h: In member function 'std::vector<VkImage_T*> swapchain:
:VirtualSwapchain::GetImages(uint32_t, bool)':
C:\Users\galoisli\go\src\github.com\google\gapid\core\vulkan\vk_virtual_swapchai
n\cc\virtual_swapchain.h:59:29: error: 'build_swapchain_image_data_' was not dec
lared in this scope
       image_data_.push_back(build_swapchain_image_data_());
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\galoisli\go\src\github.com\google\gapid\core\vulkan\vk_virtual_swapchai
n\cc\virtual_swapchain.h:59:29: note: suggested alternative: 'SwapchainImageData
'
       image_data_.push_back(build_swapchain_image_data_());
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                             SwapchainImageData
C:\Users\galoisli\go\src\github.com\google\gapid\core\vulkan\vk_virtual_swapchai
n\cc\virtual_swapchain.cpp: In constructor 'swapchain::VirtualSwapchain::Virtual
Swapchain(VkDevice, uint32_t, const VkPhysicalDeviceProperties*, const VkPhysica
lDeviceMemoryProperties*, const swapchain::DeviceData*, const VkSwapchainCreateI
nfoKHR*, const VkAllocationCallbacks*, uint32_t, bool)':
C:\Users\galoisli\go\src\github.com\google\gapid\core\vulkan\vk_virtual_swapchai
n\cc\virtual_swapchain.cpp:69:3: error: 'build_swapchain_image_data_' was not de
clared in this scope
   build_swapchain_image_data_ = [this, properties, pAllocator]() {
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\galoisli\go\src\github.com\google\gapid\core\vulkan\vk_virtual_swapchai
n\cc\virtual_swapchain.cpp:69:3: note: suggested alternative: 'SwapchainImageDat
a'
   build_swapchain_image_data_ = [this, properties, pAllocator]() {
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
   SwapchainImageData
[10/459] Linking Go executable bin\verify_gles_api.exe
ninja: build stopped: subcommand failed.

**Comment by stcdalyc** [comment]
add #include <functional> to virtual_swapchain.h fix this problem.

**Comment by takizuki** [comment]
#include <functional>

**Comment by takizuki** [comment]
#include < functional >
