### ISSUE TITLE
Black screens are captured while capturing android launcher3

### ISSUE THREAD

**Issue by digish** [google/gapid#825]
With the first pre-built release for windows msi package.
I am trying to capture the android launcher process trace for debugging one gles corruption issue.

It captures the gl/egl calls frame by frames. 
but does not show the frame buffer dumps and draw output. it just shows black in top preview pane and 
in detailed view transparent

Attaching the trace for checking.

[launcher3_20170728_1636.zip](https://github.com/google/gapid/files/1182852/launcher3_20170728_1636.zip)

**Comment by ben-clayton** [comment]
Hi @digish - thank you for the capture.
I can open this trace and inspect the frames. I see launcher icons, but before it gets to that, there are a number of frames with a sliding black texture. 

<img width="1006" alt="screen shot 2017-07-28 at 12 56 14 pm" src="https://user-images.githubusercontent.com/11505236/28716289-48172d46-7394-11e7-9c02-37ba2ae8aeb0.png">

Is your issue with this black texture?

I want to check we're both seeing the same thing before I go any further.

**Comment by digish** [comment]
thanks for update ben,
I just checked again the captured trace on both mac and windows.
On mac it is showing as expected.
but on windows same trace is not shown only black screens and after few frames only exclamation symbol icon but not actual rendered screen.

it seems windows version has some issue.

**Comment by ben-clayton** [comment]
That's interesting. Is there anything in the report view or log view that suggests some sort of replay error?

It would be useful to know the graphics driver and GPU model in your windows machine. This can be found using `gapit.exe devices` in the installation path of GAPID. Please don't copy anything you're not happy to share!

Many thanks,
Ben

**Comment by digish** [comment]
on remote desktop i am unable to launch gapid.
so will provide you with the details tomorrow or monday.

**Comment by digish** [comment]
Thank you ben for the fix.
