### ISSUE TITLE
Add Vulkan Validation to the Report View

### ISSUE THREAD

**Issue by AWoloszyn** [google/gapid#832]

**Comment by ben-clayton** [comment]
Requires [moving the GAPIS - GAPIR protocol over to gRPC](#1818).

**Comment by Qining** [comment]
This requires 3 steps:
- [x] gRPC for GAPIS-GAPIR communication (#1818 )
- [ ] piping validation data to report view if layers present (#1931 )
- [ ] package validation layer libraries with GAPID

**Comment by AWoloszyn** [comment]
Everything here is done except for packaging.
