### ISSUE TITLE
can not get framebuffer, always waiting.

### ISSUE THREAD

**Issue by stcdalyc** [google/gapid#834]
![default](https://user-images.githubusercontent.com/6738727/28756005-217a3ffa-7599-11e7-92d8-97bde2a906b8.png)

can get texture, but can not get framebuffer

**Comment by ben-clayton** [comment]
Hi @stcdalyc,

I'm sorry you're having issues with replay. To help diagnose the issue:

1. Please can you check the logs for any error messages? This can be opened with `View` -> `Tabs` -> `Log`.
2. Please can you list your GPU / driver?
3. If you do not mind sharing, please can you post the output of `gapit.exe devices`?

Many thanks,
Ben

**Comment by stcdalyc** [comment]
now it tell me fail with "target machine actively refused" and the framebuffer turn **black**
![log](https://user-images.githubusercontent.com/6738727/28780494-7e6cbe4a-7639-11e7-9e55-848e835a0092.png)

GPU is Qualconmm Adrenno (TM) 405
but i don't know how to see the driver(or you can tell me how to do)

and here is the result of gapit.exe devices (i remove the infomation of my computor)
[1.txt](https://github.com/google/gapid/files/1187720/1.txt)

**Comment by ben-clayton** [comment]
Thank you @stcdalyc - that's exactly the information I needed. I believe the problem is:

```
Failed to release HDC. Error: 0x591
```

I'll look into reproducing and see if I can fix.

**Comment by ben-clayton** [comment]
> and here is the result of gapit.exe devices (i remove the infomation of my computer)

@stcdalyc - if you are happy to, please can you include the graphics driver part of your host machine? Replay is done on the host, not the Android device.

Cheers,
Ben

**Comment by ben-clayton** [comment]
@stcdalyc - I've lowered the severity of the error that appears to be causing your issues.
Please can you try the next release (v0.5.2) to see if this helps?

**Comment by stcdalyc** [comment]
the next release(v0.5.2) is not available yet, right? because i don't see any update in https://github.com/google/gapid/releases

here is the information of my computer
[1.txt](https://github.com/google/gapid/files/1189307/1.txt)

**Comment by ben-clayton** [comment]
> the next release(v0.5.2) is not available yet, right?

Correct, we'll try to upload binaries quite regularly, but 0.5.2 is not ready yet.

Given that my change only affects a single, small executable, here is [a zipped `gapir.exe`](https://github.com/google/gapid/files/1190119/gapir.exe.zip) taken from the tip of master from our build machine. No worries if you're not keen on swapping out executables - I can ping you when 0.5.2 is out.

Thank you for the quick replies.
Ben

**Comment by stcdalyc** [comment]
the situation change this time.
![transparent](https://user-images.githubusercontent.com/6738727/28822116-a82a7d1a-76ea-11e7-82ed-5f1b6e803f5c.png)
framebuffer turn transparent now.

and here is the log and other error msg:
![error](https://user-images.githubusercontent.com/6738727/28822145-bd903104-76ea-11e7-8823-92635cceeec4.png)
![log](https://user-images.githubusercontent.com/6738727/28822163-cc741834-76ea-11e7-98a6-2bf53a576052.png)

**Comment by ben-clayton** [comment]
@stcdalyc - that's at least a step in the right direction.
Are you comfortable sharing the `.gfxtrace` file?

**Comment by stcdalyc** [comment]
here is the .gfxtrace file:
[alphatest_20170801_1904.zip](https://github.com/google/gapid/files/1190358/alphatest_20170801_1904.zip)

and here is my apk:
[AlphaTest.zip](https://github.com/google/gapid/files/1190367/AlphaTest.zip)

**Comment by ben-clayton** [comment]
Great, thank you.

**Comment by ben-clayton** [comment]
Re-opening so I can give you a binary to check this fixes your issue.

**Comment by ben-clayton** [comment]
Here's the latest [gapir.exe](https://github.com/google/gapid/files/1193491/gapir.zip) that contains the fix.

Please let me know if this works for you.

**Comment by stcdalyc** [comment]
![default](https://user-images.githubusercontent.com/6738727/28951890-3b4fb788-7900-11e7-9aa3-4892591702ec.png)
Great. it fixed. All framebuffers are ok.

but i have an another question —— Shouldn't there be some lines on it in this mode?

**Comment by ben-clayton** [comment]
> Great. it fixed. All framebuffers are ok.

Fantastic, thanks for letting me know!

> but i have an another question —— Shouldn't there be some lines on it in this mode?

Known issue. See #818
