### ISSUE TITLE
gapid-x86.apk does not exist

### ISSUE THREAD

**Issue by kenforgh** [google/gapid#850]
I build gapid success
but gapid-x86.apk does not exist
I found  x86 does not in ANDROID_ACTIVE_ABI_LIST
after I add x86 to ANDROID_ACTIVE_ABI_LIST in AndroidABI.cmake, I can not build the project

**Comment by ben-clayton** [comment]
Hi @kenforgh,

Yes, we do not currently build an x86 APK.
Do you require this for the emulator or real device?

**Comment by stcdalyc** [comment]
@ben-clayton 
does it support google official emulator or genymotion?
because i'd like to use emulator on PC when i'm coding.

**Comment by kenforgh** [comment]
@ben-clayton 
for emulator.
I will add x86 for myself

**Comment by ben-clayton** [comment]
x86 / 64 is not well supported right now.
Aside from the missing CMake rules, there's no implementation of a x64 interceptor. The x86 interceptor library isn't well tested.

**Comment by tom3q** [comment]
Do you have an approximate of the effort to enable support for x86? We already have a big number of real x86 devices on the market - all the x86 Chromebooks, which support Play Store.

**Comment by ben-clayton** [comment]
@tom3q - unfortunately it's just not a priority for us right now.
There's [already a x86 interceptor](https://github.com/google/gapid/tree/master/gapii/interceptor-lib/cc/lib/X86), but it hasn't been throughly tested.
Assuming it works, then we *may* just need to add some missing CMake rules.
We've very happy to accept pull requests!

**Comment by ben-clayton** [comment]
Hold on... there is actually an x86 apk being build, but the file name is wrong. Let me try to fix that...

**Comment by ben-clayton** [comment]
The x86 apk should now be found.
