### ISSUE TITLE
Unreal titles can 'time out' when tracing

### ISSUE THREAD

**Issue by ben-clayton** [google/gapid#855]
The Unreal engine has logic to check whether the render thread is still alive. When tracing particularly data-heavy traces, we can trip this timeout logic, causing the application to shutdown.

As pointed out by a colleague: 
* the dead thread check can be skipped if "-nothreadtimeout" appears in the command line for UE4Game
* the UE4Game command line on android is the contents of `/sdcard/UE4Game/<game title>/UE4CommandLine.txt`

We should look at ways to automatically work around this issue, or at least document this clearly.

**Comment by dsrbecky** [comment]
how about intercepting whatever function is used to get time, and remove our overhead from the time? :-)

**Comment by ben-clayton** [comment]
> how about intercepting whatever function is used to get time, and remove our overhead from the time? :-)

Even if we were mad enough to try this, how would you distinguish between this timer call and other calls to calculate frame delta-times? Maybe trying to intercept the call to open the command line flags file is more practical...

**Comment by dsrbecky** [comment]
Intercepting and adjusting time calculate freame deltas would be also desirable IMHO

**Comment by ben-clayton** [comment]
If we can't find a workaround we need to make this a known issue on the user facing docs.
