### ISSUE TITLE
dumpsys package cmd is always terminated 

### ISSUE THREAD

**Issue by kenforgh** [google/gapid#858]
dumpsys package cmd is always terminated when excute "do run gapic"
When reading comments in command.go
It seems to be cancelled by watchdog

I run gapis with command got for gapic.log
dumpsys package can run success

**Comment by ben-clayton** [comment]
I'm sorry @kenforgh, I don't think I fully understand the problem.

Are you saying that `dumpsys package` is terminated before it completes? 

Where do you observe this issue? 
* In the `Trace...` dialog?
* In the `Select Activity` dialog?
* Somewhere else?

When this is terminated, what do you see?

> It seems to be cancelled by watchdog

I'm not aware of a watchdog. Please can you link to this code?

Many thanks,
Ben

**Comment by kenforgh** [comment]
I modify InstalledPackages function as below
log.I(ctx, "InstalledPackages Before dump...")
str, err := b.Shell("dumpsys", "package").Verbose().Call(ctx)
log.I(ctx, "InstalledPackages After dump...")

when run "do run gapic" (will trigger scanDevice)
"InstalledPackages After dump..." do not show and "dumpsys package"  but the output message is a part of the outputs message when i run "dumpsys package" on device


but when l run the command 
"E:\workspace\gapidebug\debug\pkg\gapis.exe, -log-file, C:\Users\pengkun\AppData\Local\Temp\gapis.log, -log-level, Info, -gapir-args, --log C:\Users\pengkun\AppData\Local\Temp\gapir.log --log-level I, --strings, E:\workspace\gapidebug\debug\pkg\strings, --gapis-auth-token, DkyL0LPR, --idle-timeout, 10000ms, --adb, C:\Users\pengkun\android-sdk_auto\platform-tools\adb.exe"

InstalledPackages After dump... shows in the log file and "dumpsys package" also shows the same as the output when i run it on device

**Comment by kenforgh** [comment]
@ben-clayton 
--I'm not aware of a watchdog. Please can you link to this code?
In Run function of command.go
the comment line 
// We build a child context that we always cancel, so that the watchdog quits even on normal process exit
Thanks
Ken

**Comment by ben-clayton** [comment]
Is it possible you're using two different versions of adb between the working case and the non-working case?

**Comment by ben-clayton** [comment]
I'm afraid I'm unable to reproduce, nor do I know what the user-facing issue is.

**Comment by kenforgh** [comment]
@ben-clayton 
It hangs with output from stderr and stdout pipes.

**Comment by kenforgh** [comment]
@ben-clayton  
It hangs with output from stderr and stdout pipes.
But I do not know why It do not hang when running gapis without gapic
Maybe It only happens on my environment
