### ISSUE TITLE
Add more information to context combo box

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#868]
If there are many contexts, picking an "interesting" one can be tricky.
I added the thread names, but that still does always yield ideal results.
The command three has the "(1234 commands)" suffix for groups.
I think the same format would be useful for the contexts...

**Comment by ben-clayton** [comment]
I agree that the number of commands would be useful.
While the thread name is nice, it's a bit dodge, given that a context can be used on any number of threads. We should probably fix this by expanding the filter out to threads, contexts, apis, etc...

**Comment by dsrbecky** [comment]
I am definitely in favour of by-thread filtering.
Although I think thread name can be set at any time, so it is still tricky
