### ISSUE TITLE
Broken --gapis-args flag for gapic

### ISSUE THREAD

**Issue by pmuetschard** [google/gapid#874]
In https://github.com/google/gapid/pull/844/commits/f8069474b2bc14971066f940f4e925ae3307cfe9, `--gapis-args` was added, but in a broken state: if given a list of flags, or a flag in the 
`'--flag value'` format, they are not passed correctly to gapis.

**Comment by AWoloszyn** [comment]
I think the problem here is that GAPIC gets the args as a single string, and then just forwards that string on to GAPIS. GAPIC will have to replicate what we do in split_args in GAPIC so that we can correctly forward things.

**Comment by AWoloszyn** [comment]
We have a flag (should check the name) that allows you to pass a single string that will be split by gapis.

**Comment by AWoloszyn** [comment]
This has been fixed, gapic now uses "--args" which passes as a single string.
