### ISSUE TITLE
"Couldn't get framebuffer attachment" when dealing with sRGB buffers

### ISSUE THREAD

**Issue by tomgoogle** [google/gapid#876]
I have a particular Unity sample that performs a lot of converting between linear and gamma buffers and composites them onto a camera feed.

GAPIC shows the following error instead of a framebuffer:

"Couldn't get framebuffer attachment
    Cause: Communicating with gapir
    Cause: Failed to read replay postback data: Failed to resolve resource with id: 
    Cause: No converter registered that can convert from format 'name:"GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC" etc2_rgba_u8_unorm:<srgb:true> ' to 'name"RGBA_U8_NORM" uncompressed....."

![gapid_error](https://user-images.githubusercontent.com/25167811/29051178-9b45f4c6-7b95-11e7-86f2-dbbb11d4e3f7.PNG)

**Comment by ben-clayton** [comment]
@tomgoogle - please can I have a sample APK that has this issue?
