### ISSUE TITLE
Can not capture gpu trace with error: EOF:77B

### ISSUE THREAD

**Issue by tyouter** [google/gapid#894]
When I use this version of gapid(release version 0.5.1)

After configuring my device and packages, everything seems fine.

When I start capturing,it will stop immediately

 I get the following logs:
08:05:28.073 I: [gapidapk.EnsureInstalled] <gapit> Examining gapid.apk on host...
08:05:28.078 I: [gapidapk.EnsureInstalled] <gapit> Looking at installed packages...
08:05:28.905 I: [gapidapk.EnsureInstalled] <gapit> Found gapid package...
08:05:30.495 I: <gapit> Adding new device
08:05:30.495 I: <gapit> Device list:
08:05:30.495 I: <gapit>   47QDU16C05000453
08:05:30.972 I: <gapit> Package is debuggable
08:05:30.972 I: <gapit> Clearing package cache
08:05:31.335 I: [start] <gapit> Turning device screen on
08:05:31.911 I: [start] <gapit> Checking for lockscreen
08:05:31.948 I: [start] <gapit> Checking gapid.apk is installed
08:05:31.948 I: [gapidapk.EnsureInstalled⇒start] <gapit> Examining gapid.apk on host...
08:05:31.953 I: [gapidapk.EnsureInstalled⇒start] <gapit> Looking at installed packages...
08:05:32.685 I: [gapidapk.EnsureInstalled⇒start] <gapit> Found gapid package...
08:05:32.685 I: [start] <gapit> Forwarding
08:05:32.730 I: [start] <gapit> Starting activity in debug mode
08:05:33.570 I: [start] <gapit> Forwarding TCP port 55096 -> JDWP pid 31827
08:05:33.587 I: [start] <gapit> Connecting to JDWP
08:05:34.596 I: [start] <gapit> Waiting for ApplicationLoaders.getClassLoader()
08:05:34.599 I: [start] <gapit> Waiting for Application.onCreate()
08:05:36.107 I: [start] <gapit> Installing interceptor libraries
08:05:37.795 W: [start] <gapit> Killing D:\Tools\android_sdk\platform-tools\adb.exe (context cancelled)
08:05:37.795 I: <gapit> Creating file 'C:\Users\aa\Desktop\temp\trace\agnav30_20170811_1605.gfxtrace'
Press enter to stop capturing...
08:05:37.795 I: <gapit> Waiting for connection to localhost:55067...
08:05:38.897 I: <gapit> Capturing: 77B in 0s
08:05:39.313 I: <gapit> EOF: 77B

**Comment by ben-clayton** [comment]
Hi @tyouter,

It looks like the Android application unexpectedly quit. Is there anything in logcat to suggest why it terminated?

Cheers,
Ben

**Comment by tyouter** [comment]
Hi @ben-clayton

I can install my application with AndroidStudio2.3 with no problems.
I see my logcat in error level, it does not show anything useful to me. 
Since my computer does not connected to the internet. What if some library I can not access will cause some problems, for example : 08:05:36.107 I: [start] Installing interceptor libraries ?

**Comment by tyouter** [comment]
Hi @ben-clayton

I just read the installing source code 

https://github.com/google/gapid/blob/master/gapii/client/jdwp_loader.go

From the log I got above, the func loadLibrariesViaJDWP run with no error to the end because I can see this log "Installing interceptor libraries" and error message "JDWP failure" dose not show up. The source code in the end writes:

// If we did not have vulkan support, then we should try to load with
	// Application.onCreate().
	if classLoaderThread == jdwp.ThreadID(0) {
		// Wait for Application.onCreate to be called.
		log.I(ctx, "Waiting for Application.onCreate()")
		onCreate, err := waitForOnCreate(ctx, conn, classLoaderThread)
		if err != nil {
			return log.Err(ctx, err, "Waiting for Application.OnCreate")
		}

		// Create a JDbg session to install and load the libraries.
		log.I(ctx, "Installing interceptor libraries")
		if err := jdbg.Do(conn, onCreate.Thread, loadGAPII); err != nil {
			return log.Err(ctx, err, "JDWP failure")
		}
	}

	return nil

I need more information what's wrong after this installing function.

**Comment by tyouter** [comment]
Hi @ben-clayton

I just read the installing source code

https://github.com/google/gapid/blob/master/gapii/client/jdwp_loader.go

From the log I got above, the func loadLibrariesViaJDWP run with no error to the end because I can see this log "Installing interceptor libraries" and error message "JDWP failure" dose not show up. The source code in the end writes:

// If we did not have vulkan support, then we should try to load with
// Application.onCreate().
if classLoaderThread == jdwp.ThreadID(0) {
// Wait for Application.onCreate to be called.
log.I(ctx, "Waiting for Application.onCreate()")
onCreate, err := waitForOnCreate(ctx, conn, classLoaderThread)
if err != nil {
return log.Err(ctx, err, "Waiting for Application.OnCreate")
}

	// Create a JDbg session to install and load the libraries.
	log.I(ctx, "Installing interceptor libraries")
	if err := jdbg.Do(conn, onCreate.Thread, loadGAPII); err != nil {
		return log.Err(ctx, err, "JDWP failure")
	}
}

return nil
I need more information what's wrong after this installing function.

**Comment by tyouter** [comment]
Hi @ben-clayton

After connect to the internet, log has changed but still fail to run my application. "Waiting for Debugger"
dialog always show up and only "Force Close" can stop it, it seems the GAPID can not connect to my phone via adb.exe. Here is the log:

07:28:42.730 I: [gapidapk.EnsureInstalled] <gapit> Examining gapid.apk on host...
07:28:42.734 I: [gapidapk.EnsureInstalled] <gapit> Looking at installed packages...
07:28:43.603 I: [gapidapk.EnsureInstalled] <gapit> Found gapid package...
07:28:45.252 I: <gapit> Adding new device
07:28:45.252 I: <gapit> Device list:
07:28:45.252 I: <gapit>   47QDU16C05000453
07:28:45.778 I: <gapit> Package is debuggable
07:28:45.778 I: <gapit> Clearing package cache
07:28:46.393 I: [start] <gapit> Turning device screen on
07:28:46.430 I: [start] <gapit> Checking for lockscreen
07:28:46.465 I: [start] <gapit> Checking gapid.apk is installed
07:28:46.465 I: [gapidapk.EnsureInstalled⇒start] <gapit> Examining gapid.apk on host...
07:28:46.470 I: [gapidapk.EnsureInstalled⇒start] <gapit> Looking at installed packages...
07:28:47.229 I: [gapidapk.EnsureInstalled⇒start] <gapit> Found gapid package...
07:28:47.229 I: [start] <gapit> Forwarding
07:28:47.274 I: [start] <gapit> Starting activity in debug mode
07:28:48.139 I: [start] <gapit> Forwarding TCP port 53707 -> JDWP pid 5217
07:28:48.155 I: [start] <gapit> Connecting to JDWP
07:28:49.160 I: [start] <gapit> Failed to connect: EOF
07:28:51.191 I: [start] <gapit> Failed to connect: EOF
07:28:53.201 I: [start] <gapit> Failed to connect: EOF
07:28:55.203 I: [start] <gapit> Failed to connect: EOF
07:28:57.207 I: [start] <gapit> Failed to connect: EOF
07:28:59.223 I: [start] <gapit> Failed to connect: EOF
07:29:01.223 I: [start] <gapit> Failed to connect: EOF
07:29:03.224 I: [start] <gapit> Failed to connect: EOF
07:29:05.226 I: [start] <gapit> Failed to connect: EOF
07:29:07.227 I: [start] <gapit> Failed to connect: EOF
07:29:08.292 F: <gapit> Main failed
Error: Connecting to JDWP
   Cause: EOF
Tracing failed:
com.google.gapid.server.ChildProcess$EarlyExitException: gapit has exited with exit code 1
	at com.google.gapid.server.ChildProcess.runProcess(ChildProcess.java:98)
	at com.google.gapid.server.ChildProcess$1.run(ChildProcess.java:69)

**Comment by ben-clayton** [comment]
Hi @tyouter,

Are you running Android Studio at the same time as attempting to take the trace? If so, please try closing Android Studio while taking the trace.

Please let me know if this helps.

**Comment by tyouter** [comment]
Hi @ben-clayton 

Big thanks for your replay

I made it yesterday. I change my device and it works. If anyone meet the same problem, these options maybe helpful:
1、connect to the internet
2、kill adb.exe process before run this software (Close AndroidStudio, Eclipse or other related softwares)
3、use devices which not modify the original android system, do not use system like MIUI or EMUI, they may refuse adb connection by their protection settings

**Comment by ben-clayton** [comment]
I'm glad your issue has been resolved.
I've created #911 to try and get this problem sorted.
