### ISSUE TITLE
ADB over network fails

### ISSUE THREAD

**Issue by robertfoss** [google/gapid#895]
I'm seeing some issues while connecting to a device using adb over network.
Is this a supported usecase?

```
xps9550 ~ $ adb connect 172.16.1.1          
connected to 172.16.1.1:5555

xps9550 ~ $ ./Apps/gapid/debug/bin/gapit trace com.johnathongoss.libgdxtests
11:07:57.312 I: [gapidapk.EnsureInstalled] <gapit> Examining gapid.apk on host...
11:07:57.395 I: [gapidapk.EnsureInstalled] <gapit> Looking at installed packages...
11:07:59.906 I: [gapidapk.EnsureInstalled] <gapit> Found gapid package...
11:08:01.713 I: <gapit> Adding new device
11:08:01.713 I: <gapit> Device list:
11:08:01.713 I: <gapit>   unknown
11:08:01.725 F: <gapit> Main failed
Error: Process returned error
   Cause: exit status 1
```

**Comment by ben-clayton** [comment]
Hi @robertfoss,

It's something I don't think we've tried. What do you get if you type `adb devices` ? It's possible the output of that command with a remote device gives something [our parser doesn't recognize](https://github.com/google/gapid/blob/bfdcf0e6f5b7b4e49437beb428717395eef199a6/core/os/android/adb/device.go#L204-L241).

Cheers,
Ben

**Comment by robertfoss** [comment]
```
xps9550$ adb connect 172.16.1.1   
connected to 172.16.1.1:5555

xps9550$ adb devices
List of devices attached
172.16.1.1:5555	device
```

**Comment by tom3q** [comment]
FYI, ADB over network seems to work fine for me on latest master. @robertfoss, the "unknown" entry in the list returned by "adb devices" looks suspicious. Does "adb shell" work with that device?

**Comment by ben-clayton** [comment]
I may have fixed this issue with https://github.com/google/gapid/pull/985/commits/608fdde1240eacf27dd9305f265e818ecf3a4715, so please let us know if this is still an issue.

**Comment by ben-clayton** [comment]
Assuming fixed.
