### ISSUE TITLE
 Failed to connect: read tcp 127.0.0.1:51470->127.0.0.1:51464: wsarecv: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by acenodie** [google/gapid#912]
Hello, I got this error:
 Failed to connect: read tcp 127.0.0.1:51470->127.0.0.1:51464: wsarecv: An existing connection was forcibly closed by the remote host.

The detail:
0:23:54.045 I: [gapidapk.EnsureInstalled] <gapit> Examining gapid.apk on host...
10:23:54.059 I: [gapidapk.EnsureInstalled] <gapit> Looking at installed packages...
10:23:56.391 I: [gapidapk.EnsureInstalled] <gapit> Found gapid package...
10:23:58.927 I: <gapit> Adding new device
10:23:58.927 I: <gapit> Device list:
10:23:58.927 I: <gapit>   0715f7f3c6bc1704
10:24:00.455 I: <gapit> Device is rooted
10:24:00.455 I: <gapit> Clearing package cache
10:24:01.787 I: [start] <gapit> Turning device screen on
10:24:02.076 I: [start] <gapit> Checking for lockscreen
10:24:02.379 I: [start] <gapit> Checking gapid.apk is installed
10:24:02.379 I: [gapidapk.EnsureInstalled⇒start] <gapit> Examining gapid.apk on host...
10:24:02.387 I: [gapidapk.EnsureInstalled⇒start] <gapit> Looking at installed packages...
10:24:04.725 I: [gapidapk.EnsureInstalled⇒start] <gapit> Found gapid package...
10:24:04.725 I: [start] <gapit> Forwarding
10:24:05.202 I: [start] <gapit> Starting activity in debug mode
10:24:06.766 I: [start] <gapit> Forwarding TCP port 51464 -> JDWP pid 25590
10:24:06.952 I: [start] <gapit> Connecting to JDWP
10:24:07.962 I: [start] <gapit> Failed to connect: read tcp 127.0.0.1:51470->127.0.0.1:51464: wsarecv: An existing connection was forcibly closed by the remote host.
10:24:09.975 I: [start] <gapit> Failed to connect: read tcp 127.0.0.1:51472->127.0.0.1:51464: wsarecv: An existing connection was forcibly closed by the remote host.
10:24:11.984 I: [start] <gapit> Failed to connect: read tcp 127.0.0.1:51476->127.0.0.1:51464: wsarecv: An existing connection was forcibly closed by the remote host.
10:24:13.992 I: [start] <gapit> Failed to connect: read tcp 127.0.0.1:51481->127.0.0.1:51464: wsarecv: An existing connection was forcibly closed by the remote host.
10:24:16.005 I: [start] <gapit> Failed to connect: read tcp 127.0.0.1:51483->127.0.0.1:51464: wsarecv: An existing connection was forcibly closed by the remote host.
10:24:18.010 I: [start] <gapit> Failed to connect: read tcp 127.0.0.1:51495->127.0.0.1:51464: wsarecv: An existing connection was forcibly closed by the remote host.
10:24:20.019 I: [start] <gapit> Failed to connect: read tcp 127.0.0.1:51511->127.0.0.1:51464: wsarecv: An existing connection was forcibly closed by the remote host.
10:24:22.029 I: [start] <gapit> Failed to connect: read tcp 127.0.0.1:51513->127.0.0.1:51464: wsarecv: An existing connection was forcibly closed by the remote host.
10:24:24.041 I: [start] <gapit> Failed to connect: read tcp 127.0.0.1:51518->127.0.0.1:51464: wsarecv: An existing connection was forcibly closed by the remote host.
10:24:26.054 I: [start] <gapit> Failed to connect: read tcp 127.0.0.1:51520->127.0.0.1:51464: wsarecv: An existing connection was forcibly closed by the remote host.
10:24:27.724 F: <gapit> Main failed
Error: Connecting to JDWP
   Cause: read tcp 127.0.0.1:51520->127.0.0.1:51464: wsarecv: An existing connection was forcibly closed by the remote host.
Tracing failed:
com.google.gapid.server.ChildProcess$EarlyExitException: gapit has exited with exit code 1
	at com.google.gapid.server.ChildProcess.runProcess(ChildProcess.java:98)
	at com.google.gapid.server.ChildProcess$1.run(ChildProcess.java:69)

**Comment by ben-clayton** [comment]
Hi @acenodie,

Please can you confirm [whether Android Studio is also running](https://github.com/google/gapid/issues/911)?
If not, is there anything printed by `adb logcat` that could suggest why the application might have crashed?

Many thanks,
Ben

**Comment by acenodie** [comment]
Hello,I already closed my Android studio!

**Comment by ben-clayton** [comment]
What device are you attempting to trace on?
What version of Android is it running?
Is there anything printed by running `adb logcat` that could suggest why the application might have crashed?

**Comment by acenodie** [comment]
thanks, i can get the trace;
But i have some question about how i should use this software？
any some specification?
example: i am developing a camera application, i used openGL, How can I get the camera frame by capturing the trace?
sorry, my english is poor, hope you can get me.

**Comment by ben-clayton** [comment]
There's some WIP documentation being written [here](https://google.github.io/gapid).

Unfortunately we do not currently capture video frames from the camera. We intend to add support for this in the near future. I've created #913 to track this.

**Comment by acenodie** [comment]
ok.
if i draw the oes texture from the camera to FBO, can i capture the frame?

**Comment by ben-clayton** [comment]
Currently no. GAPID doesn't make any attempt to read the OES textures, hence at replay we do not have the data to correctly reproduce what would have been displayed. This is becoming more of a priority for us, so we'll hopefully have this implemented soon.

**Comment by ben-clayton** [comment]
Closing the issue as we have #913 to track the feature.

**Comment by usamal-pixel** [comment]
read tcp 127.0.0.1:50983->127.0.0.1:50982: wsarecv: An existing connection was forcibly closed by the remote host.
