### ISSUE TITLE
Not able to see captured dump

### ISSUE THREAD

**Issue by digish** [google/gapid#934]
Hi,
I have some captured dumps from dialer app which i am not able to see correctly.

[dialer_20170818_1556.zip](https://github.com/google/gapid/files/1234401/dialer_20170818_1556.zip)

seeing something like below.
![image](https://user-images.githubusercontent.com/436860/29459099-cc90a690-843f-11e7-9bfb-ca8652c11d3c.png)

thank you

**Comment by ben-clayton** [comment]
Looks like the replay process is crashing. I'll take a look.
